### ISSUE TITLE
leave shuffle or repeat activated on start if previously set

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#100]
well i guess the title already explains everything

oh and happy easter :)

**Comment by Taiko2k** [comment]
I kind of preferred it to forget, but I suppose remembering would be more the expected behavior.

Happy Easter to you too!

**Comment by legacychimera247** [comment]
well if it's by purpose it's ok then, or it can be made optionally

more than the expected behaviour it's just that sometimes, when i hear new music i like to repeat the album i was listening and not pass to the next one but i guess it may have sense as i know people that for example hate to repeat and if they really want to, they just press the back button...

**Comment by Taiko2k** [comment]
No no you've gone and said it now, no going back. :grin:

Though really it probably should be regarded as a bug, since its more the expectation that settings persist over restarts. Not worth having a setting just for that.

**Comment by legacychimera247** [comment]
ok, sorry then, but don't scare me xD
