### ISSUE TITLE
Global search issues

### ISSUE THREAD

**Issue by resiehnnes** [Taiko2k/TauonMusicBox#1007]
Good day @Taiko2k . I discovered your music player a day ago and am astonished of how good it is! Feature rich, easy to operate and beautiful.

Running latest version on Fedora 38 machine.

I experience problem with searching for some **albums** using **global search** (filter search works fine). Here is one album name I caught to cause some funky search issues:

"Past Life Analysis 3"

When I type:

"Past" - album is missing in search overlay
"Past L" - album comes up
"Past Li" - missing .. until I reach "Past Life A" then it comes up again
"Past Life Ana" - missing again and won't come up until I type in full album string "Past Life Analysis 3" then it comes up again

Another example: "Russian Roulette EP", there are **only two** name variations to make this EP show up:

"Russian R" and "Russian Roulette E"  

Some album names (as example above) do not appear at all even after typing in full name.

**Comment by Taiko2k** [comment]
Ive tried playing around with it and cant seem to replicate the behavior as you describe. What can happen is depending on what you type the target album can get pushed down the list by more relevant results. Typing the name exactly it should show. 

If you want you could try screen recording as you try search those, that might give me a better idea of what is going on there.

**Comment by Taiko2k** [comment]
Yeah certainly that looks like undesired behavior. Not sure whats triggering it. I really need to replicate it myself. I'll keep a look out for it if I do run into it.
