### ISSUE TITLE
[Feature Request] Sync Jellyfin Playlist 

### ISSUE THREAD

**Issue by gzqx** [Taiko2k/TauonMusicBox#1010]
It would be really nice if it can read the playlists on jellyfin.

**Comment by Taiko2k** [comment]
There is currently a mechanism for this in Tauon. Go MENU -> Settings -> Accounts -> Jellyfin. Then press import playlists button. It uses a push/pull model. Changes can be pulled by pressing "Regenerate" and pushed by pressing "Upload" in the playlist tab context menu.

**Comment by gzqx** [comment]
Yes, I see that. I believe what it does is to import all of the songs on Jellyfin. What I mean is following:
![Screenshot_20230806_142714](https://github.com/Taiko2k/TauonMusicBox/assets/24262751/a3396c7b-0f07-4c8d-8013-047819256b4c)
Jellyfin allow to create and sync playlists (group of some song) among devices.

**Comment by Taiko2k** [comment]
> Yes, I see that. I believe what it does is to import all of the songs on Jellyfin

That's what the top button here does, the lower one should import the playlists.

![Screenshot from 2023-08-07 02-49-45](https://github.com/Taiko2k/TauonMusicBox/assets/17271572/74045b14-d804-48fb-ab3d-c5c5fa7dbc07)

**Comment by gzqx** [comment]
I see! Soooo sorry for asking for an existing feature.
BTW, your UI design is my favorite among all Jellyfin players, thank you for your work!
