### ISSUE TITLE
tauon crashes when dragging files into new playlist

### ISSUE THREAD

**Issue by sleeplessKomodo** [Taiko2k/TauonMusicBox#1013]
OS: Linux, Fedora 38 (Nobara)
version: v7.6.6 (flatpak)

Sometimes, drag and drop works without issue, when dragging multiple files and folders into a new playlist. But then, this happens. To be specific, I'm dragging files from the dolphin file manager window, with files from a separate internal NVMe drive. Like I said, sometimes it works without issue, so I'm unsure how to proceed. 

Here's the error message from terminal:

```
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 352, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 42938, in <module>
    target = str(urllib.parse.unquote(dropped_file_sdl.decode("utf-8"))).replace("file:///", "/").replace("\r",
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4: invalid start byte
```

**Comment by Taiko2k** [comment]
Currently importing filenames with non-utf8 will cause that crash. Ive committed a fix for that now, so in the next version of Tauon it should work. In the mean time you could work around the issue by ensuring your filenames are vaild utf8.
