### ISSUE TITLE
Drag and drop to reorder

### ISSUE THREAD

**Issue by NotGabe001** [Taiko2k/TauonMusicBox#1015]
It'd be pretty convenient to drag-and-drop to reorder songs in a playlist. Sometimes I like to have a custom-ordered playlist, and the only way I've found to do that is to import them in the order I want. I could live without it, but it would be a nice feature.

**Comment by Taiko2k** [comment]
This feature does exist, you just gotta hold the shift key when dragging.

**Comment by NotGabe001** [comment]
oh wait nevermind, I didn't know you had to hold shift
