### ISSUE TITLE
sorting is not remembered if i rescan folders

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#102]
well the title explqins everything, if i have set a certain sorting and i rescan folders, the sorting is reverted to the first one (which i guess is top played tracks), would be nice to have it remembered as i generally sort music by artist and per year...

**Comment by Taiko2k** [comment]
Currently, using `Rescan Folders` will revert the playlist to the import order. Soo... currently you would indeed need to re-apply those.

I wonder how this could be improved... maybe an option to always sort by Filepath and Year By Artist on import. So in a way this is an extention to issue #96

Maybe a solution is to merge those two functions into a toggle called "Auto Sort" that will apply whenever tracks are imported.

**Comment by legacychimera247** [comment]
it's an idea, i guess that have multiple choiches for sorting it's good but most of us keep organizing music by alphabetical order and by year, so to me it's a good idea...

**Comment by Taiko2k** [comment]
I've added the feature I mentioned. Hopefully will provide a solution to this issue.

I kind of feel that the whole current way of sorting is a little messy, so I may change/overhaul this in the future.

**Comment by StrangeSeasOfThought** [comment]
The setting _auto sort on import_ doesn't seem to work anymore. Can someone confirm?

**Comment by Taiko2k** [comment]
Oh... Are you importing tracks for the first time and its not sorting by year? That might be broken now that I think about it

**Comment by StrangeSeasOfThought** [comment]
When I have new music, I rescan the folder. That's when auto sort should work, too, right? It doesn't seem to work atm.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought The 'year per artist' sorting is currently broken with auto-sort (because now tags are no longer scanned before import with the latest update, they wont have year metadata), but the filepath sorting component should be working.

Oh, also, auto-sort will have no effect if the playlist is *locked*.

**Comment by StrangeSeasOfThought** [comment]
Yeah, filepath sorting still works.
