### ISSUE TITLE
Glitched window on startup

### ISSUE THREAD

**Issue by ThoriumTextile** [Taiko2k/TauonMusicBox#1031]
Tauon runs fine, however the window is completely unusable and when other windows are dragged over, it displays a smearing/"domino cards effect"

- What method did you use to install Tauon?
  Flatpak
- What version number is shown under MENU > Settings... > About
  7.6.6
- For audio/transition related issues, what backend do you have selected under MENU > Settings... > Audio. Does the issue happen on both backends? Are you playing local files, or files from a particuar network server?
  N/A (unusable UI), playing locally.
- For crashes, it would be most helpful if you could replicate the crash and capture the error from terminal output.
```
Tauon Music Box v7.6.6
Copyright 2015-2023 Taiko2k captain.gxj@gmail.com

Window size: [1120, 600]
Gtk-Message: 21:48:34.394: Failed to load module "canberra-gtk-module"
Detected running as Flatpak
Installed as Flatpak
User files location: /home/actinyde/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/actinyde/Downloads
Found XDG-Music: /home/actinyde/Music
Install directory: /app/bin
Database loaded in 0.0 seconds.
Scanning for chromecasts...
Start controller server
Start PHAzOR backend...
Using SDL version: 2.24.0
Applying theme: Turbo
^C
```

**Comment by Taiko2k** [comment]
Can I ask what DE you're using and if you're using Nvidia graphics?

**Comment by ThoriumTextile** [comment]
> Can I ask what DE you're using and if you're using Nvidia graphics?

KDE, AMD, RX 6600 (amdgpu)

**Comment by ThoriumTextile** [comment]
@Taiko2k so idk what just happened, but i reinstalled all of my graphics drivers due to another issue, and now it works apparently. Not very helpful, i know, sorry!

**Comment by evdcush** [comment]
I am getting the same error when I attempt to `flatpak run com.github.taiko2k.tauonmb`

```
Gtk-Message: 16:35:10.102: Failed to load module "canberra-gtk-module"
```

## System Info

- Ubuntu 20.04 `5.15.0-91-generic`
- Nvidia drivers: `Driver Version: 545.23.08    CUDA Version: 12.3`
- Flatpak `1.14.4`
- Tauon has `host` filesystem privileges

```
$ flatpak info com.github.taiko2k.tauonmb  

Tauon Music Box - Play your music with style

          ID: com.github.taiko2k.tauonmb
         Ref: app/com.github.taiko2k.tauonmb/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 7.6.7
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 110.8 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: fda3523118bff30b50b27f157ea29e4292e713687680355ce9933828661c69dd
      Parent: dc944ad4c90e72a180bd0007b6a2cd287e44d3f2988ca2384e548c6d2661d3fe
     Subject: Update com.github.taiko2k.tauonmb.json (ba523715)
        Date: 2023-11-16 08:22:28 +0000
```


## Things I've Tried

- `flatpak update`
- `sudo flatpak repair`
- `--disable-gpu`
- Reinstall tauon
- Reboot

---

How can I resolve this issue?
