### ISSUE TITLE
Strange horizontal line dividers

### ISSUE THREAD

**Issue by madprops** [Taiko2k/TauonMusicBox#1035]
![tauonbug](https://github.com/Taiko2k/TauonMusicBox/assets/206498/87aed342-ef4f-41ed-8c5b-e9e09d2bb6ac)

Wondering what these lines near the top are. After track #2.

Posting this in case it's a bug.

**Comment by Taiko2k** [comment]
Its intended to indicate a change in CD, however in this case I assume its inconsistently tagged tracks that's incorrectly triggering it for you there.

**Comment by madprops** [comment]
You're right, after the second track the rest of the tracks show "Disc 1 of 1".

I'll fix the tags, thanks.
