### ISSUE TITLE
substitute original files in transcoding

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#104]
sometimes i download albums that are only available in flac, and while flac is good, my hdd is only 120 gb so cannot afford to have a flac library and i generally convert albums on the go to ogg at 192 kbps, it would be nice it tauon could have an option to transcode files then delete the originals and put the transcoded in the same folder as the originals. Sound converter have that and it's really handy...

**Comment by Taiko2k** [comment]
I've added this as a setting, hopefully there's no bugs with it. One quirk is the embedded images aren't kept, so just a simple matter of checking and using the extract image function if necessary. I've added a warning when enabling just in case. 

Hopefully users will be responsive with this and not re-encode lossy codecs too many times.
