### ISSUE TITLE
[FR]: Please scrobble "album artist" tag like before

### ISSUE THREAD

**Issue by ALi3naTEd0** [Taiko2k/TauonMusicBox#1041]
In version 7.6.6 I'm able to scrobble "album artist" tag, but after the new update it's not behaving like this anymore. A fix for this would be really appreciate it since this is a feature I use a lot, and so that I can also keep up updating the app. Thanks in advance. 🙂

**Comment by ALi3naTEd0** [comment]
PS: Notice that previous behavior is to scrobble "album artist" tag but if "album artist" is: = "Various Artists" then "artist" tag is scrobbled which is the "proper" behavior. Thanks again.

**Comment by Taiko2k** [comment]
Ive committed a revert for that change now, so next release it should behave like it used to.
