### ISSUE TITLE
menu stays open ater clicking

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#105]
if i click on something on the menu, the menu does the action but stays open, is this wanted or is a bug?i'm honestly expecting it to close :P

**Comment by Taiko2k** [comment]
Its currently intended behavior that the View Menu (Layout selector attached to the main Menu) does not close on click, but all other menus should close on click.

**Comment by legacychimera247** [comment]
ok, so we can close this one
