### ISSUE TITLE
[FR] Use artist image as background

### ISSUE THREAD

**Issue by zeskeertwee** [Taiko2k/TauonMusicBox#1052]
There is the option 'Use album art as background', but i think it would also be quite nice if we could have an image of the artist as the background there as an option. These images could be sourced from for ex. last.fm. As a fallback, it could then always fall back to the cover art if it can't find an image of the artist.
I'd love to try and implement this myself, but i've tried and cannot find where the drawing of the background and related code are.
I've also tried and successfully managed to scrape the image URLs from last.fm for an artist, but i have no idea how to implement it in the codebase.
I'd love to implement this, but i just need a few pointers on how the background drawing etc. works.

**Comment by Taiko2k** [comment]
This feature does actually exist, but it might not work since it hardly ever gets used or maintained. Iirc the setting is under MENU > Settings > Accounts > Fanart.tv

**Comment by Taiko2k** [comment]
OK Ive committed a change that moves this setting to the theme settings section, and enabled last.fm artist fetching for it

**Comment by zeskeertwee** [comment]
Thanks a lot! I didn't even know that other option existed!
