### ISSUE TITLE
Searching by sort tags

### ISSUE THREAD

**Issue by mary-ext** [Taiko2k/TauonMusicBox#1060]
It would be nice if it makes use of sort tags when searching, I have a lot of JP artists in my collection where their names are fully in kanji so the basic kana conversion isn't helping much in this scenario

**Comment by Taiko2k** [comment]
OK, Ive committed this feature for searching now. On upgrade you'll need to run "Rescan Tags" from the "Misc" submenu of the *playlist tab* context menu for this change to take effect.
