### ISSUE TITLE
[Feature request] Generator playlist for unlistened tracks

### ISSUE THREAD

**Issue by n2o4** [Taiko2k/TauonMusicBox#1068]
Requesting an option to be able to filter on `playcount equal to` so the user can have an easy view of their unlistened music.

If something like `self a pc=0 m> auto` is already possible, I'm sorry, I tried skimming the docs!

**Comment by Taiko2k** [comment]
You can use playtime instead of playcount, so you could do `pt<1`, or like `pt<10` for less than 10 seconds of playtime.
