### ISSUE TITLE
using mouse wheel to increase/decrease volume, stops chords auto-scrolling

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/TauonMusicBox#107]
hello.
well, yes. the mouse wheel affects (stops) the auto-scrolling of chords (dont know if lyrics too), even if the cursor is above the volume slider.

**Comment by Taiko2k** [comment]
Ah, this is because the scroll area was applying to the context of the entire window. I've gone and fixed this now.

**Comment by legion1978** [comment]
outstanding :)
