### ISSUE TITLE
audio is garbled with bass library

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#108]
well i know there is another thread but this is not occurring everytime as the other thread. i just have that when i am opening heavy apps or under heavy workloads and with 2 gb ram and a celeron this does happen lots of times, so i switched to gstreamer that even if it's missing some functions doeas not have any problems even with heavy workload

eg i'm opening telegram and audio gets garbled and resumes after telegram is opened

as much as i miss the crossfade that's not really an issue and gstreamer is working absolutely fine, just tought about reporting it as maybe it can be done something about...

**Comment by Taiko2k** [comment]
Probably wont help, but did you try increase the buffer setting? (In the "Audio" tab in settings).

Also to clarify, the audio is distorted, rather than stuttering?

**Comment by legacychimera247** [comment]
pulseaudio 12.2-rebootstrapped

yes, tried to 60 as suggested in the other thread but nothing changed...

**Comment by Taiko2k** [comment]
I'm hoping this issue will go away on its own eventually. For now I'm cleaning up the open issues by closing this. Further updates can be made in #69
