### ISSUE TITLE
[Feature Request] Favorite current song playing via terminal

### ISSUE THREAD

**Issue by KemonoElite** [Taiko2k/TauonMusicBox#1098]
I've been enjoying using Tauon Music Box, particularly its support for flags and integration with playerctl. However, I've run into a bit of a issue: I can't seem to find a way to favorite the current song playing without using the graphical interface.

I was thinking of piping keys to the app, but it seems like that might not work on Wayland. Do you know of any alternative methods or workarounds to achieve this? Any insights would be much appreciated.

Thanks for your time!

**Comment by Taiko2k** [comment]
There is this way in feature request #142. I assume that command mentioned there should work.

**Comment by KemonoElite** [comment]
Appreciate the response, I'll try this out asap

**Comment by KemonoElite** [comment]
This does indeed work. Appreciate the response 😀
