### ISSUE TITLE
some artists shown last on artists view

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#110]
well i listen to a band called Kent, and i noticed that i have a double entry for that with "Kent" at k letter, as it should be, and one at the end of the view with "kent" (the key is not capital)

my songs are all edited by picard so they should be all the same, maybe it's a bug?

**Comment by Taiko2k** [comment]
Are you sure there are no lower case "kent" tracks in the playlist?

**Comment by Taiko2k** [comment]
As for how to handle these kinds of dupes. I though that perhaps its better to just to let them be and let the user fix any tagging mistakes.

**Comment by legacychimera247** [comment]
i have checked and you have reason, some where kent and some where Kent, but didn't notice cause was using lollypop previously and rhytmbox that didn't make that distinction...we can close this one then...
