### ISSUE TITLE
Error Creating Window

### ISSUE THREAD

**Issue by fourbythree** [Taiko2k/TauonMusicBox#1102]
Whenever I try to launch Tauon it creates window size 0,0 so I cannot use it. I am trying to launch using

`flatpak run com.github.taiko2k.tauonmb`  

The error I get is 

`Tauon Music Box v7.7.1
Copyright 2015-2023 Taiko2k captain.gxj@gmail.com

ERROR CREATING WINDOW!
Window size: [0, 0]
2021
Detected running as Flatpak
Installed as Flatpak
User files location: /home/fourbythree/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/fourbythree/Downloads
Found XDG-Music: /home/fourbythree/Music
Install directory: /app/bin
Database loaded in 0.014 seconds.
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 359, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 4363, in <module>
    auto_scale()
  File "/app/bin/t_modules/t_main.py", line 4332, in auto_scale
    prefs.scale_want = window_size[0] / logical_size[0]
                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
`

**Comment by Taiko2k** [comment]
Try these steps:
 1. Go to your user data directory, in this case its `/home/fourbythree/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox`, and delete any file named `window.p`. Try start Tauon again.
 2. If that doesn't work, delete the `window.p`file and and file in that folder named `x11`. (this disables wayland mode)
 3. If that doesnt work, delete the `window.p` and create a blank file named `x11` (no extension, this switches it to wayland mode)

If any of those work can you tell me which one?

**Comment by fourbythree** [comment]
This is what I get after deleting window.p:

Tauon Music Box v7.7.1
Copyright 2015-2023 Taiko2k captain.gxj@gmail.com

No window state file
ERROR CREATING WINDOW!
Window size: [0, 0]
2021
Detected running as Flatpak
Installed as Flatpak
User files location: /home/fourbythree/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/fourbythree/Downloads
Found XDG-Music: /home/fourbythree/Music
Install directory: /app/bin
Database loaded in 0.014 seconds.
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 359, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 4363, in <module>
    auto_scale()
  File "/app/bin/t_modules/t_main.py", line 4332, in auto_scale
    prefs.scale_want = window_size[0] / logical_size[0]
                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero


x11 is a blank file

**Comment by Taiko2k** [comment]
If the x11 file was already there then try deleting it
