### ISSUE TITLE
Crashes when launched caused by segmentation fault

### ISSUE THREAD

**Issue by fourbythree** [Taiko2k/TauonMusicBox#1108]
Every time I launch the app I get a segmentation fault. 

This is from the most recent crash:

(tauon.py:3): Gtk-WARNING **: 10:37:29.174: gtk_disable_setlocale() must be called before gtk_init()
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
Window size: [1120, 600]
2021
Detected running as Flatpak
Installed as Flatpak
User files location: /home/fourbythree/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/fourbythree/Downloads
Found XDG-Music: /home/fourbythree/Music
Install directory: /app/bin
Database loaded in 0.014 seconds.
Scanning for chromecasts...
Start controller server
Start PHAzOR backend...
Using SDL version: 2.28.5
Error loading directory
Error loading directory

(tauon.py:3): Gtk-CRITICAL **: 10:37:30.071: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Applying theme: Rose
/app/bin/com.github.taiko2k.tauonmb.sh: line 14:     3 Segmentation fault      python3 /app/bin/tauon.py "$@"

**Comment by fourbythree** [comment]
Hey, I really love this player but this problem has been persisting. I tried two different sets of ram, and this is the only application that has this problem for me making it unusable. After launching if i try to do anything

**Comment by Taiko2k** [comment]
Looks like some kind of video driver issue. Tauon requires OpenGL acceleration but that seems to not be working here.

I can only suggest doing a system update and `flatpak update`. Otherwise I don't know how to fix it.
