### ISSUE TITLE
some artist does not have an image

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#111]
i know artists pcs are fetched automatically (from last fm i guess) but it would be nice if we could enter those even manually as some artist are missing the picture, maybe just a drag n drop would suffice, to not clutter the menu :)

**Comment by Taiko2k** [comment]
I think that's doable

**Comment by Taiko2k** [comment]
Drag and drop might be a little difficult actually. 

I've now made it so any pictures placed in a folder named `artist-pictures` (in the user data folder) with the file name `artist.png` or `artist.jpg` with "artist" being the name of the artist, will be used instead.

**Comment by legacychimera247** [comment]
great, very good.
