### ISSUE TITLE
python-pylast not installed

### ISSUE THREAD

**Issue by binarygeek119** [Taiko2k/TauonMusicBox#1116]
i keep getting this error when i try to enable lastfm.
optional module python-pylast not installed
![image](https://github.com/Taiko2k/TauonMusicBox/assets/72405030/09e2195a-ec62-46ac-9f7a-744949a6a2ad)

**Comment by Taiko2k** [comment]
I assume you're on Windows? It's a known issue with the latest Tauon release on Windows, I hope to fix it with the next upcoming release.
