### ISSUE TITLE
ram consumption

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#112]
this is more of a curiosity other than something else, about ram consumption.
So, mate usage tells me tauon is using from 500 kb to 3 mb ram, which is wonderful, but if i close the app the ram counter signs about 200 mb less. Tried with gnome usage to and i have the same result, from 500 kb to 3/3.5 mb used by tauon but if i close the up the counter frees at least 10% ram, how comes?who's wrong and who's right?

**Comment by Taiko2k** [comment]
Its certainly going to be the high one. I make mention of expected ram consumption here https://github.com/Taiko2k/TauonMusicBox/wiki/Q&A

I don't know why it would be reporting less. I appears correctly for me in both Gnome Usage and Gnome System Monitor.

**Comment by legacychimera247** [comment]
it's not correct to me but ok that does answer my question...
