### ISSUE TITLE
Album art background style does not change for songs are not in an album.

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#114]
I noticed that for songs that are not part of an album, the background, does not change after the first song. For example, if I had a list of separate single that does not fall within any album, when I come from an album song, the background would change to the current single's cover art. When another single comes up, the background stays the same.

**Comment by Taiko2k** [comment]
OK, I have this fixed. So will be available in the next release.

**Comment by keystroke3** [comment]
Thanks.
