### ISSUE TITLE
Album art as background only for Lyrics view

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#115]
I think it would be nice to have an option just for the Lyrics view.

---
Maybe it will be better not to apply background image for the top and bottom panel.

**Comment by Taiko2k** [comment]
OK, I have added a setting for this for the next version.

![Screenshot from 2019-05-13 00-27-45](https://user-images.githubusercontent.com/17271572/57582201-09767800-7516-11e9-8444-f81543deca97.png)

I increased the effect for this a bit more. I know its still somewhat dim, but I think it kinda looks better this way, and also making it brighter would take some technical reworking.
