### ISSUE TITLE
Artist images no longer work (last fm)

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/TauonMusicBox#116]
Looks like last.fm have decided its been too long since they last gave a :fu: to their userbase and have withdrawn this functionality from their API. So, artist list and artist info (in all current versions) will no longer function as expected. All players that use last.fm for artist images will be affected.

Might have to look into another service for this.
___

Possible replacement API's:

 - **Discogs**: Less images for rare artists. Images more portraits than stylized. Requires user key/login?
 - **Fanart.tv**: Less images for rare artists.

___

Update: I have sourcing from fanart.tv working. Unfortunately in testing, it seems to only have around 10% of the range of images last.fm had.

___

Update: I have added Discogs sourcing. It has many more images. They way I've set it is disabled by default and requires the user entering an account token.
In my testing, using Discogs for images fills list to about 80% for generally common artists.

**Comment by c032** [comment]
Is scrapping considered off-limits? Taking a very quick glance it seems like you can get the image by looking for an element matching the `[itemprop="image"]` CSS selector on the page.

**Comment by Taiko2k** [comment]
@c032 We still use the API for scrobbling, so its probably best we still abide by their ToS and play nice.

**Comment by Taiko2k** [comment]
Ive got both Fanart.tv and Discogs sourcing available now, this generally covers most common artists.
