### ISSUE TITLE
v4.2.2 wont start

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/TauonMusicBox#117]
Tauon Music Box
v4.2.2
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/user/.local/share/TauonMusicBox
Install directory: /opt/tauon-music-box
Locale detected: ('es_CO', 'UTF-8')
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 321, in <module>
    lang = gettext.translation('tauon', os.path.join(install_directory, "locale"), lc)
  File "/usr/lib/python3.7/gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'tauon'

**Comment by Taiko2k** [comment]
Oops, left some code for debugging active, sorry about that. I've push out an update to fix.

**Comment by legion1978** [comment]
thanks!
