### ISSUE TITLE
Could you add an edit feature to rename individual songs?

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#118]
Sometimes the player cannot find song lyrics or artist info because the naming scheme is wrong. Problem is, when I want to edit the name of the artist I don't have an option to rename the song or the artist for that particular song. I am forced to use picard which loads all the songs in the library. This is inconvenient because my music library is quite large.

**Comment by Taiko2k** [comment]
I assume you must have lots of tracks in a single folder right? (Just to clarify, its intended to only load tracks from the same folder)

Adding tag editing would be a rather major feature to implement... I think it might be better to try improve loading of Picard. Maybe making it so holding <kbd>Shift</kbd> when clicking `Edit with Picard` only opens with the single selected track?

**Comment by Taiko2k** [comment]
Holding shift currently won't work. I only meant it as a proposed solution.

You can toggle the artist list by right clicking the top corner button (the one that opens the left side panel) Unfortunately thumbnail sourcing is currently broken in the latest release, so no images will appear.

**Comment by keystroke3** [comment]
Ok, thanks. Holding shift is a good proposition.

**Comment by Taiko2k** [comment]
This shift hold adjustment is now live. Also you can now make a multi-selection and launch Picard from the selection context menu.
