### ISSUE TITLE
Is it possible to see and change or add keyboard shortcuts?

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#119]
I have been searching for the mini player for ages now and cannot find it. I wanted to know if there is way to see all the shortcuts supported and if it would be possible to change them or and new ones if possible.

**Comment by Taiko2k** [comment]
I have a list here https://github.com/Taiko2k/TauonMusicBox/wiki/Keyboard-Shortcuts May not be completely complete, but I think it mostly is.

As for remapping, all shortcuts are currently hard-coded, so its currently not possible. I'm not sure how best to approach this. I wonder if user mapping is ultimately necessary... or if we could have a single mapping that mostly suits everyone.

As for adding, are there any functions that currently don't have a keyboard shortcut that you think should?

**Comment by legion1978** [comment]
hello there

mapping should be done at some point :) 
there are some keys that simply dont work for me.. 
for instance, in the list above you have Go to playing [ " ]. i cannot use that, since it implies actually using shift+2 which does nothing .. same goes for ; + - and other keys. 
and having a single key list to cover all user needs.. i dont think itll be suitable for everyone, really.

also, i think i mentioned it before, the tab key should cycle through all display modes..
so yeah, user key mapping would be useful.

**Comment by Taiko2k** [comment]
@legion1978 I had not considered different keyboard layouts. Mapping may be important then. I think ill look at having some kind of config file for key mapping.

**Comment by keystroke3** [comment]
> As for adding, are there any functions that currently don't have a keyboard shortcut that you think should

I wish there was a shortcut to go to mini mode that did not involve the mouse, I also wish there would be a way to toggle start and stop of broadcasting using the keyboard. 
Thanks for the mini mode

**Comment by Taiko2k** [comment]
This feature is now live, you can open the keymap file by going `MENU` > `Settings...` > `Function` > `Open keymap file` Then you can adjust it from there. Hopefully it makes sense.

**Comment by awsms** [comment]
> This feature is now live, you can open the keymap file by going `MENU` > `Settings...` > `Function` > `Open keymap file` Then you can adjust it from there. Hopefully it makes sense.

Damn I didn't know about it! I just tried to set
`cycle-playlist-left Ctrl Tab` but looks like this don't work. I already tried to set `cycle-playlist-left` value to Tab only and I removed Tab for `toggle-gallery-keycontrol`, didn't work either. Do you have any idea why? :s

**Comment by Taiko2k** [comment]
@awsms 
>  I just tried to set cycle-playlist-left Tab Ctrl but looks like this don't work.

Oh, I see, that *should* work but there's currently a bug that causes `cycle-playlist-left` and `cycle-playlist-left` to not be bind-able to other keys. Ill have this fixed for the next release.
