### ISSUE TITLE
Media-keys not changing track

### ISSUE THREAD

**Issue by ghost** [Taiko2k/TauonMusicBox#12]
Hello! I'm currently on Debian, XFCE running Tauon 3.2.2

I don't know why the media keys do nothing, would be neat to have this resolved.

**Comment by Taiko2k** [comment]
I used to hook key input directly from the X server. But I didn't get the feeling this was a great way of doing things. GNOME and KDE are both providing media player control themselves now. So I removed that functionality to clean up some dependencies.

Unfortunately it means media keys won't work out the box on other desktop environments... But you can add the shortcuts manually in XFCE.

If you go to *Settings Manager > Keyboard > Application Shortcuts*

You can set the following commands, and bind them to any shortuct/key:

`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tauon /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause`

`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tauon /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop`

`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tauon /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next`

`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tauon /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous`

BTW I just found a bug that conflicts with this causing it to not work sometimes, Ill need to fix that, but you can work around it by making sure the notifications setting is **disabled** in Tauon, go to *Menu > Settings... > View > Show track notifications*

**Comment by Taiko2k** [comment]
But indeed, this isn't a great solution. Ill restore native support in the next release.

**Comment by Taiko2k** [comment]
Thanks for the kind words. And apologies I haven't provided more of an ideal solution here.
