### ISSUE TITLE
Is there a way to add album cover art?

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#120]
So I have a song that is missing cover art. I could edit it in picard, but that will load up all the songs in the folder as discussed in the previous issues. I want to know if there is a way for me to attach the cover art manually, the same way I am able to search for the cover art on google, but within the app.

**Comment by Taiko2k** [comment]
Downloading images manually to the associated folder is the intended way of getting art. There's no current way of embedding an image to a file within the app (only removal). It's for now not a feature I plan on adding.

**Comment by Taiko2k** [comment]
Ill close this now. I have added a cover art download feature, but I don't have plans to make it embed files. (Due to complexity)
