### ISSUE TITLE
Cannot enter mini-mode when window is maximized

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/TauonMusicBox#122]
Hello
Well, cant go mini by double clicking at the bottom or with a hotkey set. i cant even access right click menu actually, if the window is maximized (both system and own window decoration (manjaro linux)

**Comment by Taiko2k** [comment]
I had entering mini-mode from maximized intentionally disabled due to a bug... but I've gone ahead and fixed and committed that now.

**Comment by legion1978** [comment]
cool!
