### ISSUE TITLE
Questions about Discord presence

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#128]
I saw in the releases that Discord presence was added but only if Flatpak is used for Discord too:

> Note: Only Flatpak Discord can connect with Flatpak Tauon. (And host installs can only be used with each other)

So my questions are:

- What is meant with "host installs"? That I'd have to run Tauon from source?
- Why can't the presence work with Flatpak Tauon and non-Flatpak Discord?

**Comment by Taiko2k** [comment]
> What is meant with "host installs"? That I'd have to run Tauon from source?

I simply meant to say installed on your system as non-flatpak (e.g. `.deb` etc)

> Why can't the presence work with Flatpak Tauon and non-Flatpak Discord?

You can see technical details here https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

That command under the title *Regular (unsandboxed) apps* there will allow **Flatpak Discord and non-Flatpak** communication. But I don't fully understand how that command is intended to be used exactly. (you would need to run it after every system restart)

As for **Flatpak Tauon and non-Flatpak Discord**... hmm. You could try run:
`sudo flatpak override com.github.taiko2k.tauonmb --filesystem=xdg-run/discord-ipc-0`
I think that works. After that, you would always just need to start Discord *before* starting Tauon if you want presence to work.

**Comment by Bauke** [comment]
Running that override command does seem to work! I'll have to see if it sticks around after restarts and what happens when Tauon starts before Discord but doing it the way you described works! I guess this issue can be closed then. :smile: Keep up the good work!

**Comment by EddieEldridge** [comment]
The override command worked for me, thank you.
