### ISSUE TITLE
Reload theme (or previous theme) hotkey

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#129]
When making a theme it would be useful to be able to easily reload it and see the changes as you do them. Right now (as far as I can tell anyways) the only hotkey available is "Next theme" which is great but if you have a bunch of themes you'd have to press that a bunch of times. So would it be possible to add a "reload theme" hotkey and/or a "previous theme" hotkey? Doing next->previous is basically the same as reload but right now there's no previous theme hotkey so you have to go into the settings each time to change.

**Comment by Taiko2k** [comment]
Okay, I have added `cycle-theme-reverse` and `reload-theme` key functions and assigned  `reload-theme` to <kbd>F10</kbd>.

So will be available in the next release
