### ISSUE TITLE
Error: missing ffmpeg.exe from '/encoder' directory

### ISSUE THREAD

**Issue by f242** [Taiko2k/TauonMusicBox#130]
When i trying to encode i have error
i put ffmpeg.exe near tauon.exe - fail
i create in program's folder 'encoder' subfolder and put ffmpeg into it - fail

**Comment by f242** [comment]
fix manual please

![image](https://user-images.githubusercontent.com/10371194/59547101-c27b0880-8f41-11e9-8c71-fba2817d786d.png)


all work when put ffmpeg.exe to \tauon\user-data\encoder

**Comment by Taiko2k** [comment]
Yes, I should update the UI to better reflect this.
