### ISSUE TITLE
The queue panel area now persists when empty

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#131]
So there is only half of the panel is now available for the playlists? Not great if you have many playlists. And what if the user never uses the queue feature, that area will be always empty.

I am thinking about the new queue panel similar to the artist panel. Also there might be a queue button with a number of tracks indicator in it.

![alt text](https://i.imgur.com/pD3UMNl.png)

**Comment by Taiko2k** [comment]
I agree, there should be a way to have the previous behavior. Perhaps a setting in the settings might be the simplest solution.

I had thought about having button indicators to toggle the elements in that side panel, like at the bottom of the panel. Could be nice... though I also want to avoid cluttering the UI too much.

A right-click menu to toggle things might also work, but I don't think there's any place left for another right-click menu that is intuitive.

**Comment by Solarunit** [comment]
> Actually... Simply adding an option like `Hide when empty` / `Show when empty` to the queue menu might work.

The previous behavior wasn't perfect but it was possible to see playlists and Queue both at the same time.

> ...Though also being able to disable the playlist list would be good for anyone who doesn't use them and just wants the panel reserved for the queue. Perhaps in addition to the above `Hide when empty` function, the right click of the top corner button, instead of toggling, provides a menu to switch views, from a list such as:
> 
>     * Artist List
> 
>     * Playlists + Queue
> 
>     * Playlists Only
> 
>     * Queue Only
> 
> 
> That would also have the benefit of allowing other elements to be added the panel in the future.

I like it. Toggling by right click is hard to discover. 
+ hotkeys to switch views in the side panel

**Comment by Solarunit** [comment]
> I had thought about having button indicators to toggle the elements in that side panel, like at the bottom of the panel. Could be nice... 

Like this but horizontal and at the bottom of the panel?
 
![alt text](https://i.imgur.com/3hQqng7.png)


>though I also want to avoid cluttering the UI too much.

I totally agree

**Comment by StrangeSeasOfThought** [comment]
I like that I can switch between artist view and queue in a single mouse click. Whatever the changes, I'd prefer to keep it within a single click.

(I also have 'playlists as tabs' enabled. So there's already another way I can interact with them.)

**Comment by StrangeSeasOfThought** [comment]
After thinking some more about it... a solution I came up with that wouldn't require ui changes outside settings (maybe even config would be enough), would be for the user to be able to give weight to playlist vs. queue, like a scale. Let's say current behavior is 50:50, then e.g. 70:30 would increase the playlist area vertically and decrease queue. 30:70 would do the opposite. 100:0 would remove queue. 0:100 playlist. Maybe via a slider in settings.

**Comment by Solarunit** [comment]
The queue panel right now is called **Up Next** so it just quick info about what tracks are next.
Because it is not a real playlist it has some limitation (number of tracks, no scrollbar, etc).  

So i have some (probably bad) ideas.

- standalone queue panel (not visible when empty)
- queue panel window (queue manager)
- special queue playlist

**Comment by Taiko2k** [comment]
These ideas might be good to keep in mind, but for now, I've simply added some settings (Under `Settings...` > `View`) for two elements, which I think work fairly well. 

You can chose between showing the queue when empty or not, and now disable the playlist list if you want the entire panel reserved for the queue.

**Comment by Solarunit** [comment]
Thanks! I prefer the previous behavior
