### ISSUE TITLE
Global search to playlist + various suggestions

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#132]
Bascially a faster way to add tracks from global search to either queue (and then save as playlist) or directly to a new playlist (maybe even both?). Middle button/scroll wheel click?

Let's say I want to build a _rain_ themed playlist and global search for _rain_, right now I'd have to repeat this several times.
Using quick find is somewhat faster, but global search would be more convenient.

**Comment by Taiko2k** [comment]
If I understand correctly, you mean create a new playlist from the search results? You can do this from the quick search by using <kbd>Shift</kbd> + <kbd>Enter</kbd>. This function could be added to the global search... but I'm not sure how that should interact with non-track elements like genres, albums and artists.

**Comment by StrangeSeasOfThought** [comment]
Quick find shift + enter adds everything to a new playlist, but then I'd have to delete half the tracks again (Rain vs. train vs. rainbow vs. rain in album title vs. artist named Rain).

Instead I'd like to cherry pick some of the listed songs I can find via global search. So when I type in _rain_ I want to be able to use e.g. scroll wheel click multiple times to add the tracks about rain (and therefor avoid the ones about trains) to queue or new playlist or maybe even both options (requires another hotkey). The global search overlay would need to persist as opposed to left click (closes overlay and plays track) or right click (closes overlay and shows track in playlist).

**Comment by Taiko2k** [comment]
Ive added an experimental feature, now when holding <kbd>Ctrl</kbd> and clicking in the global search, the item will be added to the end of the **viewed playlist**. An indicator shows if the track is already present in that playlist.

**Comment by StrangeSeasOfThought** [comment]
It's perfect, thanks!

- Playlist: 

1. What do you think about adding number of tracks and total duration to where _End of Playlist_ text appears?

2. I noticed that right click track doesn't give the option to remove the track from playlist. It only appears if the entire album is selected.
I know that I can use DEL instead, but I feel like this should be possible via mouse, too.

- Queue: Right click option to shuffle the queue once.

**Comment by StrangeSeasOfThought** [comment]
- Enhancement, Playlist/Shuffle: Shift right click in playlist to ban tracks from being picked up by shuffle.

**Comment by StrangeSeasOfThought** [comment]
> Ive added an experimental feature, now when holding Ctrl and clicking in the global search, the item will be added to the end of the **viewed playlist**. An indicator shows if the track is already present in that playlist.

I use this all the time now to create playlists, so thanks again! I think, it'd be great to also have the same functionality for adding tracks to queue.

**Comment by Taiko2k** [comment]
> think, it'd be great to also have the same functionality for adding tracks to queue.

Perhaps <kbd>Ctrl</kbd> + <kbd>Alt</kbd> shortcut?

> Maybe a way to list artists in global search. Something like keyword + first letter, e.g. 'artist a' to list all artists whose name starts with A. And so on.

Yes I had thought of this before too, but never got around to implementing it

> Somewhat increase the font size of artist name in showcase. It's too small on certain resolutions (and viewed from a distance), especially when compared to the bold + larger sized track title.

Yeah I could bump the font up a step or two

**Comment by StrangeSeasOfThought** [comment]
> Perhaps Ctrl + Alt shortcut?

I'd probably avoid Ctrl because of the playlist indicator.

**Comment by StrangeSeasOfThought** [comment]
- When using middle mouse button in playlist to add track to queue, also select the track at the same time.

**Comment by Taiko2k** [comment]
> Can you please tell me the line(s) where I can edit/comment out/remove the blank area at the end of the artist list view

Indeed, this is intended to show that you are at the end of the list. If you want to change the code, do a search for this line:  
`range = (h // self.tab_h) - 1` in tauon.py. The number at the end of that line determines the extra space at the end, so you'd want to change that to:  
`range = (h // self.tab_h) - 0`

> Maybe a way to list artists in global search. Something like keyword + first letter, e.g. 'artist a' 

Though I wonder if this is more of an issue of the ranking of the current results? (What is the core issue?)

**Comment by StrangeSeasOfThought** [comment]
Thanks!

> Though I wonder if this is more of an issue of the ranking of the current results? (What is the core issue?)

There is no issue. It's just something I felt like it might be useful to have. You can already list all albums and all tracks by an artist, so, why not have a way to list 'all' artists within global search, too?

**Comment by Taiko2k** [comment]
OK; searching in the format `artist x` should only return artist results now.

**Comment by StrangeSeasOfThought** [comment]
- Issue: After end of queue, when shuffle is supposed to kick in, the last played (= last queued) track is being repeated instead.

So this might just be a case of shuffle randomly selecting the same track again, but it seems to happen noticeably often lately. I'll investigate this further over the weekend, I don't have much time right now.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought I think it would just be coincidence, the queue should be fully disengaged if its empty. I do know of a quirk where if you add items to a small playlist that has already been playing for a while, the new tracks will have a high chance is being played next on shuffle, maybe related.
