### ISSUE TITLE
Right click of the side panel top corner toggle crashes TMB

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/TauonMusicBox#133]
Hi there, since latest update, that right click crashes TMB.

Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 28277, in <module>
    queue_box.draw(0, gui.panelY + pl_box_h, gui.lspw, full - pl_box_h)
  File "/opt/tauon-music-box/tauon.py", line 23050, in draw
    self.draw_card(x, y, w, h, yy, track, fq[i], db)
  File "/opt/tauon-music-box/tauon.py", line 22848, in draw_card
    if fqo[6]:
IndexError: list index out of range

**Comment by legion1978** [comment]
after a couple of restarts (crashes) seems to work. 
did have another error queue-related: 
-added album to queue (middle click on album title list, columns inactive) 
-added another album (after current) 
-middle click on first track of the currently playing album (that song was still playing) 
i got some "thread finished" error and a crash. 
after that, the top left corner right click worked. no output

**Comment by Taiko2k** [comment]
It's probably because you still had items in the queue during the upgrade, and I forgot to allow for that, so having cleared the queue now should solve it.
