### ISSUE TITLE
TauonMusicBox Logo/Icon

### ISSUE THREAD

**Issue by officernice** [Taiko2k/TauonMusicBox#134]
I've looked and looked for an email but could not find it. I am currently working on an icon theme, and I am more or less using Tauon as my main music player. I'm just wondering if the pink/purple is a final icon? I'd love to contribute and help out with it, if it has interest. 

Thank you for your great work!

**Comment by Taiko2k** [comment]
Nope, not final necessarily. I do think that the current icon has issues / is below ideal quality. I'm open to tweaks, derivatives, or even something completely different. If you could help, that would be great.

Btw, you can find my email in the copyright notice, on the license.txt or in the about tab in settings. I just avoid placing it on the main page to avoid spam.
