### ISSUE TITLE
Clicking prev/next song when paused shows the prev/next song being played but plays the paused audio

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#135]
The title might be a little confusing but to reproduce:

- Start playing a song
- Click pause
- Click the next or previous song button
- It shows the song changed, however the audio playing is the song you initially paused

I searched for an issue about this but didn't find anything related.

**Comment by StrangeSeasOfThought** [comment]
> * It shows the song changed, however the audio playing is the song you initially paused

And the new/next song is being scrobbled.

**Comment by Taiko2k** [comment]
I can't replicate this. 

Does it do it every time? Are there any scenarios in which is does not do it? Does the issue persist with both GStreamer and BASS backend modes?

**Comment by Bauke** [comment]
Ah, no. It only happens when using BASS. With GStreamer it behaves like normal.

**Comment by Taiko2k** [comment]
Does it resume playing where it left off as if you had unpaused, or restart the track from beginning?

**Comment by Bauke** [comment]
It starts playing from the beginning again, yeah.

**Comment by Taiko2k** [comment]
OK I figured it out. I was stumped for a bit, but released its a bug in a setting that only defaults to on when in KDE Plasma.
