### ISSUE TITLE
Playlists are not visible when queue is enabled

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#136]
Playlists are not visible when queue is enabled. Only visible part of the playlist half-panel is displayed, scrolling doesn't work.

BTW https://www.omgubuntu.co.uk/2019/06/tauon-music-box-linux-music-player
:smiley:

**Comment by Taiko2k** [comment]
> BTW https://www.omgubuntu.co.uk/2019/06/tauon-music-box-linux-music-player
smiley

Oh! I was wondering where that surge in traffic was coming from. Nice to have the publicity, though I'm not a fan of the quality of journalism in the article.

> Playlists are not visible when queue is enabled. Only visible part of the playlist half-panel is displayed, scrolling doesn't work.

I'm not sure what you mean exactly, could you show me a screenshot? Also, what is the status of these two settings?

![Screenshot from 2019-06-22 15-13-56](https://user-images.githubusercontent.com/17271572/59958798-66dfea80-9500-11e9-95d3-d426d838476b.png)

**Comment by Solarunit** [comment]
Only 9/12 playlists are visible

gif

![alt text](https://ibin.co/4lT3vl6TD1kp.gif)

![alt text](https://i.imgur.com/8TaLdQi.png)

-----
I noticed that ctrl+t hotkey is missing in the wiki

**Comment by Taiko2k** [comment]
> I noticed that ctrl+t hotkey is missing in the wiki

Added now

> Only 9/12 playlists are visible

Ah okay, I understand now. I've found the issue and committed a fix.
