### ISSUE TITLE
[Flatpak] Drag and drop from external drive fails?

### ISSUE THREAD

**Issue by gibranlp** [Taiko2k/TauonMusicBox#137]
Hi,

I have just discovered this app which is great and looks great btw.

This are a few issues i have encountered since i have been using it.

To clear things up i'm using elementary os, with all my music files on a different internal hard drive on which i have linked the music folder to ~/Music in order to play it.

When i edit a song(s) with picard, the changes do not take place on Tauon, and when i click "F5" to update the status of the recent tag changes from Picard, Tauon just crashes, i also tried rescanning the music folder which Tauon does with no tag changes at all.

- Tried Reload Metadata no success
- Also tried Rescan tags with no success.
- I have checked with other music program to check if the tags changes is made to the music files, and it is correct but not in Tauon.

When i try to select in the MENU the interface Track + Art (first one) Tauon just crashes.

A "love selected" shortcut would be awesome.

When i love new tracks they don't appear on the Loved Playlist, i have to delete the playlist and create a new Loved playlist in order to get the new loved songs.

That's all i have found for now. Great app

Cheers.

**Comment by Taiko2k** [comment]
> When i try to select in the MENU the interface Track + Art (first one) Tauon just crashes.

Can you show me the output from terminal when it crashes?

To run from terminal: `flatpak run com.github.taiko2k.tauonmb`

> A "love selected" shortcut would be awesome.

Sounds like an alright idea

> new tracks they don't appear on the Loved Playlist, i have to delete the playlist

Its not unintentional behavior exactly, for better or worse.
