### ISSUE TITLE
Random Track always plays next track in album if Random Albums is/was selected

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#141]
When you have selected "Random Albums" under the shuffle icon (doesn't matter if it's enabled or disabled), when you use "Random Track (hotkey Colon)" it will always play whatever song is next in the current album. However, if you're on the last track in the album then it will actually go to a random album's first track (even if Random Albums is disabled).

**Comment by Taiko2k** [comment]
I see. I will have this fixed.
