### ISSUE TITLE
[Feature Request] Allow to love tracks via DBus

### ISSUE THREAD

**Issue by darkermatter** [Taiko2k/TauonMusicBox#142]
Hi, first off, thanks for such an amazing music player!

It would be great if there was a way to do this:
```
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tauon /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.LovePlaying
```

**Comment by Taiko2k** [comment]
Its not part of the specification, but I suppose there's no harm in adding this.

Ive now commited the `LovePlaying` method as you described and also `UnlovePlaying`. I've also added a property named `tauon:loved` (type of bool) to the metadata properties.

**Comment by darkermatter** [comment]
Wow! :+1: 

Will it be available in the Flatpak build?

**Comment by Taiko2k** [comment]
> Will it be available in the Flatpak build?

Yes, I don't foresee any problems there. Though it may be a few days before I push an update. I usually do one every week or so.

**Comment by darkermatter** [comment]
Great! I look forward to trying it. I just discovered the Plex integration in the wiki. The more I use the app, I discover more amazing stuff.

Thank you!
