### ISSUE TITLE
KDE Plasma 5.16.x notification

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#143]
With the release of KDE Plasma 5.16.x, the app's _track change notification_ looks like this:

![plasma](https://user-images.githubusercontent.com/43582772/60604370-d59e2d00-9db7-11e9-83c5-2c8790ad2181.png)

`        Notify.init("Tauon Music Box Transcode Notification")`

(Speaking of notifications, any idea why KDE Connect isn't transmitting/receiving the album artwork on Android? Is this a Tauon issue, or KDE Connect, mpris?)

**Comment by Taiko2k** [comment]
That shouldn't be there, though I guess I never thought / know that would be used for anything. I've changed it to just say `Tauon Music Box` now.

As for KDE Connect, it seems to be working fine for me. I'm using GSConnect, so maybe its a KDE issue. If you're getting artwork in the desktop mpris thing, then I doubt its an issue on Tauon's side.
