### ISSUE TITLE
Add this app to more stores!

### ISSUE THREAD

**Issue by aimproxy** [Taiko2k/TauonMusicBox#144]
Hi, I saw your application will you be able to publish in the snapcraft and in the elementary App Center?

**Comment by Taiko2k** [comment]
Unfortunately its not possible to publish Tauon Music Box on the elementary App Center as they only accept native GTK3 apps (even Qt and Electron based apps will be rejected).

As for Snap, I've looked into it, but it seems like its a bit of a hassle to get working, especially just for one distro. I ran into problems trying to get it working. And also, quoting the Wikipedia page: 

> Using snap is more time-consuming than Flatpak  :open_mouth:

 Anyway, I think Flathub is the store with the most potential. And the Flatpak package is more or less working OK as it is.
