### ISSUE TITLE
"Error connecting to Discord"

### ISSUE THREAD

**Issue by MJGHD** [Taiko2k/TauonMusicBox#145]
Hi,

I'm using both FlatPak Discord and FlatPak Tauon, yet they don't seem to want to connect to one another, with it just saying "Error connecting to Discord" when I click on "Show playing on Discord". When I run Tauon through the commandline with "flatpak run..." it says "Attempting connection to Discord" and that's it.

I'm running Debian 10 Buster (64 bit) with GNOME.

**Comment by Taiko2k** [comment]
I have been able to replicate the issue.

Flathub recently changed the necessary permissions needed for Discord communication, but I seems like I had forgotten a necessary step in updating for it.

I have updated the Flatpak with a fix for this now.

(If it still doesn't seem to work after the update, try make sure you have exited and restarted both Discord and Tauon)

**Comment by MJGHD** [comment]
Works perfectly after the update. Thanks for this great project.
