### ISSUE TITLE
[Bug] Another start up error

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#146]
I have installed the latest version of Tauon v4.5. There is a syntax error when starting it.
![Screenshot from 2019-07-15 21-03-16](https://user-images.githubusercontent.com/37796862/61237980-62e06a80-a744-11e9-8299-3fcbdea0b802.png)

**Comment by Taiko2k** [comment]
I think this is likely because you installed the wrong version of hsaudiotag, you need hsaudiotag3k. That one without 3k is the python2 version.

**Comment by keystroke3** [comment]
Running `pip install hsaudiotag3k` gives me `ERROR: No matching distribution found for hsaudotag3k
`  
I am using python 3.7 as default

**Comment by Taiko2k** [comment]
Hmm, how about if you call `pip3` instead of `pip`?

**Comment by keystroke3** [comment]
> Hmm, how about if you call pip3 instead of pip?  
I this works. I should change my system to always use pip3.

> Though, the AUR version specified in the PKGBUILD should work? Did it get removed somehow?  
I just installed it on my new machine. I did not edit any AUR files or PKGBUILD

**Comment by Taiko2k** [comment]
How did you install it, using an AUR helper?

**Comment by keystroke3** [comment]
Yes I used yay. Is there a difference if I use a helper? I also had to manually install `pygobject` and `discorgs_client`. Those errors came before the `hsaudiotag` error

**Comment by Taiko2k** [comment]
*Should* all work the same. Seems like you have some kind of issue somewhere.

**Comment by keystroke3** [comment]
I have no idea what the problem could be. The player installs without any error. Since I raised an issue here, I have reinstalled my OS twice. So I don't know how I can have the same errors on three different set ups. I don't even know how to debug the issues.

**Comment by Taiko2k** [comment]
Yeah IDK, maybe an issue with Yay. To debug... well what I might have done is try install the PKGBUILD and dependent AUR packages all manually and see if I run into any errors.

**Comment by keystroke3** [comment]
I will try and do that. I will also check to see if other helpers have the same issue. I might even try manually building AUR packages. Thanks you can close the issue now.

**Comment by Taiko2k** [comment]
Sure. I use the helper `trizen` so im sure that one works as expected.

Just to help, the specific dependencies that are from the AUR are `python-discogs-client`, `python-hsaudiotag3k` and `python-stagger`
