### ISSUE TITLE
XDG_MUSIC_DIR

### ISSUE THREAD

**Issue by tonyrh** [Taiko2k/TauonMusicBox#147]
Hi, my music folder is not `$HOME/Music` as I changed it to something else setting `XDG_MUSIC_DIR`. This works with Nautilus and Rhythmbox, i.e. when I click the shortcut named "Music" in Nautilus I go to the right directory (btw that's on a different drive than `$HOME`) and Rhythmbox adds the right directory to its library. 
Tauon however always scans the Music folder in the user's home, disregarding XDG settings. 
Could you fix that?
Some info on [xdg-user-dirs](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/).

**Comment by Taiko2k** [comment]
Okay, I've pushed a fix for this. Also fixed the downloads directory one as well.

**Comment by tonyrh** [comment]
Trying it right now, works fine thanks!
