### ISSUE TITLE
queue feedback

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#148]
v4.5.2 
- Added toast when adding to queue for improved feedback

Hi, just curious what is that?

- [Linux] Added setting to override subpixel font rendering to on

available only in config file?

**Comment by Taiko2k** [comment]
Previously, if the queue was closed, in some cases there would be no feedback for adding something to the queue at all. So this feature, (only when the left panel is closed) shows a popup box of what track you added.

**Comment by Taiko2k** [comment]
>available only in config file?
It should appear under the `window` subcategory under View.

**Comment by Solarunit** [comment]
>So this feature, (only when the left panel is closed) shows a popup box of what track you added.

Ahh, I like it.

>Tell me if it works for you!

Looks the same for me. How to check if rgb rendering is already applied? I am on Solus.

**Comment by Taiko2k** [comment]
> How to check if rgb rendering is already applied?

I find the easiest way is to take a screenshot and zoom in. The difference looks like this:

![compare](https://user-images.githubusercontent.com/17271572/51103576-3062bd00-1848-11e9-8582-45cff2338bba.png)

**Comment by Solarunit** [comment]
I have the same results. The setting is enabled on the left I guess =)
