### ISSUE TITLE
Error when trying to launch

### ISSUE THREAD

**Issue by iamrobox001** [Taiko2k/TauonMusicBox#152]
I use Arch linux with bspwm and rofi for launching applications.
I installed Tauon Music Box from the AUR repository
When I try to open it nothing shows up
So I tried to use a terminal to open it which gives me the following errors:

```
[ranger@BlueRingedOctopus ~]$ python --version
Python 3.7.4
[ranger@BlueRingedOctopus ~]$ python2 --version
Python 2.7.16
[ranger@BlueRingedOctopus ~]$ python /opt/tauon-music-box/tauon.py
Tauon Music Box v4.6.0
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/ranger/.local/share/TauonMusicBox
Install directory: /opt/tauon-music-box
/opt/tauon-music-box/t_modules/t_topchart.py:3: PyGIWarning: Pango was imported without specifying a version first. Use gi.require_version('Pango', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Pango/opt/tauon-music-box/t_modules/t_topchart.py:4: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairoNo existing star.p file
Error loading save file
Database loaded in 0.0 seconds.
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 2241, in <module>
    if os.path.isdir(music_directory):
  File "/usr/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[ranger@BlueRingedOctopus ~]$
```

**Comment by Taiko2k** [comment]
Looks like a bug. Ill fix it. 

It's triggered by failing to verify the music directory exists. Did you delete your home `~/Music` directory? Or perhaps the XDG_MUSIC_DIR target in `~/.config/user-dirs.dirs` is miss-configured. If you can amend either of those, it should start working.

**Comment by iamrobox001** [comment]
> Looks like a bug. Ill fix it.
> 
> It's triggered by failing to verify the music directory exists. Did you delete your home `~/Music` directory? Or perhaps the XDG_MUSIC_DIR target in `~/.config/user-dirs.dirs` is miss-configured. If you can amend either of those, it should start working.

I don't have a ~/Music directory or user-dirs.dirs file. I do have a ~/music which only contains symlinks to other directories. Will I need to create the ~/Music directory? Can I specify the other one which I already have?

**Comment by Taiko2k** [comment]
As a quick solution, you could just create an empty `~/Music` folder. Alternatively, clone this repo (which now has a fix applied for finding lowercase `music`) and manually update (it should be currently safe to do):

1. `git clone https://github.com/Taiko2k/TauonMusicBox.git`
2. `sudo cp TauonMusicBox/tauon.py /opt/tauon-music-box`
3. `rm -rf TauonMusicBox`

**Comment by iamrobox001** [comment]
> As a quick solution, you could just create an empty `~/Music` folder. Alternatively, clone this repo (which now has a fix applied for finding lowercase `music`) and manually update (it should be currently safe to do):
> 
>     1. `git clone https://github.com/Taiko2k/TauonMusicBox.git`
> 
>     2. `sudo cp TauonMusicBox/tauon.py /opt/tauon-music-box`
> 
>     3. `rm -rf TauonMusicBox`

This fixed it!
