### ISSUE TITLE
Please bring it to snapcraft.io 

### ISSUE THREAD

**Issue by keshavbhatt** [Taiko2k/TauonMusicBox#154]
https://snapcraft.io is consumed by millions of Linux users around the world, it would be nice to have the app packaged in snap format, for help feel free to ask anything in friendly forums anytime https://forum.snapcraft.io 
thanks. 

I also maintain one of my app here https://snapcraft.io/olivia-test

**Comment by SAOPP** [comment]
Yes guys I agree with it too, for example I have an issue right here with install into my elementaryOS, after choosen for the system or user the install process is not showing any thing else... just stopping at this point.

**Comment by Taiko2k** [comment]
@SAOPP If you're interested in investigating further with Flatpak, make sure you check the instructions on this page https://flatpak.github.io/setup/elementary%20OS/ 

Then try install via the command line: `flatpak install flathub com.github.taiko2k.tauonmb`

**Comment by keshavbhatt** [comment]
@Taiko2k oh so you are a flakpak guy 😂😂😂
