### ISSUE TITLE
Issue with micro mode

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#158]
When entering micro mode for the first time, the app skips to the next track.

**Comment by Taiko2k** [comment]
I haven't encountered this issue myself, but I've now pushed a change I think might fix it.

**Comment by StrangeSeasOfThought** [comment]
Now it jumps the current track 2+ mins forward.

**Comment by Taiko2k** [comment]
Ive pushed another fix now. I think that should fix it.

**Comment by StrangeSeasOfThought** [comment]
> I think that should fix it.

Yep, thanks!

**Comment by StrangeSeasOfThought** [comment]
> Now it jumps the current track 1-3 minutes forward.
> 
> Edit: Ok, this seems only to happen when the window is maximized.

Still happening.

**Comment by Taiko2k** [comment]
OK this time for sure.

**Comment by StrangeSeasOfThought** [comment]
I don't use double click but right click menu.

**Comment by tiotrom** [comment]
Sorry to post this here, but how do you enable the "micro" (mini) mode? Thanks

**Comment by Taiko2k** [comment]
@tiotrom 
> how do you enable the "micro" (mini) mode? 

Right click the bottom panel menu button to reveal a menu. (Or right click the bottom panel title area). Hmm... I should probably document this somewhere.

**Comment by tiotrom** [comment]
aa ok I think you need to make it a lot more intuitive ;) - maybe add the option to the menu or add a special button - cheers!
