### ISSUE TITLE
Importing XSPF playlists...

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#159]
...created by third-party apps doesn't work. I can only import XSPF playlists created by Tauon.

**Comment by Taiko2k** [comment]
I just did a test with one exported from Clementine and it seemed to work.

Perhaps try create a small identical playlist in Tauon, open them both in a text editor and see if we can isolate the difference that causes one to fail.

**Comment by StrangeSeasOfThought** [comment]
It's good to know that Clementine works, but for now I'm trying to avoid installing another app.
Besides Tauon, I have two more apps that can export XSPF playlists:

1) Kid3, which I use for tagging and has a useful feature to filter tracks.
2) VLC, which can import m3u playlists and save them as XSPF.

Importing XSPF playlists created by either Kid3 or VLC into Tauon fails and an error message pops up. All target tracks are already imported into Tauon.

Export Tauon.xspf -> open/play in VLC -> save as VLC.xspf -> import into Tauon doesn't work for example.

**Comment by Taiko2k** [comment]
Yeah, I need to improve how the files are parsed. It currently expected it to be structured in an exact way.

**Comment by Taiko2k** [comment]
I tried creating a playlist using kid3, but the locations were only relative to the local folder. I guess I'll say that this type of playlist isn't currently intended to be supported (I don't particularly see a use case for them).
