### ISSUE TITLE
Not playing with BASS

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/TauonMusicBox#160]
I noticed a couple of versions ago that TMB stopped working with BASS, so i changed it to GStreamer, but its not ideal. i get this:

ALSA lib dlmisc.c:287:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/alsa-lib/libasound_module_pcm_pulse.so ((null): /usr/lib/alsa-lib/libasound_module_pcm_pulse.so file does not exist)  
Channel not playing when should be, tring to restart
...

what exactly should i install to fix it?

thanks

**Comment by Taiko2k** [comment]
On my Arch Linux machine that file is owned by the `alsa-plugins` package. Maybe try install that. Sounds like I need to mark that package as a dependency.

**Comment by legion1978** [comment]
mmm indeed, im on manjaro and that package is already installed (actually both alsa-plugins and lib32-alsa-plugins). any ideas?

**Comment by Taiko2k** [comment]
does `/usr/lib/alsa-lib/libasound_module_pcm_pulse.so` exist for you?

**Comment by legion1978** [comment]
no. not even that folder. weird.

**Comment by Taiko2k** [comment]
Looking under Package Contents on `https://www.archlinux.org/packages/extra/x86_64/alsa-plugins/` it says it should exist. Maybe try re-install the package?

**Comment by legion1978** [comment]
if i try to uninstall those, pacman tries to also uninstall half the system packages X)))
i guess itll be TMB with Gstreamer for now...

**Comment by Taiko2k** [comment]
Just install again I mean `sudo pacman -S alsa-plugins`

**Comment by legion1978** [comment]
Ok so i just downloaded that file from your link (btw alsa-utils is not in the aur site) and placed the folders where they should be and its working. very odd really. 
thanks
