### ISSUE TITLE
[Bug] Tauon closes when I start playing any song.

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#161]
I started tauon today and wanted to start playing music, but when I click on any song, tauon shuts down. I launched it from the terminal, and this is what I got:
![error crop](https://user-images.githubusercontent.com/37796862/63007754-ec8d7000-be89-11e9-82f2-f86328143e65.jpg)
I cleared all the data from `~/.local/share/TauonMusicBox` and `~/.cache/TauonMusicBox` and then reinstalled it, but nothing changed. I tried launching it from the file manager, but the song did not play.  
I tried looking at the code, but was overwhelmed by the size of it. My debugger did not pick any problems.
Forgot to mention that I am now using ArcoLinux with bspwm. I stopped using Manjaro.

**Comment by Taiko2k** [comment]
This is a hard one. Being a segfault it wont be exactly a bug in Tauon itself, rather a issue with a dependency. Probably something to do with BASS since you say it happens when you play a song. 

Firstly I'd make sure your system is up to date.

Try switch to the GStreamer backend and tell me if that works.

**Comment by keystroke3** [comment]
> Try switch to the GStreamer backend and tell me if that works. 

I did, I checked some previous issues on this page, and saw someone mention that. I just forgot to add it to the report. I have made sure that all my software is up to date, both in the main repos and AUR.

**Comment by Taiko2k** [comment]
Hmm. If it crashes in GStreamer mode probably not a issue with bass then.

What I'd try is, maybe install the player `lollypop` and test if that works playing music (Since it has very similar dependencies to Tauon with GStreamer), and also with it installed, test Tauon.

Maybe another thing to try, in the `tauon.conf` file, test setting both these settings to false:
```
[app]
enable-mpris = false
enable-gnome-mediakeys = false
```

**Comment by keystroke3** [comment]
Lollypop works fine, no problems. Making the changes in those file does not make any difference either. If I may as, which part of the code is executed when a track is selected? Maybe I can help debug, even with my small knowledge in python. I tried looking at the code but could not figure out what does what.

**Comment by Taiko2k** [comment]
It shouldn't be possible to cause a segfault from just python, but if you edit the code with some `print()` statements we might be able to track it down.

If you wanna get messy... there a function called `def jump` ~ line 3224. (try ctrl+f search for it) When you double click a track to play it, this is the main thing that gets called.

try append
```
print("test")
time.sleep(10)
```
to the end of that function (~line 3251), see if we make it to the end with anything playing.

There's probably a better way, but I'm honestly not that familiar with debugging.

**Comment by keystroke3** [comment]
So this is interesting, it actually works for as long as the `time.sleep(10)` is executing. The output is as such:
`Enabling garbage collecting`  
`test`  
`Set output device as: PulseAudio Sound Server`  
`Open file: <music_file>`
When I increase the timer, the song continues until the timer is up.

**Comment by Taiko2k** [comment]
In that case, I get the feeling the issue might be somewhere else in the UI. Try close any open panels and just go to the basic **Tracks only** view. Then double click a track.

**Comment by keystroke3** [comment]
Yes, I believe it is a UI issue. I changed to track only view with sky theme. It works fine like that, but I no other view works. Could it be a problem with the cover art loading features? because all the other views have the cover art.

**Comment by Taiko2k** [comment]
Indeed that was my thinking too.

Out of curiosity, does `Gallery view` work?

**Comment by keystroke3** [comment]
Nope, I switched to all the view modes but the only on that actually worked was the tracks only view.

**Comment by Taiko2k** [comment]
Even switching to **tracks + art** which shouldn't be showing any art when not playing?

**Comment by keystroke3** [comment]
Switching to **Tracks only** then back to **Tracks + art** works, so long as there is no music playing. Actually, after more testing, all other modes work without music except **Gallary.** When I switch to gallary, only one album art loads before the whole thing crushes.

**Comment by Taiko2k** [comment]
If one album art manages to load... can you create a new playlist with just that track, does that work?

**Comment by keystroke3** [comment]
I could not even see which album it was. It just loaded an image and then it crushed. I created a playlist by dragging and dropping a track to an empty part of the tab bar. When I started playing the track, it crushed.

**Comment by Taiko2k** [comment]
I made a test push to master. Try clone the repo, make a copy of `/opt/tauon-music-box` somewhere local and copy the cloned repo contents in to create an updated version, then run that `tauon.py` and tell me the output.

(There really must be a better way to find whats causing the problem then putting print statements all over the place, but oh well)

**Comment by keystroke3** [comment]
Same thing. It crushes when I change to gallery view. Without music playing.

**Comment by Taiko2k** [comment]
What was the terminal output?

**Comment by keystroke3** [comment]
It is exactly the same as in the above screenshot.

**Comment by Taiko2k** [comment]
Using tauon.py from the lastest commit?

**Comment by keystroke3** [comment]
Sorry, it seems I had another tauon directory where I did the clone. I copied the new files and run it,  but I get this:
![import error](https://user-images.githubusercontent.com/37796862/63022810-5e76b100-beac-11e9-830e-a68792485667.jpg)

**Comment by Taiko2k** [comment]
looks one of the subfolders that was there got deleted, you might need to reinstall the AUR package. Sorry if I didnt explain it well.

To start again:
 1. Copy to contents of `/opt/tauon-music-box to a new folder, say a folder in home called **A**
 2. Make a new clone
 3. Copy contents of clone TauonMusicBox into A
 4. Run from A

**Comment by Taiko2k** [comment]
BTW, if you want to get up and running in the mean time, you could try the Flatpak version. I expect that to work.

**Comment by keystroke3** [comment]
Ok, so I did what you said, and copied the files. I had overwrite some of them and repopulate the music. When I switch to **Gallery**, I get this:
![ArcoLinux-2019-08-14-1565789023_screenshot_1920x1080](https://user-images.githubusercontent.com/37796862/63024603-338e5c00-beb0-11e9-9f66-2f2b5b79ec0a.jpg)

**Comment by keystroke3** [comment]
> BTW, if you want to get up and running in the mean time, you could try the Flatpak version. I expect that to work.

I think I will just wait for the fix. I really don't like using flatpaks. I find them very large, and difficult to deal with.

**Comment by Taiko2k** [comment]
Okay, that narrowed it down I'm pretty sure. Could you try clone and run again, I should be able to get the exact line now

**Comment by Taiko2k** [comment]
Seems like its an issue with `python-pillow` crashing on attempting to thumbnail the image.

Odd that its not crashing on other systems. Are you sure its not a specific set of tracks causing it?

Maybe try get pillow from somewhere else....

 1. In that folder A... run `pip download pillow`
 2. Extract the contents of the downloaded archive `Pillow*` so that the folder `PIL` is in that same folder A as `tauon.py`
 3. Try run from A again

**Comment by keystroke3** [comment]
Pillow was the problem I guess. The last suggestion worked. The images took a while to load, but everything works now. The music does not stop either. Now, can I just copy the contents of A to `/opt/tauon-music-box`?

**Comment by Taiko2k** [comment]
> Now, can I just copy the contents of A to /opt/tauon-music-box?

Sure

**Comment by keystroke3** [comment]
Ok, thanks.
