### ISSUE TITLE
Multi-Artist support

### ISSUE THREAD

**Issue by MRvillager** [Taiko2k/TauonMusicBox#163]
Can you add support for multi artist tag in accordance with xiph documentation (https://xiph.org/vorbis/doc/v-comment.html)

Example:

standard artist tag ["someone ft. someone"]
multi artist tag ["someone", "someone"]

**Comment by Taiko2k** [comment]
Do you have tracks formatted with multiple artist values? I've never actually come across a file like that.

Indeed there is currently no handling for these. The current behavior is that it simply uses last artist tag detected as the final artist value. So I suppose there should be better handling for that... Though that could get complicated, and perhaps confusing on how to deal with things that expect a single artist value.

How about a solution like this: 
 - Anywhere the ARTIST field is used or shown; combine the artists into a single string like this: `Artist1 + Artist2 + Artist3`
  - Except for the functions **artist list panel** and **global search**, which would handle each artist separately.

**Comment by MRvillager** [comment]
That's can be a good solution, but I have found another metod to separate artists in a single string indicated in the documentation of [ID3](http://id3.org/id3v2.3.0).

standard artist tag ["someone ft. someone"]
multi artist tag ["someone / someone"]

But Windows doesn't accept that, and it separate the multi artist tag in the same way that is indicated in the xiph documentation.

Therefore, the best solution is the one you indicated.

[There are some files with multi artist values.](https://send.firefox.com/download/4b8cdef0eb6b3b7a/#SosSEiJs5fdWrG4arFy3rg)

**Comment by Taiko2k** [comment]
I'm not sure what you mean by those tag formats. The Vorbis documentation mentions multiple artists are done by having multiple ARTIST comments (Not multiple names in a single comment).

**Comment by MRvillager** [comment]
I'm sorry, I was wrong to indicate tag formats like this.

**Comment by Taiko2k** [comment]
I have now committed these changes now for FLAC and OGG/OPUS files.

It will display like `artist1; artist2`, search should work showing results for each artist, and they should each now get unique entries in the artist list.

**Comment by MRvillager** [comment]
Thanks!
