### ISSUE TITLE
Rounding corners and frame/shadow for the cover-art

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#164]
Hi!
I have some ideas for the Showcase view:
 - Rounding corners and frame + shadow for the album art  in the Showcase view.
 - Frame color can be generated from the album art.

![alt text](https://i.imgur.com/VY8hIHY.png)

**Comment by Taiko2k** [comment]
For the album art in the Showcase/Lyrics view? I'm not sure rounded corners here would fit with the design language of the rest of the app. Adding a drop shadow is possible, in fact that is already done in the gallery when on the light theme. 

Would only visually work on light themes since you cant really see shadows on a dark background. I think generating a colour here would be a mixed bag.

**Comment by Solarunit** [comment]
> For the album art in the Showcase/Lyrics view?

Yes, maybe because it needs more distinguish from the different backgrounds. And I think you are right, shadow will not work. Maybe white and dark frame depending on the album art/backgrounds colors.

**Comment by Taiko2k** [comment]
Perhaps it does need a frame of some sort. Something simple like this I'm thinking.

![Screenshot from 2019-09-01 13-31-44](https://user-images.githubusercontent.com/17271572/64070806-15ea3080-ccbf-11e9-8c8b-9c49ac22920f.png)

**Comment by StrangeSeasOfThought** [comment]
Speaking of the artwork, how about displaying additional information (e.g. album title, year, genre) on mouse over (similiar to square mini mode)?

**Comment by Taiko2k** [comment]
> how about displaying additional information (e.g. album title, year, genre) on mouse over (similiar to square mini mode)?

Seems a little unnecessary/obscure to me. Better to err on the side of minimal I think.

> I have "use album art as background" enabled. I don't think a frame would look good in that case.

I think it looks okay, even with the stronger settings enabled. Even better for "Theme from album art" since the background is likely the image colour, it needs separation.

**Comment by StrangeSeasOfThought** [comment]
Could you add a frame/highlight/indicator on mouse over to the gallery artwork?

![highlight](https://user-images.githubusercontent.com/43582772/64236847-87162780-cefb-11e9-8a17-a24b1d3d0759.gif)

**Comment by Taiko2k** [comment]
Or perhaps a drop shadow with a thinn frame would be good, so it still separates from the bg on dark colours, looks a little out of place with the rest of the UI being flat, but looks nicer and pops more I think, especially with colored backgrounds.

![Screenshot from 2019-09-06 15-29-17](https://user-images.githubusercontent.com/17271572/64399179-9e9c0e80-d0bb-11e9-9dc4-818cf6cb873e.png)

@StrangeSeasOfThought Hmm, I'm not sure if its nicer like that though.

**Comment by StrangeSeasOfThought** [comment]
@Taiko2k I'm using a 3x3 gallery grid but it just looks too static imo. It doesn't need to be anything fancy, just some kind of indicator to show that it isn't simply a wall with artwork but that I can actually interact with it.
There's a different colored frame on right click, perhaps make it already appear on mouse over (with customizable color).

> looks a little out of place with the rest of the UI being flat

It's actually quite noticeable...hmm.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought I think the border like that may be too obtuse. Perhaps a highlight like this would be better:

![Peek 2019-09-06 21-34](https://user-images.githubusercontent.com/17271572/64417935-2733a280-d0ee-11e9-93d2-009550536a7a.gif)

**Comment by StrangeSeasOfThought** [comment]
Ohh, I like it a lot. (optional via config?) ^^

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought Sure, I can make it at least optional. Ive pushed it as always on for now.

As for the picture frame, I've removed the drop shadow for now.

**Comment by StrangeSeasOfThought** [comment]
Awesome, it makes the gallery seem more dynamic/lively! The effect pretty much disappears on light album artwork, though. Still, way better than before, imo.

**Comment by Solarunit** [comment]
> Or perhaps a drop shadow with a thinn frame would be good, so it still separates from the bg on dark colours

Looks really nice on this screenshot and background. I noticed that it is a right/bottom drop shadow and not drop shadow on all sides.

>looks a little out of place with the rest of the UI being flat

maybe top and bottom panels should have a drop shadow too? =)

>As for the picture frame, I've removed the drop shadow for now.

Ah, ok
