### ISSUE TITLE
Player not registering in KDE

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#165]
![image](https://user-images.githubusercontent.com/1641362/64447309-55f44d80-d0db-11e9-8eba-aea6999966f5.png)

Playing a song on youtube through Chromium seems to work well, so I'm assuming this is some Tauon issue.

![image](https://user-images.githubusercontent.com/1641362/64447330-686e8700-d0db-11e9-9094-c6d3134b6fdf.png)

As a result my media keys won't work.

This functionality worked well before, but stopped working after I clean installed my Arch system. 

I don't recall if there needs to be something done to enable Tauon with KDE for the first time or if this is a bug on new installs.

Kdeconnect's MPRIS integration still seems to work with Tauon though

```
[126] % python3 /opt/tauon-music-box/tauon.py
Tauon Music Box v4.7.0
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/c0rn3j/.local/share/TauonMusicBox
Found XDG-Downloads: /home/c0rn3j/Downloads
Found XDG-Music: /home/c0rn3j/Music
Install directory: /opt/tauon-music-box
Database loaded in 0.01 seconds.
Could not connect to gnome media keys
Applying external theme: Sky
Theme number: 7
Enabling garbage collecting
```

**Comment by Taiko2k** [comment]
Ive been able to replicate this and found a typo causing Tauon to fall out of MPRIS2 spec compliance which KDE obviously doesn't seem to like. Ive pushed a fix for this now.

**Comment by C0rn3j** [comment]
Works great, thanks!
