### ISSUE TITLE
Scroll-bar instead of arrows in the Gallery view

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#166]
I think scroll-bar will be more useful than arrows here:

![alt text](https://i.imgur.com/j6HNPUM.png)

**Comment by Taiko2k** [comment]
Yes, its a little un-intuitive how it is at the moment. 

I originally designed it this way to discourage the user from scrolling faster than the thumbnailer could keep up. But that was back before it had a caching system so its probably less of an issue now.

**Comment by Solarunit** [comment]
Thanks! But its not visible when you scroll.

**Comment by Taiko2k** [comment]
> But its not visible when you scroll.

Okay, I will fix that for the next release

**Comment by Solarunit** [comment]
ty )
