### ISSUE TITLE
Compact layout

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#167]
- I'd love be able to jump to the currently playing track in playlist by clicking on the track title and/or album artwork in the top panel (the entire area is already used for moving the app, though. And yeah, there are alternative ways to go to the playing track, still...).

- When "use album art as background" is enabled, the artwork isn't really centered in compact layout.

**Comment by Taiko2k** [comment]
>  jump to the currently playing track in playlist by clicking on the track title

Its unfortunate that SDL only allows an area to be draggable or clickable, not both like GTK can. Could have right click as a *go to playing* in that top area, though that would be a little inconsistent in behavior.

I use the play button right click to *go to playing* myself. I always saw that as the main way of doing it.

> When "use album art as background" is enabled, the artwork isn't really centered in compact layout.

Okay, I've added this as an optional setting that defaults to on.
