### ISSUE TITLE
Resizing the player window doesn't preserve full size album art

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#171]
Left panel width changes (2 times) when using centered style setting. No sure if its a bug or expected behavior.

![alt text](https://ibin.co/4vm9ndn1iqJP.gif)

**Comment by Taiko2k** [comment]
This is intentional, what its doing is snapping to the width of the gallery. 

I did this because it looks weird when you switch between gallery and the offset between the two is small. Though maybe I made the area of effect a bit too strong.

**Comment by Taiko2k** [comment]
Oh, sorry, I thought you meant right panel since you were dragging it. Yes that was also intentional, so it gives more room for the tracklist.

**Comment by Solarunit** [comment]
Ah, ok.

--
When using the "full album art mode", resizing the player window doesn't preserve the album art 1:1 aspect ratio. Maybe its a good idea not to change album art aspect ratio?

![alt text](https://i.imgur.com/bbNXL3O.png)

**Comment by Taiko2k** [comment]
Ive pushed this change now. So, now when you resize the right side panel to full size, it will stay that way on window resize.

**Comment by Solarunit** [comment]
Awesome!

**Comment by Solarunit** [comment]
It seems it doesn't work reliable.

**Comment by Taiko2k** [comment]
> It seems it doesn't work reliable.

I see what you mean, I've made some improvements.

**Comment by Solarunit** [comment]
Its working good now, thanks. I also like the snap effect.

>Tweaked drag side panel to full size art to snap in place
