### ISSUE TITLE
Cursor doesn't change its shape when I try to resize the window 

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#172]
Cursor doesn't change its shape when I try to resize the window. I am on Solus Budgie.

![alt text](https://ibin.co/4vmC1xAdcOVm.gif)

**Comment by Taiko2k** [comment]
You mean on mouse hover? That's currently not implemented. Annoyingly SDL2 doesn't expose the corner cursors.

**Comment by Solarunit** [comment]
Yes, on mouse hover. 

>That's currently not implemented

And also left/right cursors?

**Comment by Taiko2k** [comment]
Okay a bit of hacking later...

![Screenshot from 2019-09-22 01-18-03-cropped](https://user-images.githubusercontent.com/17271572/65373865-1b8fd080-dcd7-11e9-8b4c-e50aeaa276e6.jpg)

I assume this is what you meant.

**Comment by Solarunit** [comment]
This is it! =)

**Comment by Taiko2k** [comment]
My solution seems to be working alright. And yep I've fixed the border ones too.

![Peek 2019-09-22 21-22](https://user-images.githubusercontent.com/17271572/65385168-4a618180-dd7f-11e9-8a61-209ea446a1ba.gif)

**Comment by Solarunit** [comment]
Yeah, I see your gif is way better than mine =))
