### ISSUE TITLE
Delete Track File doesn't work

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#173]
Delete Track File doesn't work from the context menu (with shift key pressed)
The notification says "File moved to trash" but it doesn't.

**Comment by Solarunit** [comment]
Music files are on the another disk.

**Comment by Taiko2k** [comment]
I think the issue is send2trash is failing silently. Ill add a double check to force delete if still there.

**Comment by Solarunit** [comment]
Updated the previous comment.

It would be nice to have a confirmation dialog. 

Do you really want to delete these files:
1. file 1
2. file 2

**Comment by Taiko2k** [comment]
I wonder what the best behavior of "delete track" would be

- Delete only (never trash)
- Try trash but fallback to delete if failed
- Try trash and give error if failed (never delete)
- Try trash first then ask what to do if failed
- Always ask what to do
- Additional settings for a combination of the above

**Comment by Solarunit** [comment]
I prefer the current behavior - move to trash but with a confirmation dialog.
But it doesn't work for the files on another (ntfs) drive. 
In this case maybe adding a setting to allow delete files (which are not on the system drive) permanently would be a good idea.

**Comment by Taiko2k** [comment]
I think for now ill just treat this as a bug and leave the intended behavior (that it deletes in the case it can't sent to trash)
