### ISSUE TITLE
Playlist with 1 album and Random Albums enabled doesn't repeat playlist

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#174]
So say I have a playlist that only includes 1 album like this:

![image](https://user-images.githubusercontent.com/19501722/65405575-119bc980-ddcc-11e9-8790-f754dbcb40fd.png)

If the "Random Albums" option is enabled, when the playlist ends it doesn't repeat. If I disable the option, it does repeat properly.

**Comment by Bauke** [comment]
Thanks! The theme uses the [Dracula colors](https://draculatheme.com) that I'm very fond of. I have it available [here](https://gitlab.com/Bauke/configs/blob/master/Dracula.ttheme). :)

**Comment by StrangeSeasOfThought** [comment]
Because I just noticed the playtime lines (starline):

- Columns view disabled: Playtime lines are right-aligned.
- Columns view enabled: Playtime lines are left-aligned.

The same tracks also seem to have different starline lengths.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought 
 
>    Columns view disabled: Playtime lines are right-aligned.
>    Columns view enabled: Playtime lines are left-aligned.

That wasn't unintentional exactly.

> tracks also seem to have different starline lengths.

Probably seems this way because in columns view the starline has a variable truncation based on available space in the column, while the normal view has a fixed truncation length.
