### ISSUE TITLE
Track renaming

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#176]
- Shift click to rename only a single track.
- The renaming feature doesn't work with composer (and comment) tags, please include them, too.

Edit: Menu text is cut off in compact layout

![menu](https://user-images.githubusercontent.com/43582772/65447281-7855cd00-de36-11e9-853b-11ab0e932b49.png)

**Comment by Taiko2k** [comment]
Okay, I'd made these changes
