### ISSUE TITLE
Toggling gallery

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#177]
I often make the mistake of selecting the artist before toggling the gallery... especially in compact layout.

Toggling gallery: Wouldn't it make more sense for the gallery to jump to the playlist position/to the artist/album I'm looking at, rather than the currently playing album?

**Comment by Taiko2k** [comment]
Hmm... could try it. I've pushed this change.

**Comment by StrangeSeasOfThought** [comment]
> I've pushed this change.

It works fine, but not when opening the gallery for the first time (starting app, selecting artist, opening gallery).

**Comment by Taiko2k** [comment]
Ah, my change caused a bit of a bug, I've fixed it now.
