### ISSUE TITLE
Opening the music player disables compositing for Kwin

### ISSUE THREAD

**Issue by Kayomn** [Taiko2k/TauonMusicBox#179]
I think it's something to do with how you have SDL configured. I have a similar issue with some of my own software, and I fix it like so:
```c
// Fixes a bug on KDE desktops where launching the process disables the default compositor.
SDL_SetHint(SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR, "0");
```

**Comment by Taiko2k** [comment]
I had indeed noticed this issue. Didn't know you could set that workaround. Thanks for that!

Tested and seems to be working fine, so I've committed this fix now.

**Comment by Taiko2k** [comment]
Yep this is a regression in Tauon, I've committed a re-fix now. So should be fixed in the upcoming update.
