### ISSUE TITLE
Auto go to playing (different playlists)

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#180]
1. Playlist A (all tracks/music folder)
2. Playlist B (some tracks from playlist A)

Tracks from B are being played. Playlist A is active/selected.

--> Auto _Go To Playing_ only works on B.

- Auto _Go To Playing_  should also work on A because it has the same/all the tracks.

**Comment by Taiko2k** [comment]
When returning to B, you'd likely already be in the playing location right?

And you wouldn't *want* to *go to playing* on A unless you wanted it to be the playing instance though also?

**Comment by StrangeSeasOfThought** [comment]
Well, I usually make use of the queue. A smaller playlist provides the first dozen or so tracks for the queue, then I immediately swap to the main playlist to eventually add tracks to the queue from there/or for shuffle mode.
I rarely return to the smaller playlist after having created the initial queue.

I quite enjoy the feature that after a track change, the playlist jumps to the new playing track. It just seems weird that I have to wait for the original queue to run out, even though the currently selected playlist has the same track. If I click on go to playing, it even jumps to the same track...

**Comment by Taiko2k** [comment]
I suppose I see that as undesirable as because although it is the track playing, its not the play position. But I can see kind of see your perspective. I could add this as a config option.

Should this trigger on *Track change*, *Switch playlist*, or both?

**Comment by StrangeSeasOfThought** [comment]
> I could add this as a config option.
That'd be great, thanks!

> Should this trigger on _Track change_, _Switch playlist_, or both?
I only had on _Track change_ in mind, but a _Switch playlist_ trigger seems like a good idea, too. So preferably both.

> And should it only move the scroll position, or set the playing position as well?
I'd say only the scroll position. Unless there is some benefit to changing the playing position?

**Comment by Taiko2k** [comment]
Okay, I've added a config file option `auto-show-playing`. Switch it to `true` and give it a try.

**Comment by StrangeSeasOfThought** [comment]
When clicking on _go to playing_ the playing highlight is being used instead of selected track highlight (used by auto-show-playing).

Does clicking _go to playing_ change the playing position?

**Comment by Taiko2k** [comment]
Clicking *go to playing* always sets both the playing and selected position.
