### ISSUE TITLE
Diacritics-insensitive search

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#181]
When a song is named `StéLouse - Sociopath.mp3`, I can't simply write `ste` to search for it.

**Comment by Taiko2k** [comment]
I found a suitable library that can do this. https://github.com/redvasily/isounidecode

So should be doable. Might make it optional since a search time increase might be noticeable with large music collections.

Thanks for the coffee's by the way! :sparkle:

**Comment by Taiko2k** [comment]
Okay this should be working in the new release now. 

I've realised this is kind of an important feature and useful even for English language users, so I've set it as enabled by default.

**Comment by C0rn3j** [comment]
Works perfectly, thanks!
![image](https://user-images.githubusercontent.com/1641362/65944681-8a390080-e432-11e9-93eb-3fe657d1fa65.png)
