### ISSUE TITLE
I it possible to add mpd support?

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#183]
I have Manjaro bspwm with Polybar. I was wondering if it would be possible to add some mpd support where the Tauon communicates the current song information to the mpd service so that it can be displayed on Polybar. This will mean I don't have to check the app to know the  name of the currently playing song when I am on a different workspace. If this is too much of a request, it is understandable.

**Comment by Taiko2k** [comment]
For the purposes of displaying song information, that's really what MPRIS is for.

I found these two scripts, I'm not sure how useful they might be for you.

https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/player-mpris-simple

https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/player-mpris-tail

**Comment by keystroke3** [comment]
That works. I had to make a few changes to the script but now it works. I did not even know MPRIS existed and I have been using polybar for such a long time. I only thought that it could be done with MPD. Thanks.

**Comment by Taiko2k** [comment]
Glad it worked out.
