### ISSUE TITLE
Artist list view/filter to new playlist

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#186]
Artist list view -> filter to new playlist -> select 'Artist: ...' playlist -> artist shortcuts are not working in artist list view

**Comment by Taiko2k** [comment]
I can't seem to replicate this. Working as expected for me.

**Comment by StrangeSeasOfThought** [comment]
![artistlist](https://user-images.githubusercontent.com/43582772/66747418-c766af00-ee84-11e9-9afe-8bb990c0a897.gif)

**Comment by Taiko2k** [comment]
Oh, pressing letters on the keyboard! I see now.

Okay. Was a bit of an elusive bug, but I've fixed it now.
