### ISSUE TITLE
Title of some songs lacking metadata is hidden

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#188]
Using TMB 4.8.2

This song is fine
![image](https://user-images.githubusercontent.com/1641362/67143850-125f3880-f270-11e9-8f6b-81d16fcd7ce3.png)
This song isn't
![image](https://user-images.githubusercontent.com/1641362/67143852-17bc8300-f270-11e9-9308-05132ae1c02b.png)

[Download for the broken song](https://cloud.rys.pw/s/axESDGKRHy6EHEX), which, by the way, is terrible.

**Comment by StrangeSeasOfThought** [comment]
Bottom panel only displays {artist} - {title}. The song you linked doesn't have any metadata at all. Do you want it to display the filename instead?

**Comment by C0rn3j** [comment]
Yup, filename would be preferable if nothing else is available

**Comment by Taiko2k** [comment]
Actually, it is displaying the filename, just with the extension truncated.

Would it be preferable to show with the file extension?

**Comment by C0rn3j** [comment]
>Would it be preferable to show with the file extension?

That'd be cluttery.

It is not displaying the filename for me as you can see on the screenshot. It is not due to the size of the window, I had it way larger, just made it smaller for the screenshot.

**Comment by Taiko2k** [comment]
Oh right, you mean show in the bottom panel. I actually never noticed that was missing. I'll add that in.

**Comment by StrangeSeasOfThought** [comment]
+1 for consistency
