### ISSUE TITLE
[Suggestion] Use the first artist name to search for artist info and art.

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#189]
I noticed that Tauon does not find the bio info and artist picture when there are multiple artists in a track. For example, say a song is a collab with metadata showing artists as `Alice;Bob;Jake` , it uses the first artist it finds in the list as the artist of the song. This is because the main artist is the one who comes up first in the list and probably the one who the song belongs to like if it is part of an album.  In this case, it will identify `Alice` as the main artist and bring up her info instead of taking all the other artists as the name of the song artist. It will reduce the chances that Tauon will come up blank on artist bio and picture because it thinks the artist is the combination of all the artist names. 

I also know that this may not bring desired results in the case where the metadata is not available or no formatted properly or the track label is improper. In this case, I would not surprised if it did not find any information.

**Comment by Taiko2k** [comment]
Makes sense to me. I've committed this change now.

**Comment by keystroke3** [comment]
Oh, thanks. That was fast.
