### ISSUE TITLE
Queue shortcut

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#190]
With the addition of folder navigator it requires now an additional mouse click to go to queue (as well as back again). It'd be great to be able to quickly reach the queue like this:

artist list -F1-> queue -F1-> artist list

folder navigator -F1-> queue -F1-> folder navigator

As well as via middle mouse button click on the icon.

**Comment by Taiko2k** [comment]
The *middle mouse button* one sounds good. Maybe this function could just simply remember what the last view was, and toggle between them.

As for the shortcut, I wonder what the default key should be since F1 in use by *toggle titles*. (Or leave it unbound?)

Or another idea, maybe automatically temporarily switch to the queue view when dragging in tracks into the side panel (since neither artist list or folder navigator do anything with received drops).

**Comment by StrangeSeasOfThought** [comment]
> As for the shortcut, I wonder what the default key should be since F1 in use by _toggle titles_. (Or leave it unbound?)

Whatever is free, I guess. Or onbound. I'd assign it to F1, though. I've no use for toggling titles.

> Or another idea, maybe automatically temporarily switch to the queue view when dragging in tracks into the side panel (since neither artist list or folder navigator do anything with received drops).

That'd be a nice feature, too.

**Comment by StrangeSeasOfThought** [comment]
Something else: 

Themes: _column-xyz playing_ please.

**Comment by Taiko2k** [comment]
> *column-... playing*

That works like this with the `+` remember!

```
240,50,50		column+codec
50,240,50		column+comment
50,50,240		column+title
240,50,240		column+album-artist
```

I forgot to add this to the wiki, I've added it now.

**Comment by Taiko2k** [comment]
> automatically temporarily switch to the queue view when dragging in tracks 

I've added this now. Seems to work good I think. Perhaps don't need the shortcut with this?

**Comment by StrangeSeasOfThought** [comment]
Works well! Thanks.

I noticed some small lag in regards to the album artwork when using drag and drop.

**Comment by Taiko2k** [comment]
> small lag in regard to the album artwork

Okay I've pushed a change I think fixes it.
