### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/TauonMusicBox#192]
hello.
since last update im experiencing some high CPU usage by TMB.. it really lags everything on the PC. for instance, as i was typing this with TMB open (no music playing) there was a delay on the cursor. as soon as i closed it, theres no delay. so its pretty extreme. dunno what extra info do you need?

thanks

![image](https://user-images.githubusercontent.com/331242/68001403-f1b0be80-fc31-11e9-8ad4-def5be24c8d7.png)

**Comment by Taiko2k** [comment]
I'm not sure why it would be doing this. Doesn't do it on my end.

I'll ask some general questions.

- Does it always do it so long as Tauon is open, or only when in a specific view or layout (try close all open panels), or when playing different tracks?
- What backend mode are you in? BASS or Gstreamer?

**Comment by legion1978** [comment]
id did it as long as TMB was open, not even playing. using BASS. manjaro, cinnamon desktop. installed by AUR.

i deleted the playlists i had generated and restarted TMB, recreated some of them. it seems to be running fine now. ill report back if it does it again.

btw, i was thinking about all of those little modifications youve been adding here and there and how it could affect performance.

thanks

**Comment by Taiko2k** [comment]
Ive identified an issue with high CPU usage with haven the **gallery** enabled, does it still do it for you with the gallery closed?

**Comment by legion1978** [comment]
oh yes, as soon as i open the gallery, it starts to drag  :C

> I've pushed an update to fix this.

thanks

**Comment by chris246** [comment]
I have a similar issue on Fedora (via Flathub).

CPU load with Tauon minimized to tray and playback paused is around 15 % on one core only.  
I already disabled the gallery, but that did not change anything.

**Comment by Taiko2k** [comment]
@chris246 Im not able to reproduce this. Is there anything you think might be triggering it or does it just always to do it?

**Comment by chris246** [comment]
Hm, I observed it on multiple occasions. I'll keep a closer look on it.
I don't know if this is relevant, but the media source is a Jellyfin server from which the content is streamed.
