### ISSUE TITLE
More robust scrobbling/scrobble cache?

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#194]
I don't always have a strong/stable connection, depending on where I'm using my notebook around my house/garden. Same when using public WiFi. As a result not all tracks end up being scrobbled to Last.fm, even after reconnecting again...

**Comment by Taiko2k** [comment]
This is actually a bug, its supposed to cache them (so long as the application is open) but it was failing to.

Ive pushed a fix now.
