### ISSUE TITLE
Broadcast - Clicking on Now Streaming should select the song

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#195]
Clicking on the bottom text label selects the playing song, but when clicking the broadcasting label nothing happens, I think it should also select the song that is being broadcast.

![image](https://user-images.githubusercontent.com/1641362/68154328-92abbc00-ff47-11e9-9310-880453e04956.png)

---

As a side note, is there a way to dig out metadata like song name/artist etc through HTML(or at all)?

I've been using \<audio\> for testing
```
<audio controls>
  <source src="http://domain.com:8000" type="audio/ogg">
</audio>
```

**Comment by Taiko2k** [comment]
> As a side note, is there a way to dig out metadata like song name/artist etc through HTML(or at all)?

There should be the title embedded in the OGG stream. Though I don't know that the HTML player provides any way of obtaining that.

There's also this function:

![Screenshot from 2019-11-05 12-37-47](https://user-images.githubusercontent.com/17271572/68167072-1c4f9e00-ffc9-11e9-9935-68a962d6bea3.png)

You can see how that works here https://github.com/Taiko2k/TauonMusicBox/blob/master/templates/radio.js. A GET request to `/radio/getpic` returns JSON containing title, artist, album art and lyrics, and `/radio/update_radio` returns the song progress and id. (Yeah its a bit weird, I haven't updated this in a long time.)

**Comment by C0rn3j** [comment]
>There's also this function:

That is exactly what I want!

Though the port (7590) can't be reconfigured from what I can see, and if `broadcast-port` is set to a different port `radio.js` does not change to reflect this, breaking the web player.

**Comment by Taiko2k** [comment]
> Though the port (7590) can't be reconfigured

Yeah, I've pushed a fix for this now, so can be configured in the config file now.

> When you load /radio in a browser, and THEN start the stream, everything but the audio player will kick in. Similarly, on disabling the broadcast, the player will remain enabled.

Ive made it wait until it starts the first time to show the audio player now. And auto start and stop. I wonder if hiding the player while stopped is desiered. 

> Upgrading jquery to 3.4.1 in radio.js seems to work without a hitch.

Okay, ive bumped the version.

> And then set up the following nginx server block, making the radio player work perfect over HTTPS without the browser complaining about mixed content.

That's really cool! I didn't know you could do that.

**Comment by C0rn3j** [comment]
>Ive made it wait until it starts the first time to show the audio player now. And auto start and stop. 

Testing on both Firefox and Chromium, that doesn't seem to be the case. My only change to radio.js is now the `sound.src` line. You can see my testpage here https://proxy.rys.pw/radio/

Sometimes the autoplay works(but enabling the player when a broadcast goes online never seems to work), sometimes it doesn't, I can't seem to figure out why, though I'd assume it has something to do with browser [autoplay rules]()
![button_broken](https://user-images.githubusercontent.com/1641362/68209924-ba953100-ffd4-11e9-8b92-7a6150f1a212.gif)

As a note am using Tauon 5.0.1, not latest git, if that matters.

**Comment by Taiko2k** [comment]
Hmm works for me (with Firefox, but doesn't with Chrome). Though in my experience the audio player is rather finicky, I was surprised it was working that well for me. 

(Another option could be to implement a javascript based player and expose custom controls)

**Comment by C0rn3j** [comment]
It is broken for me in firefox also. I've to refresh the page after starting the broadcast in both browsers.
![button_broken_firefox](https://user-images.githubusercontent.com/1641362/68212002-fa5e1780-ffd8-11e9-8330-bfcc0e94f4d7.gif)

Versions:
```
firefox 70.0.1-1
chromium 78.0.3904.87-1
```

**Comment by Taiko2k** [comment]
Okay after more testing, yeah seems to only work half the time. I don't think there's an easy solution (while depending on the standard html player).
