### ISSUE TITLE
Search Improvements

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#196]
I often try to search for a song, realize that I typoe'd, press CTRL+A and backspace only for nothing to happen, or SHIFT+Arrow_Keys and songs skip on me.

It also looks like that if I press anywhere inside the text it breaks subsequent searches.

![TauonSearchBug](https://user-images.githubusercontent.com/1641362/68170324-93f0df00-ff6f-11e9-9e45-646d6ba274e8.gif)

**Comment by Taiko2k** [comment]
Oh okay, the shift+arrowkeys is supposed to work, but not due to a bug. I've fixed it now and added the ctrl+a shortcut. And fixed that other weird bug with the search text.
