### ISSUE TITLE
[Flatpak] Doesn't start due to locale.Error

### ISSUE THREAD

**Issue by contactobscurantist** [Taiko2k/TauonMusicBox#197]
Flatpak version doesn't start, producing the following message when evoked from terminal:

```
Tauon Music Box v5.0.1

Detected running as Flatpak
-- Symlink to user fonconfig exists
Running from installed location
User files location: /home/mabufu/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/mabufu/Downloads
Found XDG-Music: /home/mabufu/Music
Install directory: /app/bin
Could not set process title.
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 357, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```
My system has mixed locale and formats setting with "LC_ALL=" indeed empty.
AUR version runs fine with no warnings.

**Comment by Taiko2k** [comment]
Hmm, I don't know why its doing this. 

I'm not sure how locale exactly works with Flatpak. I can try catch the exception, this will let the app start at least, but there might be locale issues.

**Comment by brunob** [comment]
@contactobscurantist you can bypass the error with `export LC_ALL="en_US.UTF-8"` or make it permanent by editing `/etc/default/locale`, with this i can open the app without error, but... i'm not sure my it is related, i got an empty/transparent window instead of the content of the app :\

**Comment by Taiko2k** [comment]
@brunob 
> i got an empty/transparent window instead of the content of the app :\

I get the feeling it might be video driver related. Are you using an old version of `flatpak` by any change?

**Comment by brunob** [comment]
@Taiko2k thx for interest and sorry to pollute this issue, i've updated to flatpak 1.4.3 and the window is still transparent. This laptop got an old Nvidia GeForce GT 425M and i use the default x org nouveau display driver, maybe i should try to switch to an nvidia driver. Anyway, a dedicated ticket may be more appropriate.

**Comment by contactobscurantist** [comment]
@Taiko2k Thanks, it works now! And it successfully loads the English locale with no observable issues
