### ISSUE TITLE
Crash when "Edit with..." while multiple album tracks selected

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#198]
1) (right) click folder line to select all album tracks
2) Select "Edit with ..." (kid3 in my case)

**Comment by Taiko2k** [comment]
Cant seem to replicate. Can you catch the terminal output?

**Comment by StrangeSeasOfThought** [comment]
`Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 33227, in <module>
    instance.render()
  File "/opt/tauon-music-box/tauon.py", line 9648, in render
    self.items[to_call][2](self.reference)
  File "/opt/tauon-music-box/tauon.py", line 14017, in launch_editor_selection
    if pctl.g(index).is_network:
  File "/opt/tauon-music-box/tauon.py", line 3157, in g
    return self.master_library[index]
KeyError: 1944`

**Comment by Taiko2k** [comment]
Oh I see the issue. Its a bug. Ive pushed a fix now.

**Comment by StrangeSeasOfThought** [comment]
> Oh I see the issue. Its a bug. Ive pushed a fix now.

It's working now, cheers!
