### ISSUE TITLE
Global search -> multiple genres, one genre in common -> 1 combined playlist

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#199]
![globalsearch](https://user-images.githubusercontent.com/43582772/68298724-5b015900-009a-11ea-978c-a0f5b07c4816.png)

Creating a combined playlist from global search, consisting of all albums that have the searched genre in common (single and multi genre).

Genre R&B +

**Comment by Taiko2k** [comment]
Okay, ive pushed a change. See if it works as intended now

**Comment by StrangeSeasOfThought** [comment]
They should probably still be listed separately like before. But there should be a list item that combines them all into a single playlist.

**Comment by Taiko2k** [comment]
Oh I think I see what you mean... Kind of like inherits all the other genres too. Hmm... I'm not sure. I imagine that could quickly include ones entire library tho. 
___
I don't think its desirable to show full `Ballad / R&B / Soul` in the results, I think this change is good anyway.

**Comment by StrangeSeasOfThought** [comment]
Well, I'm basically fine with as it is now. I simply would've continued listing them all because there's plenty of room for them.

**Comment by Taiko2k** [comment]
8 *for* loops, man thats some scary code... So I've added this now. I think it works. Let me know what you think.

**Comment by StrangeSeasOfThought** [comment]
It doesn't seem to be working at all.

When I search _r&b_ it lists:

Genre R&B
Genre R&B+

_Genre R&B_ should only create a playlist with albums that have the single genre tag: R&B. (I don't have that one, all my r&b tracks are R&B / Soul). Instead the playlists consists of R&B/..../..../.... (basically what R&B+ should look like).

_Genre R&B+_ seems to create a playlist with the entire library.

**Comment by Taiko2k** [comment]
I'm thinking that selecting `R&B` *should* include results of multi-list genres files.

What `R&B+` is doing, as I mistakenly interpreted, is doing a semi recursive search for that genre and all related genres. Which likely could include ones entire library as I mentioned.

I don't think that having selecting `R&B+` returning results of **only** multi-list genres is at all intuitive.

**Comment by StrangeSeasOfThought** [comment]
I see.

> I don't think that having selecting `R&B+` returning results of **only** multi-list genres is at all intuitive.

What I meant for R&B+ to do is show pure R&B albums (single genre tag R&B), as well as albums that have multiple genres but R&B must be one of them.

As it is now, I won't be able to quickly create a pure R&B playlist via global search anymore.

**Comment by StrangeSeasOfThought** [comment]
Or, alternatively, this should become possible to search:

![genre](https://user-images.githubusercontent.com/43582772/68306087-2943be80-00a9-11ea-8d33-03c9178443a0.png)

**Comment by Taiko2k** [comment]
I might remove the new + behavior, since it's probably not useful or intuitive.

Hmm, maybe an idea is to go back to the original behavior, but add a result with an explicit description like `R&B (Include multi-tags)`

**Comment by StrangeSeasOfThought** [comment]
> Hmm, maybe an idea is to go back to the original behavior, but add a result with an explicit description like `R&B (Include multi-tags)`

Yes. And it'd be nice to able to search multi-tags like this:

![genre](https://user-images.githubusercontent.com/43582772/68306693-4b8a0c00-00aa-11ea-9246-d10e6dced541.png)

**Comment by Taiko2k** [comment]
Okay, I've changed to behavior to as I described now.

**Comment by StrangeSeasOfThought** [comment]
It works well.
