### ISSUE TITLE
Broadcasting improvements

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#200]
Shouldn't broadcasting be listed as a Feature in the Readme? It is a pretty neat function that I only found out through the menus and not through the documentation.

---

Right clicking a song when broadcasting is turned off shows a greyed out "Broadcast this" button.
I think the button should never be greyed out, and the button should act as a "Start broadcast and broadcast this" in the case the broadcast is not turned on.

This would also solve the issue of not being able to start a broadcast with a specific song, as the only way I figured out to start a broadcast is the Start/Stop Broadcast button which always starts on the first song in my playlist.

---

Broadcast queue - I haven't been able to find a way to setup a broadcasting queue, I'm either blind or it isn't a thing

---

Sync currently playing with broadcast - If there's indeed no broadcast queue, is it possible to sync the broadcast stream to what I'm currently playing? Not sure how desirable this would be if queues would be implemented though.

**Comment by Taiko2k** [comment]
> Shouldn't broadcasting be listed as a Feature in the Readme?
> Right clicking a song when broadcasting is turned off shows a greyed out "Broadcast this" button.

Good ideas. I do have some documentation here. https://github.com/Taiko2k/TauonMusicBox/wiki/Outbound-Broadcasting

> I haven't been able to find a way to setup a broadcasting queue

Well, the idea is you create a new playlist, since playlists can function as queues.

> Sync currently playing with broadcast

I actually used to have this feature but removed it. For a few reasons but mostly it being work to maintain.

___

I'm not really sure where to go with this broadcast feature. I wonder about its relevancy. But being able to listen along with other people is a cool thing I think, so I'd want to at least keep something like this going forward.

**Comment by C0rn3j** [comment]
> I'm not really sure where to go with this broadcast feature. I wonder about its relevancy. But being able to listen along with other people is a cool thing I think, so I'd want to at least keep something like this going forward.

Personally that is exactly what I'm using it for, just listening along with a friend or two. I imagine there are way better solutions for mass-scale broadcast and wouldn't expect TMB to become one of those tools.

>Well, the idea is you create a new playlist, since playlists can function as queues.

I didn't realize this, the wiki page you linked makes that quite clear, my bad for not checking it.

**Comment by C0rn3j** [comment]
I guess this can be closed now that the button behavior was changed and readme updated, thanks!
