### ISSUE TITLE
[Flatpak] Empty window on start

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/TauonMusicBox#201]
I got an empty/transparent window instead of the content of the app :\

I've updated to flatpak 1.4.3 and the window is still transparent. This laptop got an old Nvidia GeForce GT 425M and i use the default x org nouveau display driver, maybe i should try to switch to an nvidia driver.

_Originally posted by @brunob in https://github.com/Taiko2k/TauonMusicBox/issues/197#issuecomment-551039150_

**Comment by Taiko2k** [comment]
> maybe i should try to switch to an nvidia driver.

Yeah try that if you can.

Also try run from terminal and see if there's any errors showing. `flatpak run com.github.taiko2k.tauonmb`

Maybe try delete the `~/.var/app/com.github.taiko2k.tauonmb` folder and try again.

**Comment by brunob** [comment]
Thx for transferring it in a new issue.

I've switched to nvidia-drvier-390 (libre) and no more success.

Here is the output of `flatpak run -v com.github.taiko2k.tauonmb` :
```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/bb/.local/share/flatpak
F: Opening user flatpak installation at path /home/bb/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/bb/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2754512162
F: Allocated instance id 2855821709
F: Add defaults in dir /com/github/taiko2k/tauonmb/
F: Add locks in dir /com/github/taiko2k/tauonmb/
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/bb/.config/pulse/client.conf': Erreur lors de l’ouverture du fichier /home/bb/.config/pulse/client.conf : Aucun fichier ou dossier de ce type
F: Running '/usr/libexec/flatpak-bwrap --args 33 /usr/libexec/flatpak-dbus-proxy --args=35'
F: Running '/usr/libexec/flatpak-bwrap --args 33 com.github.taiko2k.tauonmb.sh'
Tauon Music Box v5.0.1
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Detected running as Flatpak
Running from installed location
User files location: /home/bb/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/bb/Téléchargements
Found XDG-Music: /home/bb/Musique
Install directory: /app/bin
Could not set process title.
Database loaded in 0.034 seconds.
Locale detected: en_US
No translation file available
Could not connect to gnome media keys
Using SDL version: 2.0.10
Config reload theme...
Applying external theme: Sky
Theme number: 7
Enabling garbage collecting
```
And here is the verbose outpout after deleting `~/.var/app/com.github.taiko2k.tauonmb` (still transparent window) : 

```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/bb/.local/share/flatpak
F: Opening user flatpak installation at path /home/bb/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/bb/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Regenerating ld.so.cache /home/bb/.var/app/com.github.taiko2k.tauonmb/.ld.so/cafb4e5c27ef341354e630310e9ef372332ea5fa6d197d6a45a3088fa0449c97
F: Running: '/usr/libexec/flatpak-bwrap --args 18 ldconfig -X -C /run/ld-so-cache-dir/cafb4e5c27ef341354e630310e9ef372332ea5fa6d197d6a45a3088fa0449c97'
F: Cleaning up unused container id 2855821709
F: Allocated instance id 2088730840
F: Add defaults in dir /com/github/taiko2k/tauonmb/
F: Add locks in dir /com/github/taiko2k/tauonmb/
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/bb/.config/pulse/client.conf': Erreur lors de l’ouverture du fichier /home/bb/.config/pulse/client.conf : Aucun fichier ou dossier de ce type
F: Running '/usr/libexec/flatpak-bwrap --args 33 /usr/libexec/flatpak-dbus-proxy --args=35'
F: Running '/usr/libexec/flatpak-bwrap --args 33 com.github.taiko2k.tauonmb.sh'
Tauon Music Box v5.0.1
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Detected running as Flatpak
Running from installed location
User files location: /home/bb/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/bb/Téléchargements
Found XDG-Music: /home/bb/Musique
Install directory: /app/bin
Input config file is missing... copying template from program files
Could not set process title.
No existing star.p file
Error loading save file
Database loaded in 0.0 seconds.
Locale detected: en_US
No translation file available
warning: error loading settings
Could not connect to gnome media keys
Using SDL version: 2.0.10
Config reload theme...
Applying external theme: Sky
Theme number: 7
Enabling garbage collecting
```

**Comment by Taiko2k** [comment]
Might be nice to determine if this is a Flatpak specific issue.

You could setup Tauon manually if you're willing and see if that works. Though apart from the AUR, I only have instructions for debian/ubuntu:

 1. `git clone https://github.com/Taiko2k/TauonMusicBox.git`
 2. `cd TauonMusicBox`
 3. `sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 fonts-noto python3-gi python3-cairo gir1.2-notify python3-gi-cairo`
 4. `pip3 install --user -r requirements.txt` (or install these in a virtual env)
 5. Run using `python3 tauon.py`

**Comment by StrangeSeasOfThought** [comment]
Transparent as in (very) low opacity? You can increase/decrease the app's opacity via shortcut keys.

**Comment by brunob** [comment]
\o/ @Taiko2k it works with manual install from git !

Now i've got to find how covers are handled (every folder album in my collection contain a cover.jpg file), FTR i'm coming from quodlibet.

**Comment by Taiko2k** [comment]
@brunob Good to hear. If you plan to use this, In it's current state it will be using GStreamer for playback. If you want to use BASS, see the .zip folder from the release in the releases page, and copy the lib folder to your TauonMusicBox folder.

Cover art files should work as expected. If you mouse over the art in the right panel, it will actually display E for embedded or F for file souce!

**Comment by brunob** [comment]
thx again @Taiko2k from my test it works well with gstreamer, do i have any advantage of switching to BASS (despite its cool name) ?

**Comment by Taiko2k** [comment]
> do i have any advantage of switching to BASS

Mainly just the small visualiser in the top panel. And it's needed if you use the broadcast feature.

**Comment by brunob** [comment]
@Taiko2k would you like me to update the wiki recipe here https://github.com/Taiko2k/TauonMusicBox/wiki/Manual-Setup#development-setup-on-ubuntu with the content https://github.com/Taiko2k/TauonMusicBox/issues/201#issuecomment-551067958 ?

Also, since i've been working on a snap package i maintain last week, i'm trying to generate a snap recipe for Tauon to see if it works better on ubuntu than the flatpack package, i'll get back to you if it works well, maybe we can provide this one and publish it on snapcraft.io ?

**Comment by Taiko2k** [comment]
@brunob

> would you like me to update the wiki

Sure go ahead

> maybe we can provide this one and publish it on snapcraft.io?

Perhaps if it ends up working well. I tried tinkering with snap a while back but didn't have much luck getting Tauon to work myself.

**Comment by brunob** [comment]
@Taiko2k wiki is up to date, i'll ping you as soon as i have a working snap to test :)

**Comment by Taiko2k** [comment]
As for this original issue. I'd suggest trying to update Flatpak again and trying again.

If you want to pursue the issue further, I'd suggest a Flatpak support forum since I'm fairly sure this is a Flatpak related issue.

Maybe create an issue on https://github.com/flatpak/flatpak/issues, mention the issue, your OS and that the app uses SDL2 for windowing.

**Comment by brunob** [comment]
Thx, think you can close this one :)
