### ISSUE TITLE
Wrong album art background in the Showcase view

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#202]
Wrong album art background in the Showcase view

Steps to reproduce:
1. Start song from album_1. > F5
2. F5 > Start song from album_2
3. F5

**Comment by StrangeSeasOfThought** [comment]
Same here, stuck album art background, without using showcase view.

**Comment by Taiko2k** [comment]
Okay, I've pushed a release with a fix for this.
