### ISSUE TITLE
No cover art on Track + art view

### ISSUE THREAD

**Issue by brunob** [Taiko2k/TauonMusicBox#208]
Hi, since a couple of days, i can't show anymore cover arts in Tracks + art view.

> There's now a setting to hide the album art (Right click the side panel area and click Show art box)

I've tried to do it from the tracks+art view, and i don't have the option in menu (and can't find it in the settings).

FTR, cover is shown in gallery view, in ctr+i window and also in showcase view.

I'm trying to get cover back in this view since i can recall that it allows to get covers from the web (but i may have dreamed about this feature ?), since i got some covers presents in album folder but not shown in gallery view, but well shown in ctrl+i window.

Thx in advance for your help :)

PS : what do you think about registering an IRC channel for tauon on freenode.net ? i can take charge of it if sounds useful to you.

**Comment by Taiko2k** [comment]
Yes I removed the menu entry "Hide Art Box". It could be that you had it hidden then updated. You can still toggle it with <kbd>Ctrl</kbd> + <kbd>h</kbd> shortcut. I probably should have reset this setting on upgrade to avoid this.

___

As for IRC. Hmm... So far being a small project, Github issues seemed to have served fine, though I see the appeal of instant chat. 

I feel IRC might be a little... dated and unapproachable though? I'd suggest Discord, but I realise many may have issue with that.

**Comment by brunob** [comment]
Thx for answering, again, i've finally fixed it hard way by deleting `state.p` :p 

For IRC, the advantage on discord is that it doesn't force users to have an account, and it's available directly in the browser with web client like the one we use in others software communities, cf https://kiwiirc.com/ ; anyway, feel free to ask if you want help with that one day :)
