### ISSUE TITLE
Tauon crashes when switching to "Gallery" view

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#209]
Seems to happen no matter what I do when switching to the "Gallery" view Tauon crashes and spits this out:

```
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 31434, in <module>
    if is_level_zero() and gui.d_click_ref == album_dex[album_on]:
AttributeError: 'GuiVar' object has no attribute 'd_click_ref'
```

**Comment by Taiko2k** [comment]
I see, it happens if an album tile is under the cursor when clicking to enter gallery.

I'll push a new release with a fix soon.
