### ISSUE TITLE
Is there a way to enable track change notifications for tiling WMs?

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#211]
I am using bspwm with dunst as my notification manager and when I went to enable the setting to allow track change notifications in Tauon, I got a message that my DE (or in this case WM) is not supported. Is there a way to allow notifications with dunst?

**Comment by Taiko2k** [comment]
I can't quite remember why I set it up that way. I was probably lazy and didn't / couldn't test it with other environments so I used a whitelist. I'll try enable it for everything for next release and see how that goes.

In the mean time if you're using an aur install, you can try force it. Edit `/opt/tauon-music-box/tauon.py` and change line 64 to `de_notify_support = True`

**Comment by keystroke3** [comment]
I did the edit and now it does not give me the error message, but it still does not emit the notifications.

**Comment by Taiko2k** [comment]
Do you have the package `libnotify` installed? Do you normally get notifications from other applications?

**Comment by keystroke3** [comment]
Yes and yes.

**Comment by keystroke3** [comment]
OK, I just restarted dunst and now it works.I get the Tauon notification. The cover is quite large though.

**Comment by Taiko2k** [comment]
Tauon currently outputs up to 1000x1000 thumbnails. I assumed all notifications servers resized them.. Or maybe that size is intended by dunst?

Btw also note that it wont emit notifications while the window is focused.

**Comment by Taiko2k** [comment]
I'm not sure whats going on with that text, maybe a bug with dunst? (Provided that's not literally the artist name)

**Comment by keystroke3** [comment]
> I assumed all notifications servers resized them.. Or maybe that size is intended by dunst

Maybe. I will check to see if I can resize it in dunst.

> Provided that's not literally the artist name

The song is called _Shutter Me_ and artist is _Lindsey Stirling_ and _Lzzy Hale_. I think the reason why it is showing the song name twice is because it is also showing the name of the album. I don't know where the `deluxe0.jpg` comes from. It appears to be coming from the album art since it changes when the album changes.
I wish it only showed the artist and song name, the way it is shown in dbus.
Btw, which notification daemon do you use (if any) that I can use to check if the issue is with dunst.

**Comment by Taiko2k** [comment]
Yeah it will be the name of the image. Works as expected in gnome and kde. Just uses libnotify for notifications.

**Comment by keystroke3** [comment]
I changed to `xfce4-notifyd` and I get better looking notifications. Only down side is that config options are very limited. It does not currently fit with my desktop theme and configs. 

![notify1](https://user-images.githubusercontent.com/37796862/69899334-7ef04b80-1375-11ea-8f37-4138c088aadd.png)

> I could make that configurable...

That would be nice. Thanks
