### ISSUE TITLE
tauon.po won't load into poedit for translation

### ISSUE THREAD

**Issue by Ricardo-Simoes** [Taiko2k/TauonMusicBox#213]
I'm trying to localize Tauon into Portuguese European (pt-PT), but poedit won't load tauon.po, it says wrong format or damaged file.
Can you please provide original english POT template file for translation?

Many thanks in advance
Ricardo Simões
xmcorporation.com

**Comment by Taiko2k** [comment]
Here you go. (Just remove .txt extension)
[messages.pot.txt](https://github.com/Taiko2k/TauonMusicBox/files/3919660/messages.pot.txt)

**Comment by brunob** [comment]
Nice, going to translate this one in french :)

FTR, i see that some items are dups like these one : Search artist on Wikipedia VS Search Artist on Wikipedia / same for Search artist on Sonemic.

**Comment by Taiko2k** [comment]
@brunob The capitalisation difference between those two is intentional though.

**Comment by brunob** [comment]
'k, got it, thx

**Comment by legion1978** [comment]
hi there. where are these files? i mean to translate the app? 
thnx

**Comment by Taiko2k** [comment]
@legion1978 I've got the `messages.pot` file in `locale/messages.pot`. Here's a general guide: 

 - Create a new `.po` file from the `.pot` template. (You could just copy and rename to `tauon.po`)
 - Place `tauon.po` in the file structure like this, for example French would go `locale/fr_FR/LC_MESSAGES/tauon.po`
 - If you're unsure what the language code is for your language (in the format xx_XX or xx), try run the `locale` command to see what your locale is.
- Open the po file and translate strings. Its not crucial to translate every string if you don't want to or you cant make sense of a string.
- Some strings have strict space restrictions, such as ones that appear in settings or on buttons. It will be necessary to compile and check how things look.
- To compile, run (for example) `msgfmt locale/fr_FR/LC_MESSAGES/tauon.po -o locale/fr_FR/LC_MESSAGES/tauon.mo`. Provided your locale is set correctly, the new language should now show automatically in Tauon's interface upon restart. (You can also switch manually in tauon's config file)
- In the future, you it may be helpful come back and translate any new strings. To *update* an existing po file from the pot template, run (for example) `msgmerge -U locale/fr_FR/LC_MESSAGES/tauon.po locale/messages.pot`.
- When you're ready to submit, you can create a new pull request with the changes. (Remember, its just the .po file, the .pot file should be unchanged and any .mo files excluded. You could also email me the po file if you're uncomfortable with making pull requests.

**Comment by Ricardo-Simoes** [comment]
Hello there, I have now finished the translation and uploaded to my fork and made a pull request... but I'm unsure if I have messed up with the pull request, can you please verify if everything is fine?
Many thanks in advance
