### ISSUE TITLE
Compile for Win

### ISSUE THREAD

**Issue by emipta** [Taiko2k/TauonMusicBox#214]
Taiko2K,  I love your Music Player..

I use in Debian 9&10 on my Computers,  and Windows on a Car (Last *.Exe 4.08) it's possible for you compile this new version for Win10? 

Lots of Thanks Man, you're work is very apreciated

(^_-)-☆(^_-)-☆(^_-)-☆(^_-)-☆(^_-)-☆

**Comment by Taiko2k** [comment]
Well, since you added the starry face...

Okay I've gone and added a windows build. Though do note I haven't given it much testing, and notably the folder navigator feature is not functioning in this build.

**Comment by emipta** [comment]
Thanks a Lot Taiko2k !
