### ISSUE TITLE
[Snap] access to removable media

### ISSUE THREAD

**Issue by brunob** [Taiko2k/TauonMusicBox#215]
As stated in the wiki https://github.com/Taiko2k/TauonMusicBox/wiki/Sandboxing-Quirks 

I've opened a thread about this at https://forum.snapcraft.io/t/tauon-snap-and-removable-media-permission/14507

**Comment by brunob** [comment]
Huhu, i've deleted the thread on the forum cause... it works :p 

After installing the app from software center, a  "Autorisations" button is shown which allow users to make removable media available permanently cf : 

![Capture d’écran de 2019-12-06 14-33-26](https://user-images.githubusercontent.com/418064/70326721-7e542b00-1835-11ea-9c45-07569d7043ad.png)

Should we update the wiki about this ?

**Comment by Taiko2k** [comment]
Okay, I've made an edit.
