### ISSUE TITLE
gst_parse_error: no element "pulsesink"

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#216]
Running TMB on one of my systems using gstreamer backend seems to not work, the song just doesn't play.

BASS works. Albeit with 'channel has stalled', which I suspect is not TMB's fault and is due to misconfigured pulse on the system where anything I play over HDMI sounds about 2x sped up.

[pacmd list-cards](https://github.com/Taiko2k/TauonMusicBox/files/3932568/pacmd_list-cards.txt)
[pacmd list-sinks](https://github.com/Taiko2k/TauonMusicBox/files/3932569/pacmd_list-sinks.txt)
[pacmd list-sources](https://github.com/Taiko2k/TauonMusicBox/files/3932570/pacmd_list-sources.txt)

TMB Log where I try to play via gstreamer backend and then BASS:
```
% DISPLAY=:0 python /opt/tauon-music-box/tauon.py ~/LORN\ -\ ANVIL\ \[Official\ Music\ Video\].opus
Tauon Music Box v5.1.2
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com
                                                                   
Running from installed location
User files location: /home/c0rn3j/.local/share/TauonMusicBox
Found XDG-Downloads: /home/c0rn3j/Downloads
Found XDG-Music: /home/c0rn3j/Music
Install directory: /opt/tauon-music-box
No existing star.p file
Database loaded in 0.0 seconds.
Locale detected: en_GB
No translation file available
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()     
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/tauon-music-box/t_modules/t_dbus.py", line 47, in main 
    import dbus.service
ModuleNotFoundError: No module named 'dbus.service'
Using SDL version: 2.0.10
Using GStreamer as fallback. Some functions disabled
Config reload theme...
Applying external theme: Sky
Theme number: 8    
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()     
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/tauon-music-box/t_modules/t_gstreamer.py", line 514, in player3
    player = GPlayer()
  File "/opt/tauon-music-box/t_modules/t_gstreamer.py", line 84, in __init__
    self._output = Gst.parse_bin_from_description(
gi.repository.GLib.Error: gst_parse_error: no element "pulsesink" (1)
Enabling garbage collecting
OPEN URI           
Tag Scanner: Found unhandled Vorbis comment field: language
eng                
      In file: /home/c0rn3j/LORN - ANVIL [Official Music Video].opus
Writing database to disk.
Using default sound device
Bass library initialised
Open file: /home/c0rn3j/LORN - ANVIL [Official Music Video].opus
Channel has stalled
Channel has stalled
...
```

**Comment by Taiko2k** [comment]
Have you tried changing the output target in *Audio*, GStreamer settings of Tauon? Like to "Auto" or "Alsa"?

Otherwise I'm not sure, does seem perhaps pulseaudio is miss-configured, but I'm not at all familiar with that so can't really help there.

**Comment by C0rn3j** [comment]
Auto: `gi.repository.GLib.Error: gst_parse_error: no element "autoaudiosink" (1)`

ALSA works (sped up, which is expected until I manage to track down the misconfig)

**Comment by C0rn3j** [comment]
Alright I worked around the speed-up issue, and the system now works fine audio wise, so it shouldn't be the fault of PA.

(Looks like AMDGPU doesn't handle HDMI audio well at 4K@60Hz, dropped down to 1080p and audio works)

**Comment by Taiko2k** [comment]
I assume other GStreamer based applications to Pulseaudio are also not working for you?

**Comment by C0rn3j** [comment]
Could you give me an example of such application that I could test?
I've had no issue with browsers, games or the Steam client playing audio.

**Comment by Taiko2k** [comment]
Try Clementine. Or also, try this command, should produce a test tone.

`gst-launch-1.0 audiotestsrc ! audioconvert ! audioresample ! pulsesink`

**Comment by C0rn3j** [comment]
The test tone fails the same way with failing to find `pulsesink`, whereas it works on my other Nvidia system.

So this is not TMB's fault, but now I've no clue where to look, since `PulseAudio/Troubleshooting` Arch wiki page has nothing related to this .-.

**Comment by desolatorxxl** [comment]
For the lost soul that might stumbles upon this:

On gentoo this is caused by the missing pulseaudio GStreamer plugin.
You can check it's presence by running `gst-inspect-1.0 pulsesink`, this should output some technical details if it's present and an error other wise.

To fix either install `media-plugins/gst-plugins-pulse` or `media-plugins/gst-plugins-meta USE=+pulseaudio".

**Comment by sertraline** [comment]
> To fix either install `media-plugins/gst-plugins-pulse` or `media-plugins/gst-plugins-meta USE=pulseaudio`.

`pacman -S gst-plugins-good` for arch 👀
