### ISSUE TITLE
TMB not registering in KDE

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#218]
![image](https://user-images.githubusercontent.com/1641362/70378088-e0d42680-191c-11ea-926d-e65f94df5ff3.png)

Looks like https://github.com/Taiko2k/TauonMusicBox/issues/165 popped up again, youtube in Chromium is detected fine.

**Comment by Taiko2k** [comment]
Do you have the package `python-dbus` installed? Now that I think of it, this dependency is missing from the PKGBUILD. I've gone and added it now.

**Comment by C0rn3j** [comment]
That'd be it, I was doing some house cleaning and `python-dbus` was one of the things I removed, thanks for fixing it!
