### ISSUE TITLE
No system sound after suspend

### ISSUE THREAD

**Issue by rtomasa** [Taiko2k/TauonMusicBox#219]
Suspending my computer with the application opened (sound is paused), when I power on the system again, the whole system has no sound. No error is displayed, just closing the application the sound is back and working.

OS: Fedora 31
Type: flatpack version
Sound Engine: BASS

**Comment by Taiko2k** [comment]
It would be interesting to see if the issue persists with the GStreamer backend. Try switch to it and select "PulseAudio" as the output, then test suspending again. Maybe also test output to "PusleAudio Sound Server" in BASS also if you didn't have it set to that before already.

Resuming from suspend works for me, so I assume its a Fedora related issue. I can't really help further with this so you may need to pursue a Fedora support forum.

**Comment by Taiko2k** [comment]
It only does it when a track is paused? If so, you could try setting the `disconnect-device-pause` setting to *on* in tauon's config file.

**Comment by rtomasa** [comment]
Well, I can confirm you that setting `disconnect-device-pause = "on"` made the magic.
Now the sound is working fine after coming back from suspend, and works for both pause and stop actions.

**Comment by Taiko2k** [comment]
Good that solves the issue then. 

I might just change the default of that setting to avoid this.
