### ISSUE TITLE
Hover (instead of click) to preview artist thumbnail...

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#220]
...and click to select the artist like it used to be. That way the preview automatically disappears when moving the mouse away.

**Comment by Taiko2k** [comment]
I've pushed a change to the behavior now. Would you say this is better now?

**Comment by StrangeSeasOfThought** [comment]
> I've pushed a change to the behavior now. Would you say this is better now?

It's way better imo. Perhaps add something like don't show preview for 2? seconds after click (artist selection). Right now the preview pops up too soon (when I only want to select an artist).

**Comment by Taiko2k** [comment]
> add something like don't show preview for 2? seconds after click

Good idea

> Bug: Preview pops up in compact mode now.

That was intentional, but I see how it can get in the way. I've extended the time required to hover in compact mode now.

**Comment by StrangeSeasOfThought** [comment]
Very nice!

Not sure about compact mode though, too many visible layers, etc:

![preview](https://user-images.githubusercontent.com/43582772/70614358-aca58200-1c0a-11ea-930f-2a5a008fdb1b.png)

**Comment by Taiko2k** [comment]
Ive added a border to the image now which should help.

**Comment by StrangeSeasOfThought** [comment]
It's better, thanks.
