### ISSUE TITLE
Discogs module not found - Crash at start

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/TauonMusicBox#222]
Hello. TMB wont start.

Tauon Music Box v5.1.3
Install directory: /opt/tauon-music-box
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 530, in <module>
    import discogs_client
ModuleNotFoundError: No module named 'discogs_client'

**Comment by StrangeSeasOfThought** [comment]
You just need to rebuild some dependencies, incl. discogs_client.

**Comment by legion1978** [comment]
Thank you
