### ISSUE TITLE
Missing "add to queue after current album" in gallery view

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/TauonMusicBox#224]
Hello
Option to queue album after playing one finishes is not present in gallery view context menu.

![image](https://user-images.githubusercontent.com/331242/70866708-f52aab80-1f3a-11ea-9e52-5cc527d4ff90.png)

![image](https://user-images.githubusercontent.com/331242/70866693-c1e81c80-1f3a-11ea-99dc-9267d599f37d.png)

**Comment by Taiko2k** [comment]
Okay I have added this now.
