### ISSUE TITLE
Tauon crashes on launch

### ISSUE THREAD

**Issue by lastweakness** [Taiko2k/TauonMusicBox#225]
Tauon crashes after showing the disc image on launch. I initially thought it was the AUR package's issue but now that the AUR package has been fixed, the issue still persists.

Crash log:
```
Tauon Music Box v5.1.3
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/username/.local/share/TauonMusicBox
Found XDG-Downloads: /home/username/Downloads
Found XDG-Music: /home/username/Music
Install directory: /opt/tauon-music-box
Error loading window state file
No existing star.p file
Error loading save file
Database loaded in 0.0 seconds.
Locale detected: en_US
No translation file available
warning: error loading settings
BASS not found
Could not connect to gnome media keys
Using SDL version: 2.0.10
Using GStreamer as fallback. Some functions disabled
Config reload theme...
Applying external theme: Sky
Theme number: 8
sys:1: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
[1]    74024 segmentation fault (core dumped)  python3 /opt/tauon-music-box/tauon.py
```

Any help would be appreciated since I like how the player looks from the screenshots.

**Comment by Taiko2k** [comment]
Indeed this is a separate issue to that package issue.

Hmm this kind of error is difficult to diagnose. It will likely be something to do with your arch configuration/install. I see you're not running gnome. What desktop environment is this? Could be a missing dependency that's normally present in Gnome.

I assume all your system packages are up to date?

**Comment by lastweakness** [comment]
> Indeed this is a separate issue to that package issue.
> 
> Hmm this kind of error is difficult to diagnose. It will likely be something to do with your arch configuration/install causing this bug to emerge. I see you're not running gnome. What desktop environment is this? Could be a missing dependency that's normally present in Gnome.
> 
> I assume all your system packages are up to date?
> 
> Edit: You could also consider installing with Flatpak. I expect that should work.

The desktop environment is KDE. But I do run GNOME applications like Lollypop and should have most normal dependencies covered. I thought the SDL-based UI meant that the program is desktop-agnostic. So, it shouldn't be causing issues. I'm not a fan of Flatpaks, but I could try just in the case of Tauon.

**Comment by Taiko2k** [comment]
> I thought the SDL-based UI meant that the program is desktop-agnostic. 

There is a dependency on PyGObject which is crashing here for some reason. But it should normally work in other environments. I just tested in KDE and is working there for me. So as I mentioned, maybe a configuration/package issue with your install somehow. Unfortunately I don't know how to diagnose this further.

> I'm not a fan of Flatpaks

I'm a fan. I do indeed think they are the "future of apps on Linux". Solves a lot of problems and is the better solution than Snap and AppImage.

Though I wouldn't say Flatpak is without issues right now, particularly with the file portal and drag and drop, that should be more seamless than it is now.

**Comment by lastweakness** [comment]
> There is a dependency on PyGObject which is crashing here for some reason. But it should normally work in other environments. I just tested in KDE and is working there for me. So as I mentioned, maybe a configuration/package issue with your install somehow. Unfortunately I don't know how to diagnose this further.

PyGObject works as expected, since Lollypop and some of my own little script-like programs make use of it. It is a really difficult issue to diagnose though. I will look more closely into it after tomorrow.

> I'm a fan. I do indeed think they are the "future of apps on Linux". Solves a lot of problems and is the better solution than Snap and AppImage.

Something I like about Linux's package distribution method is that dependencies are shared, unlike what we see in the case of package distribution in Mac OS X or Windows. So, creating self-contained versions of software that cannot share dependencies is not good imo. But then again, that's just me, I bet a lot of people prefer complete isolation and some level of sandboxing.

**Comment by lastweakness** [comment]
This is probably not your bug.

**Comment by lastweakness** [comment]
> I'm a fan. I do indeed think they are the "future of apps on Linux". Solves a lot of problems and is the better solution than Snap and AppImage.

About this, I still think that out of all existing solutions, AppImage is the most interesting one out of the three for me. [This](https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison) gives a decent overview and probably covers everything I want to say. I also think that sandboxing is something the user has to 'opt-in' to in the case of PCs. However, sandboxing by default does make sense on Mobile Platforms.

Unlike in the case of Flatpaks where the user has to have the `flatpak` package set up, AppImages are pretty simple and allow us to straight up execute them, which is cool imo.
