### ISSUE TITLE
Network SMB / FPT 

### ISSUE THREAD

**Issue by emipta** [Taiko2k/TauonMusicBox#226]
How is possible reproduce my intranet music (from NAS) on Tauon, actually this is my code launch.. 

/usr/bin/flatpak run --share=network --branch=stable --arch=x86_64 --command=com.github.taiko2k.tauonmb.sh --file-forwarding com.github.taiko2k.tauonmb @@u %U @@ 

But not work, not is possible add music from my intranet,  i need something more? 

Best Regards Taiko2k : 1st_place_medal: 

![Screenshot_20191218_225031](https://user-images.githubusercontent.com/37155732/71126334-1a444600-21e9-11ea-9167-f11032d6e790.png)

**Comment by Taiko2k** [comment]
Tauon doesn't support SMB directly. The way I would think of doing it is mounting the network location, then grant flatpak permission e.g.  `sudo flatpak override com.github.taiko2k.tauonmb --filesystem=/srv/music`. Then drag and drop in the folder.

If you get it working, I'd be interested to hear what the performance is like, like does it cause the UI to lag too much?
