### ISSUE TITLE
App startup time

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#228]
A couple of releases ago, the app startup time used to be noticeably faster and it looked a lot smoother/better. 

![appstartup](https://user-images.githubusercontent.com/43582772/71320734-f5cdbf80-24af-11ea-9678-8b2f7493c86a.gif)

Anyone else noticed this? Or is it only on my end?

**Comment by Taiko2k** [comment]
Yes I did make some changes to the startup sequence. Though looking at your GIF, there seems to be an issue with maximizing.

Ive pushed a change, see how that looks now.

**Comment by StrangeSeasOfThought** [comment]
Nice, thanks!
