### ISSUE TITLE
Mix album changes sorting.

### ISSUE THREAD

**Issue by Noisecommander** [Taiko2k/TauonMusicBox#231]
Hey there,
Two albums of a band, from 1997 and 1998, get sorted in between 2006 & 2009 when I add a specific album to Tauon and sort on 'Sort Year per Artist'.
Tauon now sorts the albums per year as 2001, etc, 1997, 1998, 2006, etc.

The only thing that pops out at me is that the album I added is a mix album, where all the other albums from that band are self made.
I tagged the mix album with the 'Artist' tag of the original artist (The Cure, Black Sabbath, etc) and the band in question with the 'Album Artist' tag, with different filenames to match.
All the other albums from that band have the same 'Album' and 'Album Artist' tag.

I tried to look if I did anything out of the ordinary apart from that, but I haven't been able to find anything.

Is this something you're familiar with?

**Comment by Taiko2k** [comment]
Looking into it, currently the 'Album Artist' tag is not considered. If the 'Artist' changes at any time going down the playlist, it is considered a different *batch* for sorting.

I should change this to also consider the album-artist, though, is this original behavior I described consistent with what you are seeing?

**Comment by Noisecommander** [comment]
It doesn't look like it. 
Late Night Tales is the mix album, this is how it's currently sorted:

`AIR - 10 000 Hz Legend (2001)
AIR - Everybody Hertz (2002)
AIR - City Reading (2003)
AIR - LateNightTales (2006)
AIR - Premiers Symptômes (1997)
AIR - Moon Safari (1998)
AIR - Love 2 (2009)
AIR - Le Voyage Dans La Lune (2012)`

I did just notice that everything after LateNightTales comes after it alphabetically, although still sorted per year.

**Comment by Noisecommander** [comment]
It doesn't look like it. <br>
Late Night Tales is the mix album, this is how it's currently sorted:<br>

AIR - 10 000 Hz Legend (2001)<br>
AIR - Everybody Hertz (2002)<br>
AIR - City Reading (2003)<br>
AIR - LateNightTales (2006)<br>
AIR - Premiers Symptômes (1997)<br>
AIR - Moon Safari (1998)<br>
AIR - Love 2 (2009)<br>
AIR - Le Voyage Dans La Lune (2012)<br>

I did just notice that everything after LateNightTales comes after it alphabetically, although still sorted per year.

**Comment by Noisecommander** [comment]
It doesn't look like it. 
Late Night Tales is the mix album, this is how it's currently sorted:

AIR - 10 000 Hz Legend (2001)
AIR - Everybody Hertz (2002)
AIR - City Reading (2003)
AIR - LateNightTales (2006)
AIR - Premiers Symptômes (1997)
AIR - Moon Safari (1998)
AIR - Love 2 (2009)
AIR - Le Voyage Dans La Lune (2012)

I did just notice that everything after LateNightTales comes after it alphabetically, although still sorted per year.

**Comment by Taiko2k** [comment]
Are all the ***artist*** tags identical? Even in the mix album? (So, all the artist tags of all the albums are "AIR", with no changes such as case?)

**Comment by Noisecommander** [comment]
No, all the albums, except LateNightTales, have 'AIR' as 'Artist' tag.
LateNightTales has a different 'Artist' tag for each track, but 'AIR' as 'Album Artist'.
(It didn't make a difference if I added 'AIR' as 'Album Artist' to the other albums.)

**Comment by Noisecommander** [comment]
Here's two screenshots of the tags of LateNightTales and Premiers Symptômes .

![LNT](https://user-images.githubusercontent.com/47405126/72243258-5cdc2100-35e3-11ea-9db7-2c1c2c8ca93c.png)

![PS](https://user-images.githubusercontent.com/47405126/72243262-61a0d500-35e3-11ea-8b7f-e5c1ee2f0720.png)

**Comment by Taiko2k** [comment]
> LateNightTales has a different 'Artist' tag for each track, but 'AIR' as 'Album Artist'.

Aha, so, that is to be expected. Previous versions didn't consider 'Album Artist' and would cause subsequent albums to be sorted separately. (So the first 3, LateNightTales, and the lest 4 would all be sorted separately)

Ive now committed a change so that 'Album Artist' *is* considered (as long as one of the first 3 albums 'has the same 'album artist' tag, it should detect it). 

So this fix should be available in the next release. 

If you would like to test and are using the AUR version, you can clone this repo and copy the contents to `/opt/tauon-music-box/`

**Comment by Noisecommander** [comment]
Right, I misinterpreted what you meant then.

Sure thing, I'll add 'AIR' as 'Album Artist' to the other albums and see what the new tauon.py will do.

**Comment by Taiko2k** [comment]
If you're using snap I could trigger an 'edge' channel build.

If you're using flatpak... I dont have a beta channel set up... Its a little hacky but you might be able to copy `tauon.py` to `/var/lib/flatpak/app/com.github.taiko2k.tauonmb/current/active/files/bin`.
