### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by andreaslutsch** [Taiko2k/TauonMusicBox#232]
It would be appreciated if there would be some HiDPI support to show larger menu and media buttons for higher resolutions and to be able to increase the font size of the tracklist more than 17.

**Comment by Taiko2k** [comment]
In the config file there's a setting called ui-scale. Try change it to a different value.

I regard it as being beta quality. Let me know if it works well for you.

**Comment by andreaslutsch** [comment]
I think I am missing a python3 library according to this error when I change the ui-scale:

```shell
Dev mode, ignoring single instancing
Database loaded in 0.042 seconds.
Locale detected: en_US
No translation file available
Force rerender icons
Traceback (most recent call last):
  File "tauon.py", line 3015, in <module>
    from t_modules.t_svgout import render_icons
  File "/var/git/TauonMusicBox/t_modules/t_svgout.py", line 3, in <module>
    from gi.repository import Rsvg
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 133, in load_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Rsvg, introspection typelib not found
```

**Comment by andreaslutsch** [comment]
I installed the `librsvg2-dev` library and it works, the scaling looks good, thank you for the nice music player!
