### ISSUE TITLE
Not able to open Tauon in Arch Linux.

### ISSUE THREAD

**Issue by laxudope** [Taiko2k/TauonMusicBox#233]
I am not able to open Tauon from last month. I don't know what's the issue here. I checked journalctl logs and there is something like  `kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow)`

here is gif attached. https://i.imgur.com/VgWUvu8.gif

journalctl -f output while clicking on Tauon Music Box icon: 

> Jan 18 16:40:59 0x00 kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 16760, resource id: 60817422, major code: 25 (SendEvent), minor code: 0
Jan 18 16:40:59 0x00 plasmashell[761]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2720, resource id: 60817422, major code: 2 (ChangeWindowAttributes), minor code: 0
Jan 18 16:40:59 0x00 kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 16766, resource id: 60817422, major code: 18 (ChangeProperty), minor code: 0
Jan 18 16:40:59 0x00 kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 16767, resource id: 60817422, major code: 18 (ChangeProperty), minor code: 0                                                 Jan 18 16:40:59 0x00 kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 16768, resource id: 60817422, major code: 20 (GetProperty), minor code: 0
Jan 18 16:40:59 0x00 kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 16817, resource id: 60817422, major code: 15 (QueryTree), minor code: 0
Jan 18 16:40:59 0x00 kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 16874, resource id: 60817424, major code: 18 (ChangeProperty), minor code: 0
Jan 18 16:40:59 0x00 bamfdaemon[918]: Got an X error: BadWindow (invalid Window parameter)
Jan 18 16:40:59 0x00 bamfdaemon[918]: Got an X error: BadWindow (invalid Window parameter)
Jan 18 16:40:59 0x00 bamfdaemon[918]: Got an X error: BadWindow (invalid Window parameter)
Jan 18 16:41:14 0x00 kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 17601, resource id: 60817430, major code: 15 (QueryTree), minor code: 0
Jan 18 16:41:14 0x00 kwin_x11[759]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 17606, resource id: 60817430, major code: 18 (ChangeProperty), minor code: 0

**Comment by Taiko2k** [comment]
Can you give the output of running Tauon from terminal?

`python /opt/tauon-music-box/tauon.py`

**Comment by laxudope** [comment]
➜  ~  python /opt/tauon-music-box/tauon.py
Tauon Music Box v5.2.0
Copyright 2015-2020 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/user/.local/share/TauonMusicBox
Install directory: /opt/tauon-music-box
Error loading window state file
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 550, in <module>
    import discogs_client
ModuleNotFoundError: No module named 'discogs_client'

**Comment by StrangeSeasOfThought** [comment]
@laxudope You just need to rebuild some of the dependencies, one of them is python-discogs-client.

See #205 for more info.

**Comment by laxudope** [comment]
> @laxudope You just need to rebuild some of the dependencies, one of them is python-discogs-client.
> 
> See #205 for more info.

not working. i just updated error on previous comment.

**Comment by Taiko2k** [comment]
Did you rebuild all 3 including python-hsaudiotag3k?

**Comment by laxudope** [comment]
> Edit: Make sure that's python-hsaudiotag**3k** and not have installed python-hsaudiotag.

Thank you very much. I solved the problem. There were two packages installed.
```
➜  ~  pip3 list 
Package                  Version           
------------------------ ------------------
hsaudiotag               1.1.1             
hsaudiotag3k             1.1.3             
```

I uninstalled `hsaudiotag` by this command `pip3 uninstall hsaudiotag`.
Now everything is working fine. Thanks
