### ISSUE TITLE
MacOS port

### ISSUE THREAD

**Issue by ChillHorse** [Taiko2k/TauonMusicBox#234]
Would you consider making .dmg files of Tauon?

**Comment by Taiko2k** [comment]
Yes as soon as someone buys me a macbook :wink:

Jokes aside, since I don't own a mac, my ability to test and package for macOS is limited. 

Inevitably releasing on a platform is going to necessitate platform specific solutions for things, and packaging into a .dmg will likely be a small challenge in of itself. 

So... no, I can't really say this is planned.

___

Just for fun, if anyone is interested in testing/hacking, it may be possible to ***run*** Tauon form source under macos, albeit not all features may work out the box.

How to get running:

  1. Install brew as described here https://brew.sh/
  2. Clone Tauon `git clone https://github.com/Taiko2k/TauonMusicBox.git`
  3. `cd TauonMusicBox`
  4. Install system deps `brew install pygobject3 gtk+3 sdl2 sdl2_image libnotify gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-ffmpeg`
  5. Install python deps `pip3 install -r requirements.txt`
  6. Run Tauon: `/usr/local/bin/python3 tauon.py`

Issues:

 - Audio probably wont work right away. 
    - For gstreamer, change `plulsesink` to `autoaudiosink` in gstreamer output under Audio > Settings 
    - For BASS, the auto install buttons wont work. Can be manually downloaded.
 - Mediakeys wont be working.
 -  I have no idea about how HiDPI works on macos.
  - Does Tauon make sense on macOS? Does it integrate well? Does it look good?

**Comment by tarasyyyk** [comment]
Yes, it's definitely need a good replaceemnt to default iTunes / Vox player. Unfortunately, there are no good alternatives for macOS, like AIMP for Windows. Standard iTunes sucks and Vox isn't better. There are a lot of Audio editors, audio converters for macOS, but no good audio **player**. So , creating new good-looking app (like this) is a good point.
Currently, the app is running on macOS Mojave but need to change audio output to "Auto" (autoaudiosink). Even FLAC music playing great.
Here is how it looks:
<img width="1166" alt="Tauon Music Box 2020-02-10 00-13-07" src="https://user-images.githubusercontent.com/20100011/74111096-aac05680-4b9a-11ea-9106-439ed17b3c41.png">
Here are list of bugs I found:
- BASS audio not working. Error is "Playback thread has crashed." but no errors in console.
- Album cover (images) not showing 
- non-retina adopted

**Comment by Taiko2k** [comment]
> need to change audio output to "Auto" (autoaudiosink).

Okay, I've now set this as the default

> BASS not working

Try extract the contents of this zip https://github.com/Taiko2k/TauonMusicBox/releases/download/v5.2.0/basslibsosx.zip to the `/lib` sub-folder. If you still get the "Playback thread has crashed." error, I currently have errors redirected to a file named `crash.log` in the `user-data` sub-folder.

> Album cover (images) not showing

It looks like its just gallery thumbnails are not loading? But in *side panel* and *track info* they are?

In `tauon.py` try search for this line `print('Image load failed on track: '` and un-comment the `raise` line just above it. That might reveal the error in the console.

### Questions

**Does the UI scaling setting work?** In Tauon's config file, try set `ui-scale` to `2.0` and restart the app. The UI should then look normal except everything is twice as big. (The window will still be non-retina, trying to fix that is a later step)

**Do mediakey now work?** Try `git pull` to update Tauon to latest commit then `pip3 install osxmmkeys`

**Comment by ChillHorse** [comment]
Sorry for the late reply, I'm getting mixed results on MacOS Catalina I couldn't get Gstreamer to work at all. After installing BASS GStreamer suddenly works in Auto mode? 

BASS installation is bothersome on Catalina since you manually need to right click >open every .dylib file otherwise the system will complain that it's not verified by Apple.

when trying to run with BASS I immediatly get "Playback thread has crashed" error message, crashlog indicates that OSX blocks the .dylib files even tho there's no longer a System Popup complaining that those files arent verified. Running with sudo didn't help
[Tauon-log.txt](https://github.com/Taiko2k/TauonMusicBox/files/4180024/Tauon-log.txt)


Artwork worked for me without edits

UI scaling did not work for me

**Comment by Taiko2k** [comment]
> OSX blocks the .dylib files.... "not valid for use in process using Library Validation: library load disallowed by system policy"

Well that makes things difficult. This issue might also arise when trying to bundle the app as well. :expressionless:

**Comment by ChillHorse** [comment]
> > OSX blocks the .dylib files.... "not valid for use in process using Library Validation: library load disallowed by system policy"
> 
> Well that makes things difficult. This issue might also arise when trying to bundle the app as well. 😑

Just tried something. I went to **system preferences > security** than allowed the the Terminal in both sub categories "full system access" and "developer tools"

that pretty much reduced the crash log to:

> 2020-02-10 12:15:02,361 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6542, in bass_player_thread
    player(pctl, gui, prefs, lfm_scrobbler, star_store)
  File "/Users/phk/git-repos/TauonMusicBox/t_modules/t_bass.py", line 94, in player
    BASS_FX_GetVersion = function_type(ctypes.c_ulong)(("BASS_FX_GetVersion", fx_module))
UnboundLocalError: local variable 'fx_module' referenced before assignment

**Comment by Taiko2k** [comment]
> that pretty much reduced the crash log to:

Okay, I've pushed a fix for that.

> after uncommenting raise in tauon.py it was fixed for me

That's weird. Did any error show in console after doing that?

**Comment by ChillHorse** [comment]
BASS now works.

No error message about the artwork, no.

I did mention that setting ui-scale to 2 didn't work for me, noticed it defaulted back to 1. When forcibly change the value to 2 Tauon won't start.

> Tauon Music Box v5.2.2
Copyright 2015-2020 Taiko2k captain.gxj@gmail.com
Running in portable mode
Install directory: /Users/phk/git-repos/TauonMusicBox
Dev mode, ignoring single instancing
Database loaded in 0.004 seconds.
No translation file available
Force rerender icons
Traceback (most recent call last):
  File "tauon.py", line 3093, in <module>
    from t_modules.t_svgout import render_icons
  File "/Users/phk/git-repos/TauonMusicBox/t_modules/t_svgout.py", line 3, in <module>
    from gi.repository import Rsvg
  File "/usr/local/lib/python3.7/site-packages/gi/importer.py", line 133, in load_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Rsvg, introspection typelib not found

couldn't find typelib on brew, otherwise I'd test it out

**Comment by Taiko2k** [comment]
> couldn't find typelib on brew, otherwise I'd test it out

I think it might be this it needs https://formulae.brew.sh/formula/librsvg

___

As for disabling the zooming, it seems setting `NSHighResolutionCapable': 'True'` in an info_plist file should do it. Would need to be done as part of a bundle package... Seems pyinstaller can do that as mentioned here https://stackoverflow.com/a/40676321

**Comment by ChillHorse** [comment]
installing `librsvg` fixed not being able to launch Tauon when ui-scale is 2; reverting the value to one won't scale back/down svg elements. Can confirm @tarasyyyk 's observation, except the artwork part. 
<img width="1166" alt="Bildschirmfoto 2020-02-10 um 14 46 23" src="https://user-images.githubusercontent.com/17539404/74155339-b9e3ea80-4c14-11ea-839c-82b5172e3006.png">

looks like we're getting closer to an actual OSX release. Yay!

**Comment by Taiko2k** [comment]
> 2; reverting the value to one won't scale back/down svg elements. 

This was actually an existing bug I forgot about, I've fixed this now.
___
OK, so... I have a thing: https://github.com/Taiko2k/TauonMusicBox/releases/download/v5.2.0/tauon-osx-testing.zip

- Does running this work? `open -a tauon.app`
- Is the window no longer zoomed? 

Note: Ive disabled the media keys module since it was causing problems

**Comment by tarasyyyk** [comment]
This error happens when opening app:
`LSOpenURLsWithRole() failed for the application /Users/tarasyyyk/Downloads/tauon.app with error -10810.`
It seems something related to macOS's Launch Services framework.
Tried also chmod +x but no luck.

**Comment by Taiko2k** [comment]
> This error happens when opening app

What happens if you launch the inner executable `./tauon.app/Contents/MacOS/tauon`?

**Comment by ChillHorse** [comment]
> This error happens when opening app:
> `LSOpenURLsWithRole() failed for the application /Users/tarasyyyk/Downloads/tauon.app with error -10810.`
> It seems something related to macOS's Launch Services framework.
> Tried also chmod +x but no luck.

the .app needs to be in the Applications directory, otherwise you can't run it

- BASS audio doesn't work in this test release.
- Dunno if you already did something with the `NSHighResolutionCapable`setting but it's currently blurry on retina displays
- artwork will not load in most views
- while the correct icon is displayed for tauon in the dock, the python floppy disk icon will remain in the launchpad and application directory but I guess it's not a priority at all currently since it's a test and all

**Comment by Taiko2k** [comment]
> Dunno if you already did something with the NSHighResolutionCapablesetting but it's currently blurry on retina displays

I did I thought that would work aaaaaaa

> BASS audio doesn't work in this test release.

aaaaaaaa

> switching system to external GPU wihch is not good.

aaaaaaaa

> OSX blocks the .dylib files.... "not valid for use in process using Library Validation: library load disallowed by system policy"

aaaaaaaa

> artwork will not load in most views

AAAAAAA

I can't take this confounded operating system anymore :dizzy_face:

**Comment by ChillHorse** [comment]
Tried giving the tauon.app full system privilliges but it doesn't change anything. 
Noticed two more things

- visualizer not appearing
- Transcode setting seemingly can't find ffmpeg


Let's take a breather and love Lain

**Comment by Taiko2k** [comment]
If you try run `./tauon.app/Contents/MacOS/tauon` it will print output to console, so might give a hint.

> visualizer not appearing

This isn't implemented on the GStreamer side, so to be expected if bass isn't working.

> Transcode setting seemingly can't find ffmpeg

Ah, I had hoped that would just work. Do you have ffmpeg installed? Does the command `which ffmpeg` find it?

**Comment by ChillHorse** [comment]
ffmpeg is installed and cab be found via cli

here's the output

> Tauon Music Box v5.2.2
Copyright 2015-2020 Taiko2k captain.gxj@gmail.com

> Running in portable mode

>Install directory: /Applications/tauon.app/Contents/MacOS
PyLast moduel not found, last fm will be disabled.
Database loaded in 0.021 seconds.
No translation file available
Using SDL version: 2.0.10
Using GStreamer as fallback. Some functions disabled

>(<unknown>:3704): GStreamer-WARNING **: 10:48:38.827: Failed to load plugin '/Applications/tauon.app/Contents/MacOS/libtheoraenc.1.dylib': dlopen(/Applications/tauon.app/Contents/MacOS/libtheoraenc.1.dylib, 2): Symbol not found: _th_comment_add
  Referenced from: /Applications/tauon.app/Contents/MacOS/libtheoraenc.1.dylib
  Expected in: flat namespace
 in /Applications/tauon.app/Contents/MacOS/libtheoraenc.1.dylib
Config reload theme...
Applying external theme: Wasp
Theme number: 10
Enabling garbage collecting
OPEN URI
Writing database to disk.
Image load failed on track: /Users/phk/Music/Boris Brechja/Boris Brejcha - DJ Mixes Single Tracks/1 - Boris Brejcha - Amisette _ Amisette.mp3
Image load failed on track: /Users/phk/Music/Boris Brechja/Boris Brejcha - Boris Brejcha - White Snake EP (MP3 EP)/1 - Boris Brejcha - Arche Noah.mp3
Image load failed on track: /Users/phk/Music/Boris Brechja/Boris Brejcha - Boris Brejcha - Die Maschinen sind Gestrandet (MP3 Album)/1 - Boris Brejcha - Wellenreiter.mp3
Image load failed on track: /Users/phk/Music/Boris Brechja/Boris Brejcha - Bleeding Heart/1 - Boris Brejcha - Bleeding Heart _ Bleeding Heart.mp3
Image load failed on track: /Users/phk/Music/Boris Brechja/Boris Brejcha - Boris Brejcha - Mein Wahres Ich (MP3 Album)/1 - Boris Brejcha - Flying Bird.mp3
Image load failed on track: /Users/phk/Music/Boris Brechja/Boris Brejcha - Boris Brejcha - Lost Memory (MP3 EP)/1 - Boris Brejcha - Lost Memory.mp3
Image load failed on track: /Users/phk/Music/Boris Brechja/Boris Brejcha - Boris Brejcha - Feuerfalter Special Edition (MP3 Album)/1 - Boris Brejcha - Frequenzfett.mp3
Image load failed on track: /Users/phk/Music/Caravan Palace - Wonderland/Caravan Palace - Wonderland.mp3
Traceback (most recent call last):
  File "tauon.py", line 34085, in <module>
  File "tauon.py", line 21683, in render
  File "tauon.py", line 20208, in audio
  File "tauon.py", line 930, in gen_gst_out
KeyError: 'Built-in Output'
[3704] Failed to execute script tauon

This time I had no audio from Gstreamer due to a connected USB C display (whihc I hadn't previously connected), when I changed the output in the app it crashed right away

**Comment by tarasyyyk** [comment]
> the .app needs to be in the Applications directory,

the app is not starting for me, because it was build for macOS 10.15. This error explains:
```
Referenced from: /Applications/tauon.app/Contents/MacOS/gi/../libgio-2.0.0.dylib (which was built for Mac OS X 10.15)
```

My system is 10.14.6

**Comment by Taiko2k** [comment]
Unfortunately I don't see a method forward. Too many conflicting Issues:

 - I don't know how to disable zooming on retina displays, but it seems to necessitate creating a binary .app bundle (also needed for desktop launcher?)
 - Bundling binary Brew deps doesn't seem to work for different macOS builds.
 - Many Brew deps are LGPL licensed making bundled distributions legally complicated. 
 - Bass dll's require signing unless a security setting is changed (apple may remove this setting entirely in the future)
 - It may be possible to package Tauon as a brew package and let Brew take care of the deps, but this doesn't solve the retina or bass issues.
 - A mysterious issue with image loading lingers.

**Comment by ChillHorse** [comment]
> * I don't know how to disable zooming on retina displays, but it seems to necessitate creating a binary .app bundle (also needed for desktop launcher?)

Once an .app is inside the application directory it's listed in the launcher, the .app icon is used for it in this case it was probably the pyinstaller icon. On the dock the purple CD is displayed like it should.
<img width="143" alt="Bildschirmfoto 2020-02-13 um 13 27 49" src="https://user-images.githubusercontent.com/17539404/74435399-a3cc6900-4e64-11ea-9a7b-7307bc811d9d.png">
about the scaling, I found a few more tags that can be set for Qt apps https://stackoverflow.com/questions/17211006/optimising-python-qt-apps-on-retina-displays


> * Bundling binary Brew deps doesn't seem to work for different macOS builds.
> * Many Brew deps are LGPL licensed making bundled distributions legally complicated.
> * Bass dll's require signing unless a security setting is changed (apple may remove this setting entirely in the future)
> * It may be possible to package Tauon as a brew package and let Brew take care of the deps, but this doesn't solve the retina or bass issues.

Mac installers are pretty much glorified and fancy .zip files with huge icons that tell you to drag&drop the .app to Applications/ . Some include ReadMe's and shell scripts. So instead of a .dmg you could make a .zip available with a readme.txt, install-deps-via-brew-in-directory-xy.sh and tauon.app. Not the fanciest way but a workaround.
Here's an example for a .dmg file 
![Bildschirmfoto 2020-02-13 um 13 36 54](https://user-images.githubusercontent.com/17539404/74436095-2275d600-4e66-11ea-91af-c60b62e6c9aa.png)



> * A mysterious issue with image loading lingers.

No Idea for that one tho

**Comment by Taiko2k** [comment]
I'm closing this old issue. If anyone here is still interested in running Tauon on mac, I've made a fresh issue #577
