### ISSUE TITLE
doesn't work in arch linux

### ISSUE THREAD

**Issue by Gictorbit** [Taiko2k/TauonMusicBox#236]
I just installed your music player with `yay` and when I opened it, a transparent window appears and nothing couldn't be displayed just some shadow is around the border of it 
I tried to open it from the command line to check the error but I didn't find any command

**Comment by Taiko2k** [comment]
To run from terminal you can use `python /opt/tauon-music-box/tauon.py`

**Comment by Gictorbit** [comment]
Hmm I checked that here is the result:
```
Running from installed location
User files location: /home/victor/.local/share/TauonMusicBox
Found XDG-Downloads: /home/victor/Downloads
Found XDG-Music: /home/victor/Music
Install directory: /opt/tauon-music-box
Database loaded in 0.0 seconds.
No translation file available
Using SDL version: 2.0.10
Using GStreamer as fallback. Some functions disabled
Config reload theme...
Applying external theme: Sky
Theme number: 8
Enabling garbage collecting
```

**Comment by Taiko2k** [comment]
I assume the issue might be video driver related. Do you know of any reason opengl might not work on your configuration?

**Comment by Gictorbit** [comment]
ohh I checked my graphic card driver and I find out that since last update, it has some problems then I fixed issues and music player works great thank you

**Comment by Taiko2k** [comment]
Glad to hear you got it fixed!
