### ISSUE TITLE
Add case insensitive sorting

### ISSUE THREAD

**Issue by skielred** [Taiko2k/TauonMusicBox#237]
When I display by columns, and click "Sort ascending" or "Sort descending" on columns such as Album name or Title, I'd expect the sort to do an insensitive sort.

Currently, this is not the case, so a few albums that have their name starting with a lowercase letter (this is intended, as this is their true album name) appear at the bottom of the list, after albums named with Z.

I'd like it so we can either enable case insensitive sorting, or make it the default for relevant columns.

**Comment by Taiko2k** [comment]
Not sure why I had it like that, maybe I just didn't consider that at the time.

I've committed this change now. Ignoring case will just be the new default.

**Comment by skielred** [comment]
I confirm it's fixed in the new version
Thank you 🌸
