### ISSUE TITLE
Adding a new song does not refresh existing Artist playlists

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#241]
Using Tauon 5.2.1

Let's say I've a `Default` playlist folder with all my music, I search for an Artist `Billie Eilish` and click on the Artist entry to create a new `Artist: Billie Eilish` playlist.

Now, if I add a new song and rescan the Default folder, the `Artist: Billie Eilish` playlist does not get updated, and the rescan button on the playlist is disabled.

![image](https://user-images.githubusercontent.com/1641362/74589611-fe052f80-5006-11ea-9699-f150f7828a8b.png)

The only way to refresh songs that I know of is to delete the `Artist: Billie Eilish` playlist, and re-add it via the search feature again, after which the new songs are added:

![image](https://user-images.githubusercontent.com/1641362/74589636-27be5680-5007-11ea-9d1d-49b4837825f0.png)

Is it possible to add a feature that allows for at least a manual refresh by right clicking on the playlist and pressing rescan?

**Comment by Taiko2k** [comment]
OK. I'm thinking maybe playlists that have the `Artist: ` prefix should automatically update upon any import.

Or maybe could also expand this into some kind of *smart playlist* expression code that could be added to a playlist which could allow for a range of automatic generation. 

Say for example something like: `MyPlaylist ! s"Default"a"Billie Eilish"p>2y<` which would **S**ource **A**rtist tracks "Billie Eilish" from the playlist "Default" that have a **P**laycount greater than 2, then sort the result by **Y**ear newest to oldest.

Would be a more powerful solution, though might be too weird and confusing for new users.

**Comment by C0rn3j** [comment]
>though might be too weird and confusing for new users
Well, if the current UX for making an `Artist: ` playlist doesn't change and this is just how it would look in the backend, I think even casual people would be fine with it or not notice that all.

And it'd probably make power users with properly tagged playlists super happy if you want smart playlist capable of filtering by any metadata.

**Comment by Taiko2k** [comment]
Might be useful to hear what different peoples use cases are.

@StrangeSeasOfThought I remember you were looking for smart playlists, perhaps your use case could be accommodated here.

**Comment by StrangeSeasOfThought** [comment]
> OK. I'm thinking maybe playlists that have the `Artist: ` prefix should automatically update upon any import.

That'd be great. Or just being able to refresh/rescan 'Artist: playlist' manually, doesn't need happen automatically. Either one is fine.

Smart playlists: I always create smart playlists via ratings. All my songs are rated and saved as tags. That's the most reliable solution I could find when listening to music on various devices (e.g. desktop, notebook, smartphone). Let's say I listen to music on my desktop pc, then the playcount would increase, but remain the same on my notebook and my smartphone. I would've to constantly sync my music library.
It's also quite easy to accidentally reset the playcount. And the playcount is usually higher on songs that have been in my library for a long time, so a high playcount doesn't necessarily mean that I particularly like that song.

That being said, a way to input smart playlist expression code (like your example) would still be better than not having that option at all. 

As an example: I totally love Cantata's smart playlist feature (which is also well explained and easy to understand):

![smart1](https://user-images.githubusercontent.com/43582772/74604676-7ed43200-50c0-11ea-852b-a5afb7f047ad.png)

![smart2](https://user-images.githubusercontent.com/43582772/74604679-83004f80-50c0-11ea-8cfa-7fc7d27d5079.png)

**Comment by Taiko2k** [comment]
OK. Ive made some changes now.

Now in the playlist tab menu, there is an option called `Regenerate`.

![Screenshot from 2020-02-17 20-19-37-cropped](https://user-images.githubusercontent.com/17271572/74631857-effc0e00-51c2-11ea-80bf-4b1ede78b17f.jpg)

This *should* "just work" for the original issue; pressing will re-search the original artist. There are not any other obvious changes.

___

For advanced users, you can now edit codes that generate the playlist. You can edit this by pressing <kbd>Tab</kbd> at the *rename playlist box*.

![Screenshot from 2020-02-17 20-25-08-cropped](https://user-images.githubusercontent.com/17271572/74632211-b7a8ff80-51c3-11ea-80ef-f2c26d3464b0.jpg)

I have an explanation of the codes [here](https://github.com/Taiko2k/TauonMusicBox/wiki/Generator-Codes).

___

Also, Ive added FMPS_Rating read support from Vorbis tags for use with the above function (but ive not tested it since I don't have any files with this tag) (You will need to run a tag rescan on existing tracks)

**Comment by StrangeSeasOfThought** [comment]
Woah, awesome! I don't know when I'll have enough time again to really test this, though. Perhaps next weekend.

What about album artists?

**Comment by StrangeSeasOfThought** [comment]
Generating playlists with codes works well. However, the gallery sometimes shows the same artwork multiple times or not all of the albums. I have to regenerate the playlist to fix the gallery issues.

On (smaller) playlists, not the default playlist, maybe display "x tracks" instead of "x album" below the artist name in artist list view.

**Comment by Taiko2k** [comment]
> the gallery sometimes shows the same artwork multiple times or not all of the albums.

I think I've fixed this now

> all artists have "1 album" which doesn't really look nice and isn't useful information.

OK, I've changed it now to show track count if all artists only have one album

>  'Ratings greater than' doesn't work properly (it actually seems to list tracks with 'Ratings smaller than'. Would love additional filters (has no ratings, rat<..., rat=...) and support for mp3 files.

I'll look into adding those.

Do you know what frame is used to store your ratings in the MP3's? Is it POPM? or FMPS_Rating? or both? If its just FMPS_Rating, I'm not sure where that frame is, you might need to give me a file for testing.

**Comment by StrangeSeasOfThought** [comment]
I actually use POPM (for music player on smartphone) and FMPS_Rating (for desktop/notebook music player).

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought Ok, I ive added FMPRS_Rating from mp3 now. (You'll need to tag rescan). Ive also now added the codes: `rat< rat<0.5 rat=0.5 norat`

**Comment by StrangeSeasOfThought** [comment]
Filtering with ratings works perfectly now, but only vorbis files. Doesn't work with mp3s. Should I send you one?

**Comment by StrangeSeasOfThought** [comment]
When is "automatically update" being triggered?

**Comment by Taiko2k** [comment]
> When is "automatically update" being triggered?

Should be being triggered on file import (and ignores regenerating playlists using a shuffle code)

**Comment by StrangeSeasOfThought** [comment]
Tried to add tracks from genre. My g"OST" tag didn't work, g"ost" did work. You might want to mention case sensitivity in the wiki.

**Comment by Taiko2k** [comment]
> Tried to add tracks from genre. My g"OST" tag didn't work, g"ost" did work. You might want to mention case sensitivity in the wiki.

It should be case insensitive. Can you double check that?

**Comment by StrangeSeasOfThought** [comment]
> > Tried to add tracks from genre. My g"OST" tag didn't work, g"ost" did work. You might want to mention case sensitivity in the wiki.
> 
> It should be case insensitive. Can you double check that?

It does work now... v0v

**Comment by StrangeSeasOfThought** [comment]
> OK, I've changed it now to show track count if all artists only have one album

I increased this to 2 and might even go as far as 3.
Single + Studio Album / Single + Single / Single + Studio Album + Single.
