### ISSUE TITLE
[Feature Request] Subsonic/Libresonic client integration

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#244]
I see that Tauon supports Plex, would be great if it could support subsonic as well :D

**Comment by Taiko2k** [comment]
Okay, I've committed initial support for this now.

Bear in mind, I haven't given support for these network sources a ton of testing. I'm not sure how they perform with real world use.

**Comment by legion1978** [comment]
Hi there.-- these are like Kodi, right? is this to play inside TMB media on Plex and such? or the other way around (controlling TMB via kodi for example)?

**Comment by Taiko2k** [comment]
@legion1978 It's like playing your PLEX music in Tauon. Kind of like importing a mounted network share.

**Comment by legion1978** [comment]
mmm ok i get it :) thanks.

**Comment by Taiko2k** [comment]
This should be working in the latest version. Feel free to re-open if there are any issues, or create a new issue for new related features.

**Comment by awsms** [comment]
Thanks! I'll be waiting for you to push the upadte for the snapcraft package before testing it =)

**Comment by Taiko2k** [comment]
> Thanks! I'll be waiting for you to push the upadte for the snapcraft package before testing it =)

Unfortunately the latest snap builds are currently failing. Someone is looking into the issue, I can't give an exact eta. :disappointed_relieved:
