### ISSUE TITLE
Playlist & gallery jump to a different position on their own

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#245]
I've had this bug for some time now: 

**Sometimes** the playlists jumps on its own to a different position (this has happened in the gallery, too, but less often, probably because I'm not using the gallery that often). I didn't accidentally touch the mouse wheel.

Some observations:

- While no music is playing (so maybe right after starting the app).
- It might have happened when going from playlist A to playlist B.
- It might also happen during playback, not sure (it's not the new song playlist postion change!).
- It might select a track on its own and jump to that position.
- It might want to show me that there's a track selected first, before it lets me look around the playlist freely (there's usually a short delay before the jump).

It doesn't happen always, maybe once per day.

**Comment by Solarunit** [comment]
I have noticed this too.

**Comment by Taiko2k** [comment]
Yes I've noticed this, thought it might have been just my mouse wheel malfunctioning.

Hard one to debug though. 

Ive enabled some debug messages in the latest commit. If we can launch and leave open with console, then if the playlist changes position unexpectedly, hopefully we can see a reason for that.

So if it happens, quickly check the output and copy and paste here. (take note of the times too, see if an event matched when you think it happened) (also note if a track was playing at the time)

**Comment by StrangeSeasOfThought** [comment]
Wait, what? I actually posted this? /o\

I do have this bug, but while writing the post, I felt like perhaps I should look into this more, so gave up on it. Well, it's good to know I'm not the only one.

I'd say since v5.2.0 release or v5.2.1.

**Comment by Taiko2k** [comment]
Instead of needing to keep a terminal window open, I've now built in a console. You can toggle it using the backquote key <kbd>`</kbd>

**Comment by StrangeSeasOfThought** [comment]
> Instead of needing to keep a terminal window open, I've now built in a console. You can toggle it using the backquote key `

Good idea. Can you please add console to input.txt? Backquote key doesn't work for me.

**Comment by Taiko2k** [comment]
> Can you please add console to input.txt? 

OK I've added `toggle-console` to input.txt (run Tauon at least once after updating so it adds it)

**Comment by StrangeSeasOfThought** [comment]
14:52:03 Do transition GAPLESS
14:53:12 DEBUG: Position changed by playlist change
14:53:12 DEBUG: Position set by show playing
14:53:12 DEBUG: Postion set by album locate
14:53:12 DEBUG: Position changed by mouse wheel scroll: -1

Switched from playlist B to playlist A (default playlist). Playlist didn't properly jump to the currently playing song. Actually, the currently playing song is the first song/album that is off-screen.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought Can you replicate this behavior, or was it just one off random? Do you know if subsequent "Go to playing" presses then work as expected? Also, that mouse wheel scroll there was intentional right?

**Comment by StrangeSeasOfThought** [comment]
I'm currently updating to the new version (adding my own changes), so I couldn't test it. Most likely just a one off. But I'm pretty sure this is the bug I encountered all this time. Basically the currently playling song ends up off screen for some reason which makes it seem like I scrolled. Go to playing worked, I think.
The mouse wheel scroll was probably me trying to locate the correct song.

**Comment by Taiko2k** [comment]
So.. according to that, it should have gone like this:

> 14:53:12 DEBUG: Position changed by playlist change

The tracklist view position should be where you last left of.

> 14:53:12 DEBUG: Position set by show playing
> 14:53:12 DEBUG: Postion set by album locate

You intentionally pressed "Go to playing" to show the playing track/album. Track should now be visible in the tracklist.

> 14:53:12 DEBUG: Position changed by mouse wheel scroll: -1

You scrolled slightly (within the same second you pressed "go to playing"??)

___

Soo, at what point did something unexpected happen? Did it happen as a result of your action, or spontaneously without your interaction? (the latter being how I interpret the OP)

**Comment by StrangeSeasOfThought** [comment]
IIRC:

I imported a single album (two songs). Went to "Released in 2020" playlist to test playlist auto update. Added both songs to queue. After the first song started playing I switched back to the default playlist. Auto behavior should be playlist position change to currently playing song when switching playlists. I immediately noticed that the currently playing song wasn't being displayed after switching playlists. Close by, but off-screen. So I scrolled up.

**Comment by StrangeSeasOfThought** [comment]
> You intentionally pressed "Go to playing" to show the playing track/album. Track should now be visible in the tracklist.

No, that's the auto behavior.

**Comment by Taiko2k** [comment]
Oh right, you have the `auto-show-playing` setting enabled.

Yeah, -1 is scroll down. Keep on the lookout for if it happens again.

**Comment by StrangeSeasOfThought** [comment]
I'm closing this issue for now. It happens too rarely anyway. I'll keep my eyes on it, though.

**Comment by StrangeSeasOfThought** [comment]
It happened just now. Gallery moved on its own. My hands were far away from mouse/keyboard.

20:16:06 DEBUG: Position set by show playing
20:16:06 DEBUG: Postion set by album locate
20:16:07 Do transition GAPLESS

Nothing special in console. I noticed that mouse wheel scroll when used in gallery doesn't appear in console.

**Comment by Solarunit** [comment]
@Taiko2k @StrangeSeasOfThought 
I think I found one issue - see gif:

![tmb](https://user-images.githubusercontent.com/20891064/76177153-5b367000-61c4-11ea-9cb9-8f80dcd63633.gif)

The next track in the queue is from the next album.

**Comment by Taiko2k** [comment]
@Solarunit That is currently more or less intentional behavior. Previously the playlist would not change scroll position on track advance if the next track were already in view, but with along with #169 the automatic behavior of track transition happened to be changed too.

I wonder if this (automatic) behavior is desirable.

___

The issue of this original issue, as I see it, is the possibility of the view position changing when the user is not interacting with anything that should change the view position ***and*** a track transition is not taking place.

**Comment by Solarunit** [comment]
> That is currently more or less intentional behavior.

Oh, I think it is unexpected and very confusing behavior.

**Comment by Solarunit** [comment]
> jump to playing track should always show entire album

What if the album or folder has many tracks and the next playing track is №123

**Comment by Taiko2k** [comment]
> What if the album or folder has many tracks and the next playing track is №123

I just tested this and the current behavior in this scenario is to do nothing (automatic only, manual *show playing* still shows the track)

**Comment by Taiko2k** [comment]
Okay, I've made some changes. It should be more smarter about moving the view position now. It will try avoid jolting the view if you're already looking at the track, but try to align the album to top otherwise suitable.

**Comment by Solarunit** [comment]
Thanks alot!

**Comment by StrangeSeasOfThought** [comment]
The bug is actually a hardware (driver?) issue. I've noticed it in several more applications like chrome and vlc.

**Comment by Solarunit** [comment]
@Taiko2k The behavior is the same as on my gif. Tauon 5.3.1.

**Comment by Taiko2k** [comment]
@Solarunit I see, the issue is still persisting when using the queue specifically. Ill fix this.
