### ISSUE TITLE
Broadcast tries to play deleted files

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#246]
Using TMB 5.2.1.

I have a playlist with 3 songs - A, B and C. I start broadcasting with A, then delete B off disk.
When A finishes, broadcast will try to play the deleted broken file B, instead of detecting it is gone and playing C. 

This is normally not an issue in the normal player as it'll detect the file was deleted and will mark it as such, but it does not seem this logic is triggered in the broadcast mode.

**Comment by Taiko2k** [comment]
OK, I've pushed a fix for this.

**Comment by C0rn3j** [comment]
Amazingly quick response as always, thanks for the fix!
