### ISSUE TITLE
Could not scrobble warning message

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#247]
As it is, the user has to click away the warning message every time a song couldn't be scrobbled. It makes sense, but is also somewhat annoying on a longer period of time. Especially if you don't have a (good) connection at that moment.

![error](https://user-images.githubusercontent.com/43582772/75112965-7bedba00-5649-11ea-8dd7-daf3008768b7.jpg)

Any chance of moving that message to the top, to the right of the menu button? And have it disappear automatically as soon as scrobbling worked again?

Quick mock up:

![error](https://user-images.githubusercontent.com/43582772/75112761-29ab9980-5647-11ea-90ac-bb779de566f9.png)

Or perhaps just the last.fm icon (or the warning icon) with the error message as mouse over text.

**Comment by Taiko2k** [comment]
OK. I have committed this change.

**Comment by StrangeSeasOfThought** [comment]
Ok, looks good. But shouldn't it stay there as long as scrobbling doesn't work? Does the scrobble cache survive closing the app?

**Comment by Taiko2k** [comment]
> But shouldn't it stay there as long as scrobbling doesn't work? 

Okay, ive now made it stay until the scrobbles have been sent

> Does the scrobble cache survive closing the app?

No

**Comment by StrangeSeasOfThought** [comment]
Yeah, then it's better to remain visible.
