### ISSUE TITLE
The visualizers are no longer working

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#248]
![image](https://user-images.githubusercontent.com/19501722/75375815-ca5bbc80-58c6-11ea-9594-9b3c0bad6538.png)

![image](https://user-images.githubusercontent.com/19501722/75375847-d9db0580-58c6-11ea-85c1-692590712b0c.png)

![image](https://user-images.githubusercontent.com/19501722/75375832-d2b3f780-58c6-11ea-9621-71341f690118.png)

I'm not sure when they stopped working but it's been a while. The above images show them in order, Level Meter and Spectrogram show black rectangles where they should be showing up and the Spectrum Visualizer doesn't show anything at all.

**Comment by Taiko2k** [comment]
Are you using the BASS backend setting? Visualisers aren't implemented on the GStreamer side. (Check the "Audio" tab in settings)

**Comment by Bauke** [comment]
Ah, yes. With BASS it works now.

Maybe it's a good idea to disable them entirely when using GStreamer then?

**Comment by Taiko2k** [comment]
> Maybe it's a good idea to disable them entirely when using GStreamer then?

OK, I've improved the UX for this.
