### ISSUE TITLE
Playlist panel doesn't scroll when using arrows keys

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#249]
Playlist panel doesn't scroll when using arrows keys for navigation

**Comment by Taiko2k** [comment]
OK, I've committed a fix for this now.

**Comment by Solarunit** [comment]
Thanks!

**Comment by StrangeSeasOfThought** [comment]
Using arrow keys when renaming playlists / adding playlist code also cycles through the playlists.
