### ISSUE TITLE
Adding more sources for Lyrics

### ISSUE THREAD

**Issue by farahnur42** [Taiko2k/TauonMusicBox#251]
It would be really helpful in terms of grabbing lyrics if there were more sources, at least a couple of the major ones like Genius or Musixmatch.

**Comment by Taiko2k** [comment]
Problem with a major ones is their API often costs money, have restrictive terms that don't work with open-source software, or require a user account.

And I'd prefer not to resort to/encourage scraping.

**Comment by farahnur42** [comment]
In that case I wonder how Clementine does it, and whether there are any comparable ones to these that do follow the requirements you've explained here. If there aren't any then I guess I can close this issue, but I do hope there is an adequate alternative

**Comment by Taiko2k** [comment]
Seems most players use scraping. I guess its up to the user if they want to use this, I do have a disclaimer there already.

Ive now added Genius to the list of lyrics sources

**Comment by C0rn3j** [comment]
Would you please add [Open Lyrics Database](https://lyrics.github.io/) to the list?

This would require the user to be able to specify the URL, as there is no official OLD API instance to my knowledge.

https://github.com/Lyrics/lyrics-api#web-interface

I've an instance spun up on [lyrics.rys.pw](https://lyrics.rys.pw/?title=six%20shooter) if you were to do this and needed one for testing.

---

![image](https://user-images.githubusercontent.com/1641362/75626226-2031ac80-5bc6-11ea-82cb-0aae7f8d81aa.png)

I'd rewrite this to something like "Sources will be searched in the order in which they were enabled"

**Comment by Taiko2k** [comment]
@C0rn3j It would still be possible to programmatically search and scrape the pages. Therefore is there any advantage to using a mirror?

Or alternatively, perhaps the user could download the archive as a one off and Tauon could search this locally?

**Comment by C0rn3j** [comment]
>Therefore is there any advantage to using a mirror?
The 'mirror' is a proper API and not HTML scraping, which wouldn't put needless load on the website and you can just get whatever format you want from it.

Getting the archive and making it update at some interval is an option I guess, but then you'll have to deal with parsing the archive yourself.

My preference would be to be able to point it at the API since I have that up, but I'll be happy for any solution. 

I guess adding both a scraping/archive option and a custom API endpoint option would satisfy everyone?

**Comment by Taiko2k** [comment]
Hmm. The Open Lyrics Database does seem very small :confused:. The first two options are probably more trouble than they're worth anyway. But then for the API option... a typical user isn't going to know where to find a *lyrics-api* server, and probably wont host one themselves...

**Comment by farahnur42** [comment]
While we're on the subject, how hard would be implementing something like this be? 
![image](https://user-images.githubusercontent.com/37258115/75656633-8e41a680-5c8e-11ea-95d3-2bf21d057065.png)

[Unrelated but not sure if I should create a new issue for this, but a remove duplicates function would be helpful for managing playlists]

**Comment by Taiko2k** [comment]
> While we're on the subject, how hard would be implementing something like this be?

You can always just search on the web for lyrics, then paste them into Tauon. (Right click lyrics panel > `Misc...` > `Paste lyrics`) Its not that often an artist substitution would we needed right?

> remove duplicates function would be helpful for managing playlists

Okay, I've committed a change. There's now a `Remove Duplicates` function under `Misc...` of the playlist tab context menu.

**Comment by farahnur42** [comment]
Unfortunately surprisingly more often than what it should be, especially since scraping is involved. A solid 20-30% of my collection would require this solely coz of database differences between say Genius and MusicBrainz, and I do have everything extensively tagged to begin with.

**Comment by Taiko2k** [comment]
@farahnur42 Would a text file base solution be satisfactory? Perhaps you could list pairs like this in a file:
```
Artist1:Arrt1
Artist1:Arrt2
```

Would title substitution also be necessary?

Can you give me a specific example from that 20-30%? So I have a better idea?

**Comment by farahnur42** [comment]
@Taiko2k Sure, for example songs with multiple artists involved, and with "feat. *" in the title and sometimes just the wrong order in artists for whatever reason. And I do think having title substitution as an option is helpful because of the "feat. *" in the title factor. One example off the top of my head being `Riot; Slander - You Don't Even Know Me` [or any variation thereof like Riot & Slander, "Riot, Slander" and so on], which is listed as [`Slander & Riot - You Don't Even Know Me`](https://genius.com/Slander-and-riot-you-dont-even-know-me-lyrics) in Genius's database and sometimes they **require** a "feat. *" in the title i.e `Au5; Bella Musser - Mesmerize` which is listed as [`Au5 - Mesmerize (feat. Bella Musser)`](https://genius.com/Au5-mesmerize-feat-bella-musser-lyrics). As for the text-based artist pairing solution, well depends on the implementation, if it can be somewhat automated (i.e making pairings based off of , or ; or : or & in the artist field) then it could be satisfactory, but I think the more interactive method is better anyways.

**Comment by Taiko2k** [comment]
@farahnur42 So, perhaps imagine there was an option in that lyrics menu named ***Substitute artist name***, and when you press it, you get a box with text entry that allows you to enter a new name for lyrics searching. Would that be ideal?

**Comment by farahnur42** [comment]
That should suffice, alongside a similar Substitute title option perhaps. [Partially unrelated but saving straight to tags/a .txt file with the same filename would also be a nice bonus]

**Comment by C0rn3j** [comment]
>The Open Lyrics Database does seem very small

Sadly that's a bit of a chicken and egg problem, it's not well known thus not much used.

>But then for the API option... a typical user isn't going to know where to find a lyrics-api server, and probably wont host one themselves

At this point that's true.

There's one reason why I didn't want to have my lyrics server public and that's not wanting to deal with legal letters.

However I guess that is not going to be an issue at the current size and usage of OLD, so I'm up for having my server suggested as the default until the situation changes and there's alternatives.

**Comment by Taiko2k** [comment]
@farahnur42 OK this should be ready for the next release now. It looks like this:

![Screenshot from 2020-03-05 21-19-07](https://user-images.githubusercontent.com/17271572/75961702-5b660f80-5f27-11ea-8000-5316ec951bf7.png)

Hopefully I have interpreted what you want corrently

**Comment by farahnur42** [comment]
@Taiko2k Yes that will suffice very much

**Comment by farahnur42** [comment]
Huh, substitute search doesn't seem to show up at all for songs with no lyrics found, and I don't think that's meant to be intentional. Mind checking it out? @Taiko2k 

Also is the "substitution applicable for all tracks" mentioned in the wiki going to still be a thing in the final release?

**Comment by Taiko2k** [comment]
@farahnur42 Its just the lyrics panel doesn't show if there's no lyrics. The only other way to get to the lyrics menu is by the Showcase/Lyrics view. Hmm... Perhaps this could be improved somehow...

> Also is the "substitution applicable for all tracks" mentioned in the wiki going to still be a thing in the final release?

By that I mean if any other track also has a matching string, the same search replacement will apply. That's more or less desired right?

**Comment by farahnur42** [comment]
Ah, yeah the phrasing is kinda confusing there at first since I assumed it applied globally instead of just for every entry that matches the same initial string which in hindsight is kind of a misread on my end as well, maybe a clarification on that would be helpful or a rephrasing i.e "It will apply every time onwards once corrected on the same entry"

**Comment by farahnur42** [comment]
Huh, "," or ";" doesn't seem to get replaced with "-" when it should be; pretty simple fix by the looks of it tho.

Additionally, interesting behaviour I've noticed is that it just doesn't show lyrics outside of showcase if an .lrc file is available and I believe that is coz of the lyrics panel not showing up for whatever reason.

**Comment by Taiko2k** [comment]
> Additionally, interesting behaviour I've noticed is that it just doesn't show lyrics outside of showcase if an .lrc file is available and I believe that is coz of the lyrics panel not showing up for whatever reason.

Actually it just wasn't implemented there. I've pushed a change to fix this now.

> Huh, "," or ";" doesn't seem to get replaced with "-" when it should be; pretty simple fix by the looks of it tho. [And the & replacement doesn't seem to be working either, but I assume that's why it's not been mentioned here yet]

Ok I think ive fixed the "&" now.

These are a little confusing. Like I assume `artist&artist` should expand to `artist-and-artist`. What should "," and ";" expand to?

**Comment by farahnur42** [comment]
@Taiko2k they would just get replaced with a "-" i.e for [Muzz, Koven & Feint](https://genius.com/Muzz-koven-and-feint-worth-the-lie-lyrics) -> Muzz-koven-and-feint because that is how Genius lists multiple artists for say more than two artists sometimes.

**Comment by farahnur42** [comment]
@Taiko2k Do you have a Discord server or account that I can contact instead with improvements? Got a few thoughts but don't wanna litter the issues any further than I already have (Riot is also fine, hell I'll take Hangouts if necessary).

**Comment by Taiko2k** [comment]
@farahnur42 OK, I made a server https://discord.gg/v4EmhES

**Comment by Taiko2k** [comment]
Ill close this to clean up. Genius has since been added. If there are any further specific source suggestions you can create a new issue.
