### ISSUE TITLE
Playlist list: jump from the last to the first playlist

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#252]
There is a jump from the last to the first playlist when using arrows keys.

**Comment by Taiko2k** [comment]
That's intentional :kissing_smiling_eyes:

What was your expected behavior? Do you propose that is shouldn't cycle?

**Comment by Solarunit** [comment]
Not sure 100% but i think it shouldn't. Well in the playlist you can't do that.

**Comment by Taiko2k** [comment]
I think its good the way it is. Lets you access the first and last playlists easier.

**Comment by awsms** [comment]
> Not sure 100% but i think it shouldn't. Well in the playlist you can't do that.

I had the first feeling the first time I used the left/right arrows, i was expecting a -/+15 sec in the song instead of scrolling playlists.
