### ISSUE TITLE
Dynamic playlist crashes when filtering by year

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#253]
TMB 5.3.0

Create a new playlist with the code `a y>2018` and regenerate it - Tauon will crash. Same with `<`

Using `a y=2018` works just fine.

It looks like `y>` and `y<` are both filters and sorters, so maybe they're clashing?
```
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 36126, in <module>
    instance.render()
  File "/opt/tauon-music-box/tauon.py", line 10633, in render
    self.items[to_call][2](self.reference)
  File "/opt/tauon-music-box/tauon.py", line 13385, in regenerate_playlist
    if int(pctl.master_library[item].date[:4]) > value:
ValueError: invalid literal for int() with base 10: ''
```

---

It'd be great if the playlist regenerated on its own if the playlist code was edited

---

I might be blind but I couldn't find the [Generator Codes](https://github.com/Taiko2k/TauonMusicBox/wiki/Generator-Codes) linked from the table of contents on the right. Maybe merging it(renaming it to just Playlists?) with or mentioning it in the existing `Exporting Playlists` entry would be a good idea?

**Comment by StrangeSeasOfThought** [comment]
> It'd be great if the playlist regenerated on its own if the playlist code was edited

I was about to suggest this.

+1

**Comment by Taiko2k** [comment]
> It looks like y> and y< are both filters and sorters, so maybe they're clashing?

Actually, its because I forgot to handle cases where the year (assumed to be the first 4 digits of the date field) isn't a number. These will be ignored now.

> It'd be great if the playlist regenerated on its own if the playlist code was edited

Okay, I've made this change now.

> I couldn't find the Generator Codes linked from the table of contents on the right. 

Okay, I've added a link as "Smart Playlists" in the side panel

**Comment by StrangeSeasOfThought** [comment]
Something else:

Often, when I can't decide on what to listen to, I enjoy looking up and playing albums with the same release day as the current day.

Right now, I can type e.g. **03-02** via global search and it lists all the years with album releases on the 2nd of March. Then I can click on the year to find the album in the playlist.

I'd love for the smart playlist to be able to do this. Check current date, look for releases on the same month and day, add them to playlist.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought Okay, I've added the code `today`, so you can use it like `a today` for all tracks that have today's day of the year. I think that should work.

**Comment by StrangeSeasOfThought** [comment]
> @StrangeSeasOfThought Okay, I've added the code `today`, so you can use it like `a today` for all tracks that have today's day of the year. I think that should work.

Works perfectly, thanks!

**Comment by C0rn3j** [comment]
@Taiko2k Thanks so much for fixing this feature up, now it's extremely convenient to use with the pop-up documentation!
