### ISSUE TITLE
Top and bottom of the list indication improvements

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#254]
What do you think about this android style indication when you are reaching the end or top of the list?

![indication](https://user-images.githubusercontent.com/20891064/75630803-bb467880-5bfe-11ea-8d74-d6f9373e83f5.gif)

**Comment by Taiko2k** [comment]
OK, here's what I got:

![Peek 2020-03-02 19-43](https://user-images.githubusercontent.com/17271572/75651759-3e7ad380-5cbe-11ea-97ba-8bbec8ce6c8b.gif)

**Comment by StrangeSeasOfThought** [comment]
The original looks better imo. Especially when artist info is being displayed.

Tthere's currently the "End of Playlist" notification at the bottom. I think it'd be better to display this with some tracks still visible instead of on a blank page. Or just use an indicator, too.

**Comment by Solarunit** [comment]
> OK, here's what I got:

I think I like this more. Not as contrast as on my gif.

**Comment by Solarunit** [comment]
>There's currently the "End of Playlist" notification at the bottom. I think it'd be better to display this with some tracks still visible instead of on a blank page. Or just use an indicator, too.

I agree. Maybe add the "End of Playlist" to the "last track" position or just remove it completely. 
+ indicator at the bottom

**Comment by Taiko2k** [comment]
> I think it'd be better to display this with some tracks still visible instead of on a blank page.

What I like about the current behavior, is if you scroll the the bottom, then import stuff to the playlist, that album will be perfectly alligned to the top

**Comment by StrangeSeasOfThought** [comment]
Whenever a new track is selected, the album is being displayed at the top. Can this be prevented for the last track/album on the playlist? Basically, if there's enough room show a few more tracks in front of the last album.

![playlist](https://user-images.githubusercontent.com/43582772/75773697-b42e8000-5d4e-11ea-9c76-eae3dd6fee31.png)

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought 

> the album is being displayed at the top. Can this be prevented for the last album on the playlist? 

I feel like aligning the last album to the top is sometimes desirable. 

> Whenever a new track is selected

It shouldn't do this just when selecting a track right?

**Comment by StrangeSeasOfThought** [comment]
> I feel like aligning the last album to the top is sometimes desirable.

Well, I can live with that. But because the scroll bar fades away, some kind of indicator would be appreciated. Depending on the layout it's not always easy to see whether there are more tracks on the playlist.

> It shouldn't do this just when selecting a track right?

Right. (Selecting an artist in artist list view selects a track from the same artist and jumps to that position,)

**Comment by Solarunit** [comment]
The problem is that scroll bar is only visible when you scroll. Yes its looks very good and minimal but not very practical. You just don't know where in the playlist you are. 
I am thinking about 3 solutions:

1. Scroll bar is always visible
2. Always visible very thin scroll bar which becomes normal size when hovering and dragging it (or when scrolling) 
3. Some indicators on the top and bottom of the playlist. I am not sure where to put them.
