### ISSUE TITLE
"Gapless playback" makes a crossfade when playing the previous track

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#255]
Is it the expected behaviour while using the BASS AudioLibrary & the gapless playback option; that it will make a crossfade when playing the previous song? 

Yet, I disabled every "fade" options in the Bass plugin settings: 
![Screenshot from 2020-03-03 01-43-33](https://user-images.githubusercontent.com/48278661/75731712-a9dd9900-5cf0-11ea-9809-32532d81edb4.png)

**Comment by Taiko2k** [comment]
The behavior should be dependent on the setting `Use fade on track jump` but there's currently a bug causing it to always fade on previous. Ive committed a fix for this now.
