### ISSUE TITLE
Adding several artists/albums with the Global Search

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#258]
I'm not sure how works the Ctrl key in the Global Search. Can I add several artists at once? Or do I have to search for a keyword, add X artist, redo the same search, add X artist etc.
What I'm trying to achieve is to add every "X" artists occurrences, which includes "X feat Y", "X and Y" etc.

(In this example, I would like to add every "USAO & *" in a playlist at once, since "USAO" alone will only add tracks made by "USAO" alone.
![Screenshot from 2020-03-07 04-08-59](https://user-images.githubusercontent.com/48278661/76135674-8769b980-6029-11ea-8e8f-2240de39bc46.png)
![Screenshot from 2020-03-07 04-08-44](https://user-images.githubusercontent.com/48278661/76135675-88025000-6029-11ea-9b2a-7982d2e2a1cf.png))

**Comment by Taiko2k** [comment]
Holding <kbd>Ctrl</kbd> while clicking items in *global search* will add tracks to the currently open playlist. (Only if tracks are not in the playlist already).

That might still be a little cumbersome. Another way you could do this is to use the find box:
 1. Navigate to a playlist that has all your tracks. 
 2. Press <kbd>\\</kbd> to open the *find* box.
 3. Type `USAO`, then press <kbd>Shift</kbd> + <kbd>Enter</kbd>. 

This will create a new playlist of all tracks that include that string. So, in some cases that could include unrelated tracks depending on the artist name.

**Comment by awsms** [comment]
> Holding Ctrl while clicking items in _global search_ will add tracks to the currently open playlist. (Only if tracks are not in the playlist already).

Ok so I just tried it, and it will add the tracks *times I click. So if I hold Ctrl and click 5 times on an artist, everything will be added 5 times. Is it this is a bug?


> * Navigate to a playlist that has all your tracks.
> * Press \ to open the _find_ box.
> * Type `USAO`, then press Shift + Enter.

That did the trick, thanks! I had to press Ctrl+F though, I don't think I've remapped it but \ did absolutely nothing.

**Comment by Taiko2k** [comment]
> Is it a bug or an expected behaviour? (Since you mentioned only if they are not already in the current playlist)

Oh, perhaps it doesn't. Never mind.
