### ISSUE TITLE
[Bug] Tauon crashes with a quick search (NameError: name 'edge_playlist' is not defined)

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#260]
How I can reproduce it:
1) Press quick search (Ctrl+F for me)
2) Search for a song
3) Go to the the first result with Arrow Up, then press Arrow Up again
4) Instead of going back to the last result, or just doing nothing and staying on the first result, the program will crash

Logs (from the CLI, after launching tauon from the terminal - I'm using the snap package):

> Traceback (most recent call last):
  File "/snap/tauon/114/tauon.py", line 36860, in <module>
    edge_playlist.pulse()
NameError: name 'edge_playlist' is not defined

**Comment by Taiko2k** [comment]
I can confirm this. Will fix.

Thanks for the detailed report!

**Comment by awsms** [comment]
You're welcome!
Just by curiosity, what should be the behaviour? Going back to the last result and restart the 'wheel' again?

**Comment by Taiko2k** [comment]
> Just by curiosity, what should be the behaviour?

It should run the *top of scroll area* animation to indicate there's nothing further in that direction. The selected track should remain the same.
