### ISSUE TITLE
[Features requests] Adding an equalizer and a tempo switcher

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#261]
I don't know if this is easily doable, but adding a metronome to change the tempo/speed of a song, and an equalizer would be some great functionalities.

**Comment by Taiko2k** [comment]
The BASS backed mode has an EQ (In the `audio` tab in settings, there's a button). 

Tempo may be possible to implement (Relative adjustment. I imagine absolute setting would be difficult), though I find it hard to imagine what the use case is.

Unfortunately I'm not familiar enough with GStreamer to implement these easily. Its quite a difficult library to understand.

**Comment by LukeZBaker** [comment]
I've only ever found changing the tempo useful for listening to podcasts.

**Comment by Taiko2k** [comment]
Since this request was opened, the direction of Tauon has changed slightly, in that its clearer that these kind of extra audio features are not a focus. Ill close this now.
