### ISSUE TITLE
Saving the databse at constant interval instead once at each closure

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#262]
My computer happens to crash a LOT, and I noticed that the database was only saved at the closing of Tauon; which leaded for me to a lot of data lost (playlists made and songs imported lost, lost the n# count of each track played etc)
Shouldn't the database be constantely saved, let's say every 5 minutes, instead just once when the program closes cleanly?

**Comment by Taiko2k** [comment]
Oh, it *should* save after modifying playlist. But there's a bug that's causing it to fail. I'll fix that.

As for play counts, those are saved every 10 minutes of playtime. (So at worst you lose the last 10 minutes)

**Comment by awsms** [comment]
Thanks, I didn't know for the play counts. Now I see what's the "Auto Save" in the logs every 10 mins.
Is the "Loved" status also auto-saved after "loving" a track?

**Comment by Taiko2k** [comment]
> Does the "Loved" status should also be auto-saved after "loving" a track, and it's also affected by the same bug for the playlist not auto-saved?

No, it will be saved along with the playcounts at the same 10 min mark.
