### ISSUE TITLE
A few suggestions/proposals about the playlists ergonomy

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#263]
A few things I noticed that would be clearly more ergonomical, being able to:
- copy-paste songs from a playlist to another with just using `Ctrl+C` & `Ctrl+V` instead having to `Ctrl+C`, then right-click and click paste
- reverse the sorting order of a list by clicking on it, instead of a right click, then chose Sort Ascending/Descending
- queue directly a song with `Ctrl+Q` while using the Quick Find, instead of having to quit the quick search, queue with `Ctrl+Q`, then redoing another search
- (a feature of Audacious that I love) copy a song/folder on the clipboard in a file explorer, then pasting it in Tauon to import them

What do you think about it?

**Comment by Taiko2k** [comment]
> (a feature of Audacious that I love) copy a song/folder on the clipboard in a file explorer, then pasting it in Tauon to import them

This *should* already be working. (Tested copying from both Nautilus and Dolphin).

> copy-paste songs from a playlist to another with just using Ctrl+C & Ctrl+V instead having to Ctrl+C, then right-click and click paste

This should work, though there's currently a bug where this won't work if there's anything in the system clipboard. I'll fix that.

> reverse the sorting order of a list by clicking on it, instead of a right click, then chose Sort Ascending/Descending

Sounds like a good idea. Though, Tauon doesn't *remember* what the previous sort direction was, but I could make it something like click once for descending, twice for ascending.

> queue directly a song with Ctrl+Q while using the Quick Find, instead of having to quit the quick search, queue with Ctrl+Q, then redoing another search.

Okay that should be an easy fix.

**Comment by awsms** [comment]
Thanks for all the hard work!

> This _should_ already be working. (Tested copying from both Nautilus and Dolphin).

I just tried again with both Nemo & Nautilus, and confirm it doesn't work for me :s

**Comment by Taiko2k** [comment]
> I just tried again with both Nemo & Nautilus, and confirm it doesn't work for me :s

OK looking into it more I've identified two issues. 

 1. Copying from Nemo doesn't work. 
 2. Using Paste from the context menu doesn't work (only ctrl+v shortcut works) 

Is this consistent with what you experience? 

I'll fix these anyway.

**Comment by awsms** [comment]
I just installed Dolphin to test, and it works. Still not working with Nautilus though for some reason.

> 2\. Using Paste from the context menu doesn't work (only ctrl+v shortcut works)

Yep, the "Paste" from the context menu is greyed, only the Ctrl+V shortcut worked.

**Comment by Taiko2k** [comment]
Interesting, the format of your Nautilus is different to mine. Anyway, I've fixed it for the format Nemo uses so that should fix it for your Nautilus too.

> Yep, the "Paste" from the context menu is greyed, only the Ctrl+V shortcut worked.

Yep ill have this activate correctly now. This also means you will now be able to *insert* a folder to the tracklist using the track menu like you can with the existing internal clipboard.

**Comment by Taiko2k** [comment]
This should be working now
