### ISSUE TITLE
Arrow keys navigation doesn't work in the Gallery view

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#264]
Arrow keys navigation doesn't work in the Gallery view. I can use UP down DOWN key but not LEFT and RIGHT. LEFT and RIGHT keys switch playlists instead.

In order to switch to the Gallery view from the Tracks+Art view I am using Tab key.

**Comment by Taiko2k** [comment]
I can confirm this bug. Ill have a fix on the way soon.

**Comment by Taiko2k** [comment]
OK Ive pushed out a new release now.
