### ISSUE TITLE
[bug] Crash for no apparent reason

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#265]
Hi, so the player crashed for absolutely no reason. According to the logs, it would be because it can't read/write the file star.p (while Tauon obviously has read/write access to the wole ~/snap/tauon/ folder):
```
Traceback (most recent call last):
  File "/snap/tauon/136/tauon.py", line 38093, in <module>
    pickle.dump(star_store.db, open(user_directory + "/star.p", "wb"))
PermissionError: [Errno 13] Permission denied: '/home/user/snap/tauon/136/.local/share/TauonMusicBox/star.p'
```

By the way, when I relaunched it, I noticed the current playlist (not the listing of files, I mean the actual songs playlist, with the queue etc) was not saved. Isn't it auto-saved as well?

**Comment by Taiko2k** [comment]
Probably Snap being weird or something, I don't think its a bug in Tauon exactly, cause as you say, it should have write access. I'll add an exception handler for it in case is happens in the future, so at least the app then won't crash.

> Isn't it auto-saved as well?

No, the queue and some changes to playlists such as order changes aren't auto saved. Prefer to avoid writing to disk that frequently really.

**Comment by Taiko2k** [comment]
OK, I've released this change to Snap now. It will show a message instead of crashing now. Let me know if you encounter it again often.
