### ISSUE TITLE
[bug] Small bug related to the queue

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#266]
Since the update that implemented #263 (queue directly a song with `Ctrl+Q` while using the Quick Find), it's not possible anymore to queue a song _without_ having to quick search with `Ctrl+F` first. Can you reproduce it or this is coming from me?

**Comment by Solarunit** [comment]
Ctrl+Q doesn't work for me.

**Comment by awsms** [comment]
> Ctrl+Q doesn't work for me.

What's your keybind for the queuing a song? (check out your input.txt config if you're not sure).
Can you do a quick search, then queue a song?

**Comment by Solarunit** [comment]
the default Ctrl+Q is.

> Can you do a quick search, then queue a song? 
Yes

**Comment by Taiko2k** [comment]
Yep that was silly of me, I forgot to finish implementing this properly.
