### ISSUE TITLE
[Feature Request] Love/Un-love Shortcut

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#267]
Not sure if its needed but why not? 
E.g. CRTL+L

**Comment by Taiko2k** [comment]
There is love-selected and love-playing in the input file, they're just not bound to anything by default

**Comment by Solarunit** [comment]
love-selected i think

**Comment by Taiko2k** [comment]
OK, This ctrl+I to love-selected should now be bound in the release version.
