### ISSUE TITLE
[Feature Request] Being able to resize the left pannel

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#269]
Because it's either too large, either too tight :P
![Screenshot from 2020-03-28 23-31-31](https://user-images.githubusercontent.com/48278661/77835385-5a9e5300-714c-11ea-9cb6-1f4230d35fb7.png)
![Screenshot from 2020-03-28 23-30-50](https://user-images.githubusercontent.com/48278661/77835388-5bcf8000-714c-11ea-9f8c-0b0a92309a93.png)

**Comment by Taiko2k** [comment]
Currently the width is automatically determined based on a number of factors. I feel like this is more convenient than *needing* to manually resize the panel. (And like, I don't think you would adjust this panel for aesthetic reasons like you would the right side panel, so having this auto makes more sense here)

Perhaps the Folder Navigator needs more automatic adjustment. I'm thinking maybe expand based on: a. The number of folder levels that are open, and b. On available space.

**Comment by Taiko2k** [comment]
OK I've released this change. I'm not sure its a great solution, but I feel its more feasible / in the better direction than full drag control like the right side panel.
