### ISSUE TITLE
premium Tauon

### ISSUE THREAD

**Issue by alex-kovac** [Taiko2k/TauonMusicBox#270]
The other day Tauon updated to 5.4.1 via Elementary App center.
But, upon starting Tauon, there was a notice: "Your FREE TRIAL of Tauon Music Box has come to an end! Upgrade to a Tauon PREMIUM subscription to play tracks in any order." See attachment.

Since I could not find any info about Tauon trials or premium Tauon here, on the [website](https://taiko2k.github.io/tauonmb-site/) or elsewhere. And, if I am not mistaken, there was no mention of Tauon trials/premium when installing the first time or in [release notes](https://github.com/Taiko2k/TauonMusicBox/releases), it got me a little surprised. 

Anyone else getting this warning?

![Screenshot from 2020-04-01 16 31 59](https://user-images.githubusercontent.com/174563/78162620-6db06c00-7447-11ea-8581-5a2f11b3a5eb.png)

Thanks!

**Comment by Taiko2k** [comment]
Just an April Fool's joke. You can revert by clicking. MENU > "Upgrade to premium".

It will go away completely once the date changes over.

**Comment by alex-kovac** [comment]
Oh You! 
Genius. You got me absolutely and completely there! +Nearly a heart attack!
Tried to be razor cool and 'rational' about all the jokes in the real world just to get handed one properly from the digital domain. Update 5.4.1!

You made my day! Enjoy and stay safe.

**Comment by Taiko2k** [comment]
I'm glad you liked it! I was worried myself that someone might not see it as amusing.

I'll leave this issue up for a bit in case anyone remains confused by it.

**Comment by Solarunit** [comment]
Also the random song is playing and you need to Upgrade to a Tauon PREMIUM again after restart :smile: 

--
I just wanted to create a new issue: it is impossible Upgrade to a Tauon PREMIUM :smile:

**Comment by Solarunit** [comment]
How about Tauon Android version next year? :+1:
