### ISSUE TITLE
Error installing Tauom from flathub

### ISSUE THREAD

**Issue by haevalencia** [Taiko2k/TauonMusicBox#272]
I try to install using the following command: 
`flatpak install flathub --user com.github.taiko2k.tauonmb -y`

I receive the following output:
```
Error: While charging app/com.github.taiko2k.tauonmb/x86_64/stable from the remote repository flathub: opcode set-read-source: Opening content object 442af3544c4ad7e55b3a05958e9b2f83f42b852d7343457d9a245b5bd91053f7: Couldn't find file object '442af3544c4ad7e55b3a05958e9b2f83f42b852d7343457d9a245b5bd91053f7'
error: Failed to install com.github.taiko2k.tauonmb: While it is charging app/com.github.taiko2k.tauonmb/x86_64/stable from the remote repository flathub: opcode set-read-source: Opening content object 442af3544c4ad7e55b3a05958e9b2f83f42b852d7343457d9a245b5bd91053f7: Couldn't find file object '442af3544c4ad7e55b3a05958e9b2f83f42b852d7343457d9a245b5bd91053f7'
```

flatpak 1.6.3 on fedora 31 XFCE 4.14

**Comment by Taiko2k** [comment]
Seems like a Flatpak issue to me. Can you install other apps from Flathub? Interestingly that version of Flatpak is a very recent release.

Maybe try run the command again. If it's still happening, I'd suggest opening an issue here https://github.com/flatpak/flatpak/issues

**Comment by haevalencia** [comment]
> Seems like a Flatpak issue to me. Can you install other apps from Flathub? Interestingly that version of Flatpak is a very recent release.

I also thought about it, but it only happens to me with this application.

**Comment by Taiko2k** [comment]
Seems to work fine for me (I'm using Flatpak 1.6.2)

You could wait until the next release/build of Tauon on Flathub, maybe the error will go away then. But I doubt its anything I'm doing wrong specifically.

**Comment by TingPing** [comment]
Try running `flatpak repair --user`

It installs fine here.

**Comment by haevalencia** [comment]
> Try running flatpak repair --user

Work for me. I believed that `repair` tool detected when it was used as root or user and not that the `--user` argument had to be added, sorry.
