### ISSUE TITLE
[Arch Linux] Crashes on startup [FIXED]

### ISSUE THREAD

**Issue by officernice** [Taiko2k/TauonMusicBox#273]
Had some problems with the player for some time but I just used another player. Now I got stubborn.

Distro: Arch
DE: Xfce
WM: Xfwm4
Kernel:  5.6-3-arch1-1

> /opt/tauon-music-box/tauonmb.sh %U
> Tauon Music Box v5.4.2
> Copyright 2015-2020 Taiko2k captain.gxj@gmail.com
> 
> Running from installed location
> User files location: /home/user/.local/share/TauonMusicBox
> Found XDG-Downloads: /home/user/Downloads
> Found XDG-Music: /home/user/Music
> Install directory: /opt/tauon-music-box
> Error loading window state file
> Traceback (most recent call last):
>   File "/opt/tauon-music-box/tauon.py", line 603, in <module>
>     from hsaudiotag import auto
> ModuleNotFoundError: No module named 'hsaudiotag'

I do have hsaudiotag installed as well but I end up with the same error.

**Comment by Taiko2k** [comment]
Specifically, you would need to remove hsaudiotag and install hsaudiotag3k.

However, these AUR deps have been a source of issues for a while. Ive gone ahead and bundled them in with the main package now. So, if try install from the AUR again it should work now.

**Comment by officernice** [comment]
You are a champion. Thank you, sir.
