### ISSUE TITLE
Light mode overrides title info color below seek bar

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#274]
Without `light-mode`, the text gets set to the `title info` color:

![image](https://user-images.githubusercontent.com/19501722/79234921-7c8d1a80-7e5a-11ea-8091-a4db0aaf1b29.png)

With `light-mode`, the text gets set to white:

![image](https://user-images.githubusercontent.com/19501722/79234835-5cf5f200-7e5a-11ea-8c1c-1ef98b7c837e.png)

It's not a particular issue for the example above, but it is for actual light themes that change the bottom panel background:

![image](https://user-images.githubusercontent.com/19501722/79235097-b1996d00-7e5a-11ea-91ce-b9b270fe15a1.png)

(By the way, love [the Tauon site](https://taiko2k.github.io/tauonmb-site/), it looks really cool and it's great seeing all the features it has in one place like that! :heart:)

**Comment by Taiko2k** [comment]
Thanks, glad you like the site!

____

As for this issue, to solve it I've gone and added a new colour key to the theme files called `bottom title`, so now you can always specify this colour directly.

You'll need to git pull (or wait for next release). If you have any custom light themes, you'll need to update those with this new key.

**Comment by Bauke** [comment]
That fixed it, looks great now! :tada:
