### ISSUE TITLE
Using cetered style breaks auto lyric downloads

### ISSUE THREAD

**Issue by yuannan** [Taiko2k/TauonMusicBox#276]
I'm not sure if this is certainly the case but seems to be broke for me.
View > Metadata side panel > Use centered style
When this is ticked lyrics will auto download. If I search from them it will still appear and work fine.

On Arch Linux: 5.6.5-zen3-1-zen. Built from the AUR.

**Comment by Taiko2k** [comment]
Indeed I see this is a bug.

Ive pushed a fix now. So will be in the next release.
