### ISSUE TITLE
AUR package won't play audio properly until I install the optional dependencies.

### ISSUE THREAD

**Issue by yuannan** [Taiko2k/TauonMusicBox#277]
I had to install: ffmpeg  noto-fonts-cjk  p7zip  unrar  python-plexapi  picard  gst-plugins-good  gst-plugins-bad  gst-plugins-ugly

I suspect it's probably the gst plugins. Not a big deal and only took me a few minutes but would be nice to have it work out the box.

Arch Linux 5.6.5-zen3-1-zen

**Comment by Taiko2k** [comment]
Okay, I've set gst-plugins-good gst-plugins-bad and gst-plugins-ugly as non-optional now.
