### ISSUE TITLE
Search for tracks

### ISSUE THREAD

**Issue by Mumrik93** [Taiko2k/TauonMusicBox#278]
Not sure if this is the best place to ask, but I really cant find where I'm able to search for a specific track in my music library. My library is pretty big (over a thousand tracks) so i really need to search in case i wish to find a specific track, and i cant seem to find where I can make such a search. Where do I go to make a search for a specific track? 

**In case there are no such feature, would it be possible to add such a feature in a future release?**

**Comment by Taiko2k** [comment]
Either the "Find" (Ctrl+F) or "Global Search" (Type anywhere) should be able to accomplish this. Take a look here https://taiko2k.github.io/tauonmb-site/#search

**Comment by Mumrik93** [comment]
> Either the "Find" (Ctrl+F) or "Global Search" (Type anywhere) should be able to accomplish this. Take a look here https://taiko2k.github.io/tauonmb-site/#search

Worked great! Thank you!
It would still be nice though if there was a GUI option to search, maybe somewhere in the Playlist Navigation bar? As a user I recommend it!

**Comment by Taiko2k** [comment]
There is the global search entry in the bottom panel menu. As for having a dedicated field in the top panel, I don't think the space cost it worth it, even if the learning curve is increased a bit.
