### ISSUE TITLE
"theme from album art" doesn't work sometimes

### ISSUE THREAD

**Issue by jsomedon** [Taiko2k/TauonMusicBox#279]
To reproduce:
1. set "generate theme from album art"
2. try to switch between several songs with different album arts
3. after several switchs, some theme colors don't get updated, for example, song A's album cover is about red yellow green and song B's album cover is about black grey blue, when I switch from A to B, I expect my theme to be about black grey blue but it's red yellow grey or red green grey -- so I expect colors in A but not in B shouldn't be there when I switch to B. Interesting thing is, if I restart the program and play B, then theme color matches up correctly.

Terrific project btw. :-D

**Comment by Taiko2k** [comment]
Okay I believe I know what you're talking about. I've now committed a fix for this, so will be fixed in the next release.
