### ISSUE TITLE
Sunken theme: scroll-bar color

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#280]
Hi! 
Playlist scroll-bar color is white in the playlist. 
I think it should be the same as scroll-bar in the Playlists list:

![alt text](https://i.imgur.com/gAL43EY.png)

---
BTW awesome new release! 

I think Sunken is my new favorite theme (not sure about the green progress bar, I think its too contrast).
Cucumber Splash is also great. 

Pattern overlay for the background art - love this! :+1: 
Is it possible to make it a little bit more brighter?

I don't use tabs but great improvements here too.

**Comment by Taiko2k** [comment]
> I think it should be the same as scroll-bar in the Playlists list

I see what you mean. I suppose though, since these are always shown, I didn't want them to be distracting.

> Is it possible to make it a little bit more brighter?

Yes, I could add more steps here... Though allowing it too bright reduces contrast with the text.

![Screenshot from 2020-05-04 14-45-58](https://user-images.githubusercontent.com/17271572/80933383-9b5a4d80-8e17-11ea-9500-f0980fc0902f.png)

**Comment by Solarunit** [comment]
> I see what you mean. I suppose though, since these are always shown, I didn't want them to be distracting.

I was talking about scroll-bar in the Playlist, maybe its a little bit distracting right now. Also it doesn't look as polished as scroll-bar in the left panel I think. 

>Though allowing it too bright reduces contrast with the text.

I agree, probably my monitor brightness is too low.

**Comment by Solarunit** [comment]
I am curious is it possible to create a theme with glass effect?

**Comment by Taiko2k** [comment]
> I am curious is it possible to create a theme with glass effect?

Through to the desktop? Its something ive thought about, but basically the answer is no. To even begin one would have to hack support for this into SDL2, which is above my skill level / expertise.

**Comment by Solarunit** [comment]
Something like this:

![alt text](https://i.imgur.com/PbVFQTv.png)

**Comment by Taiko2k** [comment]
@Solarunit That's an interesting idea, but I don't think it quite fits with the existing style of the app. 

It could be used maybe in an alt-skin or new mini-mode of some sort. Though I don't plan on working on any new major UI features for a while.

**Comment by Solarunit** [comment]
Ok, I see.

**Comment by Solarunit** [comment]
I am using Sunken theme as my main theme. I like it a lot, thanks =)
