### ISSUE TITLE
snap does not have permission to read music/files

### ISSUE THREAD

**Issue by chrisdlangton** [Taiko2k/TauonMusicBox#283]
Using the snap, the only version of this app shown to Ubuntu 20.04 users, makes this app borked for all purposes when not connecting to a remote sources.

So for any basic use of your own content on your own computer, this app is completely borked

Basically snap will not allow access to filesystem, so all audio is inaccessible.

You could solve the issue by trying to run as a snap with unconfined mode from what i can tell (not a secure choice, but is usable at least)

**Comment by Taiko2k** [comment]
It should be able to access files in your home directory by default. You can extend permissions to removable media from the software store app under *Permissions*:

![Screenshot from 2020-05-05 15-47-20-cropped](https://user-images.githubusercontent.com/17271572/81033457-dc219780-8ee7-11ea-9571-ce1a76987f8e.jpg)

**Comment by chrisdlangton** [comment]
@Taiko2k i toggled all perms before posting, also tried loading various files from various locations including $HOME/Music and from other disks and mounts (`/mnt` and `/media`).

I've switch to flatpak and it is working flawlessly with picard and discord.

If you can't replicate, you might not have the same Ubuntu 20.04 setup (i chose zfs on root and had a large enough nvme to access the advanced partition manager for zfs on root and moved my `/home` outside so it is it's own zpool and not in rpool).

**Comment by Taiko2k** [comment]
That's just snap I suppose. Can't simply disable confinement cause it requires going though an approval process.

I was gonna suggest trying Flatpak. Good to hear that's working.
