### ISSUE TITLE
Permission error accessing one or more files

### ISSUE THREAD

**Issue by tglhteam** [Taiko2k/TauonMusicBox#286]
Hello! I installed Tauon Music Box from the Ububntu application center. When I try to drag the folder with the music into the program window, it displays the following message - "Permission error access one or more files". Music folders are located on different hard drives. I understand that there is something with access rights, but I don’t know how to fix it. Please help me.
Ubuntu 20.04 Lts x64
Tauon Music Box 5.5.2

**Comment by Taiko2k** [comment]
Is your HDD mounted under `/media`? If so, you can click the **permissions** button here in the app centre:

![Screenshot from 2020-05-05 15-47-20-cropped](https://user-images.githubusercontent.com/17271572/81033457-dc219780-8ee7-11ea-9571-ce1a76987f8e.jpg)

And enable: 

![Screenshot from 2020-05-11 22-09-50-cropped](https://user-images.githubusercontent.com/17271572/81550397-3f259980-93d4-11ea-9479-30b2c70a98c9.jpg)

**Comment by tglhteam** [comment]
Many thanks! It works! Sorry, I forgot that there are settings. Your program is super! I liked your joke on April 1!))))

**Comment by Taiko2k** [comment]
Thanks! And glad to hear its working now. I might actually change that error message to give more detailed instructions.
