### ISSUE TITLE
Notification appears twice when a playlist repeats

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#287]
Say I have a playlist with just one track:

![image](https://user-images.githubusercontent.com/19501722/81856162-ee3ab000-954f-11ea-969e-4b0f942ad873.png)

When it goes to repeat, the notification for track change appears twice:

![image](https://user-images.githubusercontent.com/19501722/81856141-e24eee00-954f-11ea-9fcb-8c94b5f4773c.png)

**Comment by Taiko2k** [comment]
I can't seem to replicate this.

Does it always do it? Under that condition only? (I assume the condition making it repeat is the *end of playlist* setting being set to "Repeat playlist")

**Comment by Bauke** [comment]
Yeah, it always happens when any playlist ends and goes back to the first song. The "end of playlist action" is indeed set to "Repeat playlist".

**Comment by Taiko2k** [comment]
Oh yes, I'm getting it.

Okay, I've committed a fix for this now.
