### ISSUE TITLE
Metadata tag read error

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#288]
Encountered this today and not particularly sure what's wrong with it, Picard is able to read and edit everything just fine. Playback also works, noticed this when they appeared weird in the playlist:

![image](https://user-images.githubusercontent.com/19501722/82122480-76ed6200-9783-11ea-9008-5419233561a1.png)

Tauon output:

```
Reloading Metadata for Yorushika - ただ君に晴れ.flac
Warning: Tag read error
     On file: Music/Yorushika/負け犬にアンコールはいらない/Yorushika - ただ君に晴れ.flac
```

This happens with all the files from the album, so I'm not sure if it's the files in particular or something else. I can send you them if necessary, @Taiko2k.

**Comment by Taiko2k** [comment]
Okay, send one of them and I'll try see what's going on.

**Comment by Taiko2k** [comment]
Okay so the issue related to the fact there's an ID3 tag appended to the start of the FLAC file which Tauon didn't expect. Exact Audio Copy adds this by default apparently, though I don't think that's something that *should* be done.

Regardless, I've now changed Tauon's behavior so that it'll search further into the file for the start of the FLAC stream, so this should solve the issue. If you could, can you do a git pull and test this on the rest of your files? Doing "Reload Metadata" on the album should be sufficient to see if its working.

**Comment by Bauke** [comment]
It worked, but only for a few of the songs. I'll send you one of these next, I guess. xD

![image](https://user-images.githubusercontent.com/19501722/82142624-406c2180-982d-11ea-90ef-97015e888214.png)

**Comment by Taiko2k** [comment]
Okay, just had to make a small tweak. Try it now.

**Comment by Bauke** [comment]
That did it, it's all good now! Thanks so much! :tada:

**Comment by DesertStars** [comment]
> Okay so the issue related to the fact there's an ID3 tag appended to the start of the FLAC file which Tauon didn't expect. Exact Audio Copy adds this by default apparently, though I don't think that's something that _should_ be done.

That'd be correct, FLAC files should use Vorbis comments ideally, unfortunately a lot of software still write ID3 tags to FLAC files incorrectly which are generally used for MP3 files.

**Comment by Taiko2k** [comment]
@DesertStars Indeed, interestingly as the FLAC site says:
> FLAC has it's own native tagging system which is identical to that of Vorbis. They are called alternately "FLAC tags" and "Vorbis comments". It is the only tagging system required and guaranteed to be supported by FLAC implementations.
>
> Out of convenience, the reference decoder knows how to skip ID3 tags so that they don't interfere with decoding. But you should not expect any tags beside FLAC tags to be supported in applications; some implementations may not even be able to decode a FLAC file with ID3 tags.
