### ISSUE TITLE
Use Album Artist in Artist List

### ISSUE THREAD

**Issue by PietroPate** [Taiko2k/TauonMusicBox#292]
Would it be possible to add the option to use Album Artist in the left pane Artist List? 

Behavior should be exactly the same as the current Artist List but using the Album Artist tag if it exists and the Artist tag otherwise.

In any case, thanks for the awesome app, had been looking for a MusicBee replacement for a while!

**Comment by Taiko2k** [comment]
There is actually a config setting named `artist-list-prefers-album-artist` that will enable the behaviour you describe. 

It currently defaults to off. I wonder perhaps this should default to on...

**Comment by PietroPate** [comment]
Awesome, thanks! 

Which behavior should be default I don't know, it is definitely a personal thing but for example I use Album Artist instead of Composer for classical music and sorting by that helps a lot

**Comment by Taiko2k** [comment]
Does indeed seem to be a personal thing. Ill leave it as is then.
