### ISSUE TITLE
No controls via Gnome or via playerctl, mpris-ctl nor dbus metada

### ISSUE THREAD

**Issue by msmafra** [Taiko2k/TauonMusicBox#301]
Hello.
Running version 6.0.0 on Dev mode,  python3 tauon.py, works perfectly, but the autoupdated Flatpak to 6.0.0 is not showing its controls on Gnome (Fedora 32) at least, I can't control or get information via playerctl or mpris-ctl nor the metada is appearing on dbus-monitor.
I gave some more permissions to it via Flatseal, but no change.

While running the Flatpak version:

❯  doas -- journalctl -f 
```
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Exception in thread Thread-2:
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Traceback (most recent call last):
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]:   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]:     self.run()
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]:   File "/usr/lib/python3.7/threading.py", line 870, in run
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]:     self._target(*self._args, **self._kwargs)
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]:   File "/app/bin/t_modules/t_dbus.py", line 45, in main
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]:     import dbus
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: ModuleNotFoundError: No module named 'dbus'
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Tauon Music Box v6.0.0
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Copyright 2015-2020 Taiko2k captain.gxj@gmail.com
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Detected running as Flatpak
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Running from installed location
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: User files location: /home/marcelo/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Found XDG-Downloads: /home/marcelo/Downloads
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Found XDG-Music: /home/marcelo/Música
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Install directory: /app/bin
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Database loaded in 0.017 seconds.
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Translation file loaded
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Using SDL version: 2.0.12
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Using GStreamer as fallback. Some functions disabled
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Config reload theme...
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Load Bio Data
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Applying external theme: Carbon
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Theme number: 2
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Load Bio Data
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Load cached bio and image
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Auto Save
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Enabling garbage collecting
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Writing database to disk.
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: Unloading SDL...
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: SDL unloaded
Jul 05 17:11:21 tars com.github.taiko2k.tauonmb.desktop[157638]: bye
Jul 05 17:11:21 tars systemd[2927]: flatpak-com.github.taiko2k.tauonmb-157616.scope: Succeeded.
Jul 05 17:11:21 tars systemd[2927]: flatpak-com.github.taiko2k.tauonmb-157616.scope: Consumed 9.558s CPU time.

```
Only after closing the above is shown.

❯ playerctl metadata
No players found

❯ playerctl --player=tauon metadata
No players found

Now running it via python tauon.py

❯ playerctl --player=tauon metadata
tauon mpris:trackid             /com/tauon/127/-1
tauon mpris:length              0
tauon xesam:album               Augmented Reality
tauon xesam:albumArtist         Holon
tauon xesam:artist              Holon
tauon xesam:title               A Most Fragile Existence
tauon xesam:url                 file:///home/marcelo/M%C3%BAsica/Holon/Holon%20-%20Augmented%20Reality/Holon%20-%20Augmented%20Reality%20-%2009%20A%20Most%20Fragile%20Existence.mp3
tauon xesam:asText              
tauon xesam:autoRating          0.29999999999999999
tauon xesam:composer            
tauon tauon:loved               false
tauon xesam:comment             Visit http://holon-subatomic-audio.bandcamp.com
tauon xesam:genre               
tauon mpris:artUrl              file:///home/marcelo/Projects/TauonMusicBox/cache/export/Augmented%20Reality0.jpg

Everything else, like controls, dbus seems to work either:
❯ dbus-monitor | grep -E "genre|comment" -B 0 -A 3

                  string "xesam:comment"
                  variant                      array [
                        string "Visit http://holon-subatomic-audio.bandcamp.com"
                     ]
--
                  string "xesam:genre"
                  variant                      array [
                        string ""
                     ]

**Comment by Taiko2k** [comment]
Looks like I missed out a module when rebuilding the manifest. Should be fixed with an update now.

**Comment by msmafra** [comment]
Working again. Awesome. Thx!
