### ISSUE TITLE
Rescan - Removes other folders

### ISSUE THREAD

**Issue by RickAndTired** [Taiko2k/TauonMusicBox#302]
Rescan doesn't work with multiple folders - it removes other folders

**Steps**
- Create `playlist`
- Add `folder 1` to `playlist`
- Add `folder 2` to `playlist`
- Rescan `playlist`

**Result**
`folder 1` is rescanned
`folder 2` is removed

**Comment by Taiko2k** [comment]
There's a known issue in that it will only rescan `folder 1` and not `folder 2`, I should fix that. But I can't seem to replicate a situation where it removes `folder 2`. For me it remains in the playlist.

**Comment by RickAndTired** [comment]
I'm using the Snap if that makes a difference

**Comment by Taiko2k** [comment]
> I'm using the Snap if that makes a difference

That shouldn't make a difference.

Are you performing the same procedure as I am here?

![Peek 2020-07-06 12-34](https://user-images.githubusercontent.com/17271572/86545813-58d2ff80-bf85-11ea-9964-5eff7b45b22c.gif)

**Comment by RickAndTired** [comment]
I am performing the same procedure.

After some more testing I found it's an issue if the second folder has the same name as the first with additional characters.
My problem was I was using `test` and `test 2` in my initial test of the rescan feature.
The same issue happens if you have `music` and `musical`

**Comment by Taiko2k** [comment]
Okay I see, that makes sense.

**Comment by Taiko2k** [comment]
I've committed a fix for both these issues now (which hopefully works as expected).

Though, there remains an issue where if you manually remove a folder or tracks from the playlist (e.g. by selecting tracks and pressing <kbd>del</kbd>), it will come back on folder rescan. I think that might be tolerable? You'll still be able to reset a playlist by pressing `Clear`.

**Comment by RickAndTired** [comment]
Seems intended and even beneficial (in cases of accidental deletion) to bring back tracks on a rescan.

**Comment by Taiko2k** [comment]
This should be live now in the new release. Let me know if its working as expected for you.

**Comment by RickAndTired** [comment]
It's working well, thank you!
