### ISSUE TITLE
Lyrics jump around after being successfully searched

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#307]
The GIF is a bit glitchy but it should show what I mean, the lyrics seem to jump around and change even though they're already found. My naive guess is that Tauon is going through all the lyrics sources and saving each one over one another, instead of saving just the first one it successfully finds.

![Peek 2020-07-11 14-08](https://user-images.githubusercontent.com/19501722/87223790-155f0380-c380-11ea-893b-f4896af9aa4a.gif)

**Comment by Taiko2k** [comment]
Odd I never noticed that before. Ive released an update with a fix. Let me know if its working properly now.

**Comment by Bauke** [comment]
Seems to be good now, thanks! :sparkling_heart:
