### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by congard** [Taiko2k/TauonMusicBox#308]
Hi, I have issues with UI scaling: DPI settings doesn't apply from `.Xresources` (how I set it). It would be nice if the player could change the scale of the interface.
I'm using ArchLinux, KDE, Tauon v6.0.2 from AUR.
- - -
![Screenshot_20200711_232312](https://user-images.githubusercontent.com/35779485/87233254-77465a00-c3ce-11ea-9436-37850f8cbb39.png)
![Screenshot_20200711_232331](https://user-images.githubusercontent.com/35779485/87233257-7b727780-c3ce-11ea-9bce-5624fd06182b.png)

**Comment by Taiko2k** [comment]
Okay I've committed some changes for this. I think this should be working now but I don't have any HiDPI configuration to fully test this myself.

BTW it should be currently safe to do a partial upgrade of your AUR install to try it out:

`git clone https://github.com/Taiko2k/TauonMusicBox.git`
`sudo cp TauonMusicBox/tauon.py /opt/tauon-music-box/`
 `rm -rf TauonMusicBox/` (cleanup)

So, when you then restart the app, it *should* have the scale correctly applied. Let me know how that goes.

**Comment by congard** [comment]
It seems to be ok:

![Screenshot_20200712_110155](https://user-images.githubusercontent.com/35779485/87241985-4a775e80-c431-11ea-97e1-80c280a07fe2.png)

![Screenshot_20200712_110944](https://user-images.githubusercontent.com/35779485/87241988-519e6c80-c431-11ea-8196-31c30294a569.png)

Good job, thank you! Also, it would be very cool if you add the ability to change UI scaling... I.e auto-detect DPI + add scale slider to the settings will be a very nice option

**Comment by Taiko2k** [comment]
Okay, I've now added a slider to `Settings` under the `Window` tab that lets you set the scale factor directly.

Due to a bug in the last commit, you'll need to set these settings once you upgrade for scaling to work again.

**Comment by congard** [comment]
@Taiko2k it working nice, thanks!
