### ISSUE TITLE
Cover quality over MPRIS is very low

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#31]
I am using kdeconnect which puts the album cover from MPRIS over the lockscreen, it seems Tauon is sending that in a very low quality.

Tauon: 
![image](https://user-images.githubusercontent.com/1641362/52331505-a5b15000-29f8-11e9-8880-ad42cb29bbc8.png)

DeaDBeeF:
![image](https://user-images.githubusercontent.com/1641362/52331516-ae098b00-29f8-11e9-9688-5fe809ab3036.png)

**Comment by Taiko2k** [comment]
I didn't imagine it would be used for anything large, so I set the maximum to a small 250x250, but I can increase that, I wonder what that value should be... 500.. 750.. 1000?

**Comment by C0rn3j** [comment]
The cover in example is 1000x1000.

Going through my few albums, I can see some covers in 1500x1500.

One of the covers is even a 6400x6400 3MB PNG file.

What would be the downsides of blasting a full 3MB cover over MPRIS2?
Worst case with 'low end' wireless 802.11n - being capable of some 6~MB/s with good signal on a decent device - is there any reason not to set max to 1500x1500/2000x2000?

The example is on an 'older' phone with a Full HD resolution, and some high end phones nowadays have a higher res screen than my 27" 1440p monitor, so sending really high res covers over MPRIS2 might have a point?

**Comment by Taiko2k** [comment]
Ill try setting this to 1000x1000, I think higher wouldn't be necessary for anything that uses MPRIS2. Small up-scaling if necessary probably wouldn't be noticeable anyway.

These are cached to disk, so would want to avoid unnecessary disk IO.

**Comment by C0rn3j** [comment]
This does not seem to be fixed in 3.7.0.

Also switching between the embedded cover and file cover for a song does not immediately sync on the music player, I have to switch to another song to refresh the cover.
Not 100% sure if this is on Tauon's side or Kdeconnect's.

**Comment by Taiko2k** [comment]
Try click `MENU` > `Database` > `Reset Image Cache` I think that should fix it. 

As for it not immediately switching, indeed there was no mechanism for switching this midway through a song, but it seems like I've got this functionality fixed/working now (Though may be a while before I do another release)

**Comment by C0rn3j** [comment]
Am fairly certain the image cache was reset on upgrade.

Anyway I did a manual reset, switched a song and the covers are still blurry.

**Comment by Taiko2k** [comment]
Yes I believe these are being cached by KDEConnect. I have no idea how to flush that though.

**Comment by C0rn3j** [comment]
Yup, it was kdeconnect's cache, thanks a lot for fixing it!

*  adb shell 
*  `su` (with root access allowed in devel settings)
 *  `rm /data/data/org.kde.kdeconnect_tp/cache/album_art/*`
 * Reboot the phone (to restart kdeconnect)
 * Restart the music player
