### ISSUE TITLE
Nexcloud Access

### ISSUE THREAD

**Issue by bepolymathe** [Taiko2k/TauonMusicBox#311]
Is it possible to access a remote folder containing music on a remote Nextcloud server?

**Comment by Taiko2k** [comment]
You might be able to mount the folder to a location then import that. I see reference on how to do that here https://wiki.archlinux.org/index.php/Nextcloud#Synchronization under "Mounting files with davfs2".

I have no idea what the performance would be like though. You could try it and tell me.

**Comment by bepolymathe** [comment]
I think i need flatpak permissions ? Something like that ?

`sudo flatpak override com.github.taiko2k.tauonmb --filesystem=davs://my.account@cloud.test.net/remote.php/webdav/Music`

**Comment by Taiko2k** [comment]
I'm saying you can't use a URL directly, Tauon doesn't know how to open that. But you maybe could use another program to mount it as an ordinary folder, thus any app could then open the files.

You would need flatpak access to that mounted location. You could just use `sudo flatpak override com.github.taiko2k.tauonmb --filesystem=host`
