### ISSUE TITLE
ctrl + q shortcut to queue a track can be confusing

### ISSUE THREAD

**Issue by Porkepix** [Taiko2k/TauonMusicBox#316]
It's pretty common to have `ctrl + q ` quitting the currently focused software. Due to that, having it to queue tracks can be a little bit confusing. I have a guess with this issue and the other one I opened that this project might be used by people where DM/WM offer such shortcuts natively, and therefore doesn't have such issue.

So, I don't wanna sound too presumptuous as I think shortcuts were well-thoughts when they were picked, but I think it was still worth opening this issue just in case to let you know.

**Comment by Taiko2k** [comment]
Interesting.

I could rebind ctrl+q to quit and bind *queue track* to something else maybe. I'm not sure what that should be though. I'm open to suggestions.

**Comment by Solarunit** [comment]
shift+q maybe?

**Comment by Taiko2k** [comment]
> shift+q maybe?

Interesting idea, actually I think I'll go with alt+q

**Comment by Solarunit** [comment]
>actually I think I'll go with alt+q

BTW there are several shortcuts with shift and none with alt
https://github.com/Taiko2k/TauonMusicBox/wiki/Keyboard-Shortcuts

**Comment by Taiko2k** [comment]
> BTW there are several shortcuts with shift and none with alt

I kind of choose them based on what's comfortable, shift+q seems kind of awkward to me, and a bit risky since if you miss-press and hit ctrl now it will close the app.
