### ISSUE TITLE
Top-left button (playlists) is clickable, but does nothing when on the "showcase + lyrics view"

### ISSUE THREAD

**Issue by Porkepix** [Taiko2k/TauonMusicBox#317]
This is probably because "showcase + lyrics" view comes on top of other views, and so what's might seems to be a glitch is actually not that annoying, and cause hassle to fix while being not that important. (Although, that view comes with a "Return" button on the bottom left, maybe this could be turned into a return one?)

**Comment by Taiko2k** [comment]
Okay I've changed it to exit showcase view when clicking the top-left button. When doing so it will open the left panel if it wasn't already. This should avoid it seeming like anything is a glitch hopefully.
