### ISSUE TITLE
Some lyrics won't load from LyricWiki

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#32]
For example What For from Dead Astronaut's album Constellations.

![image](https://user-images.githubusercontent.com/1641362/52332396-c7abd200-29fa-11e9-9f91-4613ec115890.png)

A [DeaDBeeF plugin I use](https://github.com/C0rn3j/deadbeef-lyricbar/blob/master/src/utils.cpp#L172) can load them fine -
![image](https://user-images.githubusercontent.com/1641362/52332412-d4302a80-29fa-11e9-8b36-d790bac7df8d.png)

**Comment by Taiko2k** [comment]
Currently as it works its not automatic, need to right click the area in the side bar and click `Search Lyricwiki` manually. Hmm perhaps this is not intuitive...

**Comment by C0rn3j** [comment]
Oh, I saw it working for other songs in my collection, they apparently seem to have `unsyncedlyrics` tag in them with the lyrics, so I got confused as to why one song would work and other wouldn't.

I'd suggest doing what the DB plugin does - autodownload them upon playing the song.

**Comment by Taiko2k** [comment]
Just to clarify, the file you gave me doesn't appear to have a lyrics tag. And the manual lyric wiki search here works independently of whatever is detected in the tag.

As for doing this automatically... I kinda feel like this might be unfair load on LyricWiki, especially since this *is* scraping and not via an API.

**Comment by C0rn3j** [comment]
>Just to clarify, the file you gave me doesn't appear to have a lyrics tag.
Yeah I was talking about a DIFFERENT file loading lyrics just fine because it has lyrics, but this one didnt, hence the initial report.

>As for doing this automatically... I kinda feel like this might be unfair load on LyricWiki, especially since this _is_ scraping and not via an API.

Maybe manual by default and checkbox by settings then?

Or better, automatic by default but lyrics are saved to the file if they aren't there already(would have to somehow inform the user before doing so), so there's no needless repeated requests across different devices/players.

**Comment by Taiko2k** [comment]
Just a progress update.

I added a simple setting to automatically get lyrics. After trying it out, I think it actually works quite well.
![screenshot from 2019-02-07 16-49-22](https://user-images.githubusercontent.com/17271572/52389534-c4970b80-2af8-11e9-8fe6-ba80faeb3a7f.png)


I also added a setting to hide the album art box so the lyrics in the side panel can take up the full height akin to what it looks like in your screenshot.

![screenshot from 2019-02-07 16-45-23](https://user-images.githubusercontent.com/17271572/52389465-83066080-2af8-11e9-8da7-2c8627e370f0.png)

**Comment by Solarunit** [comment]
Lyrics from LyricWiki only stored in the player database? Is it possible to save it to the tracks metadata?
If the track already has lyric in the metadata, how to see it?

**Comment by Taiko2k** [comment]
@Solarunit If lyrics are found in tags, it will be shown by default. (In the *right side panel*, and in the "Lyrics view" layout mode.)

As for saving these back to the tags, no, there's no current way to do this. I think that could be a good feature, but that would be dependent on it being programatically available. Unfortunately most advanced tagging libraries on Python are under incompatible licenses. With what I have available, it would only work with MP3 and possibly FLAC (if the user has the flac package installed).

**Comment by Solarunit** [comment]
> If lyrics are found in tags, it will be shown by default. (In the _right side panel_, and in the "Lyrics view" layout mode.)

I guess I need to find some file with lyrics to test it =)
