### ISSUE TITLE
[Snap] Tauon crashes on launch

### ISSUE THREAD

**Issue by SodaFormulas** [Taiko2k/TauonMusicBox#320]
Hi,

I haven't used Tauon for a few weeks but when launching it now, the window appears (all black) for a second then disappears.

Here is the trace from the Terminal:

```
~$ tauon
/snap/tauon/321/snap/command-chain/alsa-launch: line 7: export $var="\$dir${$var:+:\$$var}": bad substitution
/snap/tauon/321/snap/command-chain/alsa-launch: line 7: export $var="\$dir${$var:+:\$$var}": bad substitution
Tauon Music Box v6.0.3
Copyright 2015-2020 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/soda/snap/tauon/321/.local/share/TauonMusicBox
Found XDG-Downloads: /home/soda/Téléchargements
Found XDG-Music: /home/soda/Musique
Install directory: /snap/tauon/321
Error loading window state file
Input config file is missing... copying template from program files
No existing star.p file
No existing album-star.p file
Database loaded in 0.0 seconds.
Translation file loaded
Applying scale based on xft setting
1.05
Force rerender icons
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 888, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/tauon/321/tauon.py", line 3663, in <module>
    from t_modules.t_svgout import render_icons
  File "/snap/tauon/321/t_modules/t_svgout.py", line 3, in <module>
    from gi.repository import Rsvg
  File "/snap/tauon/321/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Rsvg, introspection typelib not found
```

I've tried deleting the Tauon config folder in Snap. I've uninstalled Tauon and reinstalled it. It's the same.

System : Ubuntu 20.04 64b / GNOME 3.36.3 / X11

I love this music player, thanks for developing it.

soda.

**Comment by Taiko2k** [comment]
Okay I've found the issue and fixed it. It was a Snap packaging issue that was triggered when using a non-standard DPI / HiDPI. Interestingly yours seems to be just slightly above standard DPI.

Ill try get the next stable version of Tauon out within the next day or so. In the mean time you can switch to the Tauon Snap edge channel by doing:
`snap switch --channel=edge tauon`
`snap refresh`
But I highly recommend not staying on that channel longer than necessary. You can switch back using:
`snap switch --channel=stable tauon`
`snap refresh`

**Comment by SodaFormulas** [comment]
Wow, you rock !

Works perfectly now. Thanks for the faster than light fix :D 

My laptop is an old Thinkpad T430s from 2012, with a 1600x900 (16:9) resolution. Great screen at the time (HiDPI wasn't a thing yet).
