### ISSUE TITLE
[feature request] It would be nice to be able to see the contents of a album without making it play

### ISSUE THREAD

**Issue by zSucrilhos** [Taiko2k/TauonMusicBox#324]
It would be cooler to be able to see the contents of the album X by clicking on it and then choosing some track to put on my queue.
This way makes playlists' creation easier and i can queue tracks directly.

**Comment by Taiko2k** [comment]
You mean in the gallery? Did you know you can right click an album and select `Show in Playlist`?

**Comment by Taiko2k** [comment]
You could also turn off `Single click to play` under `View` in `Settings` which will show the album in the tracklist on click without playing.

**Comment by zSucrilhos** [comment]
Amazing! I did not know of the single click to play option. Thanks and sorry for bothering heh :(

**Comment by Taiko2k** [comment]
No problem! This project isn't at the popularity where such questions are a bother. It also gives me a hint of where users might be getting stuck.
