### ISSUE TITLE
Unable to select audio output from list

### ISSUE THREAD

**Issue by Bl4cKn1gh7** [Taiko2k/TauonMusicBox#33]
My system has two video cards that show their HDMI/DisplayPort outputs as audio devices along with my normal sound cards, the problem is that this prevents me from using PulseAudio as its pushed past the region that is selectable.
![image](https://user-images.githubusercontent.com/34180098/52432090-92c17d00-2ad7-11e9-8390-f2118db34950.png)

**Comment by Taiko2k** [comment]
Yes that needed fixing, I was being lazy and putting it off thinking, no way someone would have that many sound cards lol.

Anyway, i've made that properly contained and scroll-able now

![screenshot from 2019-02-08 13-44-20](https://user-images.githubusercontent.com/17271572/52452534-367a5e00-2ba8-11e9-994d-ab99fa38a1a3.png)

(don't mind the names, I was just populating the list for testing)

**Comment by Bl4cKn1gh7** [comment]
lol cool, thanks!
