### ISSUE TITLE
HiDPI slider doesn't scale some elements

### ISSUE THREAD

**Issue by sk22** [Taiko2k/TauonMusicBox#332]
So, I set the UI scale slider to 2x

For example, the artist should be further away from the song title.

![image](https://user-images.githubusercontent.com/6217438/90156356-a0bb2280-dd8c-11ea-9081-071116cdbd89.png)

Similarly, the date metadata isn't as far away from the album name as it should be.

![image](https://user-images.githubusercontent.com/6217438/90156530-d9f39280-dd8c-11ea-8ed3-ca8f2ff390fe.png)

I don't know if this issue exists elsewhere, but this might be the case.

**Comment by Taiko2k** [comment]
Okay, this should be fixed now.
