### ISSUE TITLE
Support pasting multiple Spotify links

### ISSUE THREAD

**Issue by sk22** [Taiko2k/TauonMusicBox#333]
In Spotify Desktop, you can select multiple (or all, using CTRL+A) songs in a playlist/album. The clipboard then contains a list of links, separated by new lines. 
When pasting such a list into a new playlist, only one song will be added. Please support adding multiple songs at once. (Say, as an alternative to automatically importing Spotify playlists - as they appear to not be contain all songs, but only a few?) Thanks!

**Comment by sk22** [comment]
> (Say, as an alternative to automatically importing Spotify playlists - as they appear to not be contain all songs, but only a few?)

I created a separate issue for this: https://github.com/Taiko2k/TauonMusicBox/issues/334

**Comment by Taiko2k** [comment]
Okay I've committed this now. As a bonus the URI type links can now be pasted as well.

**Comment by sk22** [comment]
thanks!
