### ISSUE TITLE
Restarting pulseaudio service kills playback

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#337]
```
tauon-music-box 6.1.3-1
```

I've the Default audio output selected.
I play some music, then if I do `systemctl restart --user pulseaudio`, Tauon stops playing music, with nothing in the logs.

Selecting another song spams this in the logs('trying' is typoed here by the way):
```
Channel not playing when should be, tring to restart
```

Going to settings and doubleclicking Default again makes music play again.

Ideally, Tauon should pick up that Pulse died and play again.
For example, Chromium handles this case alright.

I do realize this is a bit of an edge case since not everyone breaks pulse on the regular like me, but it'd still be nice if this was handled.

**Comment by Taiko2k** [comment]
Okay, I've committed a change for this.

While this fix should work when playing back local files, playback of inbound radio streams will still break. Is this satisfactory?

Note that this will only apply to the GStreamer backend. Applying to the BASS backend is no longer applicable as its now been removed.

**Comment by C0rn3j** [comment]
>While this fix should work when playing back local files, playback of inbound radio streams will still break. Is this satisfactory?

For my use case, definitely!

>Note that this will only apply to the GStreamer backend. Applying to the BASS backend is no longer applicable as its now been removed.

I was about to be sad as I've been using BASS still but it turns out you already implemented all the main features in GStreamer, so awesome, thanks!

**Comment by Taiko2k** [comment]
> BASS still but it turns out you already implemented all the main features in GStreamer.

Yep. I remember you use the broadcast feature. Just letting you know this should work mostly the same as it did before, but now the plan is to have the stream at `/stream.ogg` on the same port as the metadata page, rather than the stream being on a separate port. (So you'll need to reconfigure your proxy thing if you update and still use that feature).
