### ISSUE TITLE
playlists are changing when switching desktops

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#34]
When switching desktops using CTRL+ALT+ LEFT (Right) - playlists are also switching.
Tauon (Flatpak) v3.6.0.

**Comment by Taiko2k** [comment]
This is because the left and right keys are intended to change the playlist. I could fix this by not registering if either of those modifier key are pressed.

**Comment by Solarunit** [comment]
tauon3.6.X2.flatpak
Still happening when using ALT+ LEFT/RIGHT
