### ISSUE TITLE
Can't play the song

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#346]
I have noticed today that the player does nothing when I start to play any song. Restart of the player helps but then it happens again. I can reproduce it by switching to another playlists and starting the song by double click. The timer stays at 00:00.

Tauon 6.2.5
Solus Budgie

**Comment by Taiko2k** [comment]
Does this happen specifically and only when switching to another playlist?

How did you install Tauon, Flatpak? Also sanity check, do those files you want to play exist?

**Comment by Solarunit** [comment]
>Does this happen specifically and only when switching to another playlist?

this happens on the first launch and sometimes when switching to another playlist


>How did you install Tauon, Flatpak? 

yes

>Also sanity check, do those files you want to play exist?

yes

>Does running form terminal produce any interesting output?

Detected running as Flatpak
Installed as Snap
User files location: .../.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: .../Downloads
Found XDG-Music: .../Music
Install directory: /app/bin
Database loaded in 0.161 seconds.
Using UI scale: 1.0
Could not connect to gnome media keys
Init GStreamer...
Using SDL version: 2.0.12
Applying theme: Sunken
Auto save playtime
Traceback (most recent call last):
  File "/app/bin/t_modules/t_gstreamer.py", line 549, in main_callback
    self.id = track.url_key
**AttributeError: 'TrackClass' object has no attribute 'url_key'**

**Comment by Taiko2k** [comment]
Hmm. I assume you must have been using that same installation of Tauon for a long time? I must have forgotten to provide upgrade code at some point. Ill try push an update to fix this soon (next day or so)

**Comment by Taiko2k** [comment]
Okay you should be able to update now, let me know if the issue is fixed.
