### ISSUE TITLE
Internet radio record issue on Ubuntu

### ISSUE THREAD

**Issue by Tauonese** [Taiko2k/TauonMusicBox#347]
I'm using Ubuntu 20.04. Tauon creates the encoding folder (encode-output) in the default directory but no files are created with the record stream/auto split option selected. I'm using the pulse audio engine trying to capture mp3 streams but nothing gets recorded.  I'm guessing it's a LAME or gStreamer config issue but I have ubuntu-restricted-extras installed and updated to the current versions. Recording of audio streams works fine with Sayonara. Any ideas?

**Comment by Taiko2k** [comment]
I did a quick test and I *can* replicate this issue. Seems to be related to running on Ubuntu / Snap. I'll look to investigate further when I have the time.

**Comment by Taiko2k** [comment]
Could you try update and see if its working now?

**Comment by Tauonese** [comment]
Pleased to report that it looks like it is now working. I tested with mp3 and aac streams and it recorded, split and named them correctly.

**Comment by Tauonese** [comment]
Kudos for producing a really cool piece of software and for your support. I love the modern interface, speed and lack of bloat/unnecessary functions. Most of all it appears to be solid. Nice work. Thanks for giving us the benefit of Tauon.

**Comment by Taiko2k** [comment]
Yeah I'm not actually sure what the issue was exactly, but building a new snap seems to have fixed it.
