### ISSUE TITLE
Tauon does not fully respect remembering window size/placement in KDE Plasma

### ISSUE THREAD

**Issue by Scotty-Trees** [Taiko2k/TauonMusicBox#348]
Greetings Dev(s),

I just wanted to say amazing music player, been using it a lot this year and love it, please keep up the great work!

So, the issue I have is maybe a simple one to fix (I hope anyways!), but my issue is every time I open/restart the music player, it doesn't seem to stay in the last window position that it was in before. What I mean by that is, in KDE Plasma, I have a system setting set to center all windows on the desktop, so applications that I don't have fully maximized will spawn right in the center. But for whatever reason Tauon loves to spawn in the center, but at a lowered down center than all the other windows that I use which are not maximized. Like if I have a window say Dolphin file manager, non-maximized and I drag Tauon to be resized to be exactly like Dolphin, when I close and reopen Tauon, it'll spawn a bit lower than Dolphin, so it's like centered vertically, but it's not centered horizontally, if that makes any sense I hope it does. I am hopeful there is a way (I'm using the flatpak version btw on Solus) to make Tauon respect system settings and centered the window in the desktop every time it is opened or restarted or what have you. If this can't be done for whatever reason I will understand as well so no worries, just hoping to try to help make this player just a little bit better in my own way. Good luck dev(s) and keep up the great work, it's my daily player!

**Comment by Scotty-Trees** [comment]
Just a quick follow up! This is how it looks when  I normally use Tauon, in a windowed mode, centered and sized like this.
![Screenshot_20200913_114248](https://user-images.githubusercontent.com/45135187/93026888-d8f19300-f5ce-11ea-866d-bde179008a2c.png)

However, whenever I close and reopen Tauon (or restart my laptop for example) in KDE Plasma (5.19.4 as of writing this), Tauon doesn't remember the exact window size and location placement that it last hand. I don't know if this is related to python, or KDE, or flatpak, but when a reopen Tauon, it'll be placed lower down than it was before and in the screenshot below you can now see how I have a Konversation window behind it now peeking out. If there's anyway to keep the same window size and placement respected in KDE Plasma I would appreciate it. If not for whatever reason, that's okay too, just please feel free to let me know and thanks again for an amazing music player in linux! 

![Screenshot_20200913_114320](https://user-images.githubusercontent.com/45135187/93026892-df800a80-f5ce-11ea-8db0-7f1b570eb4eb.png)

**Comment by Taiko2k** [comment]
Currently I don't define where the window should be when opening. So I assume the window manager should be placing it where it wants. Its odd that its not working as you expect like other windows. 

I don't think I have any further control over that behavior. But what I can do is define exactly where the window will be when opened. I could set the window to the exact location it was when it was last closed, adding this option in the form of a setting. Would that be satisfactory?

Just to clarify, its not the ***size*** that's changing at all, just the position of the window?

**Comment by Scotty-Trees** [comment]
Thank you very much for the quick reply. I think adding an option to set the window to the exact location it was when it was last closed would be a perfect solution. And yes, to clarify, the size remained the same for the window, it was just always the position that was always changing downwards from it's last use. 

Hope that helps clear up anything, and I appreciate the work you're doing for this music player in Linux. Side note, having the colors in the soundbar change based on the current album art is probably one of my favorite features. Keep up the great work!

**Comment by Taiko2k** [comment]
> I think adding an option to set the window to the exact location it was when it was last closed would be a perfect solution.

Okay, I've committed this change now. You will be able to find this option under the "Window" tab of settings in Tauon. I expect I'll push a new version release with this within the next few days.

By the way, thanks for the positive feedback, it means a lot!

**Comment by Scotty-Trees** [comment]
You're very welcome and no worries, if I have any other issues/bugs or maybe even a feature request or two, I'll be sure to let you know. Thanks again for making using Linux even better with applications like this, that means a lot to me as well. Cheers!

**Comment by Taiko2k** [comment]
Okay release is out. Let me know if its working properly for you.

**Comment by Scotty-Trees** [comment]
Just updated and tested, works as intended. This issue is fixed! Thank you very much for helping me with this so quickly, appreciate your work! I'll definitely have a few more features/ideas to suggest!
