### ISSUE TITLE
Quick fetch cover art for Showcase + Lyrics view

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#351]
Basically, have this context menu from the regular view:

![image](https://user-images.githubusercontent.com/19501722/93603527-69134c00-f9c4-11ea-8c98-e193a736f133.png)

Also available in the Showcase + Lyrics view, at the moment it's just the lyrics context menu from the sidebar:

![image](https://user-images.githubusercontent.com/19501722/93603614-88aa7480-f9c4-11ea-8d06-e55fe1803d56.png)

**Comment by Taiko2k** [comment]
Okay, new release has this change.
