### ISSUE TITLE
window interface glitch

### ISSUE THREAD

**Issue by Kansasmanjaro** [Taiko2k/TauonMusicBox#353]
When I move other windows above tauon. The footprint of other windows will be left on Tauon's window for a couple of seconds.
My os is Manjaro KDE 20.1.
What's is the cause of this problem? Non of other app have this problem.

![Screenshot_20200920_123334](https://user-images.githubusercontent.com/71604917/93717969-a6034e00-fb3e-11ea-801e-a797926f7525.png)

**Comment by Kansasmanjaro** [comment]
It's KDE Compositor problem, after restart compositor. The problem is gone.

**Comment by Taiko2k** [comment]
Since Tauon uses gpu acceleration these issues are more common. Seems to be a common issue with KDE in particular. I don't know of any permanent solution unfortunately.

**Comment by Taiko2k** [comment]
Ill close this since I don't think there's anything I can do. Its a KDE issue really.
