### ISSUE TITLE
Synchronized lyrics from tags?

### ISSUE THREAD

**Issue by tralph3** [Taiko2k/TauonMusicBox#354]
I would like to have the program read the synchronized lyrics from my tags. I prefer to store them there rather than on a separate file, I've had other players mix lrc files before, embedding lyrics on the tags was the solution. This player can read them, but they display as plain text.

**Comment by Taiko2k** [comment]
I've taken a quick look into this. Unfortunately it seems not as simple as sourcing the `.lrc` from tags since embedded synced lyrics uses a different format. Its probably more work right now than I'm keen on doing for such a uncommonly used feature.

Out of curiosity while file/tag type are you using? MP3 with the SYLT tag?

**Comment by tralph3** [comment]
I use ID3 tags I guess, but my embedded lyrics have the same format as they did in the lrc files. Lines with two digits for hours, two digits for minutes and two digits for seconds (some have three digits but shouldn't give issues)

**Comment by Taiko2k** [comment]
> I use ID3 tags I guess, but my embedded lyrics have the same format as they did in the lrc files. 

But I'm assuming this may be different once saved into the MP3. What tool do you use to embed them? Or could you give me an MP3 with embedded lyrics to inspect?

**Comment by tralph3** [comment]
I use Mp3tag, always used the same method. Here's one as an example: 
[song.zip](https://github.com/Taiko2k/TauonMusicBox/files/5273524/song.zip)

**Comment by Taiko2k** [comment]
Oh okay I see. The content of `.lrc` file is just stored as standard lyrics. That field (USLT) is intended for unsyned lyrics (Hense the 'U'). So its kind of hack to put them there. Do you use other apps that interpret those as synced?

Anyway, fortunately its pretty trivial to implement detecting and accepting this in Tauon, so I've done that. The time format being different was an issue, but I've made allowances for that. So, I've committed this change now so going forward these synced lyrics should show.

**Comment by tralph3** [comment]
Yay thanks a lot. They are in unsynched because most players that support synchronized lyrics still detect the unsynched field as synchronized if they have the tags, and they don't detect the synched tag at all, so for broader compatibility I put them there and hope the player recognizes them, which in most cases works. I use Phonograph on my phone and it works, and I was using Music Bee before switching to Linux and it worked there too. Btw the change hasn't been compiled right? So I'll have to do that myself, no worries.

**Comment by tralph3** [comment]
Nvm, I'll just replace my tauon.py on /opt with the new one. I actually wanted to make this change myself but couldn't find it in the "lyrics related" file, didn't know it was there :P

**Comment by Taiko2k** [comment]
> I use Phonograph on my phone and it works, and I was using Music Bee before switching to Linux 

So its not too uncommon, that's good to hear.

>  Btw the change hasn't been compiled right? So I'll have to do that myself, no worries.

I actually pushed a release only 10 minutes before you created the issue haha. I'll probably do another new release in a few days. But yeah manually replacing just the `tauon.py` will work in the mean time.

**Comment by tralph3** [comment]
Btw the it's working, but the timing seem a bit... off. Sometimes it's perfect, sometimes it's too soon, sometimes it lags behind, and I know the timings are correct. I made them with MusicBee, and they were working to the milisecond there. Don't worry tho, this is something *all* players get wrong, only MusicBee had perfect synched lyrics. Timers are hard for computers...

**Comment by Taiko2k** [comment]
> Btw the it's working, but the timing seem a bit... off. Sometimes it's perfect, sometimes it's too soon, sometimes it lags behind, and I know the timings are correct. I made them with MusicBee, and they were working to the milisecond there. Don't worry tho, this is something all players get wrong, only MusicBee had perfect synched lyrics. Timers are hard for computers...

Interesting, it does seem off. The issue is likely more to do with the audio pipeline than timers. As en experiment, try switch to the experimental Phazor backend (Leave the rest of its sub-settings as default). Let me know how you perceive the lyric timings with that. I anticipate it will be far more accurate.

![Screenshot from 2020-09-25 00-44-44](https://user-images.githubusercontent.com/17271572/94147137-0391f480-fec9-11ea-934f-369565b0462d.png)

**Comment by tralph3** [comment]
Still off, maybe a bit better but certainly not perfect. I noticed it tends to go faster than the lyrics, and sometimes a bit slower. It's more consistent with the timings unlike GStreamer, which was all over the place, but this is barely an improvement. Still, I don't want to tell you what to do or diminishing your work, this is the best player I've seen apart from MusicBee, honeslty, people don't seem to understand that looks are really important. Anyway, if you want to continue testing, I can give you a specific song I use which has a lot of quick lyrics, it's perfect to see if the timing is correct or not (and yes, I did a good job of synching them): 
[Todd - Lord Chancellor's Nightmare Song.mp3.zip](https://github.com/Taiko2k/TauonMusicBox/files/5278411/Todd.-.Lord.Chancellor.s.Nightmare.Song.mp3.zip)

**Comment by Taiko2k** [comment]
Haha that's a fast paced song. Good for testing.

Upon more inspecting Ive found some pretty bad mistakes in the code (the ms part wasn't being applied for example). Still some weirdness going on though. I made my own file for testing, which it seems pretty accurate with. 
[Lrc Sync Test.zip](https://github.com/Taiko2k/TauonMusicBox/files/5279902/Lrc.Sync.Test.zip)

But then with your file the timing seems off by about a word. Is it bad timing on my lrc file? Or is there some variance in accuracy of playback between the two files by Tauon? 

Ive pushed some changes, you might wanna do a git pull. Let me know your impression. (Also when testing, take note if you're on GStreamer or Phazor, could be helpful if you test both.)

**Comment by tralph3** [comment]
We probably should open a new issue... I'll test and let you know.
