### ISSUE TITLE
[Feature Request] Allow selfsigned SSL certificates

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#355]
Hi, I recently changed my airsonic server and i'm using a selfsigned certificate. When I try to scan it, I see this error in my terminal:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /airsonic/rest/getIndexes?u=admin&t=xxxx&s=xxx&v=1.13.0&c=Tauon+Music+Box&f=json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))
```
Could it be possible to add a tickable option to allow selfsigned certificates?

**Comment by Taiko2k** [comment]
There are two paths we could take. Could either try disable SSL verification, or provide the nessasary certs. Do you have a preference for either? The former is probably easier.

Actually, I don't know if this is supposed to just work automatically if you have the certificates installed on your machine. Do you know if you do?

**Comment by awsms** [comment]
I actually ended up buying a domain name, just to have an actual certificate and using airsonic in tauon. Closing the issue :)

> Actually, I don't know if this is supposed to just work automatically if you have the certificates installed on your machine. Do you know if you do?

I have absolutely no idea how SSL is implemented in python. I'll probably dig it later
