### ISSUE TITLE
stuck at scanning tags

### ISSUE THREAD

**Issue by Kansasmanjaro** [Taiko2k/TauonMusicBox#356]
When the music library is large and complicated(say 3T, 5000 albums), Tauon will stuck at the scanning tags stage. The number of remaining tags stop decreasing for hours and CPU usage is high. I restart tauon it stays the same, rescan the library, still stay the same.
After reboot several times, the scanning tags process continues and finishes. 

- What's the possible reason for this?
- Is there a "number of album" limit for one Tauon library tag?
- Is there a limit for the size of the Tauon cache file?
- is it because of a strange character in the tags?
- or corrupted cue files?

![Screenshot_20200923_221422](https://user-images.githubusercontent.com/71604917/94102161-19cf8000-fdf7-11ea-941d-eb6c4cdfe644.png)

**Comment by Taiko2k** [comment]
Its likely getting stuck at some specific file/s. Could be any number possible causes. Can you tell which file it got stuck on? (It usually scans them linearly from top to bottom, so, if you can see which one it was supposed to scan next but didn't, that's likely the file) Then try import just that file and see if it still gets stuck. If so, send me the file and ill try figure it out.

If you can't identify the file that way, I can try enable some additional logging then get you to run from git.

**Comment by Kansasmanjaro** [comment]
Thanks. I tried to find the problematic cue or music file, couldn't find it. The library is too huge to find it.
I will run the logging tool you suggested. Please let me know how to proceed.
Another issue: Some of the files exist in the library but I can't play them, it jumps to the next one after it plays for 0.2 seconds. I guess that's because the tags for these files were not read by Tauon.

**Comment by Taiko2k** [comment]
> Some of the files exist in the library but I can't play them, it jumps to the next one after it plays for 0.2 seconds. I guess that's because the tags for these files were not read by Tauon.

If they weren't scanned yet then that was likely the issue. I recently disabled double checking length at playtime, so its likely assuming its the default length of 0 and triggering an advance immediately.

> Please let me know how to proceed.

Okay, you'll need to setup from git master and run from terminal. Tell me if you need more help with that.  ***or:***

 - If you installed using AUR, you can just copy `tauon.py` from this git to `/opt/tauon-music-box/`, then open terminal and run `tauon`

 - If you installed using Flatpak, you can copy `tauon.py` to `/var/lib/flatpak/app/com.github.taiko2k.tauonmb/current/active/files/bin` and run from terminal using `flatpak run com.github.taiko2k.tauonmb`

It should now list every file it attempts to scan, try see which one it gets stuck on and if you can replicate it reliably.

**Comment by Kansasmanjaro** [comment]
My Tauon was installed in /opt/tauon-music-box/, I've run tauon in the terminal.  The following is all the output in the terminal. Looks like the character in Japanese or European in my files are not supported. But there are files with tag info in Japanese and Chinese displays well in the library and plays well.

> (tauon.py:42397): Gtk-WARNING **: 01:30:35.248: Locale not supported by C library.
>         Using the fallback 'C' locale.
> 
> (tauon.py:42397): Gtk-WARNING **: 01:30:35.261: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (tauon.py:42397): Gtk-WARNING **: 01:30:35.261: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (tauon.py:42397): Gtk-WARNING **: 01:30:35.261: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
> Gtk-Message: 01:30:35.275: Failed to load module "appmenu-gtk-module"
> Running from installed location
> User files location: /home/ma/.local/share/TauonMusicBox
> Found XDG-Downloads: /home/ma/Downloads
> Found XDG-Music: /home/ma/Music
> Install directory: /opt/tauon-music-box
> SET LOCALE ERROR
> Database loaded in 0.937 seconds.
> Applying scale based on xft setting
> Using UI scale: 2.0
> Could not connect to gnome media keys
> Init GStreamer...
> Using SDL version: 2.0.12
> Applying theme: Turbo
> Auto save playtime
>

**Comment by Taiko2k** [comment]
If you copy `tauon.py` from git master to `/opt/tauon-music-box/`, then run and try import your library again, you should see each file in the terminal as its scanned. We really wanna find a specific file that its not working with.

**Comment by Kansasmanjaro** [comment]
Thanks! 
I found the problematic file. The music file is corrupted flac. In the attchment is it.

[24. Johann Sebastian Bach – Der Landpfleger sagte.zip](https://github.com/Taiko2k/TauonMusicBox/files/5277538/24.Johann.Sebastian.Bach.Der.Landpfleger.sagte.zip)

**Comment by Taiko2k** [comment]
Ah good. Yes that FLAC is very corrupted. I've made a fix now so it shouldn't stall in this situation.
