### ISSUE TITLE
[Feature Request] Sort album by the time they were added into the library

### ISSUE THREAD

**Issue by Kansasmanjaro** [Taiko2k/TauonMusicBox#357]
I currently simply use a "newly added" playlist to get focus on my CDs, but if this function is added I can scroll down to find the CDs I added one day ago, one month ago, etc,

Thanks for your terrific work! This is the BEST  music player.

**Comment by Taiko2k** [comment]
This could be added. 

Though there is currently the "Date Modified" sorted playlist (Under playlist tab > Generate) which was kind of intended for this purpose. Maybe try that, see if it works well for you.

**Comment by Taiko2k** [comment]
In the latest release I've added a new sorting option under `Sort...` named `Sort by Imported`. Perhaps this will achieve what you're looking for?

**Comment by Kansasmanjaro** [comment]
> In the latest release I've added a new sorting option under `Sort...` named `Sort by Imported`. Perhaps this will achieve what you're looking for?

Thank you! That's perfect.
This player is the best music player on all platform I used. I have tried so many different players on Win10, Macos and Linux.
On win10, you have musicbee. On macos, Swinsian.
Tauon is smoother, minimalistically beautiful, and faster. With Picard it achieve all the functions I used in Musicbee.

**Comment by Taiko2k** [comment]
> Thank you! That's perfect.
This player is the best music player on all platform I used. I have tried so many different players on Win10, Macos and Linux.
On win10, you have musicbee. On macos, Swinsian.
Tauon is smoother, minimalistically beautiful, and faster. With Picard it achieve all the functions I used in Musicbee.

Glad to hear you're having a good experience!
