### ISSUE TITLE
Synchronized lyrics' timings are off

### ISSUE THREAD

**Issue by tralph3** [Taiko2k/TauonMusicBox#358]
We'll continue the "investigation" if you will here, from #354

So, I tested again with the newest commits and I can say that with the song I gave you earlier, it's still off, but at least it's consistent. By that I mean, there's a delay, the lyrics get highlighted after they started to be sang, but it appears to be the same delay consistently, wich is a good thing. Maybe this is caused because there's three digits in the miliseconds section? The only reason I have them like that is because MusicBee generated them like that. With your test "song", the timings were perfect, no issues at all. All of this was with GStreamer, I don't have the other option for some reason when I downloaded the program from git, I was using the aur version previously.

**Comment by tralph3** [comment]
Never mind, I just realized your test song had 3 digits for miliseconds too...

**Comment by Taiko2k** [comment]
I'm thinking it might actually be your lyrics that have some timing bias. 

Here I've inspected in Audacity. As as example I've highlighted the part of the audio that is the word "love". Your timing actually starts part way through the word, a drift of about 500ms from where I might put it.

![test2](https://user-images.githubusercontent.com/17271572/94231344-ea845480-ff57-11ea-8e37-6d893c2cd8c4.jpg)

I'm not sure the reason. MusicBee might have some kind of bias, or there might be different ways of measuring MP3 position between different applications.

**Comment by tralph3** [comment]
Well... apparently I did the synching wrong? Like, not wrong, they are a bit after the line starts because I usually like to synch them to a beat or something, and that's what it's doing. So your app is fine actually, I just forgot I did it that way. I managed to make MusicBee run after all, and I can use it to compare with yours now and I see that it's actually the same, so good job! Your app is working as intended and I should up my lyric synching game (I have so many albums synched that I forget which ones are good and which ones are a bit wonky).

**Comment by tralph3** [comment]
Well now I'm unsure... I never was *that* off with my timings, this feels odd, even on MusicBee, I don't remember to have it feel like this. Maybe wine is introducing lag? Idk. Look at this, sorry for having it hear double, I tried to sync them as good as I could: https://streamable.com/4ffeod
