### ISSUE TITLE
[Feature Request] Scrobble count from last.fm

### ISSUE THREAD

**Issue by lux5512** [Taiko2k/TauonMusicBox#359]
I think last.fm scrobble count would be a nice addition. 

Clementine has it, so it might be possible to add there as well.

Thank you for your work, found this player recently and have been enjoying it quite a lot!

**Comment by awsms** [comment]
I also would love to see this feature implemented in Tauon. I think the overall number of scrobbles on a song is more relevant than the number of playing on Tauon itself.

**Comment by Taiko2k** [comment]
I assume the idea would be that there's a way to one-off sync all tracks with the server side scrobble count? Hmm that may be difficult without hammering the API. Would just syncing the value of a single track on scrobble be an acceptable compromise?

**Comment by lux5512** [comment]
> I assume the idea would be that there's a way to one-off sync all tracks with the server side scrobble count? Hmm that may be difficult without hammering the API. Would just syncing the value of a single track on scrobble be an acceptable compromise?

Absolutely. Thank you for you hard work.

**Comment by Taiko2k** [comment]
Is syncing the value even needed? Or is just a count of how many times the track has been scrobbled from Tauon preferred?

**Comment by awsms** [comment]
@Taiko2k I pretty much believe a sync is need.

**Comment by Taiko2k** [comment]
Update: Okay, Ive pushed this feature. Here's how it works:

 - Whenever a track is scrobbled, it increments a counter.
 - You can view the scrobble counts as a column in the columns view.
 - You can one off fetch counts for **all** tracks using a function in settings (This process is ***very*** slow, so you'll probably only want to do it once.)

**Comment by awsms** [comment]
> * You can one off fetch counts for **all** tracks using a function in settings (This process is _**very**_ slow, so you'll probably only want to do it once.)

Any chance this could be possible on an album/track basis too in a future update?

**Comment by Taiko2k** [comment]
Okay this should be live now in the latest release.

> Any chance this could be possible on a playlist/album/track basis too in a future update?

I'm not super keen on investing too much into this feature. See how it goes.
