### ISSUE TITLE
[Feature Request] Improve playback icons

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#361]
There should only be a single play/pause icon, which changes to the play/pause icon based on whether the current track is playing or not:

![Pause/play controls](https://user-images.githubusercontent.com/9282837/94352191-2ecf3c00-00a1-11eb-850a-d4d9b6dcb337.png)

Having multiple is confusing and redundant, I'd never use the first icon there. If you want to view the current playing track, you can just click the song's title.

The icons should also be positioned like any standard music player (previous track/pause-play/next track).

The stop icon is also redundant. I'd never use this.

![Play/repeat icons](https://user-images.githubusercontent.com/9282837/94352193-3098ff80-00a1-11eb-8586-608954d96864.png)

The play/repeat icons should be standard icons. I had no clue at first glance what these icons do without first hovering over them and seeing the tool tip.

**Comment by Taiko2k** [comment]
> There should only be a single play/pause icon

Indeed the play button is a little redundant, in fact it is combined with the pause button if one resizes the window narrow. But I think it provides better visual balancing having play its own button. So its intentional.

> The icons should also be positioned like any standard music player

Again, intentional. The reasoning is the when one is using *next* or *back*, they are likely to want to use the other, so those should be adjacent.

> The stop icon is also redundant. I'd never use this.

It does do something though, it unloads the track from the interface, and causes the track to play from beginning if played again. (Also some behind the scenes techinal stuff, but I suppose that's not important.)

> The play/repeat icons should be standard icons.

The shape of standard icons don't fulfil my spacial requirement for this.

To be frank, my intention with Tauon isn't to "be like every other player", if it were then it would just be like every other player. A lot of the interface and behavior in Tauon is somewhat experimental, even if things don't work out for the better, I think its fine to have tried being different. I also don't care to sacrifice freedom of experimentation in favour of new user experience, its not really the goal.

**Comment by dspacejs** [comment]
@Taiko2k sure. I like how it's different. But at least change this:

> Indeed the play button is a little redundant, in fact it is combined with the pause button if one resizes the window narrow. But I think it provides better visual balancing having play its own button. So its intentional.

Given the fact you can just click on the song title, I don't really see the point of having the play icon for the same purpose (especially when it can easily be confused with the pause icon, which is what's used to toggle between play/pause).

> The shape of standard icons don't fulfil my spacial requirement for this.

They're even smaller than what is currently used. The icons for repeat/shuffle are rectangular, standard icons have a square dimension. 

> To be frank, my intention with Tauon isn't to "be like every other player", if it were then it would just be like every other player. A lot of the interface and behavior in Tauon is somewhat experimental, even if things don't work out for the better, I think its fine to have tried being different. I also don't care to sacrifice freedom of experimentation in favour of new user experience, its not really the goal.

I think that's cool and I really like the design. But I do think these tweaks should still be made, having a clear UI/UX is important too

**Comment by Taiko2k** [comment]
> Given the fact you can just click on the song title, I don't really see the point of having the play icon for the same purpose (especially when it can easily be confused with the pause icon, which is what's used to toggle between play/pause).

The go to playing function of the play button is only secondary really. I think the play button should still exist regardless of if it does that or not.

> They're even smaller than what is currently used. The icons for repeat/shuffle are rectangular, standard icons have a square dimension.

That's the thing, I think the standard ones are too square, thin and small, where I would prefer something more rectangular and defined. Being identifiable would be a bonus, but I want it to look good, and I think the current ones do, they have nice visual spacing and large hit boxes. 

Yeah its debatable, but its also kind of an established design feature I don't wanna be quick to change.

**Comment by dspacejs** [comment]
@Taiko2k 

> The go to playing function of the play button is only secondary really. I think the play button should still exist regardless of if it does that or not.

I disagree here. Think in terms of design principles—if the user sees both a play and pause button, but they both do totally different things and are separated from each other, isn't this confusing? I had to click around with the media controls until I figured out how they worked. The purpose of a button should be obvious by default without the user having to play around with it.

> That's the thing, I think the standard ones are too square, thin and small, where I would prefer something more rectangular and defined. Being identifiable would be a bonus, but I want it to look good, and I think the current ones do, they have nice visual spacing and large hit boxes.

I like the idea of using something custom that keeps the player unique. Perhaps you could make your own custom icons for shuffle/repeat? I'm not exactly sure what it'd look like, but you could do something fancy that still makes the function obvious, but gives it its own style.

**Comment by Taiko2k** [comment]
> if the user sees both a play and pause button, but they both do totally different things and are separated from each other, isn't this confusing?

Its how tape decks work, so I don't think the idea is too unfamiliar.

> Perhaps you could make your own custom icons for shuffle/repeat? I'm not exactly sure what it'd look like, but you could do something fancy that still makes the function obvious, but gives it its own style.

Possibly. I'm not sure how it would look either though, but if I figure something out then it might eventually be changed.
