### ISSUE TITLE
[Bug] Search glitch

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#364]
If you search for something, scroll to the bottom until nothing is selected, then hit Enter, this happens:

![Peek 2020-09-27 13-48](https://user-images.githubusercontent.com/9282837/94355974-3fdf7380-00c8-11eb-89d2-6b1728c4d97f.gif)

**Comment by Taiko2k** [comment]
Okay, Ive committed a fix for this.
