### ISSUE TITLE
[Bug] Show in gallery not working

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#365]
If I right click a song (such as the one highlighted in this screenshot), and select "Show in Gallery", it selects the wrong album in the right-hand view:

![Screenshot from 2020-09-27 14-44-58](https://user-images.githubusercontent.com/9282837/94356692-4eca2400-00d0-11eb-9c20-e64d53274d22.png)

Other times I've tried this it seemed to work, so I'm not sure what's wrong.

**Comment by Taiko2k** [comment]
It groups based on folder, not album. So not a bug exactly. 

Perhaps there could be better visual feedback in the gallery for tiles that cover many single tracks from different albums, rather than presenting it as if it were a single album.

**Comment by dspacejs** [comment]
@Taiko2k hmm, not sure how I turned on this view. I'm a bit confused how it got here. I thought it was from one of the items under "MENU" in the top, but it doesn't seem like it.

**Comment by Taiko2k** [comment]
![Screenshot from 2020-09-27 20-11-09-cropped](https://user-images.githubusercontent.com/17271572/94358472-b5b20200-00fd-11eb-8f69-73415018dcea.jpg)

The main layouts are here under MENU. The top one is the default. 2nd from the top is the gallery, which is the one in your screenshot.

**Comment by dspacejs** [comment]
@Taiko2k doesn't show for me for some reason, only the full gallery view does (not where it's on the right sidebar):

![Screenshot from 2020-09-27 16-36-01](https://user-images.githubusercontent.com/9282837/94358539-f94a4300-00e0-11eb-8603-f52c5252202e.png)

**Comment by Taiko2k** [comment]
Oh, you have to click the gallery button again once selected to toggle that sub setting.

**Comment by dspacejs** [comment]
@Taiko2k oh ok. That's pretty confusing, I didn't know you could do that. Perhaps add it as another option so it's explicit?
