### ISSUE TITLE
[Feature Request] Add ability to move song to trash from the app

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#366]
I have some duplicates in my library. It'd be nice to be able to delete from within the app, instead of having to open my music folder in a file browser and delete it there.

**Comment by Taiko2k** [comment]
When you right click a track, in the context menu, you can hold <kbd>Shift</kbd> to reveal the option `Delete Track File`. This will move to trash if possible otherwise delete.

This probably should be better documented.

**Comment by dspacejs** [comment]
@Taiko2k I don't think you should have to shift-click to see this. Instead, maybe just move it to a "trash" view, where items are deleted after x days (or can be deleted by the user if they choose to). This way if the user accidentally deletes something, they can easily recover it. But not showing the menu item makes it hard to find, you have to go to the docs to find it. 

Also, just realised shift clicking also shows the "After Current Track" item below "Add To Queue". I think this should be shown by default as well, it's pretty common to add something next in queue before other items in the queue. Again, I don't think users should have to read the docs to figure out how to do something basic like this.

**Comment by Taiko2k** [comment]
> Again, I don't think users should have to read the docs to figure out how to do something basic like this.

There's already a ton of stuff you need to read the docs for. Its basically a "You have to read the docs" player at this point.

**Comment by dspacejs** [comment]
@Taiko2k I think it should be pretty straightforward to use. Reading the docs should be for power users who want to get more out of the experience. Things should be easy to use and intuitive out of the box IMO.

**Comment by Taiko2k** [comment]
@dspacejs Well not as bad as vi. At least the close button is in somewhat of an expected place here.

**Comment by dspacejs** [comment]
@Taiko2k haha yeah. But this is a GUI. It's not a command line interface, in which case I'd expect to have to read the docs.

The GUI should just work without reading the docs. Any keyboard shortcuts or advanced features should be optional and for power-users.
