### ISSUE TITLE
[Feature Request] Add indicator to the active playing playlist

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#37]
I think that it will be very useful to have an active playing playlist indicator.

**Comment by Taiko2k** [comment]
There is actually in the horizontal top tabs, albeit subtle, though indeed perhaps the playlist side panel should have this as well

**Comment by Solarunit** [comment]
Yeah, I was talking about playlist side panel =)

**Comment by Taiko2k** [comment]
Btw you can right click the play button which quickly takes you to the playing playlist.

**Comment by Solarunit** [comment]
I know, a very useful feature! Left click also works.

**Comment by Taiko2k** [comment]
I can mirror the subtle shading used in the top panel here like this:

![screenshot from 2019-02-08 12-41-04](https://user-images.githubusercontent.com/17271572/52450269-34f86800-2b9f-11e9-9f93-5f1565346bd9.png)

I used to have a large distinct yellow play sign to indicate this, but I didn't like the aesthetic of that.

**Comment by Solarunit** [comment]
It's hard to see.
I'm thinking about these options:

1.
![Alt Text](https://ibin.co/4WG0gqiZ7dOe.png)

2. 
![Alt Text](https://ibin.co/4WG1ir0d4ztt.png)

3. Or we can just use a different text color for the playing playlist

**Comment by Solarunit** [comment]
4. highlighting like horizontal tabs maybe

![alt text](https://ibin.co/4WGHJTt4ovNI.png)

**Comment by Taiko2k** [comment]
I think I like idea 1, gives clearer separation than the highlight, without being too overbearing. I'm thinking yellow.

![screenshot from 2019-02-08 19-43-54](https://user-images.githubusercontent.com/17271572/52463162-ce913b00-2bda-11e9-997f-6b50953fbe92.png)

The main reason this doesn't follow the top panel colours is this part of the UI is intended look good for any given background colour so it can work well with the auto theme function.

![screenshot from 2019-02-08 19-47-47](https://user-images.githubusercontent.com/17271572/52463295-3d6e9400-2bdb-11e9-9c97-870f9837ce2f.png)

**Comment by Solarunit** [comment]
What do you think about the option to disable on/off playlists switches? I don't use it at all.

**Comment by Taiko2k** [comment]
I could make it so its disabled along with disabling the top tabs, since managing top tabs are the main function of the switches. Maybe I could leave just the yellow indicator so it still serves the purpose of displaying which playlist is playing.

The switches also serve an obscure function of being skipped when transitioning from previous playlists. Though it's not even a feature I've ever used.

**Comment by Solarunit** [comment]
> I could make it so its disabled along with disabling the top tabs, since managing top tabs are the main function of the switches. Maybe I could leave just the yellow indicator so it still serves the purpose of displaying which playlist is playing.

Looks like a good idea to me. 
Although I think some users may find these switches useful even when top tabs are disabled.
Do you plan to implement some kind of Playlists Manager, where users can enable/disable playlists, lock playlists, sort playlist (by creation date, play time)?

**Comment by Taiko2k** [comment]
I hadn't considered a playlist manager like that. I'm not sure about the idea though, none of those features seem necessary to me. Perhaps I'm not familiar with the use cases.

**Comment by Solarunit** [comment]
Player which I was using on windows has Playlists Manager, but I never used it.

**Comment by Taiko2k** [comment]
In regards to #36 

I think I might have better solution, how about just adding a setting titled `Always pin new playlists`, then you could disable this setting, and unpin all existing playlists, then the top tabs would be effectively disabled.

I think this makes more sense in the context of how things are intended to work. You could still use top panel tabs if you later wanted to, and there's no edge cases where functionality is broken.

**Comment by Solarunit** [comment]
`Always pin new playlists`
So the idea is that top tabs = reсent pined playlists
I see some problems with the top tabs:
1. To see the most resent playlists we must unpin some old playlists, because they are hidden. (Not a problem if you only use few playlists)
2. Width of the tabs depends of the playlist' name lengths and it can be very long (e.g. "artist-album").
3. The number of available tabs is limited because we can't scroll them, especially when player window is not maximized.

**Comment by Taiko2k** [comment]
Well, not *recent*, just shows the first that will fit. With the idea that the user would indeed need to unpin others if they want to see more.

So those are indeed limitations, but I don't see any solution that's a hugely improved paradigm.

**Comment by Solarunit** [comment]
> Well, not _recent_, just shows the first that will fit. With the idea that the user would indeed need to unpin others if they want to see more. (Or re-order them)

Do you think that the users will pin/unpin playlists? Because it is rather unique concept. Other players just have horizontal or vertical playlists "tabs"

**Comment by Taiko2k** [comment]
I think top tabs give the most convenience, especially if the window is sized small, or the user has few playlists open. But becomes cumbersome if there's many playlists. Once a user has many playlists, they can transition to using the side tabs, and pinning and unpinning for quick access to individual tabs.

Yes it's a little unorthodox but I think it works alright, and is reasonably aesthetic, I think removing parts of it as it works currently would be a downgrade.

**Comment by Taiko2k** [comment]
Hmm, I'm not sure I'm happy with option 1 after all, it does conflict with the pin function (in the case if pinning and unpinning the playing playlist, where would not be correct feedback for that)

**Comment by Solarunit** [comment]
What about different text color for the playing playlist? We already have quite a colorful playlist.

**Comment by Taiko2k** [comment]
I don't think that would work well, as mentioned, the background could be any colour, so it wouldn't consistently look good.

**Comment by Solarunit** [comment]
Another variant with marker. But it will look weird if we disable the pin switcher.

![alt text](https://ibin.co/4WUfSedESG35.png)

**Comment by Solarunit** [comment]
Another idea:

![alt text](https://ibin.co/4WmSNiKEOPVu.gif)

**Comment by Taiko2k** [comment]
Heres my current working concept

![screenshot from 2019-02-24 12-27-16](https://user-images.githubusercontent.com/17271572/53292929-c8809880-382f-11e9-9269-cc49f3353a83.png)

**Comment by Solarunit** [comment]
Not bad I think. And playlist will also be highlighted (like selected playlist)?
How will it look on another theme? Maybe the marker color should depends on the main theme color.

**Comment by Taiko2k** [comment]
As I currently have it, there is no highlight, and does follow theme colour.

![screenshot from 2019-02-24 14-11-50](https://user-images.githubusercontent.com/17271572/53293740-52cff900-383e-11e9-91b0-3c27ab8ce536.png)

**Comment by Solarunit** [comment]
I think marker+highlight looks better on screenshot, but having 2 highlighted playlists will look confusing.
