### ISSUE TITLE
[Bug] Auto-update smart playlists

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#371]
If I love a track, it should automatically update the "Loved" playlist. It seems to have done this in some instances, but not all. I had to delete and regenerate this playlist for the recently loved track to show up. 

The same principle applies to all smart playlists (but I haven't tested the others).

**Comment by dspacejs** [comment]
@Taiko2k is there a workaround for this in the meantime? Besides creating a manual playlist

**Comment by dspacejs** [comment]
I also think "Loved" should probably be an existing playlist by default, given the fact it shows in dropdown menus etc

**Comment by Taiko2k** [comment]
There are actually 2 ways of making smart playlists auto-update, however there happens to be another bug that prevents this working properly with *loved* playlists. (Fixed in master)

The reason auto updating isn't enabled by default is I feared performance issues if a user were to have many smart playlists. Though I am contemplating enabling auto updating just for loved playlists by default.

**Comment by dspacejs** [comment]
@Taiko2k I'd say loved is worth it. 

You could probably also just use a queue or something. Periodically update the smart playlists on a schedule. Only update the parts that need updating (if possible) to update performance.

Alternatively just update the smart playlists when the user opens them. Instantly load cached songs, then add a loading spinner or something to allow for any other songs to go in.

e.g for "Has Lyrics". So long as you have a list of songs with a boolean for this, you can easily do a filter (which shouldn't be an expensive operation) and can run instantly whenever you open the playlist. If caching is necessary, load the cached songs first (with this in operation in the background), and update the playlist if there's any changes.

**Comment by Taiko2k** [comment]
Yeah triggering the update on playlist open sounds like a good idea. I might go with that, and have playlists auto updating on by default.

**Comment by Taiko2k** [comment]
Update: Ive now got a setting in settings named `Auto regenerate playlists`. It defaults to off. 

![Screenshot from 2020-10-02 23-00-24](https://user-images.githubusercontent.com/17271572/94911754-16c54580-0503-11eb-919e-d545889f910f.png)


When enabled, a single playlist will be reloaded when switching to it (and all playlists will be updated when importing new tracks.) (Also note of course some types of generated playlists are exempt from this, such as smart shuffled playlists.).

**Comment by dspacejs** [comment]
@Taiko2k I think it should default to "on" for important playlists, like "Loved". That's something users would generally expect to auto-update by default
