### ISSUE TITLE
[Feature Request] Add default keybinding for love-playing

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#372]
I think this is a feature that's used enough to be worth having a default keybinding. I used `L Shift Ctrl` myself, which seems suitable since `love-selected` is `L Ctrl`.

Btw, I hope you don't mind all the issues I'm making, I've just been thinking of lots of ideas as I've been using it lol

**Comment by Taiko2k** [comment]
> I think this is a feature that's used enough to be worth having a default keybinding. I used L Shift Ctrl myself, which seems suitable since love-selected is L Ctrl.

Okay, I've set that as the new default. Note that this won't apply for old installations, only new ones.

> Btw, I hope you don't mind all the issues I'm making, I've just been thinking of lots of ideas as I've been using it lol

It's okay, I'll get through them.
