### ISSUE TITLE
[Feature Request] Add Songwhip integration

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#373]
https://songwhip.com

So music can easily be shared between different platforms. It's an alternative to `Copy "Artist - Track"`. Not a big deal, but would be nice to have.

**Comment by Taiko2k** [comment]
Interesting. Unfortunately the platform Bandcamp is missing, which is pretty major IMO. Also there doesn't seem to be a way create a link in a deterministic way, or verify if a link is valid. For accurate results, it seems one needs to use the search.

**Comment by dspacejs** [comment]
@Taiko2k yeah I haven't used it much. Might be worth considering though

**Comment by Taiko2k** [comment]
I'm not super feeling this one, so ill close this.
