### ISSUE TITLE
[Feature Request] Show notification when song is added to playlist via keyboard shortcut

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#374]
If I "love" a song, it adds it to the "loved" playlist. But there's no way for me to know whether it actually worked or not (e.g I could've accidentally pressed the wrong keys). Unless I manually check, by right-clicking the song or going into the playlist.

Therefore I think a notification should be added when a song is added to a playlist—or at least just when it is done so via a keyboard shortcut.

**Comment by Taiko2k** [comment]
Makes sense, there's already a toast for adding stuff to the queue for the same reason.

**Comment by Taiko2k** [comment]
Okay I've committed a change now. When toggling a love using a keyboard shortcut, this toast will appear:

![Screenshot from 2020-09-29 16-41-34-cropped](https://user-images.githubusercontent.com/17271572/94510254-d0f24e00-0272-11eb-995c-0755f7357df2.jpg)

**Comment by dspacejs** [comment]
@Taiko2k you could add a heart icon to it too? before the "Loved track" text

**Comment by Taiko2k** [comment]
Okay, this change is live
