### ISSUE TITLE
[Feature Request] Add ability to edit metadata within the app

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#376]
Instead of having to use something external like Picard.

**Comment by nudnyzjeb** [comment]
This seems by all metrics excessive and unnecessary, as there are already a couple of beautiful programs like kid3, puddletag and picard (not as beautiful as tauonmb is, though), which can edit tags of different formats (vorbis, idv3) and perform certain operations, such as: auto-detecting text encoding (CP-1251 for cyrillic), performing a set of renaming operations that you'd typically want to perform on warez music, automatically applying not-so-simple capitalization rules.

Instead, what needs to be added, and for what many users (at least 5 including me) yearn is an internal tag editor that doesn't actually directly edit the files. This feature is very much handy when files need to remain unchanged, for example: always (or when you participate in a p2p that relies on files being unaltered during the exchange - torrenting, ed2k, ipfs).

**Comment by Taiko2k** [comment]
@nudnyzjeb Not writing changes to tags would certainly be easier to implement. Though I never really intended for someone to invest so much into the local database.

To help me get a better perspective, what operations / changes would you typically want to apply using an internal only tag editor?

**Comment by nudnyzjeb** [comment]
![err](https://i.loli.net/2021/04/26/dCWSsNokjnV9TqA.jpg)
...somewhere, someone, at some point actually thought that this was a good idea.

**Comment by Taiko2k** [comment]
I see. Though its probably out of scope really, at least that's how I feel right now. It would be quite a lot of work.

> Another interesting feature would be automatically translating japanese and chinese symbols into latin 

Search can currently lookup kana using Latin. Adding more may be possible, though I also don't want to make search any slower, and if one knows such languages they probably have an ime installed anyway.

You mentioned encodings. Tauon does have a "fix mojibake" function. It currently only works to fix Japanese text, but could be extended to detect Cyrillic.

**Comment by nudnyzjeb** [comment]
>Search can currently lookup kana using Latin. Adding more may be possible, though I also don't want to make search any slower, and if one knows such languages they probably have an ime installed anyway.

I was still talking about local db and how it could be very useful, e.g. by translating asian characters to _replace_ them with romaji/pinyin.
Sometimes you just get used to writing everything in romaji.

>russian mojibake

Âÿ÷åñëàâ Áóòóñîâ - Ãèáðàëòàð \ Ëàáðàäîð
:  )
I only remember seeing this kind of mojibake - cp1251-encoded text assumed to be iso-8859-1.
Someone made a list of those - http://cyclowiki.org/wiki/Кракозябры

**Comment by Taiko2k** [comment]
Okay I've made some progress on this now.

Its pretty basic, but allows you to edit one or multiple selected tracks. It applies to the local DB only (with consideration for use cases @nudnyzjeb was referring to). 

![Screenshot from 2021-07-29 18-09-22](https://user-images.githubusercontent.com/17271572/127441016-d36a9052-9fa1-48c8-b4eb-1ccc42389b93.png)

**Comment by awsms** [comment]
>p.s. Another interesting feature would be automatically translating japanese and chinese symbols into latin script, so that it becomes searchable with the usual keyboard layout.

Similar to this, european special characters break the search (for example can't find 'jésus' by searching 'jesus')

**Comment by Taiko2k** [comment]
> Similar to this, european special characters break the search (for example can't find 'jésus' by searching 'jesus')

This should work. I just did a quick test and it seems to be working for me. Try again and if you're sure its not working, could you tell me what search method you used, and what field the text appears in?

**Comment by awsms** [comment]
> > Similar to this, european special characters break the search (for example can't find 'jésus' by searching 'jesus')
> 
> This should work. I just did a quick test and it seems to be working for me. Try again and if you're sure its not working, could you tell me what search method you used, and what field the text appears in?

I just tried again, it works in the 'global search mode', but not the Ctrl+F (search in a playlist mode)

**Comment by Taiko2k** [comment]
This is in release version now. I ended up adding the ability to optionally write to tags.

I'll close this issue now since its getting a little long. For further functionality/bugs just create a new issue.
