### ISSUE TITLE
[Feature Request] Add ability to disable transcoding

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#377]
All my music is in FLAC. I accidentally transcoded it and it messed up the audio quality. I had to reimport my music and delete the transcoded files.

I know you can turn the transcoding into FLAC. But this isn't a feature I want to use at all. And to prevent users from accidentally doing it, I think the feature should be able to be disabled (or just require a confirmation dialogue to do so).

**Comment by Taiko2k** [comment]
Well, the codec shouldn't matter, by default it outputs all files to the encoder directory anyway so no major harm done.

Ive added a setting to disable this menu entry now though. (Under settings > function)
