### ISSUE TITLE
[Feature Request] Add UI animations

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#378]
Just some basic ones. Such as sliding/fading in a song when you add it to the queue. Or popping in dropdown menus. It makes the UX feel a bit smoother. 

[Ant Design](https://ant.design/) has some good examples.

**Comment by Taiko2k** [comment]
Animations run risk of making the UI feel slow to use, so I avoid them on any elements that are interactable. It's a strict design philosophy I adhere to.

**Comment by dspacejs** [comment]
@Taiko2k I think it depends. You can use ones that feel very fast and snappy, without lag.
