### ISSUE TITLE
[Feature Request] Enable Ctrl + click to select songs

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#379]
Instead of just Shift + click. So you can select songs that are apart from each other, without selecting all the songs in between.

**Comment by DesertStars** [comment]
I agree, but I think it should be added alongside Shift + Click, instead of as a replacement so you can use them both.

**Comment by dspacejs** [comment]
@DesertStars oops yeah that's what I meant, you'd still want to be able to use both.

**Comment by Taiko2k** [comment]
This change has been committed now.
