### ISSUE TITLE
[Feature Request] Global Hotkeys settings

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#38]
I miss Global Hotkyes settings. Do you plan to add hotkeys configuration?

**Comment by Taiko2k** [comment]
Global hotkeys is a wonfix for me. The Linux desktop gods have declared them to be deprecated as Wayland does not support them and its intended that the desktop should handle all hotkeys now. I'm not really interested in adding X11 specific features at this point.

As for any key mapping, its not something I have planned. I was hoping the current key layout would be sufficient.
