### ISSUE TITLE
[feature request ] create an internet radio playlist 

### ISSUE THREAD

**Issue by jediafr** [Taiko2k/TauonMusicBox#380]
Being able to add intenret radios in playlist (separate or not from the local music).

**Comment by GLLM** [comment]
My most missed feature :)

Fantastic player otherwise !

**Comment by Taiko2k** [comment]
I don't have intention of integrating this with the main playlists (For both technical and design reasons). A redesign of the Radio UI Box is probably in order though. 

If anyone can come up with a UI concept for this, or maybe just an idea of how it should look, that could be helpful.   
 - > Note that the maximum width it can be is 560px as that's currently the minimum width the window can be.

**Comment by jediafr** [comment]
Oh thanks for still considering that request alas i'm not much gifted in the artistic department. My main grip with Internet radio today isn't with the layout but mostly with the lack of support for playlists (a minor one)  AND MPRIS commands (not being able to switch between radios using the media buttons is a major no go for me).

**Comment by Solarunit** [comment]
What if when we switch to the radio mode:

 - playlists list = radio stations list 
 - playlist = song history
 - some buttons are hidden (next, previous...)

**Comment by Taiko2k** [comment]
Its now possible to create different radio lists, so ill close this now

**Comment by GLLM** [comment]
@Taiko2k : oh, great news !
How should we proceed to create one ?  couldnt find it on the website.
Thanks a lot

**Comment by GLLM** [comment]
Great, thanks for this feature !!!

<This is why we can't have nice things>
Just missing is the ability to see the radio playlist next to the other playlist :-P
</This is why we can't have nice things<
