### ISSUE TITLE
[Feature Request] Ability to refresh Airsonic playlists

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#382]
I would like to know if it'd be possible to add a "Rescan Folder" option (in the right-click context menu) on Airsonic/Subsonic playlists, the same way you can rescan a folder.

**Comment by Taiko2k** [comment]
Okay, Ive added this as part of the `Regenerate` function. After updating you'll need to add the Airsonic collection playlist one more time for this to start working.
