### ISSUE TITLE
[Suggestion] About the queue

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#383]
I just encountered an unexpected situation.
Let's say I have 2 playlists. I'm currently playing the first one in shuffle mode, and I'd like to listen some song from the 2nd playlist.
Once this song has ended, I would obviously like to go back where I was in the first playlist, but it actually starts a new one, randomly generated from the second playlist.
Shouldn't the queue be completely independent how the playlists are handled, I mean just add the songs selected to the queue and do nothing more?

**Comment by Taiko2k** [comment]
This behaviour is intentional. Its useful if you *want* it to continue from another playlist. If you want to revert to the first playlist, you'll have to queue something from it.

**Comment by awsms** [comment]
>If you want to revert to the first playlist, you'll have to queue something from it.

I see. But then it will generate a new shuffle playlist again of the first playlist, instead of resuming from where it played the last song

**Comment by Taiko2k** [comment]
Repeats while shuffle is on will still be avoided per playlist.
