### ISSUE TITLE
[Question] Duplication of imported music 

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#386]
If you've imported a song to a playlist, then create another playlist and drag-and-drop a folder into it that contains this song. Will the song be duplicated? Or is there only a single reference to each music file?

**Comment by Taiko2k** [comment]
If you import a file again, if its the same full file-path, the existing database entry will be reused. You can easily test this by using the *go to playing* function, if it locates it in the playlist as the playing song, then its the same reference.

If you move the file, then that will be treated as a different unique entry. It's for this reason if you move your whole library and re-import, its good the go `MENU` > `Database...` > `Remove missing tracks` to clean things up.

**However** for the purposes of *play-count*, *loves* and *ratings*, tracks are treated as unique separately by their file name, and not the full path.
