### ISSUE TITLE
[Feature Request] Libre.fm support for scrobbling

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#388]
libre.fm is a FOSS alternative to Last.FM
https://git.gnu.io/foocorp/librefm/-/wikis/home

**Comment by Taiko2k** [comment]
Do you use this yourself?

**Comment by awsms** [comment]
I do, yes https://libre.fm/user/aawsm

**Comment by Taiko2k** [comment]
I wonder, do you think if a user selects libre.fm, should artist bio data still be downloaded from last.fm? (Or should those features simply stop working?)

**Comment by Taiko2k** [comment]
Okay, I've committed this feature now. There's now an option to toggle Libre.fm in the Last.fm settings. (Shows when logged out).

A limitation is that you can only have one or the other enabled and not both at the same time. Hopefully that wont be too inconvenient.
