### ISSUE TITLE
[Feature Request] Show duration of playlist

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#391]
Sometimes I'm building a playlist for something specific, and need the total time to be for a specific duration.

**Comment by Taiko2k** [comment]
This isn't shown in the main screen. But with the playlist selected you can go `MENU` > `Settings...` > `Stats` and it tells you the playlist duration there.

**Comment by dspacejs** [comment]
Oh, I think it should be added somewhere then. Maybe in the right sidebar?

**Comment by Taiko2k** [comment]
I don't think this needs to be known all the time so I'd rather keep the UI clean.

How about this, the selection menu could display the duration of the selection:

![Screenshot from 2020-10-03 22-07-58-cropped](https://user-images.githubusercontent.com/17271572/94987748-24430400-05c5-11eb-82aa-cc5b2f385d65.jpg)

Then, you can just do a <kbd>Ctrl</kbd> + <kbd>a</kbd> then right click to quickly find the current duration of the whole playlist. Also allows you to find the duration of any selection.

**Comment by dspacejs** [comment]
@Taiko2k I think that's nice for seeing the duration for selected songs. But I don't think you should have to do `Ctrl` + `a` on the playlist view to do this. Some other options would be:

* Show duration when you right-click a playlist in the sidebar/tabs
* Add settings for what to show in the sidebar, one of which would be the duration
* Just always show the duration of the playlist with some minimal UI so it doesn't become too cluttered

I'd say the latter is ideal. You could add a bar that aligns with the columns for the playlist on the left:

![Screenshot from 2020-10-03 20-34-07](https://user-images.githubusercontent.com/9282837/94989978-cf4cc100-05b7-11eb-8d1d-4d40d958d713.png)

And inside it just have some basic text for the duration like you do in your screenshot "[53:27]" or something
