### ISSUE TITLE
[Feature Request] Album view

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#393]
It would be nice if there was an album view, like there is for artists. So you can view all the songs in an album, with the album art presented somewhere (plus its info).

**Comment by Taiko2k** [comment]
Tauon actually did used to have an album view such as you describe. But I removed it, my reasoning was that the view, although an alternate layout visually, didn't really provide any additional core functionality. The gallery + tracklist effectively supersedes it. 

Better to keep the interface streamlined. It was also a fair maintenance burden, having to replicate tracklist functionality.

**Comment by dspacejs** [comment]
@Taiko2k then how can a user view all songs in an album? Sometimes I want to play music from an album on shuffle/repeat, without other music. If there's no album view you can't do this (unless you add the songs to a playlist, which would basically be duplicating the album).

**Comment by Taiko2k** [comment]
> (unless you add the songs to a playlist, which would basically be duplicating the album).

If you want to isolate a single album, that's basically the intended way of doing it. You can delete the playlist when you're done.

There's also another way you can shuffle within an album which is by enabling modes `Album repeat` and `Shuffle`

**Comment by dspacejs** [comment]
@Taiko2k 

> If you want to isolate a single album, that's basically the intended way of doing it. You can delete the playlist when you're done.

But then you have to create and delete it, which is a bit of a nuisance. I think this is a pretty standard feature that should be in every music player.

> There's also another way you can shuffle within an album which is by enabling modes Album repeat and Shuffle

How do you do this?

**Comment by Taiko2k** [comment]
> How do you do this?

Right click the repeat button and select `Repeat Album`, then also have standard shuffle on.
