### ISSUE TITLE
[Feature Request] Map `Delete` key to move songs to trash

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#397]
I thought this was what it was doing, but the songs weren't in the trash.

Alternatively add an extra key if `Delete` has some other function. Such as `Shift` + `Delete` to move to trash.

**Comment by Taiko2k** [comment]
I kind of feel like having a keyboard shortcut for this is too easy. Like you could do a Ctrl+A Shift+Delete to delete your whole music library. Doesn't feel right.

**Comment by dspacejs** [comment]
@Taiko2k hmm yeah, maybe. I guess this isn't a common operation. It just has been for me personally because I have lots of duplicate files
