### ISSUE TITLE
[Feature Request] "Love" multiple selected songs at once

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#399]
If you select multiple songs, you should be able to do `Ctrl` + `L` to love all of them (plus add a dropdown menu item for it).

**Comment by Taiko2k** [comment]
I'm gonna go wontfix on this one. Its not really the intended purpose of the feature that you can love many tracks at once.

**Comment by dspacejs** [comment]
@Taiko2k I think it should. Sometimes there's a bunch of songs I like when I'm browsing my library. I already know which songs I like because I imported my music to this app, which means liking multiple songs at once is pretty common
