### ISSUE TITLE
[Feature Request] Edit auto queue

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#402]
There's a default queue, even when you haven't manually added any songs to it. Users should be able to edit this.

An example use case: I'm shuffling a playlist. I like most of the music, but don't feel like listening to some of the songs. If I can remove these songs from the queue, or rearrange them in a way that suits my mood, this is useful.

**Comment by Taiko2k** [comment]
> There's a default queue, even when you haven't manually added any songs to it. Users should be able to edit this.

I think I understand the paradigm you're talking about, some other players use it, but Tauon doesn't. In Tauon, when the queue is empty, the queue is off and the playlist is played as is.

> An example use case: I'm shuffling a playlist. I like most of the music, but don't feel like listening to some of the songs. If I can remove these songs from the queue, or rearrange them in a way that suits my mood, this is useful.

So in Tauon... the intended way of selectively altering upcoming tracks in a playlist, would be to create another playlist. You can create a smart shuffled playlist based on another playlist.
