### ISSUE TITLE
[Feature Request] Auto-reload artist playlists when rescanning music library

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#403]
Sometimes I add new songs/edit/remove songs for an artist. But the corresponding artist playlists don't refresh, so I have to manually go and recreate them.

This should happen automatically.

**Comment by Taiko2k** [comment]
If you have the `Auto regenerate playlists` option enabled, this should work... it should reload after a rescan, and after re-entering the playlist.

![Screenshot from 2020-10-07 15-25-50](https://user-images.githubusercontent.com/17271572/95280487-9b241980-08b1-11eb-96ba-560a426d32f9.png)

If its not doing it with that enabled, then its possibly a bug. Did you have it enabled?

**Comment by dspacejs** [comment]
@Taiko2k ah, that's why. I had this option turned off. Thanks.
