### ISSUE TITLE
[Feature Request] Support selhosted maloja instances for scrobbling

### ISSUE THREAD

**Issue by mannp** [Taiko2k/TauonMusicBox#404]
https://github.com/krateng/maloja

I've just started using maloja and it appears to have musicbrainz compatible api endpoints.

We enter the url of our instance and add our api key and that's it.

Would appreciate your consideration :+1:

**Comment by Taiko2k** [comment]
Okay I've committed this now.

It will now be possible to change the target URL used by the Listenbrainz scrobbler. To do this you set the value `custom-listenbrainz-url` in Tauon's config file.

I haven't tested this myself so it would be helpful if you can. You'd need to setup Tauon from latest git master. If you do, let me know if its working.

**Comment by mannp** [comment]
That's great, thanks for making the changes for testing.

I've cloned locally and can execute tauon.py but the config in user-data seems to keep getting overwritten?

I have also opened the config from the gui, reloaded and reopened to find the settings gone?

Small point, but one thing I have noticed is that for maloja the api key can be what you want and not just in the format of listenbrainz... I have used a valid listenbrainz api key too, but the settings disappear.

Likely I am doing something wrong locally.

**Comment by Taiko2k** [comment]
Ah yes you're right, those are both issues. Ill fix the config not saving. For the API key not being accepted... that makes sense. Can you tell me the **length** of the API key you use? So I can keep some kind of validation.

**Comment by mannp** [comment]
The example in the maloja config example file was 64 chars, so I have used the same.

I also note that after adding my api key and url in the tauon config file, lastfm shows as enabled and listenbrainz as disabled.

I am unable to enable listenbrainz as I have not pasted the key, but have entered it into the config file.

Appreciating your code overhead for adding a separate item for a bespoke url, I'd hate these changes to cause issues for your listenbrainz users...

**Comment by Taiko2k** [comment]
>  but have entered it into the config file.

There is verification on the config entry too so that won't work.

I'll just disable verification if a custom URL is entered. Should be a good enough balance. 

I'm not quite ready to commit my working changes right now, ill let you know when, then you can try again. Thanks for testing btw!

> I'd hate these changes to cause issues for your listenbrainz users...

I'm not sure there even are listenbrainz users :pensive:

**Comment by mannp** [comment]
> I'm not sure there even are listenbrainz users pensive

LOL Okay :) only me then...

> I'll just disable verification if a custom URL is entered. Should be a good enough balance.

Sounds good.

> There is verification on the config entry too so that won't work.

I see okay.

> I'm not quite ready to commit my working changes right now

No problem, take your time :)

**Comment by Taiko2k** [comment]
Okay, I've pushed that change now. I still haven't done extensive testing myself, so there might still be issues, let me know if its working.

**Comment by mannp** [comment]
So I am getting the following error from tauon when the attempt to scrobble is made;

> {'code': 400, 'error': 'Invalid JSON document submitted.'}

Seems odd unless that is the error tauon is receiving from my maloja instance?

Additional small point is the api key extends over the edge of the player window at 64chars  :)

**Comment by Taiko2k** [comment]
Sure the URL is correct? It should be something + `/apis/listenbrainz`?

If thats correct... Ive done all I can easily do there. It does say its experimental, perhaps its not working.

From here, it might be easier to just implement the native API. Since this is such a bespoke service, I would just implement this as a config file option without any UI settings or controls.

Do you keep your server accessible to the internet? If so it would be convenient if I could use your server for testing, could you perhaps email me the URL and a key?

**Comment by mannp** [comment]
Yes I believe the url is correct, but I note that it states to include a username for listenbrainz and not to leave it empty, but I don't see the ability to add a username in tauon?

> 
> ListenBrainz |  
> -- | --
> API URL | Your Maloja URL followed by /apis/listenbrainz
> Username | Any name, doesn't matter (don't leave empty)
> Auth Token | Any of your API keys

I hope to get it behind my traefik2 instance but not sure when that might be as yet. Need to understand how to harden it and setup some 2fa for the admin login first....

Happy to test though :+1: 

And very cool if you are able to use their native API :)

**Comment by Taiko2k** [comment]
> but I note that it states to include a username for listenbrainz 

Yes, Listenbrainz doesn't use a username, so I find that part confusing.

Anyway, I've tried added native now. But its completely untested.

Do a git pull...

Add your maloja server url to `maloja-url` and api key to `maloja-key` in the config file. After reloading the config file, it should start working. (Try play a song thats > 30s for >50%, then press stop (or let the song finish), then see if it worked. You should see the `Submit Maloja scrobble` in the log when it tries)

**Comment by Taiko2k** [comment]
Woops, made a typo in to config file, please pull and try again.

**Comment by mannp** [comment]
> Submit Scrobble Stereophonics - Street of Orange Light
> Submit Maloja scrobble
> Re-queue scrobble

Nothing in the maloja log to my surpise ....

Seems I had an extra space in my url ... testing again.

**Comment by Taiko2k** [comment]
Should it not be `http://192.168.10.17:42010/api/newscrobble`?

(On a another note, that `re-queue` is a bug, I've pushed a fix)

**Comment by mannp** [comment]
After latest git pull;

> Submit Scrobble Stereophonics - Street of Orange Light
> Submit Maloja scrobble
> Re-queue scrobble

This is what it says in my admin area

> If you use another browser or another music player, you could try to code your own extension. The API is super simple! Just send a POST HTTP request to http://192.168.10.17:42010/apis/mlj_1/newscrobble (make sure to use the public URL) with the key-value-pairs

**Comment by Taiko2k** [comment]
Huh, the readme said to use that different URL. Have you tried both?

The requeue is fine now... It does that if it fails. (Before the fix it would always do it)

**Comment by mannp** [comment]
Retry with other url in progress :)

**Comment by mannp** [comment]
Getting the same error < Not allowed > and i have checked the api key and it is correct.

Hope you don't mind but I posted on maloja too in the hope their dev can help directly... (https://github.com/krateng/maloja/issues/39)

**Comment by Taiko2k** [comment]
Oh okay. I just hope its not something I'm not doing right. (Really shouldn't trust my 1AM code too much)

**Comment by mannp** [comment]
> Oh okay. I just hope its not something I'm not doing right. (Really shouldn't trust my 1AM code too much)

LOL, hey thanks for trying that late!

Much appreciated.

Well I know they have changed their api endpoints, looking at github, so I was confused as to which was the correct endpoint.

I assume I have quoted the correct url from the admin gui, but I am unclear.

I am trying to simulate the request with Postman to see if it gives me a clearer error.

**Comment by mannp** [comment]
POST http://192.168.10.17:42010/api/newscrobble?key=<key>&title=The Way I Feel&artist=Keane

> {
>     "status": "success",
>     "track": {
>         "artists": [
>             "Keane"
>         ],
>         "title": "The Way I Feel"
>     }
> }

**Comment by Taiko2k** [comment]
Oh, as parameters? Okay I've made a change, try now.

**Comment by mannp** [comment]
https://github.com/krateng/maloja/issues/31

There was previously an issue passing in as a JSON, if that is how you were passing originally?

**Comment by mannp** [comment]
Boom!

> Submit Scrobble Stereophonics - Bust This Town
> Submit Maloja scrobble

11 seconds ago |   Stereophonics – Bust This Town

**Comment by Taiko2k** [comment]
Yeah I was trying to use JSON before.

**Comment by mannp** [comment]
> Yeah I was trying to use JSON before.

That should work though, so maybe the fix didn't fully fix.... https://github.com/krateng/maloja/issues/31

As that would be why we were getting the <Not allowed > error..

Is it better to use JSON?

**Comment by krateng** [comment]
Hey, Maloja dev here - glad to hear you got it working.

As for the URL, sorry for the confusion! The readme still shows the old API url, which still works, but the recommended one to use is `/apis/mlj_1`.
JSON would imho be better than query string, I'll see if I can find the issue.

**Comment by Taiko2k** [comment]
> Is it better to use JSON?

I dont really know. But I suppose if it works it works.

**Comment by krateng** [comment]
On my end scrobbling works with

`
    d = {}
    d["artist"] = track.artist
    d["title"] = track.title
    d["key"] = prefs.maloja_key
    data = json.dumps(d)
    

    try:
        r = requests.post(url, data=d)`

**Comment by mannp** [comment]
That revised api endpoint doesn't work for me ... there is no error returned to tauon, but Postman returns a html page...?

http://192.168.10.17:42010/apis/mlj_1/

Edit: Okay it appears to be 

http://192.168.10.17:42010/apis/mlj_1/newscrobble

**Comment by mannp** [comment]
> On my end scrobbling works with

Hope that means something to you @Taiko2k  :) (if you haven't logged off already in your part of the world!)

**Comment by krateng** [comment]
I opened a PR with my exact changes, this way the user can simply specify their base Maloja URL without the API path (e.g. `https://maloja.mydomain.tld`) in the config.

Thanks for the native support, it's much appreciated!

**Comment by Taiko2k** [comment]
@mannp I've now pulled @krateng's changes incuding the new in-UI settings. I've also added an `Enable` setting to toggle Maloja independently. Could you please pull and test these changes?

**Comment by mannp** [comment]
@Taiko2k just tested and it works great, including the test button, the setting of the url to the base url (http://192.168.10.17:42010) without a trailing slash.

One submit scrobble is displayed in the log.

> Submit Scrobble Stereophonics - Bust This Town -> 18 seconds ago | Stereophonics – Bust This Town

An observation is that the scrobble submit does not occur until the very end of the track, it might even be the start of the next track, rather than taking into account any thresholds ... not able to set the show thresholds option as that might be just for Listenbrainz (it says there is no key, so guessing it is just for LB)

Thanks for you great work, I am happy my data is staying with me again :)

**Comment by Taiko2k** [comment]
@mannp Good to hear its working.

> An observation is that the scrobble submit does not occur until the very end of the track

Yes that is intentional. It still registers the scrobble at the threshold, but waits until the track has stopped playing to submit it. It's done this way so it doesn't show at the same time as any "Now Listening" data. Although Maloja doesn't have that, its just how Tauon's scrobbling mechanism works, and who knows, Maloja may have a "Now listening" feature in the future. (Well, I could change it to submit just Maloja immediately, let me know if that's wanted) 

>  not able to set the show thresholds option as that might be just for Listenbrainz

Oh yes, I almost forgot, I should add that. It should already work, it's actually the same setting for all, I just need to show it in the Maloja settings too.

**Comment by mannp** [comment]
Hi @Taiko2k no need for anything specific for me on scrobble submission, as I wasn't entirely sure when the actual submission was made previously. I don't see any need for anything special for Maloja.

> 
Oh yes, I almost forgot, I should add that. It should already work, it's actually the same setting for all, I just need to show it in the Maloja settings too.

Okay great, just pulled your latest master and the threshold shows fine :+1: 

**Very very small point,** happy for you to ignore it, but maybe a generic scrobbling logo or an 'S' would be better than showing the lastfm logo/icon one in the menu when it is not being used?  :)

**Comment by Taiko2k** [comment]
>  but maybe a generic scrobbling logo or an 'S' would be better than showing the lastfm logo/icon in the menu when it is not being used?

For now, ill just disable the icon when only Maloja is active. If it ever gets an official icon it could then be added.

**Comment by mannp** [comment]
> > but maybe a generic scrobbling logo or an 'S' would be better than showing the lastfm logo/icon in the menu when it is not being used?
> 
> For now, ill just disable the icon when only Maloja is active. If it ever gets an official icon it could then be added.

Sounds like a sensible plan :)
