### ISSUE TITLE
[Feature Request] Search wider for artists generated playlists 

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#405]
Currently, if you generate an artist playlist for the artist `Someone`, it won't add the `Albumname - Someone & Somebody` albums, or `Trackname (feat. Someone) - Somebody` tracks.
I'm asking for adding a regex that will search for %artistname_case_insensitive% in every artist field, then generate a playlist with all the previous occurences.
Maybe as a facultative option in the settings in case it's annoying/not relevant enough for certains?

**Comment by Taiko2k** [comment]
Doing it that way is prone to turning up false positives. If you're expecting feats. etc, you could use generate a playlist using the *find* function (<kbd>Ctrl</kbd> + <kbd>F</kbd>).
