### ISSUE TITLE
Stats about Music Library

### ISSUE THREAD

**Issue by DesertStars** [Taiko2k/TauonMusicBox#407]
Any option to have some statistics about the music library we have? It could show the total size of library, number of tracks, duration, types (Album/Soundtrack/EP/Single and so), file type percentage - FLAC/MP3/AAC - and stuff like that, like Foobar2k does. Example:

```
Total Size:
140GB (150 653 451 231 bytes)

Items Selected:
20304

Rate Sample:
44100 Hz (99.6%); 48000 Hz (0.3%); 22050 Hz (0.0%)

Avg. BitRate:
242 kbps

Codec:
MP3 (98.9%); FLAC (1.1%); AAC (0.1%)

Codec Profile:
MP3 VBR V0 (58.4%); MP3 CBR (24.4%); MP3 VBR V2 (14.3%); FLAC (1.1%); MP3 VBR (1.0%); MP3 VBR V1 (0.4%); MP3 VBR V4 (0.2%); MP3 VBR V3 (0.1%); MP3 ABR (0.1%); AAC LC (0.1%)

Encoding:
lossy (98.9%); lossless (1.1%)

Tool:
LAME3.97 (46.3%); LAME3.97b (12.9%); LAME3.90 (7.2%); LAME3.96r (3.7%); LAME3.92 (2.8%); LAME3.98a (1.1%); LAME3.93 (1.1%); LAME3.95 (0.9%); LAME3.98b (0.9%); LAME3.91 (0.8%); LAME3.96 (0.7%); LAME3.97r (0.6%); reference libFLAC 1.1.2 20050205 (0.4%); reference libFLAC 1.1.4 20070213 (0.3%); reference libFLAC 1.1.1 20041001 (0.2%); reference libFLAC 1.2.0 20070715 (0.2%); LAME3.97a (0.1%); LAME3.90 (alpha) (0.1%); iTunes v5.0.1 (0.1%); LAME3.88 (alpha) (0.1%); LAME3.89 (alpha) (0.1%); LAME3.90a ...
```
Example above was taken from https://hydrogenaud.io/index.php?topic=60663.0, but I think not all of them are necessary, track count and total size would be really good in my opinion though.

**Comment by Taiko2k** [comment]
You can already use (Playlist tab context menu) > `Misc...` > `Export playlist stats`. Which has some stats, not all of those above, but I could add **file type**, and **total size**.

I hesitate to add a *global* stats printout, because unless the user has recently run `Remove missing tracks`, there may be invalid entries in the global database. What you could do is just make a playlist of all music you want included.

**Comment by DesertStars** [comment]
> You can already use (Playlist tab context menu) > `Misc...` > `Export playlist stats`. Which has some stats, not all of those above, but I could add **file type**, and **total size**.

Yeah, that seems like a good solution overall, it could be improved a bit though.

>I hesitate to add a global stats printout, because unless the user has recently run Remove missing tracks, there may be invalid entries in the global database. What you could do is just make a playlist of all music you want included.

Fair enough, I'll just do what you've suggested instead.

**Comment by Taiko2k** [comment]
Here's my modifications to the stats readout. I've changed the formatting to be more like your example, and added **Total local size**, **Track duplicates**, **Track types**, **are CUE** and bitrates for OGG and MP3. 

```
Playlist:
Example Playlist

Generated:
Sat 10 Oct 2020 14:18:15

Tracks in playlist:
1122

Track duplicates:
0

Total local size:
20.2 GB

Playlist duration:
2 days, 22:16:11

Total playtime:
20 days, 2:28:10

Track types:
MP3 (50.8%); FLAC (48.0%); OGG (1.2%); M4A (0.1%)

Percent of tracks are CUE type:
0%

MP3 bitrates (kbps):
320 (43.2%); 128 (28.8%); 192 (3.2%); 256 (2.3%); Others (24.4%)

OGG bitrates (kbps):
192 (100.0%)


-------------- Top Artists --------------------
```

I see you mentioned `Album/Soundtrack/EP/Single` but, I don't think there's any way of even guessing that. Would have to call an external API to lookup every item, which is way too extreme.

**Comment by DesertStars** [comment]
> Here's my modifications to the stats readout. I've changed the formatting to be more like your example, and added **Total local size**, **Track duplicates**, **Track types**, **are CUE** and bitrates for OGG and MP3.
> 
> ```
> Playlist:
> Example Playlist
> 
> Generated:
> Sat 10 Oct 2020 14:18:15
> 
> Tracks in playlist:
> 1122
> 
> Track duplicates:
> 0
> 
> Total local size:
> 20.2 GB
> 
> Playlist duration:
> 2 days, 22:16:11
> 
> Total playtime:
> 20 days, 2:28:10
> 
> Track types:
> MP3 (50.8%); FLAC (48.0%); OGG (1.2%); M4A (0.1%)
> 
> Percent of tracks are CUE type:
> 0%
> 
> MP3 bitrates (kbps):
> 320 (43.2%); 128 (28.8%); 192 (3.2%); 256 (2.3%); Others (24.4%)
> 
> OGG bitrates (kbps):
> 192 (100.0%)
> 
> 
> -------------- Top Artists --------------------
> ```
That's pretty decent, having an indication whether there's a duplicate or not is a good idea too.

> I see you mentioned `Album/Soundtrack/EP/Single` but, I don't think there's any way of even guessing that. Would have to call an external API to lookup every item, which is way too extreme.

Yeah, I wasn't really expecting that to be happen, just wrote that in case it was possible, it's no big deal.

**Comment by StrangeSeasOfThought** [comment]
> I see you mentioned `Album/Soundtrack/EP/Single` but, I don't think there's any way of even guessing that. Would have to call an external API to lookup every item, which is way too extreme.

(I use the id3tag 'grouping' for this.)

**Comment by Taiko2k** [comment]
Okay my mentioned change is now live. 

Let me know if you want to suggest any further changes, though I'm not sure what more to do, Tauon doesn't track encoding profiles for example.

**Comment by DesertStars** [comment]
> Let me know if you want to suggest any further changes, though I'm not sure what more to do

Can't really think anything else either that isn't minuscule or wouldn't be really hard to get it as a metadata, this is pretty good overall in my opinion, thanks.
