### ISSUE TITLE
[Feature Request] Prioritise folder.* when displaying album art

### ISSUE THREAD

**Issue by masaklaw** [Taiko2k/TauonMusicBox#409]
My use case is as follows:
- I have multiple artwork images for each album, such as `cdart.png`, `fanart.jpg` and finally `folder.jpg` (the actual album art).
- I currently have to manually click to choose the correct album art for each album, because _Tauon_ automatically chooses the first image file (alphabetically?)

It wold be great if the correct album artwork file was automatically chosen, based on a configured regexp or glob or something similar.

**Comment by Taiko2k** [comment]
Indeed currently it is effectively alphabetical, the exception is that embedded art is always first.

This could be added. A few things we need to think about:

 - Do we want this as a user configurable expression, or does it generally apply enough to everyone that we can hard-code it?
 - Do we want to **exclude** certain art entirely, or just **reorder** it?
 - What pattern are we looking for exactly?

Though, I'm not a fan of expressions like regex, so ill be avoidant of adding that.

Here's my proposal, simply have a hard-coded list of names of artwork that are given lowest priority in the ordering. For example `cdart.*, fanart.*`

**Comment by masaklaw** [comment]
Hmm, I don't know if these specific names are generic enough to be hardcoded. The examples I have given are specifically artwork files that some [Kodi](https://kodi.tv/) skins use.

Maybe something simple and similar to what [Clementine](https://www.clementine-player.org/) does?

_Clementine_ has one simple setting for this: <q>Preferred album art filenames (comma separated)</q>, and there I simply set `folder`  - so a base file name without extension. It could then take these files with _priority_.

Even a single file name instead of several comma would be good.

**Comment by Taiko2k** [comment]
I've gone ahead and hardcoded `folder.*` as having first priority over other names. I assume this should solve the issue for you.

**Comment by masaklaw** [comment]
> I've gone ahead and hardcoded `folder.*` as having first priority over other names. I assume this should solve the issue for you.

Thanks a lot!

**Comment by Taiko2k** [comment]
This should be live with the latest release now.
