### ISSUE TITLE
Crossfade option

### ISSUE THREAD

**Issue by linakba** [Taiko2k/TauonMusicBox#411]
used to be part of earlier versions but missing in version 6.3.3. : the "transitions" options in Menu -> Settings -> Audio including "enabling crossfade" and "Use gapless playback"

**Comment by Taiko2k** [comment]
I concluded that gapless playback would be universally preferred over crossfade. Keeping crossfade would be somewhat of a maintenance burden for what I perceived as a little used feature. 

Do you prefer crossfade transitions?

**Comment by linakba** [comment]
I assume gapless playback is enabled by default as the option is removed from Audio settings?
Maybe it's just me - I sometimes skip to the next track and I prefer a smooth transition... but I don't know how elaborate this is for you to maintain.

**Comment by Taiko2k** [comment]
> but I don't know how elaborate this is for you to maintain.

Yeah crossfade might be *nice to have* as an option, but would require a quite a major rewrite of things to restore this feature now. So I can't see it happening at this point, *gapless only* is sort of the direction that's been taken.

**Comment by Taiko2k** [comment]
On re-reading your issue, I see you said `I sometimes skip to the next track and I prefer a smooth transition` which actually refers to a different setting which was `Fade on track jump` which is a slightly different matter, and now that I think of it, that is a more important issue, though difficulty remains. 

I did come up with a way of implementing this on the Phazor backend. So, next version, you should see this setting return here:

![Screenshot from 2020-10-13 19-31-24](https://user-images.githubusercontent.com/17271572/95823773-b21fab80-0d8a-11eb-9b29-f35e124fd91f.png)

**Comment by linakba** [comment]
Yes that sounds great! I havent tested Phazor yet but I will try it to see if there are any bugs appearing, but as I mostly play mp3 files from local disc I assume it'll work just as fine as Gstreamer.

**Comment by Taiko2k** [comment]
This change should be live with the latest release now. As mentioned you'll have to switch to Phazor for it to work. Let me know if there's any issues.
