### ISSUE TITLE
Tauon doesn't remember my ListenBrainz token

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#412]
Just had this happen today, I'm on the latest commit eeb2060.

![image](https://user-images.githubusercontent.com/19501722/95847113-9eedeb00-0d4c-11eb-95e9-40d296d4a6ed.png)

It seems that closing Tauon makes it forget the ListenBrainz token, and then the invalid authorization error pops up once it goes to submit something again.

**Comment by Taiko2k** [comment]
Okay brushed up some of the code, try again on the latest commit.

**Comment by Bauke** [comment]
That seems to have done it, thanks! :heart:
