### ISSUE TITLE
Equalizer: first and last band broken

### ISSUE THREAD

**Issue by bellegarde-c** [Taiko2k/TauonMusicBox#414]
https://gitlab.gnome.org/World/lollypop/-/issues/2588

Found while debugging this one that the issue is also in TauonMusicBox.

This is visible while putting second band to max and changing first band.

![Capture d’écran du 2020-10-23 21-45-22](https://user-images.githubusercontent.com/57196916/97047399-32a78e80-1579-11eb-90ce-699be3093dfa.png)

Looks like you need to use nbands plugin if you want to keep a 10 band equalizer.

Thanks to Clementine devs!

**Comment by Taiko2k** [comment]
Thanks for the heads up! 

I've gone ahead and switched to using nbands as suggested (https://github.com/Taiko2k/TauonMusicBox/commit/54cadb33c9c5953571d8e8fc0c837c64b6b9b9fe), following the commits you made to Lollypop. Here's hoping I interpreted it right. It seems to be working.
