### ISSUE TITLE
Plex playback stop working

### ISSUE THREAD

**Issue by ariflukito** [Taiko2k/TauonMusicBox#419]
Hi, I'm not sure why plex playback stop working today. The progress running but there's no audio. 
I tried both AUR and flatpak version. 
There are a few minor updates on pulseaudio today but downgrading them don't seem to fix the problem.

Launching on terminal giving me this error message:

**PHaZOR**
```
Get plex stream
Writing database to disk.
pa: SRC error code 0pa: ERROR, encoding format not supported!
pa: Load file failed
```

**GStreamer**
```
Get plex stream
Writing database to disk.
Stall...
Stall...
Stall...
```
Do you have any idea why? Thank you.

**Comment by Taiko2k** [comment]
I can confirm I'm hitting this issue also.

Looking into it, I see that when the stream is requested, plex is returning error "400 Bad Request". I'm not sure why, maybe they changed something about their API, or perhaps its temporary issue.

**Comment by ariflukito** [comment]
Today it was working for first few songs. Then I tried to change to PHaZOR and it stops working again. The issue persists when I changed the audio back to Gstreamer.

**Comment by Taiko2k** [comment]
Oh wait, it is working for me.

Try check in the PLEX web UI if you can play your tracks there? (Are the files accessible?)

**Comment by ariflukito** [comment]
It's working for me as well now. I think it was the server itself that had an issue. I didn't realise it was running out of space. Sorry for the false report. Thank you for looking into it.
