### ISSUE TITLE
Can't open config file/data folder from the Menu

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#42]
Can't open config file/data folder from the Menu. Also can't open folder from context menu.
I'm using flatpak version.

**Comment by Taiko2k** [comment]
This is working for me. Maybe restart the application? Or are windows opening on a different window?

Does running these commands to open your home folder work?

Enter the sandbox shell with this:
`flatpak run -d --command=sh com.github.taiko2k.tauonmb`
then run
 `xdg-open ~/`

**Comment by Solarunit** [comment]
`flatpak run -d --command=sh com.github.taiko2k.tauonmb`
`error: runtime/org.gnome.Sdk/x86_64/3.30 not installed`

I'm using Solus.

**Comment by Taiko2k** [comment]
Oh, try it without the -d flag:
`flatpak run --command=sh com.github.taiko2k.tauonmb`

**Comment by Solarunit** [comment]
`Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.OpenURI' on object at path /org/freedesktop/portal/desktop`

**Comment by Taiko2k** [comment]
There's our issue. I'm not sure why though.

Hmm, the flatpak setup page for Solus https://flatpak.org/setup/Solus/ mentions installing this: 
`sudo eopkg install flatpak xdg-desktop-portal-gtk`

Do you have `xdg-desktop-portal-gtk` installed?

**Comment by Solarunit** [comment]
No, I've just installed flatpak 1.0.6 from the Solus Software Center.

**Comment by Solarunit** [comment]
`sudo eopkg install flatpak xdg-desktop-portal-gtk`
`The following package(s) are already installed and are not going to be installed again`

**Comment by Taiko2k** [comment]
If that doesn't work, I see there might be a package called `xdg-desktop-portal` maybe try install that?

**Comment by Solarunit** [comment]
So package xdg-desktop-portal-gtk wasn't installed.
Now everything works. Thanks!

**Comment by Taiko2k** [comment]
Glad to hear!
