### ISSUE TITLE
[Bug]  Wrong ui when hight scale

### ISSUE THREAD

**Issue by catsout** [Taiko2k/TauonMusicBox#420]
Wrong ui at setting with small width and 2.0 scale.

 <img src="https://user-images.githubusercontent.com/36527596/100195663-a2bb8280-2f32-11eb-8460-3e49855ee8f8.png" width = "600" height = "960" alt="p" align=center />

app version: 6.4.3(flatpak)

**Comment by Taiko2k** [comment]
Okay, its a bug regarding the UI scaling for those tabs. I've committed a fix for it now. This will be included in the next release of Tauon, (probably v6.4.4) whenever that will be.

**Comment by catsout** [comment]
Is it possible to support touch scroll?

**Comment by Taiko2k** [comment]
> Is it possible to support touch scroll?

Unfortunately I don't have a touchscreen to test such a feature.
