### ISSUE TITLE
[Bug] Songs incorrectly marked as not found

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#421]
# Overview

Songs that weren't available in the past (because I opened the app with my library, without connecting the internal drive that contained the music files) are still marked as unavailable, even though the drive that contains these files is now connected:

![Screenshot from 2020-11-26 08-56-38](https://user-images.githubusercontent.com/9282837/100288128-edd2a580-2fc5-11eb-97d6-aaaf09fa799b.png)

## Environment

- Ubuntu 20.04.1 LTS
- GNOME 3.36.3

**Comment by Taiko2k** [comment]
The current intended solution is to go MENU > Database > Mark Missing as Found

**Comment by dspacejs** [comment]
@Taiko2k that worked, thanks. I do think this should happen automatically, though

**Comment by Taiko2k** [comment]
>  I do think this should happen automatically, though

Yeah, having to manually click that is probably unnecessary. Ive now made it automatic and removed that option.
