### ISSUE TITLE
Tauon Doesn't Support/Recognize right click actions in Gnome?

### ISSUE THREAD

**Issue by Scotty-Trees** [Taiko2k/TauonMusicBox#423]
My apologizes, I'm not sure of the accuracy of my title, but I'm using Pop!_OS 20.04 (which uses Ubuntu 20.04 LTS as it's base) which uses Gnome 3.36.3 and I noticed in an update or two ago when you right click on Tauon in the Dock/Icon tasklist, there are options to Play/Pause, Previous Track, Next Track, etc. However, when I attempt to click these, the music does not pause, the tracks do no skip forward or backwards, the actions are basically null. I'd love to help troubleshoot or fix this issue if it's a bug. Or if possibly it is maybe a Pop!_OS bug or perhaps even a Gnome Dash to Dock extension bug I'm not so sure at the moment. As I always like to provide a screenshot, here is what I'm referring to below that doesn't seen to have any action when clicked. Let me know if there's anything I can do or run to help out. I haven't had a chance to say it in a while, but this app keeps getting better and better and it's already far surpassed what I've needed/wanted in a music app, thanks for all the hard work man!

![Screenshot from 2020-11-26 22-33-01](https://user-images.githubusercontent.com/45135187/100411591-d6340500-3037-11eb-897f-31a8b1db7e36.png)

**Comment by Taiko2k** [comment]
Don't worry its almost certainly a Tauon *related* issue. Its unfortunate the way I implemented these is kind of unreliable. I find it randomly starts working sometimes, try reboot your system maybe. 

With Tauon running, check what happens if you visit `http://localhost:7813/playpause/` in your web-browser? Does that work to play/pause, or does it return some kind of error page?

Also I assume you installed using Flatpak?

BTW I love your desktop background!

**Comment by Scotty-Trees** [comment]
Ah yes I forgot to mention it is indeed the flatpak version. Trying that link in my web browser, Vivaldi, turns up the error below. If the play/pause feature is still wonky, no worries man, it'd be nice to have for sure, but my current work flow I usually just play/pause things from the Mpris indicator button extension in my top right panel.

If you wanna check out the background, I got it from here, which has plenty of other great backgrounds as well: https://www.goodfon.com/wallpaper/2k-widescreen-background-house-home-isolated-deserted-mounta.html

![Screenshot from 2020-11-26 23-00-21](https://user-images.githubusercontent.com/45135187/100412924-9a9b3a00-303b-11eb-8fa1-7396f357fa1e.png)

**Comment by Taiko2k** [comment]
Yeah, I really need to probably overhaul how that works. Its kind of low priority for me atm though.

> If you wanna check out the background, I got it from here

Thanks, and it ultrawide too, cool!

**Comment by Scotty-Trees** [comment]
Yeah, agreed it's a low priority, but I didn't see anyone else post a bug about it, so I figured I would just put it out there in case anyone else had the issue as well. Get to it whenever you have the extra time, but I'm not gonna worry about it since Tauon still kicks ass. But if you ever do fix it, put that in the release notes so I see it ha ha

**Comment by Taiko2k** [comment]
@Scotty-Trees Ive released a new version of Tauon now. Could you tell me if this issue is still persisting with this new version? (v6.4.4)

**Comment by Scotty-Trees** [comment]
> @Scotty-Trees Ive released a new version of Tauon now. Could you tell me if this issue is still persisting with this new version? (v6.4.4)

"You son of a *****, I'm in!" (rick and morty reference, couldn't help myself, lol)
I was planning on Friday to do the general update of my system for Pop!/Flatpak, etc, but this is as good a time as any! I'll do an update shortly and get back to you within an hours time or less. Fingers crossed it works as intended!

**Comment by Scotty-Trees** [comment]
Ok, just did an update and a restart and tested out the Play/Pause, Previous/Next options under Phazor and..............IT WORKS! Good well done my dude! Even fades the way I'm used to now when I pause it which is definitely a nice touch too. Thank you kindly for this wonderful update!

**Comment by Taiko2k** [comment]
Okay cool! Did turn out do just be a silly mistake on my part.

Fyi the fades are a feature of Phazor. Its one of the reasons I built it, cause I liked those fades too.

**Comment by Scotty-Trees** [comment]
No worries man, silly mistakes will always happen to us. Cheers for fixing yours very quickly. And I look forward to the next update in the future :)
