### ISSUE TITLE
Player window is blinking on the first boot.

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#43]
Player window is blinking about 5-10 sec on the first boot.
Tauon flatpak version, Solus.

**Comment by Taiko2k** [comment]
Just once, or continuously? Also what colour does it blink to? Also, is it a hard blink or a fade?

**Comment by Solarunit** [comment]
Content of the window is fading. I will try to record it.

**Comment by Taiko2k** [comment]
Is it briefly fading to black? If so I think I might have an idea of what it is

**Comment by Solarunit** [comment]
Here it is: 

![alt text](https://ibin.co/4WUPQYIA7dFk.gif)

**Comment by Taiko2k** [comment]
Ah yes I'm pretty sure this is the fader animation (the once when you click settings) is malfunctioning. I'm not sure *why* it only sometimes occurs, something to do with the frame timings I think. I've tried a fix, heres the current dev version if you want to test:

https://github.com/Taiko2k/TauonMusicBox/releases/download/v3.5.3/tauon3.6.X1.flatpak

**Comment by Solarunit** [comment]
How to install it side-by-side with current version?

**Comment by Taiko2k** [comment]
Just overwrite. It should be safe. And you can downgrade if it doen't work.

**Comment by Solarunit** [comment]
There is no blinking after 1 reboot.

**Comment by Taiko2k** [comment]
Seems like its fixed then (btw I found theres a bug in tauon3.6.X1 that causes it to crash when making new playlist, you might want install the previous stable version)
