### ISSUE TITLE
[Feature Request] Stream Jellyfin Music

### ISSUE THREAD

**Issue by RealStickman** [Taiko2k/TauonMusicBox#430]
My search on how to use the API for Jellyfin yielded the following results:  
[Reddit Thread about the similarities/differences to Emby API](https://old.reddit.com/r/jellyfin/comments/g3ksve/jellyfin_api_full_documentation/)  
[Python API client mentioned in the above thread](https://github.com/iwalton3/jellyfin-apiclient-python/blob/master/jellyfin_apiclient_python/api.py)  
[Jellyfin terminal Music player mentioned](https://github.com/tryffel/jellycli)  

Much of the API is apparently still the same as Emby, so [this](http://swagger.emby.media/?staticview=true) should apply for the most part. One exception is Authentication, mentioned in the reddit thread above.

**Comment by Taiko2k** [comment]
Ive created a new branch `jellyfin` and prepared the UI side for it.

Perhaps someone who knows Python, client API programming and who has a Jellyfin server for testing could finish off the API side. I haven't got time right now to do so.

If someone wants to do this... 

## Contributing guide

To get started, see the file `t_modules/t_jellyfin.py` (in the `jellyfin` branch) and fill in the function prototypes there. Ive already got the necessary code in place so that there *shouldn't* (read probably will be but lets hope not) be any need to dive further into Tauon's internal spaghetti code.

#### Rules
 - Code must be your own, no copy and paste from others code.
 - Don't introduce any new dependencies. Though you can use the existing `requests` and `json` for example.

**Comment by Taiko2k** [comment]
I've merged @ritlew's PR for this into master. Feel free to test and report if its working as expected.

**Comment by ritlew** [comment]
One thing I forgot to mention that during the import there is no feedback for the user (unlike airsonic). Is there capability to add that? Right now it retrieves the library information and sorts and processes it which took a few seconds for my library

**Comment by Taiko2k** [comment]
> during the import there is no feedback for the user

Right, I forgot to add that, should be fixed now.

BTW I've noticed that the *headers* that include the access token aren't used in the function `resolve_stream`. Can the stream be accessed without the token?

**Comment by ritlew** [comment]
Uhh.... it looks like my jellyfin allows me to stream music without being authenticated... I'm not sure if that's some sort of configuration or....

**Comment by ritlew** [comment]
lol https://github.com/jellyfin/jellyfin/issues/1501
> This is an issue that was inherited from emby. The streams will take a session parameter, but it is not required. So it is possible for users to stream without authorization.

**Comment by Taiko2k** [comment]
Its fine as it is for now then. Needing to add header support for stream URL's in Tauon is a small nuisance, but that can be addressed in the future if needed.

**Comment by RealStickman** [comment]
I noticed the Album cover does not load for music imported from jellyfin. It throws this error.
```
Jellyfin album art api error: 404 Error processing request.
IMAGE NETWORK LOAD ERROR
```

**Comment by Taiko2k** [comment]
> I noticed the Album cover does not load for music imported from jellyfin. It throws this error.

@ritlew any idea on what the issue could be here? I assume cover art is working for you?

**Comment by ritlew** [comment]
![image](https://user-images.githubusercontent.com/16658359/105270727-46589600-5b64-11eb-8548-b42e006b9345.png)
yep

**Comment by ritlew** [comment]
@RealStickman can you post version info about your jellyfin instance?

**Comment by RealStickman** [comment]
I'm using Jellyfin 10.6.4.  
The Albums with a cover should all have a cover.jpg in their folders and some also have it embedded in the music files. Jellyfin Web does show the images.

**Comment by ritlew** [comment]
No idea what the problem could be other than a malformed URL since it is 404ing. Though it could be a buggy api too, I wouldn't put it past a Frankenstein's monster like jellyfin

**Comment by Taiko2k** [comment]
I've given this a test myself now. I see what you mean with the seeking being weird with Phazor. Ive made a tweak that seems to solve it. Also its working fine for me with GStreamer.

As for the album art, I'm getting a similar but different error:

```
Jellyfin album art api error: 404 "<track title> does not have an image of type Primary"
```

Even though album art is showing in the web UI. It is recognising the name of the tracks so I don't think the URL is malformed in this case.

I'm testing with Jellyfin 10.7.0 rc2

**Comment by ritlew** [comment]
Hmm all of my music had album art as the primary image, which I thought made sense. I didn't look much into it since it was hard to find information and album art being the primary image makes intuitive sense

**Comment by Taiko2k** [comment]
Ive found a solution for the album art for me by using `AlbumId` as the ID for the artwork rather than the track ID. Ive committed this change now.

**Comment by ritlew** [comment]
Works for me

**Comment by RealStickman** [comment]
Works for me as well

**Comment by RealStickman** [comment]
I noticed that sometimes the playback stops after the first second or so. This can happen when I deliberately click a file or also when the song automatically starts in a playlist. The issue seems to be related to big files, as I only had that problem with my FLAC files so far.  
This is what is shown in the terminal when this problem occurs. Local playback of the same files does not have any issues.
```
pa: Samplerate detection warning.
pa: End of stream
pa: Buffer ran out at end of track
```

One semi-reliable way of getting the track to play was selecting a different track and then selecting the original track again. Though that comes with its own problems as sometimes the other track will stay selected, while playing the original track. Not sure if this is specific to streaming from jellyfin.
![tauon_interface_wrong_track](https://user-images.githubusercontent.com/61015582/105491467-9b0c2600-5cb6-11eb-9631-127869401a37.png)

**Comment by Taiko2k** [comment]
@RealStickman This is likely related to having a slow connection. I assume your server is over the internet? There is some improvement needed to be done here. In the mean time, if you find it to be annoying you may have better luck switching the backend to GStreamer.

**Comment by ritlew** [comment]
I also don't find phazor very reliable

**Comment by RealStickman** [comment]
@Taiko2k Works perfectly fine with GStreamer

**Comment by Taiko2k** [comment]
This is now in a release version, so ill close this now, but feel free to comment further if you run into more problems.

The issues with Phazor are noted. I can't replicate the issues myself so I can't give an immediate hack-fix, but improving its reliability is a long term goal.

**Comment by mannp** [comment]
Hey, thanks for the adding of Jellyfin support 👍🏻 

I am struggling to know if its actually connected to my library and wondered if there was a possibility of adding a test connection button like some of the other services have? :)

As mentioned above there is no feedback on progress of a successful connection so its hard to tell what is going on.

At the moment it appears to have accepted my details and shows 'Accessing JELLYFIN library...' so can I assume that the login details and url are correct and it is scanning my library, as its taking a good while.

I wondered if it was possible to stop and restart the scan if the login or url details are changed? As there is no way I can see to stop a scan :)

Just some feedback and thanks again for the addition.

Going to check the logs to see what is happening.... :)

**Comment by Taiko2k** [comment]
@mannp Okay I've committed a new test button for Jellyfin. 

A progress counter shouldn't be necessary as the import shouldn't take too long. If it seems to be taking forever I assume something went wrong and it stalled. 

I've also improved the error handling now so it should be less likely to stall without giving an error.

**Comment by mannp** [comment]
@Taiko2k many thanks for your changes, I will pull the master branch again tomorrow and give it a try 😃

**Comment by mannp** [comment]
``Applying theme: Sky
Auto save playtime
Traceback (most recent call last):
  File "/home/local/Builds/TauonMusicBox/tauon.py", line 42200, in <module>
    pref_box.render()
  File "/home/local/Builds/TauonMusicBox/tauon.py", line 27350, in render
    self.tabs[self.tab_active][1](x + side_width, y + header_width, content_width, content_height)
  File "/home/local/Builds/TauonMusicBox/tauon.py", line 25821, in last_fm_box
    jellyfin.test()
  File "/home/local/Builds/TauonMusicBox/t_modules/t_jellyfin.py", line 80, in test
    self._authenticate(debug=True)
  File "/home/local/Builds/TauonMusicBox/t_modules/t_jellyfin.py", line 67, in _authenticate
    info = response.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Taiko2k** [comment]
Maybe we're getting something other than json there. Could you try edit the file t_modules/t_jellyfin.py @ line 67, above the line `info = response.json()` insert a line: `print(response.text())` and try again, see what's printed to the terminal.

**Comment by mannp** [comment]
I get this after adding the print ...

```
Traceback (most recent call last):
  File "/home/local/Builds/TauonMusicBox/tauon.py", line 42200, in <module>
    pref_box.render()
  File "/home/local/Builds/TauonMusicBox/tauon.py", line 27350, in render
    self.tabs[self.tab_active][1](x + side_width, y + header_width, content_width, content_height)
  File "/home/local/Builds/TauonMusicBox/tauon.py", line 25821, in last_fm_box
    jellyfin.test()
  File "/home/local/Builds/TauonMusicBox/t_modules/t_jellyfin.py", line 81, in test
    self._authenticate(debug=True)
  File "/home/local/Builds/TauonMusicBox/t_modules/t_jellyfin.py", line 67, in _authenticate
    print(response.text())
TypeError: 'str' object is not callable
```

**Comment by ritlew** [comment]
What version of jellyfin are you using?

**Comment by mannp** [comment]
> What version of jellyfin are you using?

Version: 10.7.0

Operating System: Linux

Architecture: X64

**Comment by ritlew** [comment]
I actually see some changes to the API on 10.7.0-rc1. I'll investigate later when I have time

**Comment by mannp** [comment]
> I actually see some changes to the API on 10.7.0-rc1. I'll investigate later when I have time

Thanks :) what is the latest version currently supported by your addition?

**Comment by ritlew** [comment]
We did testing on 10.6.4

**Comment by Taiko2k** [comment]
I tested on 10.7.0 rc2 which worked. Seems to me this could be a configuration issue of some sort.

**Comment by ritlew** [comment]
I'm confused how a post request to the auth endpoint is returning the app HTML

**Comment by mannp** [comment]
> I tested on 10.7.0 rc2 which worked. Seems to me this could be a configuration issue of some sort.

Anything particular in mind? I am not sure what there is to configure.

I note I have Easy Pin Code enabled in my profile but not sure what else could be different.

**Comment by Taiko2k** [comment]
I don't really have much of a clue. Maybe its how the docker is configured.

Do you know if other Jellyfin clients are working?

**Comment by mannp** [comment]
> Do you know if other Jellyfin clients are working?

The android one is working fine, I log in that using the Easy Pin Code, as my password is 50 chars.
