### ISSUE TITLE
[Feature] Reorder playlist by drag & drop

### ISSUE THREAD

**Issue by GLLM** [Taiko2k/TauonMusicBox#432]
HI !

I'd like to to able to reorder my playlists by selecting one or more files and move them around in the playlist (and not having to deal with the nice but cumbersome Generator (which additionally seems to impact all playlists at once)

Using 6.4.4.

Thanks
GLLM

**Comment by Taiko2k** [comment]
You can drag to re-arrange tracks in the tracklist. Just if you're wanting to drag a single track you need to hold down the shift key.

**Comment by GLLM** [comment]
Oh, yes, when holding SHIFT, it does work.*
Very sorry about this.
I'm closing the issue :)
