### ISSUE TITLE
Starting Tauon again after it's minimized to tray should open it again

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#438]
At the moment, when Tauon is minimized to the tray, if I try to run it again it will stop and tell me it's already running. Instead, I was expecting Tauon to un-minimize and open itself. Any chance this could be added?

**Comment by Taiko2k** [comment]
Okay, I've committed this behavior now

**Comment by Bauke** [comment]
Awesome, thanks so much! :D
