### ISSUE TITLE
Tauon no longer working after Python update

### ISSUE THREAD

**Issue by deafwhippin** [Taiko2k/TauonMusicBox#439]
I recently updated to the new 5.10 Kernel and it seems to have broken a few things, but all of them have been fixed after reinstalling except for Tauon. I've completely uninstalled and reinstalled the program from the AUR and while tauonmb.sh attempts to start according to my task manager it immediately closes out.

Trying to run tauon.py directly from terminal using python results in this output:
```
Tauon Music Box v6.4.6
Copyright 2015-2020 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/lich/.local/share/TauonMusicBox
Found XDG-Downloads: /home/lich/Downloads
Found XDG-Music: /home/lich/Music
Install directory: /opt/tauon-music-box
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 399, in <module>
    from sdl2 import *
ModuleNotFoundError: No module named 'sdl2'
```

I have sdl2 installed, am I missing something? Is there a log that I could reference to help? Thanks!

**Comment by Taiko2k** [comment]
Its caused by the update from Python v3.8 > 3.9. You just need to rebuild any AUR python packages. The main ones for Tauon are: `python-pysdl2 python-hsaudiotag3k python-stagger python-pylyrics python-isounidecode python-pulse-control`.

**Comment by deafwhippin** [comment]
That worked! Thank you so much!

**Comment by Whayme** [comment]
You can use [rebuild-detector](https://aur.archlinux.org/packages/rebuild-detector/) to generate a list of all the packages that need it.
