### ISSUE TITLE
Minimizing Tauon to tray before playing a song makes the tray menu items not work

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#441]
Came across this just now, after launching Tauon I minimized it to tray without starting a song. I then went to the tray menu and clicked on Open but it didn't work. Then I tried the other menu items and none of them worked either. Eventually I ended up having `SIGKILL` Tauon to get it to close. If I play a song and then minimize, everything works fine.

**Comment by Taiko2k** [comment]
Are you sure you can replicate that behavior consistently? I don't imagine playback would affect the tray like that.

What desktop environment / extention are you using? I find that its only really worked reliably with GNOME + "AppIndicator and KStatusNotiferIem Support".

**Comment by Bauke** [comment]
Seems pretty consistent, with some testing I also noticed that the tray items don't even work without minimizing to tray. For some reason only after I start a song. I'm using a 5-day-old-ish Xubuntu 20.04 install so whatever the defaults are for that. [Here's a video][1] of the issue.

[1]: https://streamable.com/99vm0r

**Comment by Taiko2k** [comment]
Huh that's weird. I can't think of any solution though. I think it comes down to the state of trays on Linux really.

**Comment by Bauke** [comment]
Ah, no problem then. I'll just remember to not minimize before playing a song. :P
