### ISSUE TITLE
Audio sometimes garbled on playback resume [Phazor]

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/TauonMusicBox#443]
If you encounter this issue, could you please reply with the name of the distro you use and method of Tauon install (AUR, Snap, Flatpak, etc)

**Comment by minecrafter37224521** [comment]
I had audio garble for me once a while ago, haven't had the issue again but I'm on Pop OS 20.10 with Flatpak Tauon.

**Comment by Taiko2k** [comment]
I'm 95% sure this was a pipewire bug that has been fixed now.
