### ISSUE TITLE
[Bug] Wrong URL shown when playing radio

### ISSUE THREAD

**Issue by GLLM** [Taiko2k/TauonMusicBox#444]
Hi @Taiko2k,

currently playing some radio in TauonMusic (fingers crossed for #380 btw, as the way radios are accessed/seen is cumbersome).

The shown URL is wrong
![image](https://user-images.githubusercontent.com/3989573/104090279-0ea14280-5276-11eb-8cbe-c06357a20c52.png)
It should have been :
http://fr.ah.fm:8000/192k#AH.fm

THanks
GLLM

**Comment by Taiko2k** [comment]
Okay, I've committed a fix for this now.

**Comment by GLLM** [comment]
I'll check at the next upgrade, and will close if all is OK !
Thanks @Taiko2k !

**Comment by GLLM** [comment]
It's working, thanks
