### ISSUE TITLE
Add a toggle play/pause to the remote control API

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#448]
I've been playing around a bit with the remote control API and like what it's capable of so far, though I wish there was a route that toggled playing. Right now if you call `/play` and a song is playing, it just keeps going (which makes sense). I'd love a route like `/play_toggle` that when a song is playing it pauses and when paused it starts playing. At the moment I have 2 keyboard shortcuts that just `curl` the API to play and pause, and having a way to toggle with just one would be amazing.

**Comment by Taiko2k** [comment]
There is another hidden interface only available for the local machine that has this. You can use `curl http://localhost:7813/playpause/`

**Comment by Bauke** [comment]
Ohh awesome, that works!
