### ISSUE TITLE
Audio glitching and window blinking first start after reboot

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#45]
Song playing only few seconds after first starting player (after system boot) and then the next song starting playing, I think it is related to https://github.com/Taiko2k/TauonMusicBox/issues/43

tauon3.6.X1, Solus.

**Comment by Taiko2k** [comment]
I can't seem to replicate this.

One reason it might skip is if there is a long IO delay... though, I guess it doesn't make sense it would play the first few seconds. 

Still, if it only does it after a full system reboot, that leads me to believe the issue is external of nature.

**Comment by Solarunit** [comment]
> Still, if it only does it after a full system reboot, that leads me to believe the issue is external of nature (or a local bug caused by an external factor)

Yes, I launch player right after the boot. Song is playing ~10 sec, then some glitch happening and the next song starting playing.

**Comment by Taiko2k** [comment]
As an experiment, does it still do it if you access the file in another application first?

**Comment by Solarunit** [comment]
I will try another player next time.

**Comment by Solarunit** [comment]
I've tried deadbeef - no problem.

**Update** about the issue: 
1. first song is playing ~10 sec
2. glitch happening
3. second song starting playing without a sound ~5 sec
4. glitch happening
5. second song starting playing again with sound

**Comment by Taiko2k** [comment]
Is your music on an additional/external HDD? Or is it on your home/system drive?

**Comment by Solarunit** [comment]
It is on an internal HDD. I will check when music is on the system SSD today.

**Comment by Solarunit** [comment]
Same problem with system SSD.

**Comment by Solarunit** [comment]
Just tested on another PC.
So it is definitely related to https://github.com/Taiko2k/TauonMusicBox/issues/43
Player window is starting blinking and it affects the song.

**Comment by Taiko2k** [comment]
I wonder, does it still do it with the visualizer disabled?

But anyway, yes it does seem to be distribution / driver related in some way.

**Comment by Solarunit** [comment]
visualizer is disabled

**Comment by Solarunit** [comment]
**update**

PC with intel GPU
Tauon 3.8.1

Window is blinking ~1 min (starting around 20 sec). And top and bottom yellow indicators (top/end of the palylist) are also blinking. 
No problem with audio.
**Mini mode is not affected.**

**Comment by Taiko2k** [comment]
Quite strange. These animations work on timers, so what I suspect is happening is that the function that gives the current clock time `time.time()` is returning inconsistent values somehow, almost as if the system clock is changing. That could cause the timers to give negative values which would cause those animations to cycle. 

(Until the time difference is made up, so... the system clock jumped back 1 minute?)

Hmm, I could try harden the animation timers against this. But I don't know why the clock could be changing in the first place though.

**Comment by Solarunit** [comment]
> Quite strange.

Yeah. 
So top and bottom animations are blinking at the same time. Like this:

![alt text](https://ibin.co/4aD2Cz5jC1gl.gif)

**Comment by Taiko2k** [comment]
Yes, I'm able to replicate that by setting a negative time value, I expect the monotonic time function will fix it.

**Comment by Solarunit** [comment]
Interesting, that I can't reproduce this bug now on another PC with Nvidia GPU.

**Comment by Taiko2k** [comment]
I think for some reason, on the first PC, something is changing the system clock.

**Comment by Solarunit** [comment]
> Edit: But maybe that's normal? Anyway, it was a bug in the way Tauon created timers, it should have been able to handle that.

Well i had this bug on both PCs but symptoms were slightly different.

**Comment by Solarunit** [comment]
Looks like the bug is fixed! :tada: 
Thanks! :notes:
