### ISSUE TITLE
High CPU use when clicking/tapping

### ISSUE THREAD

**Issue by AngusP** [Taiko2k/TauonMusicBox#454]
Hi, noticed that if I tap my trackpad quickly anywhere in the Tauon window it's enough to use 100% on a single CPU core. Not playing or running any background tasks (I've just installed). I've checked with a mouse and either I can't click fast enough or a mouse is fine (weird, huh?!). Using an Apple Magic trackpad over USB, but I'd guess it'd be the same for a laptop trackpad or a touchscreen?

Thought I'd mention it, it's not a serious issue but might hint at a problem somewhere in event handling? I don't get any CPU behaviour like this tapping rapidly in Firefox or other app.

Happy to provide further details, I'm running Fedora 33 Silverblue on a Ryzen 5600X

**Comment by Taiko2k** [comment]
Yep I'm aware of this quirk. Dealing with this hadn't been a priority due to its innocuous nature, but now that you bring the issue up I'll try get around to addressing it.

**Comment by Taiko2k** [comment]
Okay this should be fixed now in the new release (v6.4.9)
