### ISSUE TITLE
[Feature Request] Change playlist position from oldest to latest album by clicking on the artist again

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#457]
I have a lot of artists with 20+ albums. It'd be great if I were able to change the playlist position from the oldest album to the latest album by clicking again on the artist in the artist list view.

Same artist:
1st click: Show oldest album.
2nd click: Show latest album. (Not a double click which starts playback.)
3rd click: Show oldest album.

**Comment by Taiko2k** [comment]
Subsequent clicks already has the intendef function of jumping to the next block instance of that artist. Which is why you see that behaviour when there is another album in between.

**Comment by StrangeSeasOfThought** [comment]
> Subsequent clicks already has the intended function of jumping to the next block instance of that artist. Which is why you see that behaviour when there is another album in between.

Right, but I'm talking about the main library where all albums by the same artist are usually one block.

**Comment by Taiko2k** [comment]
Hmm. I kind of see your use case now, but I don't see that your described behaviour makes sense for general use over the current behavior. 😕

**Comment by StrangeSeasOfThought** [comment]
> Hmm. I kind of see your use case now, but I don't see that your described behaviour makes sense for general use over the current behavior.

Any chance for something like this mockup:

![artist](https://user-images.githubusercontent.com/43582772/107033871-3375d080-67b6-11eb-80df-3d421848ed5d.jpg)

The album count is only going to grow larger in the future. It takes me already 16+ seconds for some artists to scroll from the oldest to the latest release...
