### ISSUE TITLE
After v6.4.9 flatpak update, songs randomly freeze for about a second

### ISSUE THREAD

**Issue by Scotty-Trees** [Taiko2k/TauonMusicBox#458]
Greetings,

Been using and loving your application since I first discovered it and do so on the daily so thank you very much for your continued work! Now with the pleasantries out of the way on to the business. So things "appear" to be a buggy at the moment. I say appear because I'm honestly not sure at the moment what might be the root cause of this.There could be more than one factor here, but to add I am on PopOS! running Gnome 3.36.8, and the systems flatpak was recently updated this week to 1.8.5 right before your application was updated to v6.4.9. Not sure if that's relevant or coincidental, but before these updates I didn't have the current problem, which is songs will randomly freeze for about a second and then continue playing on. It has happened a handful of times already this week and I use my system in the same way each day i.e. not a demanding workload. Sometimes when the freeze happens for a second, my CPU will spike to 100% in System Monitor, and hang my system for about a second or two. Other times, when the music freezes, I see no CPU spike at all, and my system remains responsive the whole time, which is a bit odd to have no indication of any issue. I've tested some music on both PHAZOR and GStreamer and the second or so freeze of audio does occur on both. PopOS! recently updated their kernels to 5.8.0-7642-generic as well as the nvidia drivers that I use from 455 to 460.39, so it would honestly not surprise me if there is some underlying bug in the kernel or nvidia drivers. Truthfully as of writing this I want to blame the nvidia drivers. Sadly, I can't accurately reproduce this, it may happen once in the day, not at all, or say 2-5 times in the day. I'm gonna try to use Rhythmbox (not a flatpak app) for the next day or two or so to see if that freezes at all as well or not, then I can safely assume if it's more an issue of my system than Tauon, but I thought at the very least I'd mention it here for now in case I may not be the only one.

**Comment by Taiko2k** [comment]
That does sound concerning. Good you already tested both backends cause that would have been the first thing I'd ask. Since you say it happens on both, that would lead me to guess it's an underlying system issue rather than a bug in Tauon.

Will be interesting to see if you say it happens still with other players.

**Comment by Scotty-Trees** [comment]
If you wouldn't mind leaving this issue open for a while (maybe a week or two) I'd probably have a better understanding. In the past, any sort of freezes have usually been from the kernel or nvidia. But if it does happen on Rhythmbox, I'll test out maybe one more player just to make certain. More than likely you can probably ignore this issue, but like I mentioned, just wanted to bring it to attention in case I wasn't perhaps the only one. Gonna miss using Tauon for the next couple of days, but it's a sacrifice to help out :)

**Comment by Scotty-Trees** [comment]
Well, it's been about two weeks and this issue has only happen twice since then. Randomly happened on Rhythmbox as well, so I can't say the problem is with Tauon, it might been something to do with something else, but I haven't narrowed it down. With any luck, maybe it just doesn't happen to be as often if I'm lucky enough!

But in the mean time, if you wouldn't mind you can go away and close this issue. If I ever end up do finding out 100% what's wrong and it's related I'll let you know. Until then, keep making this awesome player even better each release! :)

**Comment by Taiko2k** [comment]
I'm glad to hear! ... Well, that the bug I'd unlikely Tauon, not that you're still having the issue of course.

Are you using a mechanical HDD? If so, perhaps its failing or being bottlenecked somehow. I'm not sure. Its not an issue I've experienced myself. Maybe try unplug any unnecessary devices and see if it still happens... Though as you've said it happens rarely, makes its difficult to narrow down.

I hope you're able to get it sorted somehow!

**Comment by Scotty-Trees** [comment]
SSD drive actually. I've had various stages of freezing on other distros in KDE Plasma as well, but I could never pin it down to anything other than it either being the linux kernel or the nvidia drivers since I have a hybrid graphics card for my laptop. Generally PopOS 20.04 doesn't freeze and I don't overload my laptop outside of a few Vivaldi tabs and some music or podcast playing. So I think I'll just have to chalk it up to one of those more than likely culprits for now. It might only happen like once a month, once a week, so it's difficult to constantly have htop open and recording to see the issue, but I shall digress for now! Thanks again for the quick responses and keep up the great work my dude.
