### ISSUE TITLE
[Feature Request] Add support for tracker music (.xm, .mod, s3m, etc.)

### ISSUE THREAD

**Issue by rtomasa** [Taiko2k/TauonMusicBox#463]
So that's it, all music players in Linux capable from playing tracker music are very old and/or difficult to install. It would be super to add support for these files.

**Comment by Taiko2k** [comment]
Okay, I've committed this feature now.

This adds support for the following file types: **XM**, **MOD**, **IT**, **S3M** and **MPTM**. It will be included in the now upcoming Tauon release v6.5.0.

Just a note, once you upgrade, make sure you have "PHAzOR" selected under the audio settings of Tauon for the best quality. (While Tauon will attempt to play tracker files using GStreamer if selected, it is somewhat unreliable.)

**Comment by rtomasa** [comment]
Super!!! Yes, I always have PHAzOR selected and not really interested in network server, so at least for me this is more than enough. Thanks a lot for this super quick update!

**Comment by Taiko2k** [comment]
Okay this is live now
