### ISSUE TITLE
Sort by Album Name

### ISSUE THREAD

**Issue by Sonico98** [Taiko2k/TauonMusicBox#464]
Pretty much the same way we can sort albums on PLEX or most music players. Being able to import the whole music folder and automatically sort everything by Album Name would make things a bit less confusing. Right now trying to browse my files using the gallery view doesn't make much sense, it feels like everything is randomly ordered, specially when trying to find a series of albums (Example Vol.1, Example Vol.2, Example Vol.3, etc).

**Comment by Taiko2k** [comment]
Well, sorting purely by album alphabetically would shuffle the artists which is also kind of random. Never mind that though. I've looked into it more and found its possible to access the source track file path, and sorting by path would be ideal. From there the user can sort to whatever using the existing methods. So I've gone ahead and committed this change.

So yeah, it was kind of random before, but this should be fixed now.

Just, once you upgrade, you will need to click "Import music to playlist" again under Tauon's PLEX settings again to see this change applied.

**Comment by Sonico98** [comment]
That was fast! I didn't want to reply until I could try it out, and it's perfect now, thanks for your work! Guess this can be closed now.
