### ISSUE TITLE
Make "Search Track on Genius" actually use the Genius search

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#465]
At the moment when you try to "Search Track on Genius" for a song, Tauon tries to guess the URL (as far as I can tell) for the Genius page with mixed results. If it's just a singular artist and a simple title it usually guesses correctly. But with featured or multiple artists, or remixes, more often than not does it guess incorrectly. So when you do get an incorrect guess, you have to use the search bar anyway.

My suggestion is to use Genius' search instead. `https://genius.com/search?q=text%20here`

If you wanted to get fancy, another option would be to combine both ways here and make it conditional depending on the HTTP status of Genius. Before opening the page in the browser, Tauon could make a HEAD request to Genius and then if it returns a 404, use `/search?q=`.

**Comment by Taiko2k** [comment]
Okay I've made the *fancy* change you described. It should be in the new release of Tauon now.
