### ISSUE TITLE
Package size should be minimized

### ISSUE THREAD

**Issue by tommyalatalo** [Taiko2k/TauonMusicBox#466]
I just installed the application on Arch and noticed that the Noto fonts included seem to be adding roughly 250mb to the package. Would it be possible in the future to not use these huge font packages as to slim down the application package? 
It seems quite excessive that a music player installation size is 650mb in total?

**Comment by Taiko2k** [comment]
Tauon's UI is specifically designed around Noto fonts, so they are pretty much mandatory. However, I see that I have noto-fonts-cjk as a required dependency but that's probably really doesn't need to be required, so I've gone ahead and set that as an optional dependency, replacing it with the standard noto-fonts package. This shaves around 200mb off the minimum install size.

Ive also taken a look at the Flatpak, and seen some unnecessary files were being included, so I've shaved about ~100mb off that as well.

**Comment by tommyalatalo** [comment]
All of that sounds really good, does this mean that these updates will be in a coming in a future release, resulting in a significantly smaller package?

**Comment by Taiko2k** [comment]
I've already updated the AUR release version now. After you update you can run `sudo pacman -R noto-fonts-cjk` to claim back some space.

As for the Flatpak version, the install size now totals 70mb, it will be published within a few hours.

**Comment by tommyalatalo** [comment]
Damn, that was fast! Thanks for giving me back some of that disk space :+1:

**Comment by Taiko2k** [comment]
Oh boy I see that `noto-fonts-extra` is also taking up 340mb install space. Unfortunately that package has some specific font styles that are used in some places in the UI. Its unfortunate the way Arch Linux has chosen to split these files. Alas there's nothing to do about that.

If you're desperate for space, what you could do is edit the PKGBUILD yourself and remove the line `'noto-fonts-extra'` from the depends list. Then you can remove that package and free up a further 340mb. You might not even notice the difference. (You'd just need to make that edit every time you update)

**Comment by tommyalatalo** [comment]
I'm not exactly at a loss for disk space, but those font packages struck me as bizarre in size. Is there no way to update the package build to cherry-pick the fonts that are needed from some other source online perhaps?

**Comment by Taiko2k** [comment]
> Is there no way to update the package build to cherry-pick the fonts that are needed from some other source online perhaps?

That's what the flathub build script does. But for a system package I'd need to programmatically change where it looks for font files otherwise it would conflict with the actual font package, which is messy and kind of a hassle to work around. Easier to just live with the large package dependency.
