### ISSUE TITLE
Spotify authorization not working

### ISSUE THREAD

**Issue by tommyalatalo** [Taiko2k/TauonMusicBox#467]
After setting the `Client ID` and `Client Secret` for Spotify, pressing the `Authorise` button ends up with a broken link to a blank page that says `INVALID_CLIENT: Invalid redirect URI`

**Comment by Taiko2k** [comment]
Hmm. Did you make sure to do the step where you enter the redirect URL in the Spotify dashboard?

**Comment by tommyalatalo** [comment]
What is the redirect URL I should enter into the Spotify dashboard, does Tauon supply that somewhere? 
I tried adding the URL from the failed authorization, but that's clearly not it as it's not working.

**Comment by Taiko2k** [comment]
Click the ? box next to where you enter the key in Tauon. Follow the URL it gives. That should take you to the instructions.

**Comment by Taiko2k** [comment]
Okay, I've pushed an update now that eliminates the need for the user to generate API keys. This makes the setup process much simpler. You'll just need to press the "Authorise" button once again after updating.

**Comment by Taiko2k** [comment]
After some consideration, its probably more suitable for the user to provide their own client ID. So I've reverted that and changed the button layout to be more explicit about where to find instructions.
