### ISSUE TITLE
LyricWiki parsing for instrumental songs is broken

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#47]
![image](https://user-images.githubusercontent.com/1641362/52622176-717ed900-2ea9-11e9-9aa2-467a836513fa.png)

Looks like the parsing doesn't expect "{{instrumental}}" in there.

http://lyrics.wikia.com/api.php?action=query&prop=revisions&rvprop=content&format=xml&titles=Dead_Astronauts:Roam

**Comment by Taiko2k** [comment]
The library used is https://github.com/geekpradd/PyLyrics

Unfortunately, it doesn't seem like this is actively maintained anymore. But I can add a workaround on this end, might be easier.
