### ISSUE TITLE
Folder navigator auto-update

### ISSUE THREAD

**Issue by inalone** [Taiko2k/TauonMusicBox#472]
Hi,

It seems that the folder navigator seems to work on an "on-demand" basis, I was wondering if it were possible to implement an auto-update feature for this.

**Comment by Taiko2k** [comment]
I've now committed a fix specifically in regards to it not reloading on a playlist "regenerate" as you mentioned in the Discord channel. Other scenarios need to be fixed on a case by case basis.

**Comment by inalone** [comment]
much appreciated :)
