### ISSUE TITLE
Can't pause a song after starting and can't play another song

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#473]
When I start a song I can't pause it at all. I tried using space bar, media keys, using pause option in the tray icon and clicking the pause button on Tauon. When I do all those actions, the pause button toggles between on and off state and MPRIS registers the pause/play signal. The progress bar does not update with the song, and I can't jump to another song. Clicking on the progress bar to move jump to different sections of the song does nothing. When I try to change the song, everything updates except the audio and progress bar. The volume bar is not working either, I can adjust the levels, but the volume does not change with it.
I am running the git version on Arco Linux. Here is the terminal output:
```python3
(tauon.py:181599): Gdk-CRITICAL **: 11:59:42.239: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Applying theme: Neon Love
Auto save playtime
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ted/Projects/TauonMusicBox/t_modules/t_phazor.py", line 514, in player4
    r = aud.get_result()
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/ted/Projects/TauonMusicBox/lib/libphazor.so: undefined symbol: get_result

```

At the end of a song, it doesn't go to the next song, but gives this output:
```
pa: End of stream
pa: Buffer ran out at end of track
```

**Comment by Taiko2k** [comment]
Because you're running the git version and changes have been made to phazor, you need to manually recompile it. Just run `bash compile-phazor.sh`

**Comment by keystroke3** [comment]
Running `bash compile-phazor.sh` gives:
``` bash
Package libopenmpt was not found in the pkg-config search path.
Perhaps you should add the directory containing `libopenmpt.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libopenmpt', required by 'virtual:world', not found
In file included from src/phazor/phazor.c:32:
/usr/include/opus/opusfile.h:110:11: fatal error: opus_multistream.h: No such file or directory
  110 | # include <opus_multistream.h>
      |           ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
mv: cannot stat 'libphazor.so': No such file or directory
```

**Comment by Taiko2k** [comment]
Theres a new dependency needed. On Arch its `libopenmpt` <sup>(AUR)</sup>.

**Comment by keystroke3** [comment]
Ah, yes. It works now. Do I need to rebuild phazor every time I git pull?

**Comment by Taiko2k** [comment]
> Do I need to rebuild phazor every time I git pull?

Not necessarily, but you would if changes are made to it. You could rebuild every time for good practice, or just wait until you run into any problems.

**Comment by keystroke3** [comment]
Ok, great! Thanks. Take care of yourself, don't strain yourself and hands too much.
