### ISSUE TITLE
Continous lyric display through songs

### ISSUE THREAD

**Issue by inalone** [Taiko2k/TauonMusicBox#478]
Hi,

When I'm listening to an album for the first time I quite like to have the lyrics up - at the moment, I have to right click and search for lyrics on each song and would like a way to make this happen without me having to manually do it each time.

Thanks

**Comment by Taiko2k** [comment]
There was previously a setting "auto-search" lyrics that I disabled. I'll re-enable it next release.

**Comment by Taiko2k** [comment]
There is now a config option to auto search lyrics on the conifg file in the new release (v6.5.4)

**Comment by inalone** [comment]
Works perfectly, thank you.
