### ISSUE TITLE
Player skips some songs unprompted

### ISSUE THREAD

**Issue by Yohe-Am** [Taiko2k/TauonMusicBox#479]
I can't determine what's causing this but once in a while, while going through a playlist, it skips a song after it plays the first 1 or 2 seconds. This showed up in the last week or two. I know this is not a lot to go on, I'll update if I notice something else.

**Comment by Taiko2k** [comment]
Hmm. Okay 2 questions. Do these tracks it skips show a duration of 0? Do these tracks all share a common file type?

**Comment by Yohe-Am** [comment]
> Hmm. Okay 2 questions. Do these tracks it skips show a duration of 0? Do these tracks all share a common file type?

1. No, the duration shown is accurate. And if I manually go back and play the skipped song, all's dandy. 

2. Yes, all of my library is in MP3.

**Comment by Taiko2k** [comment]
Oh also, are these local files, or on a network server?

**Comment by Yohe-Am** [comment]
> Oh also, are these local files, or on a network server? Also, does this happen when manually selecting a track, or only once the previous song has reached the end?

1. Local files.
2. This happens when it's going through a playlist.

I have large playlists that are composed of many albums (libraries are technically a playlist in TMB anyways). I usually want to play a single album at a time so I drag/drop the album to the `Playlist+Queue` sidebar to create a new temporarily lived playlist and play that. Digression, I know, sorry. But I go through this dance because the `queue` functionality requires I set an `Auto-stop` if I want to avoid playing my whole library. A setting for this would be much appreciated as well. I should open an issue...

**Comment by Taiko2k** [comment]
You mentioning the queue is interesting because I have recently received another report if tracks being skipped with it.

As for you feature request, I imagine it could be a persistant setting/toggle named something like "album auto stop". Do you have an idea on where this setting  should go?

**Comment by Yohe-Am** [comment]
> You mentioning the queue is interesting because I have recently received another report of tracks being skipped with it.

To be clear, the track skipping issues I've experienced happened while I was just using plain playlists, no queues involved.

> As for you feature request, I imagine it could be a persistant setting/toggle named something like "album auto stop". Do you have an idea on where this setting should go?

I personally won't mind if this was hidden in the settings page. But rather than focusing on albums as units, would be preferable if the toggle simply prevented the player from going back to the playlist when it's done with the queue. In fact, a toggle to disable the collapsing of albums on the queue would be nice. One more thing that'd appeal to folks used to MusicBee. I really should open an issue...

Thanks for the quick replies~

**Comment by Taiko2k** [comment]
There's now a config file option `end-queue-stop`. Its maybe a little weird how it works, but might fulfil your requirement

As for the skipping, can you please tell me if this is still occurring in the new release? (v6.5.4)

**Comment by Yohe-Am** [comment]
Sorry for the late reply, was busy. 

`end-queue-stop` works well enough and the skipping issue indeed appears to be gone and everything seems to be inorder.

Thanks for everything.
