### ISSUE TITLE
Fail to install TauonMusicBox on Pop!os20.04

### ISSUE THREAD

**Issue by cuijiahuawx** [Taiko2k/TauonMusicBox#480]
ID                                   Branch          Op          Remote           Download
 1. [✗] com.github.taiko2k.tauonmb           stable          i           flathub          1.0 kB / 69.2 MB

Error: Failed to read commit e3a3e2182a776990b7d10ace76432a966de950433dd75c9cb113c44cbecf170f: No such metadata object 537a53d9b9251f91d559c112176ff3d11edb2cd4449602faefed4f0178e37f7b.dirtree
error: Failed to install com.github.taiko2k.tauonmb: Failed to read commit e3a3e2182a776990b7d10ace76432a966de950433dd75c9cb113c44cbecf170f: No such metadata object 537a53d9b9251f91d559c112176ff3d11edb2cd4449602faefed4f0178e37f7b.dirtree

Help!!!

**Comment by Taiko2k** [comment]
I've heard of someone getting this error before, I forgot what the exact resolution was. Maybe try run `sudo flatpak repair` and/or `flatpak repair --user`.

**Comment by cuijiahuawx** [comment]
@Taiko2k It dose't work.The warning appears as same as before, after I run "flatpak repair --user".

**Comment by Taiko2k** [comment]
Same with `sudo flatpak repair`?

**Comment by cuijiahuawx** [comment]
@Taiko2k Yes.

**Comment by Taiko2k** [comment]
Is this an update to an existing installation? If so try uninstall then reinstall the Tauon Flatpak. 

Otherwise, if you're sure you've tried both those repair commands, I'm kind of out of ideas unfortunately.

**Comment by cuijiahuawx** [comment]
@Taiko2k I have try all above, but still failed.Finally,I gave up.And I have installed software using snap now.Thank you for your replay.

**Comment by Taiko2k** [comment]
Okay that works. Its unfortunate flatpak seems to have some issues.
