### ISSUE TITLE
[Feature Request] HiDPI support

### ISSUE THREAD

**Issue by summonholmes** [Taiko2k/TauonMusicBox#485]
Hi, I really like admire your work here.  However, the interface is too tiny on my 4k display.  Where does HiDPI support stand right now?  I'm not seeing any mention of HiDPI in the issues, manual, or sidebar.

**Comment by Taiko2k** [comment]
You can scale the UI using a setting under MENU > Settings > Window.

There is mention of this on the Q&A page. Perhaps I should give it its own wiki page so its clearer.
