### ISSUE TITLE
[Feature Request] Visualization in the Lyrics View

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#49]
What if we have similar visualization in the Lyrics View. What do you think?
https://www.youtube.com/watch?v=SHQHJo5-HV0

![alt text](https://ibin.co/4WtCcfguj5b6.png)

**Comment by Taiko2k** [comment]
Interesting, though, I think it looks nice here because it is per-rendered and uses anti-aliasing. Doing this in real time may be tricky / expensive.

**Comment by Solarunit** [comment]
tricky / expensive because of the wiggle effect?

What if it is just this static visualization:

![alt text](https://ibin.co/4WwSljD7HwYP.png)

**Comment by Taiko2k** [comment]
I mean, its smooth, and like, there's subtle differences in width of the size of each bar.

**Comment by Solarunit** [comment]
Ah, ok

**Comment by Taiko2k** [comment]
Ill keep it in mind though, I may pursue it if I feel interested in exploring possibilities here, but its not a priority for me at the moment.

**Comment by Taiko2k** [comment]
I tried playing around with this idea, actually doesn't seem to look too bad even just keeping it basic.

![screenshot from 2019-03-05 11-50-08](https://user-images.githubusercontent.com/17271572/53768285-42ee9e00-3f3d-11e9-820b-13564422d1bb.png)

**Comment by Solarunit** [comment]
I agree. It can be used when the song doesn't have a lyrics. Or if you don't want to see the lyrics there might be a button (or context menu option) to hide the lyrics.
I don't use visualizer on the top panel because it's too small.

**Comment by Taiko2k** [comment]
I have a prototype for the blurred background... 

![screenshot from 2019-03-05 17-44-50](https://user-images.githubusercontent.com/17271572/53781674-9decb900-3f6e-11e9-8067-934d6fd2e6e2.png)

Seems to only look good half the time. Nice on dark images, but bad on brighter ones. So I probably wont go with this.

**Comment by Solarunit** [comment]
We need an integrated AI that will select nice looking covers and use them as background =))

**Comment by Taiko2k** [comment]
Imagine users seeing a machine learning toolkit in the dependency list of a music player, they might freak out. :grin:

But anyway, ill keep the blurred bg in mind, might think of a better way to utilize it in the future.
