### ISSUE TITLE
[Bug] Discord Rich Presence Elapsed Time

### ISSUE THREAD

**Issue by ILikeToCode1337** [Taiko2k/TauonMusicBox#490]
When skipping through a track, the elapsed time on the Discord rich presence doesn't update.
![Yv2v6G9YXz](https://user-images.githubusercontent.com/78124644/112694731-c2c86780-8e7a-11eb-831a-6ef9d1343865.gif)

**Comment by Taiko2k** [comment]
Currently its intended to be "time spent listening" so its not a bug exactly. I could change it... Actually I was considering changing it to "time remaining". I think that might be more useful. Its what some other apps already do.

**Comment by ILikeToCode1337** [comment]
> Currently its intended to be "time spent listening" so its not a bug exactly. I could change it... Actually I was considering changing it to "time remaining". I think that might be more useful. Its what some other apps already do.

I didn't expect it to have been "time spent listening" when playing a track since the time resets when it moves onto the next track. The "time remaining" is what I'd like to see. Maybe even add a setting to change the time to your liking in the function tab.
