### ISSUE TITLE
questions about flatpak version

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#50]
When installing player, runtime gnome.Platform v3.30 was installed ~1GB.

1. If gnome.Platform v3.30 is available in the system, do you need to install it also via flatpak? 
2. What if the system was updated and it has now the version of runtime player using, what will happen to the flatpak version?

**Comment by Taiko2k** [comment]
When you install a flatpak app, (by any method) it will ask to download the runtime. It will then keep the runtime and it will be available for any other app that needs it.

If a new runtime is needed, that will need to be download as well, and the old one will be kept too, even if no other app needs it. I believe you need to uninstall them manually if you want to free up space.

And flatpak runtimes are just for flatpak, it doesnt use gnome installed on your system, even if happens to be similar versions.

**Comment by Solarunit** [comment]
Thanks for the explanation.
