### ISSUE TITLE
"Status: Error — Discord Not Running?"

### ISSUE THREAD

**Issue by CyberAzure** [Taiko2k/TauonMusicBox#500]
_Status: Error — Discord Not Running?_

I have been facing this issue for a week or two.
I thought it was maybe a glitch, so I closed Discord and re-opened it.
_Nothing._
Then I tried closing Tauon Music Box(TMB) and leaving Discord open.
_Nothing either._
Then I tried closing both.
_Nothing..?_
I restarted the whole system, and still nothing.
It was working fine, I don't know what caused this to happen.
70% of the reason I use TMB is because of the Rich Presence for Discord and modern look.
I still love it and will keep using it, but this makes me kinda sad 'cause my friends won't be able to see what I am listening to.

I use the Flatpak version, Ubuntu 20.10 with a few themes here and there.
Discord is totally normal, no plugins or anything silly.

**Comment by Taiko2k** [comment]
Maybe try set the permission again https://github.com/Taiko2k/TauonMusicBox/wiki/Flatpak-Permissions#discord-rp

Also try experiment with the order you start both apps. It can be finicky with that.

**Comment by CyberAzure** [comment]
> Maybe try set the permission again https://github.com/Taiko2k/TauonMusicBox/wiki/Flatpak-Permissions#discord-rp
> 
> Also try experiment with the order you start both apps. It can be finicky with that. (I.e begin with both apps fully closed)

**IT WORKED!!!**

Thanks, i didn't knew there was even a wiki for that.
You should link the wiki when a error like this pops-up, like _"See (link) for help."_ or something.
Anyways, thanks, now i can show my friends what i am listening to.
