### ISSUE TITLE
Some info from cue sheet missing when imported

### ISSUE THREAD

**Issue by Ascalony** [Taiko2k/TauonMusicBox#502]
I've got many files (tta, flac and other formats) that are a whole disc which have associated cue sheets. When they are imported in to Tauon, some of the information is not added into the player. Here's an example of part of one of these sheets with values Test A-D inserted for clarity:

```REM GENRE Classical
REM DATE 1989
REM DISCID 0411340F
PERFORMER "Test A"
SONGWRITER "Test B"
TITLE "Strauss Gala 'An der schonen blauen Donau'"
FILE "Strauss, Johann - CD2- Wiener Philharmoniker - Willy Boskovsky.ape" WAVE
  TRACK 01 AUDIO
    TITLE "Geschichten aus dem Wienerwald, op.325"
    PERFORMER "Test C"
    SONGWRITER "Test D"
    INDEX 00 00:00:00
    INDEX 01 00:00:33
  TRACK 02 AUDIO
[...]
```
In this example, the album artist field ought to be Test A but is never set. The artist field is correctly set to Test C and, if missing on the track-level, is filled also correctly by Test A. The composer field remains unpopulated either way; priority ought to be given to Test D and then the album-level Test B.

**Comment by Taiko2k** [comment]
Thanks for clear and detailed report! 

I've now committed these changes as you described.

Previously album-artist was only read from `MAIN PERFORMER`, but now will fall back to top level `PERFORMER`. Mappings of `SONGWRITER` to composer was missing completely but now has been added. 

Note that once Tauon is upgraded you will need to re-import the related folders for the change to take effect.

**Comment by Ascalony** [comment]
Have tested and it works as expected. Thank you :smile:
