### ISSUE TITLE
[Feature Request] More ways to control volume

### ISSUE THREAD

**Issue by Ascalony** [Taiko2k/TauonMusicBox#503]
Hello, I have a pair of suggestions that I think would be nice to have in Tauon:

1) I read the API documentation on the wiki and thought that it would be useful to have something for volume up and down. I know that you can set a specific volume already but going by increments can be useful as well. I've usually got programs that I keep running daily in separate workspaces to keep my windows manageable. It would be nice to write a small script that raises or lowers the volume with key presses instead of having to switch to and focus on Tauon's winow.

2) Manipulating the volume by scrolling up and down on the tray icon (possibly also play/pausing on middle click). If the player is minimized, can be an easy way to control things without having to open a menu.

**Comment by Taiko2k** [comment]
Scrolling on the tray for volume should already work (Though known not working with Flatpak version)

Perhaps increment volume should be added to the API. You're not the first to enquire about that.

In the mean time, you can use the program playerctl and use a command like `playerctl -p tauon volume 0.05+`

**Comment by Ascalony** [comment]
I'm not using the flatpak version but am on wayland; I suppose that scrolling on the icon not working may be a limitation of my choice of panel/environment. Just in case, I forced SDL to use the wayland backend and that didn't make a difference. I suppose I need to look into what prevents things from working exactly.

Thanks for the suggestion on an alternative, at any rate. It would be nice to have it in the API either way.

**Comment by Horuyuki** [comment]
> Scrolling on the tray for volume should already work (Though known not working with Flatpak version)
> 
> Perhaps increment volume should be added to the API. You're not the first to enquire about that.
> 
> In the mean time, you can use the program playerctl and use a command like `playerctl -p tauon volume 0.05+`

And I can add a key board short cut to this command right? or was your idea just to type in the terminal?

**Comment by Taiko2k** [comment]
> And I can add a key board short cut to this command right? or was your idea just to type in the terminal?

For just local you can edit input.text, by default volume is set to Shift +Up/Down.

For global control, most DEs allow you to bind commands to shortcuts.

**Comment by Taiko2k** [comment]
Volume setting has now been added to remote API in release version
