### ISSUE TITLE
Main Music playlist doesn't remember to default to last selected sorting option

### ISSUE THREAD

**Issue by Scotty-Trees** [Taiko2k/TauonMusicBox#506]
Greetings again!

I did a reinstall of PopOS over the weekend and while everything is back up and running just fine, I came across something I can't seem to figure out in the lovely Tauon player. It's more than likely I'm a bumbling fool than a bug or issue, but perhaps it may be both who knows :P

Upon installing Tauon flatpak, I imported my music folder and added a few playlists generated from that as well. Whenever I add new music, I make sure to re-scan the main music playlist and every time I do a re-scan it takes the sorting list from what I had selected before as "sort by filepath" which is what I want btw, aka like an A-Z band/album listing for my main music playlist, but it keeps changing it back to what I believe is the default to "sort by imported" 

I try to edit the main music playlist generator to sort it the way I want, but it appears the main music playlist is not editable by the generator, only playlists that are generated from it. Basically, is there anyway to make Tauon remember the last selected sort by selection so whenever the app is open/closed/or re-scan, it still defaults to whatever the user had last selected? Hope this makes sense to ya and thanks as always for creating a really fantastic music app, it's probably one of my most used apps :)

**Comment by Taiko2k** [comment]
I dont blame you, even I have to stop and think about how this is supposed to work.

What's the code string that you attempted to apply to the main playlist?

**Comment by Scotty-Trees** [comment]
Well that's just the thing, I can't edit anything for the main music playlist. it's the playlist that was created when I imported my music folder, so I feel like Tauon doesn't want to let you edit the main music folder that it relies on, it appears to me like it's not editable, but any playlist generated from that main music list is editable. Know what I mean?

It shows "Result is Empty" any time I add any type of string to the generator for the main music playlist that I imported, shown here: 
![Screenshot from 2021-04-18 16-32-14](https://user-images.githubusercontent.com/45135187/115161528-dd4dc500-a063-11eb-9818-a832b168b0c2.png)

In one of my other playlists that I generated from the main music list, I can edit the generator anyway I like and get the green "OK" what you typed in is good message, shown below :P
![Screenshot from 2021-04-18 16-32-42](https://user-images.githubusercontent.com/45135187/115161555-066e5580-a064-11eb-8c8e-0734d8d90823.png)

**Comment by Taiko2k** [comment]
Well its saying that particular string won't produce anything. It needs to be a valid string essentially.

In this case I believe you'd want to set the generator of the main playlist to something like `self a path`

**Comment by Scotty-Trees** [comment]
self a path does give me an "OK" and does change the sorting to how I'd like it. When I do a quick rescan, it ignores what is specified in the generator however. If I make it "self a path auto" then when I do a quick rescan, then it stays in the sorting path that I'd like it to. I thank you very much for your help, that solves this little generator doohickey thing for me haha, very much appreciated mate.

**Comment by Taiko2k** [comment]
Glad to hear that solves it
