### ISSUE TITLE
Clearing tags cache after rescan

### ISSUE THREAD

**Issue by Horuyuki** [Taiko2k/TauonMusicBox#509]
Hey!

So this time I made sure to read and try out everything before asking here.

I was changing the album title tag of an album since it was in Japanese. And after I did, I double checked it with other players and tag editors. All of them were able to show the renewed album tags after clearing of the or a rescan.

I pressed the rescan button and tried removing the playlist and then adding the folder again. But it still retained the old tagging. What can I do to rescan and clear the tag cache so the updated information can be shown?

Thanks!

**Comment by Taiko2k** [comment]
Right click a track and select Meta... Reload metadata to reload for its album. OR right click a playlist tab, select misc... Rescan tags

**Comment by Horuyuki** [comment]
Yup that worked nicely thanks! Maybe you can include it in the manual or make it happen with a full rescan?
