### ISSUE TITLE
[Feature Request] Pause playback when computer goes to sleep

### ISSUE THREAD

**Issue by ariflukito** [Taiko2k/TauonMusicBox#512]
As the title, it would be nice if TMB can pause playback when computer goes to sleep.
Also option to stop computer goes to sleep when song is playing. Thank you.

**Comment by Taiko2k** [comment]
Okay, I've committed these changes.

There will be a new option in the config file named `block-suspend` which defaults to off

**Comment by Taiko2k** [comment]
Okay this is now in release version, you should also now find this setting in page 4 of settings > function.

**Comment by Taiko2k** [comment]
> Can you make this to work with screen blanking as well?

That's not so straightforward, you might just need to disable that in your de settings.
