### ISSUE TITLE
[Question] How to copy track hearts from one Touon flatpak to another Touon flatpak?

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#513]
How to copy track hearts from one Touon flatpak installation to another Touon flatpak installation? Music files location is the same.

**Comment by Taiko2k** [comment]
See this wiki page https://github.com/Taiko2k/TauonMusicBox/wiki/Keeping-track-of-playcounts

**Comment by Solarunit** [comment]
Thanks! I will try to copy `star.p` file

**Comment by Solarunit** [comment]
It works!
