### ISSUE TITLE
How to search through the library without creating a new playlist or playing the album?

### ISSUE THREAD

**Issue by Darkmaster006** [Taiko2k/TauonMusicBox#515]
So there's two things I don't know how to do that may be available. If not, it'd be cool to have them. First, is there any way to search for an artist and click on them and be re-directed to the artist's position on the "Library" playlist where all the music tracks are? Instead of creating a new playlist solely for that artist. Second, is there any way to search for an album and click it without it starting playing? Thank you!

**Comment by Taiko2k** [comment]
Both of these should be achievable by right clicking the result in search rather than left click.

**Comment by Darkmaster006** [comment]
Thank you! Works like a charm, except when an artist is present on a compilation, searched here from 'KANA-BOON' for example and led me to this. How to "keep" searching for the next instance?
![Screenshot from 2021-05-01 08-58-29](https://user-images.githubusercontent.com/21136515/116781754-68af5900-aa5b-11eb-95f4-5b108e9cb3d2.png)

**Comment by Taiko2k** [comment]
>  How to "keep" searching for the next instance?

The global search can't do this, its a limitation.

The "Artist panal" can do this however, and also "quick find" can effectively too.

**Comment by Darkmaster006** [comment]
> > How to "keep" searching for the next instance?
> 
> The global search can't do this, its a limitation.
> 
> The "Artist panal" can do this however, and also "quick find" can effectively too.

Excellent. The 'Quick Find', which I had not tried until now, works wonders for basically everything (from searching specific words in songs to searching artists), thank you. What do you mean with the 'Artist Panel', though? How can I search through it?

**Comment by Taiko2k** [comment]
> What do you mean with the 'Artist Panel', though? How can I search through it?

I meant the artist list panel, but it can't search using text actually, so nvm, quick find works better for that.
