### ISSUE TITLE
MBIDs not being submitted to ListenBrainz for .m4a files

### ISSUE THREAD

**Issue by rooiratel** [Taiko2k/TauonMusicBox#516]
I enabled listenbrainz sync, and it's working great, but I noticed that all .m4a files are not working.

All the greyed out songs below are .m4a files, and all the others are not:

![screenshot](https://user-images.githubusercontent.com/34131729/116781781-8691b380-aa85-11eb-9634-33ce3da8e0cc.png)

**Comment by Taiko2k** [comment]
Apologies for the delay, this should be fixed in the new v6.7.0. You will need to do a "tag rescan" from the playlist, misc context menu for this fix to take effect.

**Comment by rooiratel** [comment]
No worries. I really appreciate it! I was wondering how you would do it since .m4a files are _ass_ to work with. I see you used mutagen, nice.

Anyway I tested it and it's working great. Thanks again for fixing this, and for making an awesome music player.
