### ISSUE TITLE
Documentation: Nextcloud Music Subsonic integration

### ISSUE THREAD

**Issue by almereyda** [Taiko2k/TauonMusicBox#517]
The settings menu offers to enable HTTP basic authentication thanks to #424 and #311 has a conversation about accessing music in Nextcloud. Yet, the documentation does not reveal how to access it, nor what kind of Airsonic support is present in Nextcloud, and where to configure it.

Additional documentation about how to set up both ends of the integration will help users like me understanding what is expected from them to get this work.

**Comment by Taiko2k** [comment]
I'm not entirely sure what kind of configuraton #424 was reffering to, perhaps they were using this https://github.com/owncloud/music. 

Details on how to set that up might be a bit outside the scope of Tauons documentation.

**Comment by almereyda** [comment]
Thanks for the quick look. Indeed that is what is required here, and they have a separate documentation about how to use it as a Subsonic source:

- https://github.com/owncloud/music#ampache-and-subsonic

Maybe everywhere it says *Nextcloud* in the UI, we should say *Nextcloud Music* instead and have an external link (icon) ready to send people to that documentation?

**Comment by Taiko2k** [comment]
OK I'll change the in app text to say *Nextcloud Music*, and also mention it in the wiki documentation.
