### ISSUE TITLE
Is it possible to have different view modes for different playlists?

### ISSUE THREAD

**Issue by Darkmaster006** [Taiko2k/TauonMusicBox#518]
Is there any way to do this? To give an example, having a 'General' playlist with 'Gallery View' and then a 'Favourites' with the 'Tracks + Art'. If not, could it be implemented? Just thought it'd be cool. Thank you.
EDIT: Also thought it could be nice to have both the gallery view of album arts and the album art and info of the album player. Maybe with customisable 'elements'?
EDIT 2: Is it possible to shift between the views with a key? (just as F2 is used to shift between themes, for example).

**Comment by Taiko2k** [comment]
Ill go with wonfix for this, I don't want the added complexity.

You can cycle views, use square bracket buttons, and views can be bound to specific keys in the keymap file.
