### ISSUE TITLE
Player crashes in Gallery View

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#52]
tauon3.6.X1
When there are 1-2 albums in Gallery View and you press left/right key several time - player will crash.

upd
Also it is impossible to select the 1 album using UP key

**Comment by Taiko2k** [comment]
I've found and fixed the UP key issue when going up to the first album.

As for the crash, I may have fixed it, I will need to do more testing.

**Comment by Taiko2k** [comment]
Heres latest version if you want to test https://github.com/Taiko2k/TauonMusicBox/releases/download/v3.5.3/tauon3.6.X2.flatpak

**Comment by Solarunit** [comment]
tauon3.6.X2.flatpak
Still crashes. And the UP key doesn't work at all.

**Comment by Taiko2k** [comment]
For the crash, could you give me the error in the terminal output? (tauon3.6.X2.flatpak)

To run from terminal: `flatpak run com.github.taiko2k.tauonmb`

**Comment by Solarunit** [comment]
`Playlist is too noisy for power bar.
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 21679, in <module>
    gal_jump_select(True, 1)
  File "/app/bin/tauon.py", line 13608, in gal_jump_select
    alb = get_album_info(playlist_selected)
  File "/app/bin/tauon.py", line 13531, in get_album_info
    default_playlist[current - 1]].parent_folder_name:
IndexError: list index out of range
`

**Comment by Taiko2k** [comment]
Hopefully fixed this time

https://github.com/Taiko2k/TauonMusicBox/releases/download/v3.5.3/tauon3.6.X3.flatpak

**Comment by Solarunit** [comment]
Looks good. Thanks!
