### ISSUE TITLE
Metadata problem

### ISSUE THREAD

**Issue by Darkmaster006** [Taiko2k/TauonMusicBox#522]
![imagen](https://user-images.githubusercontent.com/21136515/117064760-ff4e7500-acfc-11eb-89cb-f0f77e4409e6.png)
For some reason, these songs, which are properly tagged as I'll show below, have neither Artist nor Album. I've reloaded the metadata but nothing happens. Any ideas?
![imagen](https://user-images.githubusercontent.com/21136515/117064903-26a54200-acfd-11eb-8546-20c1242b789f.png)

**Comment by Taiko2k** [comment]
Fix for this has been committed

**Comment by Taiko2k** [comment]
This is in release version now, let me know if it's all good.

**Comment by Darkmaster006** [comment]
Seems to work correctly now, awesome.
