### ISSUE TITLE
Multi-CD Album grouping when using Jellyfin as the source

### ISSUE THREAD

**Issue by jibsaramnim** [Taiko2k/TauonMusicBox#525]
First off; thank you so much for building this wonderful music player, I was so happy when I stumbled upon your work as up until now I had struggled to find a music player replacement after fully switching to Linux. So, really, thank you!

--- 

I'm really happy with the recently introduced Jellyfin support, and have switched over to using this as soon as it came out. It's been working well for the most part, with the only exception so far seemingly being that playback stats are not synced, and the main subject of this issue; multi-CD albums don't seem to be grouped as such, with songs showing up in one list instead. I've attached a screenshot of one such example:

![image](https://user-images.githubusercontent.com/18850/117604064-6b165f00-b18f-11eb-846f-e9719b6857e9.png)

My albums are correctly tagged and contain all the necessary meta information, and shows up correctly in Jellyfin:

![image](https://user-images.githubusercontent.com/18850/117604220-c6e0e800-b18f-11eb-83dd-ab1165612790.png)

Before I switched to using Jellyfin I had directly loaded up my music library in Tauon, and multi-cd albums showed up fine using this method, leaving me to believe it's _probably_ specific to the Jellyfin implementation.

I can provide additional information if it's helpful. I thought I'd start with this to see if anyone else may have the same behavior, or if it's somehow something I did wrong.

**Comment by Taiko2k** [comment]
Okay I've made a commit which I think should fix it. 

Note that once you upgrade you'll need to re import your library into Tauon for this change to take effect.

**Comment by bastianvv** [comment]
I can confirm multi-disc albums are now showing correctly for me, except when I sort by Imported.
![Screenshot_20210513_000551](https://user-images.githubusercontent.com/21223384/118076608-809eab00-b380-11eb-82f6-c357ff385263.png)
Also, I'll open a new issue for the playback stats sync, it's the only thing I'm missing from Tauon.

**Comment by Taiko2k** [comment]
> except when I sort by Imported

Well nothing to do about that, that is what it is. You'll need to apply some kind of sorting if sort by import alone happens to be undesirable.

**Comment by bastianvv** [comment]
Yes, I noticed right after commenting that that's how it's meant to be. Thanks for your amazing work!
