### ISSUE TITLE
Sync Jellyfin playback stats

### ISSUE THREAD

**Issue by bastianvv** [Taiko2k/TauonMusicBox#529]
I would love that a Jellyfin Collection syncs playback stats with the server. That is, whenever I play a song in Tauon, Jellyfin updates the play count and shows the track in the Recently Played section of the music library:
![Screenshot_20210513_011310](https://user-images.githubusercontent.com/21223384/118081554-92d11700-b389-11eb-8430-0f49785f498c.png)

On a final note, I want to thank you for this great music player, by far the best I've ever used in terms of looks and features. It's not easy to find a player in Linux that lets you manage a big library like mine, and even less so with so many integrations. Thanks again for your excellent work!

**Comment by Taiko2k** [comment]
Woo got it working. Ive committed this change now.

As for play counts, I'm not sure Jellyfin tracks that, I've not seen where you can view those stats if so. But with this change the *Recently Played* should now update and it now shows the playback status in the Jellyfin dashboard.

![Screenshot from 2021-05-13 22-10-03](https://user-images.githubusercontent.com/17271572/118112692-75f41c80-b439-11eb-9a8e-a240acb9b6e2.png)

**Comment by bastianvv** [comment]
Awesome! I tested it and it works perfectly. Thank you so much.
As for play counts, AFAIK Jellyfin does store the times you've played a certain item, but doesn't show it anywhere unless you have the Playback Reporting plugin installed, which I have, and the plugin is showing the items correctly too ;)
Should I close this issue?

**Comment by Taiko2k** [comment]
> Should I close this issue?

Sure. Though, are you happy to use the dev version for a while or would you rather me hasten the next release?

**Comment by bastianvv** [comment]
I'm happy with the dev version for now, take your time to prepare the new release ;)
