### ISSUE TITLE
Navigation keys don't work in Gallery View

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#53]
I've noticed that sometimes navigation keys don't work in Gallery View. I can switch between Art and Gallery View.

**Comment by Taiko2k** [comment]
I've figured out the bug, it happens if you enter the gallery with Tab, but then exit via the normal method and then re-renter via Tab.

I've also made an improvement now to make it show the selected album when entering the Tab mode.
