### ISSUE TITLE
Codec support library screen

### ISSUE THREAD

**Issue by KoO-303** [Taiko2k/TauonMusicBox#532]
Would it be possible to add codec info some where on library screen. As I don't use playlist much just mostly have full library open.
As in mp3 , flac , or even @320 @ 256 so on etc
Thanks

**Comment by Taiko2k** [comment]
Not sure what you're referring to as *library screen*, but the track list does have a column for codec/file type. 

I'm not inclined to add codec info in many places since I believe it's relatively unimportant information that is prone to placebo effect.

**Comment by KoO-303** [comment]
Sorry just so many options found it Thanks.
Solved.
