### ISSUE TITLE
[Question] Tauon was updated today?

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#534]
Hi @Taiko2k :wave: 
Flatpak version was updated today? I don't see new release. 
Also, do you know how display package version when using `flatpak update`?

**Comment by Taiko2k** [comment]
Yes this was effectively a repack of v6.6.0 for Flatpak. 

This was an adjustment of the base permissions to allow Tauon to inhibit suspend/shutdown and fix a crash when enabling the associated setting.

I don't think there's a way to see a human readable package release number.

**Comment by Solarunit** [comment]
Good to know, thanks
