### ISSUE TITLE
Tauon crashes on launch

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#535]
For context, I had my computer crashing while Tauon was running. When I rebooted, I had this message in the terminal:

```Tauon Music Box v6.6.1
Copyright 2015-2020 Taiko2k captain.gxj@gmail.com

Running in portable mode
Found XDG-Downloads: /home/user/Downloads
Found XDG-Music: /home/user/Music
Install directory: /home/user/Appz/TauonMusicBox
Database loaded in 1.974 seconds.
Applying scale based on xft setting
Using UI scale: 1.0
Start controller server
Could not connect to gnome media keys
Start PHAzOR backend...
Using SDL version: 2.0.10
Traceback (most recent call last):
  File "./tauon.py", line 38983, in <module>
    toggle_album_mode(True)
  File "./tauon.py", line 20058, in toggle_album_mode
    reload_albums(quiet=True)
  File "./tauon.py", line 24255, in reload_albums
    playlist = pctl.multi_playlist[target_pl_no][2]
IndexError: list index out of range
```

**Comment by Taiko2k** [comment]
Seems like the app data has become corrupted. You will need to delete the state.p file from the user data folder to reset the player. (This will detete all playlists)

Were you activity interacting with Tauon at the time your computer crashed?

**Comment by awsms** [comment]
I was able to fix it by removing the old state.p file, and renaming state.p.backup to state.p!

I was scanning a directory when my PC crashed.
I've already experienced crashes while actively using Tauon before, but I never was unable to relaunch the program afterwards like here.
