### ISSUE TITLE
[FR] Rescan a single directory (without subfolders)

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#536]
I'd like to rescan folders that do not contain any subfolders (the ones with a little orange box next to them).
Would it be possible to add a "Rescan Folder" option in the context menu for them?

![Screenshot from 2021-06-06 03-04-08](https://user-images.githubusercontent.com/48278661/120909280-e4607f00-c673-11eb-9206-38b3768df0f3.png)

**Comment by Taiko2k** [comment]
Okay I've committed this now.

Its a little inconsistent this being in the folder navigator menu but not the tracklist folder menu, but oh well its probably fine.

**Comment by Taiko2k** [comment]
This should be live now
