### ISSUE TITLE
Plex playback broken

### ISSUE THREAD

**Issue by ariflukito** [Taiko2k/TauonMusicBox#537]
Hi after updating python-plexapi to version 4.6.0, TMB plex playback is broken. It fails authorization.
Thank you for your great work.

**Comment by Taiko2k** [comment]
I got in touch and they've now released v4.6.1 which would fix it. Ref https://github.com/pkkid/python-plexapi/pull/778.

Try update and let me know if it's working.

**Comment by ariflukito** [comment]
Yes it's working now. Thank you @Taiko2k!
