### ISSUE TITLE
[ Feature Request / How to? ] Add option to Remove individual tracks from a playlist when said tracks were added together as an album.

### ISSUE THREAD

**Issue by RichTheWolf257** [Taiko2k/TauonMusicBox#539]
I'm using v6.6.0 downloaded from Ubuntu Software in Ubuntu 20.04. When I add a complete album to a playlist, there's no option to remove individual tracks within that album from the playlist. I can remove the whole album using the right-click menu, but when I right-click an individual track the "Remove" option is missing from the same menu. 

If _I'm_ missing something, of if there's a way to edit playlists outside of the application, please let me know.

Thank you.

**Comment by Taiko2k** [comment]
There's actually no current way of deleting an individual track using the mouse input alone, but you can with the keyboard using the <kbd>Delete</kbd> key with a track selected.

**Comment by RichTheWolf257** [comment]
Thank you!
