### ISSUE TITLE
Album art not showing in track+art view

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#54]
I update the player to the latest version using the AUR on Manjaro stable. When I started playing a song, the album art is not showing up where it normally does on track+art view. Only the lyrics are visible. The art is visible in lyrics view.
![screenshot from 2019-02-17 10-58-48](https://user-images.githubusercontent.com/37796862/52910062-2434aa00-32a3-11e9-9b76-cc39cbf9614c.png)

**Comment by Taiko2k** [comment]
There's now a setting to hide the album art (Right click the side panel area and click `Show art box`)

But this is not supposed to be the default setting, ill need to repack and release.

**Comment by Taiko2k** [comment]
OK, this *should* be fixed for new upgrades now, but since you already upgraded, it'll have no effect, just need to press that button to show it again.
