### ISSUE TITLE
Filename makes Tauon freeze and enter freezing loop

### ISSUE THREAD

**Issue by cadr10** [Taiko2k/TauonMusicBox#541]
There are some filenames that makes Tauon freeze. You can't really make it work without deleting state files in local folder. It freezes trying to play a song -> force close it -> it opens in the same song. 

This is what terminal gives 

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/tauon-music-box/tauon.py", line 4628, in notify_update_fire
    self.mpris.update()
  File "/opt/tauon-music-box/t_modules/t_dbus.py", line 406, in update
    'xesam:url': "file://" + urllib.parse.quote(track.fullpath),
  File "/usr/lib/python3.9/urllib/parse.py", line 863, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce3' in position 54: surrogates not allowed
```

**Comment by Taiko2k** [comment]
Seem like you might have filenames that aren't utf8, while its allowed in Linux, might not be here. That's fine, ill just catch the error there. Ive committed this now.

Though that error there shouldn't cause the app to freeze, so there might be remaining bugs in relation to this.

**Comment by cadr10** [comment]
Thanks for the quick fix. With the latest version I can play the songs that were crashing Tauon. As the bug is fixed, I am closing the issue. Thanks again for the fix and developing this awesome music player :)
