### ISSUE TITLE
Japanese characters are unreadable after update

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#543]
I noticed that there were some font-related changes in the latest update. But japanese characters become unreadable for me:

![alt text](https://i.imgur.com/g5c9UC5.png)

Tauon Flatpak 6.6.1

**Comment by Taiko2k** [comment]
Ah. Previously I included Japanese fonts with the Flatpak package. But in this update I removed them... cause maybe it makes sense? (It adds 40mb to the download size).

I guess the new expectation would be that you install Japanese fonts on your host system. (I assume you don't already?)

I guess it would be good to hear peoples feedback on this change.

**Comment by Solarunit** [comment]
> I removed them... cause maybe it makes sense? (It adds 40mb to the download size).

I think 40 MB is not a small size. Why fonts are so heavy? :thinking: 
Is there a way to compress it maybe?

> I guess the new expectation would be that you install Japanese fonts on your host system. (I assume you don't already?)

No, I didn't
The problem is that it's not very convenient. 

- You should know, that you have to install some fonts
- You should know what kind fonts to install and what package
- You should know where to install from and how
- possible flatpak permissions issues

**Comment by Taiko2k** [comment]
Well that 40mb is compressed already. It includes Chinese and Korean and multiple weights, so is why its large.

I added some documentation to the wiki on how to install the fonts, but yeah issue is not many people read it.

Mmm yeah seems this is going to be more of a problem than its worth, so ill add them back in. Expect a Flatpak update soon and then tell me if its working again.

**Comment by Solarunit** [comment]
Ah, thanks! 
I personally don't mind additional 40MB for such convenience.

**Comment by Taiko2k** [comment]
Okay update should be ready about now

**Comment by Solarunit** [comment]
Its working again, thanks!
