### ISSUE TITLE
[QUESTION] Can I modify Tauon's Discord rich presence?

### ISSUE THREAD

**Issue by CyberAzure** [Taiko2k/TauonMusicBox#544]
Silly question I know, but can I modify the name and/or icon that it shows on the profile?
Like, there's some text file that I can change?
I use the Flatpak version, of course.
By the way, Tauon for me is the best music player to ever exist on Linux. ^-^

**Comment by Taiko2k** [comment]
No, Tauon doesn't have any user configuration for this. 

The only way would be to modify Tauons source code then run source with it connecting to your own Discord app account. I would say its not worth the trouble, though I do know of at least one other user who has done this.

Glad you like Tauon btw!

**Comment by CyberAzure** [comment]
I would like to know where should I start with that, I just want to change de icon and name after all, shouldn't be too difficult for me to do that(I hope so lol).
Or, maybe assign that "other user" here?

**Comment by ArthRMH** [comment]
/var/lib/flatpak/app/com.github.taiko2k.tauonmb/current/active/files/bin click right button edit it with your text editor app
line 21095 there'll be a _thing_ called "client_id" in there you can put the id you want to change the icon, put 864018911862325309 there if you wanna test it (don't know how my friend done that i'll ask him and tell you later)
I don't really know how to change the name, but i bet it is in that code there too
Extra: If you wanna change the order that the artist name - album name and song name appears just change (line 21162 ending at line 21170), here's an example
```
title = "Unknown Track"
            tr = pctl.playing_object()
            if tr.artist != "" and tr.title != "":
                title = tr.artist + " - " + tr.album
                if len(title) > 150:
                    title = "Unknown Track"

            if tr.album:
                album = tr.title
            else:
                album = "Unknown Album"
```
title = tr.artist + " - " + tr.album (the " - " goes for what you wanna put between the artist name and title name. for example, it you wanna then to be separated with an ":" just put title = tr.artist + ": " + tr.album and you'll be good to go. Changing the tr.artist to tr.album tr.title and vice-versa change the order too.
Hope i helped you, heh

**Comment by CyberAzure** [comment]
Thank you fellow brazilian man ^^
Gonna try messing around with that right now.

**Comment by KaueGamer7765** [comment]
![image](https://user-images.githubusercontent.com/55243871/126312584-1054a1cf-6716-4a4b-b2b5-ef6b51437d3a.png)

**Comment by ArthRMH** [comment]
![snoop dogg bom demais](https://user-images.githubusercontent.com/86346283/126312980-22d347b7-9e97-44cb-937b-9c4864a491be.gif)

**Comment by CyberAzure** [comment]
Aight so, managed to change the icon, but, I don't know how to put custom icons on that.
Seems like a bunch of numbers, not a link to cdn.discord or Imgur.
And thus, didn't find any way to change the name either, oddly strange...

**Comment by Taiko2k** [comment]
You'll need to go to the developers section of the discord site and create an app. Then under rich presence you can fill in details like the name. Then set the API key in tauons source code.

**Comment by CyberAzure** [comment]
That'll change the name from "Tauon Music Box (Insert Music Note Emoji Here)" to whatever I put there?

**Comment by Taiko2k** [comment]
You register a discord app, see you'll enter the name here:

![Screenshot from 2021-07-21 23-31-44](https://user-images.githubusercontent.com/17271572/126482184-bb76e45c-e037-493e-bab7-56e059c88a7f.png)

And you'll need to replace the client id in tauon.py here:

![Screenshot from 2021-07-21 23-30-29](https://user-images.githubusercontent.com/17271572/126482291-e1b8daaa-8ed9-4fe0-88b1-b967286cb58e.png)

You'll need to disable any auto-updating with Flatpak or your changes will be overwritten on next update btw

**Comment by CyberAzure** [comment]
Well, that prompts me with "Error - Discord not Running?"
I did something wrong?

**Comment by Taiko2k** [comment]
Under line `21202` where it prints that error message, try insert `raise` on a line underneath. That might trigger a more detailed error.

**Comment by CyberAzure** [comment]
Like this?

```
#show_message("Error connecting to Discord", mode='error')
        gui.discord_status = "Error - Discord not running?"
        raise
        prefs.disconnect_discord = False
```

**Comment by Taiko2k** [comment]
yes (with all those 4 on the same indent of course). Then try run the program again

**Comment by CyberAzure** [comment]
Umm...nothing happens..?

**Comment by Taiko2k** [comment]
works for me

**Comment by CyberAzure** [comment]
Managed to get it to work, for some reason I got to run `sudo flatpak override com.github.taiko2k.tauonmb --filesystem=xdg-run/discord-ipc-0` again.
But, the icon doesn't show :<

**Comment by Taiko2k** [comment]
you'll need to upload your own icon, then replace the name in the code

**Comment by CyberAzure** [comment]
Now everything's working fine, thank you all! <3  ^3^

**Comment by ArthRMH** [comment]
np 😽

**Comment by CyberAzure** [comment]
Welp, after last update, my rich presence just vanished _(I knew this would happen, but I just opened gedit to edit the code again)_, and the `/var/lib/flatpak/app/com.github.taiko2k.tauonmb/current/active/files/bin/tauon.py` has no `client_id` line anymore, it just has 186 lines now.

**Comment by Taiko2k** [comment]
@CyberAzure the bulk of the code has been moved to t_modules/t_main.py. So just look for client ID there.

**Comment by CyberAzure** [comment]
Thanks! Worked just fine.
_And, still love Tauon Music Box with my heart._
