### ISSUE TITLE
Confused about Windows status

### ISSUE THREAD

**Issue by wyndon** [Taiko2k/TauonMusicBox#545]
On the project's website, there isn't any mention of Windows, but I heard about Tauon supporting Windows in the past. There's also some issues that were opened discussing about Windows releases, which were provided at the time but now they are deleted.

I'm confused. Is Windows supported ? This should probably be stated somewhere. If it's supported, installers could be provided on each release, or at least instructions on how to compile it (there's also no instructions for Linux tho).

**Comment by Taiko2k** [comment]
Basically Windows support was dropped quite a while ago now. It's mentioned in the Q&A section of the Wiki.
