### ISSUE TITLE
Add a snap package

### ISSUE THREAD

**Issue by michaelbukachi** [Taiko2k/TauonMusicBox#55]
Hello guys. Just installed this music player and I love it! One thing I found awkward was having to download a flatpak file. I didn't even have flatpak installed on my system. I would to setup a snap package, if it's alright with your guys?

**Comment by Taiko2k** [comment]
I don't think having a snap package is a bad idea, though, I'm not familiar with how snap works. 

I could look into it. Are you familiar with snap building? If you could contribute to making a snapcraft.yaml that could be good. Though, I would prefer to submit the final package to the store myself.

There's quite a few dependencies, I'm not sure it will be easy.

**Comment by michaelbukachi** [comment]
Awesome. I'll make the `.yaml` file and make a pull request so that you can do the final package submission.

**Comment by Taiko2k** [comment]
You could take a look at the flatpak manifest for reference.

A few quirky things the we'll need to look out for,

 - For python3-pylast, an unreleased git version is required (latest/master or recent commit at https://github.com/pylast/pylast
 - Bass libraries are needed in the `lib` folder of the apps root folder, for the flatpak version im getting these from a zip file I uploaded here https://github.com/Taiko2k/TauonMusicBox/releases/download/v3.4.0/basslibs64-dec2018.zip
- App needs enough file-system permissions to enable drag and drop
- The app needs permissions to be able launch other apps
- User data/cache/config folders are not used by default, currently they are used if `/usr /opt or /app` are in the CWD. I'm not sure what the filesystem looks like from a snapped apps perspective, may need to push some adjustments for this.

**Comment by michaelbukachi** [comment]
I've been going though `tauon.py` and noticed that it has a lot dependency on flatpak.

**Comment by Taiko2k** [comment]
I just support flatpak directly. There are many adjustments to make it work smoothly. Now that I think about it, I think it may be better to only use flatpak for now to keep the maintinence cost low.

I don't think it will always be hard to install via flatpak once it is better supported by distros anyway.
