### ISSUE TITLE
[Bug] Crash when opening stats menu

### ISSUE THREAD

**Issue by ggttttggggtt** [Taiko2k/TauonMusicBox#551]
Opening the stats menu crashes Tauon, with this message in terminal:

> Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 42759, in <module>
    pref_box.render()
  File "/opt/tauon-music-box/tauon.py", line 27859, in render
    self.tabs[self.tab_active][1](x + side_width, y + header_width, content_width, content_height)
  File "/opt/tauon-music-box/tauon.py", line 27409, in stats
    ddt.text((x2, y1), locale.format_string('%d', len(default_playlist), True), colours.box_sub_text, 12)
AttributeError: module 'sdl2.locale' has no attribute 'format_string'

I'm on Arch, using the AUR package, latest packages, no compositor, with a GTX 1060.

**Comment by Taiko2k** [comment]
Okay, a fix for this has been pushed and released now.
