### ISSUE TITLE
[Feature request] Search box for tracks

### ISSUE THREAD

**Issue by david-cortes** [Taiko2k/TauonMusicBox#558]
Would be nice to have an optional search box (ideally placed at the top alongside playlist tabs) that would allow typing the name of some track (to match by file name and metadata), show a list of matches, and allow double-clicking a match to start playing the playlist that contains it from that track.

**Comment by Taiko2k** [comment]
I assume you might not know about the two existing search features. You can read about them here https://github.com/Taiko2k/TauonMusicBox/wiki/Find-and-Search.

**Comment by david-cortes** [comment]
Oh, good to know, didn't realize just typing within the app would do a global search. BTW it doesn't display the file name  of matches, even though it does match file names even if the search keyword is not in the metadata.
