### ISSUE TITLE
Jellyfin: Albums order

### ISSUE THREAD

**Issue by Tau5** [Taiko2k/TauonMusicBox#583]
Right now, songs from albums imported in jellyfin are not ordered properly

**Comment by fwuffyboi** [comment]
Has this been fixed? I've currently got this issue.

**Comment by Taiko2k** [comment]
@fwuffyboi Yes that should be fixed. Did you do anything to change the sorting? To reset, right click the playlist tab and press "Regenerate". If its still not ordered correctly, could you show me a screenshot of the issue?

**Comment by fwuffyboi** [comment]
@Taiko2k ah thank you. that fixed it!
