### ISSUE TITLE
Deleted Artists / Tracks Continue to Appear in Search Results (via typing).  Remove Missing Tracks option doesn't function.

### ISSUE THREAD

**Issue by rstrube** [Taiko2k/TauonMusicBox#588]
**Version:**
6.7.1

**Background:**
I recently deleted a bunch of old music from my HD that I don't listen to anymore.  I noticed that when searching for artists that have  been deleted (by starting to type the name) results _still_ show up.  When clicking on the artist in the results screen, it takes me to their albums but all the tracks are greyed out (because they're no longer on the HD).

**What I've Tried:**
I have tried **Rescan Folder** on the primary **Music** playlist, and it _does_ appear to remove the (now deleted) artists from the primary listing of tracks, but the deleted artists still appear when executing a search (via typing the artists' names).

I have tried deleting the **Music** playlist completely, and then re-adding it via **MENU -> Import Music Folder**.  The deleted artists still appear when executing a search (via typing the artists' names).

I have also tried using the **MENU -> Database -> Remove Missing Tracks** option.  This doesn't appear to function, but it does lock the interface from searching displaying the message "Please wait for cleaning process to finish".  I've waited for 10 mins but the process never appears to complete.  Checking on CPU usage nothing appears to be running (CPU usage for tauonmb is near zero).

**Further Information**
- Exporting the Database as a CSV file and then viewing the CSV still shows that the deleted artists and tracks are still in the database.
- My music library is relatively small (about 5K)

**Comment by Taiko2k** [comment]
Yeah, specifically the issue was with a worker thread not correctly waking up after I made changes regarding power usage last release.

A new release is out now with (a hopefully) working fix. Let me know if any issues persist.
