### ISSUE TITLE
No visual feedback when adding to queue 

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#59]
There is no visual feedback when adding to queue by ctrl+q hotkey compared to MMB.

![alt text](https://ibin.co/4XicIarylmRc.png)

**Comment by Taiko2k** [comment]
Ah, I forgot activating this would need to trigger a redraw. I've commit a fix.

**Comment by StrangeSeasOfThought** [comment]
Do I need to enable this somewhere?

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought  It only shows when columns view is disabled. It's kind of an old feature, I'm not sure what to do with it.

**Comment by StrangeSeasOfThought** [comment]
Ah, it doesn't show when disabling columns view and tracks are already queued. Only on newly queued tracks.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought No, it does. Though also, this doesn't show for queued albums, only queued tracks.

**Comment by StrangeSeasOfThought** [comment]
Right, wrong playlist.
