### ISSUE TITLE
Sort by numeric order (even one digit numbers) when sorting alphabetically

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#601]
When you have "2" and "15", 15 will appear in first

for ex "Best of me Vol.15" will appear before "Best of me Vol.2" in folder tree/playlists, which can be annoying when you're trying to correctly sort a lot of compilations

**Comment by Taiko2k** [comment]
Can you tell me how it got into this state? Did you use a sort function? Or just imported?

**Comment by awsms** [comment]
I imported the folders, then sorted using the bar by clicking on the Filepath row

![Screenshot from 2021-11-14 15-26-34](https://user-images.githubusercontent.com/48278661/141685343-96a9bbbf-003e-4682-92c8-86154cb954e2.png)

**Comment by Taiko2k** [comment]
Okay I've now set filepath and filename sorting to use a natural sort. Still, if not all file names have a track number in them, you'll want to right click playlist > Sort... > Sort by Track Numbers every time.

**Comment by Taiko2k** [comment]
Due various issues im going to revert this change. One of which is that the algorithm is too slow. You can still use Sort by Track Numbers to manually fix the track numbers.
