### ISSUE TITLE
minimize the app

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#603]
The question is quite simple, how should i minimize the app?using gnome i generally minimize the apps by middle clicking (with the mouse) on the title bar, but in tauon it does not work, nor there's a button to do it...

**Comment by Taiko2k** [comment]
Tauon is respecting the gnome setting to not have a minimise button. But not being able to middle mouse click to minimise might be an oversight. So that functionality should be added.

**Comment by legacychimera247** [comment]
well you are still able (on gnome apps) to minimize by right clicking on the bar and have the usual menu, here i have nothing ot the visualizer menu

anyway, if you can make the middle click to work that would be great...

**Comment by legacychimera247** [comment]
I guess this is still open?would still be nice to have that middle click to minimize it

**Comment by Taiko2k** [comment]
Okay Ive now committed a new context menu with minimize as well as middle click to minimize.

Note that due to limitations these two new features won't work on the Windows version.

**Comment by Solarunit** [comment]
BTW you can also use `Super` + `H` shortcut

**Comment by legacychimera247** [comment]
> Okay Ive now committed a new context menu with minimize as well as middle click to minimize.
> 
> Note that due to limitations these two new features won't work on the Windows version.

ah that's great, thabk you

don't care about windows anyway as i'm on linux :)
