### ISSUE TITLE
only see albums for that artist

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#605]
if you click on an artist you are promptly sent to the first album for that artist, but you can still scroll up and down to see other artists. It would be nice to have the ability to see only albums (or songs) for that artist (maybe a tickbox in the options?)

**Comment by Taiko2k** [comment]
Part of the general design philosophy of Tauon is to not use filtered views, so I think this request is out of scope. So, basically, it's intended to be this way.

(You can right click, filter to new playlist if you really want to isolate them)
