### ISSUE TITLE
Wrong album cover

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#608]
Some albums have a wrong cover or is missing (of course cover is there) how do i modify this?

**Comment by Taiko2k** [comment]
I'm not sure exactly what you mean. Does closing and opening Tauon fix the issue?

**Comment by legacychimera247** [comment]
here's an example
![Uploading Schermata da 2021-11-10 19-42-52.png…]()

**Comment by legacychimera247** [comment]
i'll give you an example
![Schermata da 2021-11-10 19-42-52](https://user-images.githubusercontent.com/22254556/141174067-445fa103-edd2-4b13-8e13-c4cd6aa75537.png)

**Comment by legacychimera247** [comment]
wait a second, seems that my music is incorrectly tagged, which is weird but will explain the problem, guess we can close this one then...

**Comment by legacychimera247** [comment]
decided to reopen this one, despite having now set everything correctly, tauon still has the wrong cover in the album grid, how do i modify that?
![Schermata da 2021-11-10 20-00-29](https://user-images.githubusercontent.com/22254556/141176571-97955ad8-11e1-48c7-a3cb-15176325992f.png)

**Comment by Taiko2k** [comment]
Did restarted not fix it? If not try go menu > database > reset image cache.

**Comment by legacychimera247** [comment]
Ok thank you, this "should" fix the issue, i'll let you know and close the issue in case...

**Comment by legacychimera247** [comment]
that did the trick
