### ISSUE TITLE
picard not working

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#609]
hello, downloaded flatseal, granted tauon the right permissions, still says picard is not installed or needs permissions, maybe it only support flatpak picard?cause mine is in rpm...

**Comment by Taiko2k** [comment]
Are you sure you granted the right talk permission? See https://github.com/Taiko2k/TauonMusicBox/wiki/Flatpak-Extra-Steps#edit-with-picard I don't have instructions on how to to it with flatseal, just the terminal.

I know this is quite annoying. I'm hoping Flatpak will have a better solution in the future.

**Comment by Taiko2k** [comment]
Oh, you might also need to give full filesystem access

**Comment by legacychimera247** [comment]
Set either full filesystem access OR home access, maybe i need both at the same time?

**Comment by Taiko2k** [comment]
Full, plus the permission mentioned in the article above.

**Comment by legacychimera247** [comment]
So, are you telling me i need to enable all 3 checkboxes at the same time?

**Comment by Taiko2k** [comment]
All system files, which includes home so checking home is redundant I'm pretty sure.

You also need to use the terminal to give that other special permission.

**Comment by legacychimera247** [comment]
i missed the last command, i thought just giving permissions was goo enough, thank you...
