### ISSUE TITLE
song played changes if i change artist in the artist list

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#612]
So, as you suggested i'm just opening a playlist for each artist, and that was exactly what i wanted, but now, i have a problem with that. Everytime i'm listening to an artist and i open another artist on the grid, next song is the first for that new artist

example : 
1 play a song
2 click on another artist without playing it
3 when the current song finish the current record does not continue and next song is from the new artist

don't know if it's intended but it's very inconvenient, at least in my opinion

**Comment by Taiko2k** [comment]
Right, okay. That behaviour wasn't strictly unintended but that seems like a good idea that it should continue and not change to the new artist.

I've committed this change now.

**Comment by legacychimera247** [comment]
ok thank you
