### ISSUE TITLE
Using Tauon from source makes it crash after a while

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#615]
It happens randomly. Never when I'm playing music and only when its in the background. I don't run it from terminal and instead use the provided .desktop file so I don't get any logs. Is this something you're aware of?

**Comment by Movisivi** [comment]
Going back to flatpak for now

**Comment by Movisivi** [comment]
Another issue I noticed is no crossfade when switching tracks now only on play/pause. 6.8.0 is working normally.

**Comment by Taiko2k** [comment]
> I don't run it from terminal and instead use the provided .desktop file so I don't get any logs

A log would be helpful. You can use something like `journalctl --since "5 min ago" | grep tauon`.

> Another issue I noticed is no crossfade when switching tracks now only on play/pause.

Likely it fell back to the GStreamer backend. You need to run `bash compile-phazor.sh`, then switch to Phazor in the audio settings of Tauon.

**Comment by Movisivi** [comment]
I hadn't compiled phazor. Let's see if that solves it

I mostly see a bunch of Gstreamer unloaded  messages, nothing useful it seems, runs in portable mode, shows my scrobbles. This is the only thing that stands out to me

https://pastebin.com/9sRSHg7D

**Comment by Movisivi** [comment]
So I finally got dependencies and successfully compiled phazor. Now when I try to set it in the settings Tauon stops responding and all I can do is force quit. Here's the log

Using crash workaround for gdk crash
/usr/lib/python3.10/site-packages/gi/overrides/Gdk.py:329: DeprecationWarning: Gdk.Cursor.new is deprecated
  return cls.new(*args, **kwds)
Database loaded in 0.019 seconds.
Applying scale based on xft setting
Using UI scale: 1.0
Start controller server
Init GStreamer...
Using SDL version: 2.0.16
Applying theme: Turbo
Device not found, fallback to PulseAudio
Exception in thread Thread-4 (player3):
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mjbrm/github/TauonMusicBox/t_modules/t_gstreamer.py", line 968, in player3
    player = GPlayer()
  File "/home/mjbrm/github/TauonMusicBox/t_modules/t_gstreamer.py", line 98, in __init__
    self._output = Gst.parse_bin_from_description(
gi.repository.GLib.Error: gst_parse_error: specified empty bin "bin", not allowed (5)

(tauon.py:24222): GStreamer-CRITICAL **: 13:35:25.645: gst_device_monitor_dispose: assertion '!self->priv->started' failed
Auto save playtime
Device not found, fallback to PulseAudio
Device not found, fallback to PulseAudio
Device not found, fallback to PulseAudio
Device not found, fallback to PulseAudio
Device not found, fallback to PulseAudio
Device not found, fallback to PulseAudio
Device not found, fallback to PulseAudio
Reload backend...
Killed

**Comment by Movisivi** [comment]
Btw please update flatpak to 6.8.2 already

**Comment by Movisivi** [comment]
Sleeping on it, it looks like it wasn't setting cause I was clicking the Phazor option too many times(?) causing it to freeze. Its set successfully now. So the Github Tauon is setup the same way as the Flatpak version now. Now let's see if it crashes.

**Comment by Taiko2k** [comment]
Yeah switching the backend is a little rusty

**Comment by Movisivi** [comment]
So I used it all day yesterday, through the .desktop and through terminal, and it hasn't crashed once. Switching to Phazor seemed to have helped. I think I can safely close this now.
