### ISSUE TITLE
Display Bit depth + Sample rate for lossless files instead of bitrate

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#617]
Since bitrate information is completely useless for lossless files, wouldn't it be better to display the bit-depth and sample rate instead? (for ex. "996kbps" would become 16bit / 44.1kHz)

To clarify, I'm talking about the "Bitrate" row in the "Columns view" mode.

**Comment by Taiko2k** [comment]
Okay this is how I got it looking:


![Screenshot from 2021-11-21 22-29-39](https://user-images.githubusercontent.com/17271572/142756753-338573b7-26b0-4f6a-8f86-9e7959b08933.png)
