### ISSUE TITLE
Auto-name doesn't work for the Default playlist

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#62]
Auto-name doesn't work for the Default playlist.
flathub version 3.7.0

**Comment by Taiko2k** [comment]
Just delete it and make a new playlist then :grin:

I'm not sure this is desired behavior anyway, if the user opens files using 'open with...' they go here, so they might not want this playlist to be renamed.

**Comment by Solarunit** [comment]
I think you're right. Not a problem to delete it.
