### ISSUE TITLE
Audio cuts out at random when seeking

### ISSUE THREAD

**Issue by ggttttggggtt** [Taiko2k/TauonMusicBox#622]
I'm using the AUR package on Arch with Phazor (haven't tried Gstreamer) and Pipewire. It seems like there's a small chance on seek for the audio to cut out completely, and it can be fixed by restarting Tauon. I was spam clicking in the video, but it can happen when seeking normally. 

https://user-images.githubusercontent.com/87790164/143484203-0e34c212-8ca3-4463-92f5-e81e11064852.mp4

**Comment by Taiko2k** [comment]
OK I can replicate this. 

Looking into it, I understand part of why it's happening but the root cause it quite elusive. Disabling compiler optimisations seems to make the issue go away. Might have to just leave those off :/

**Comment by Taiko2k** [comment]
Okay I think I found and fixed the bug. Ill need to do more testing and see if the issue comes up again.

**Comment by Taiko2k** [comment]
v6.8.2 is out now with my attempted fix. Let me know if this issue happens again.
