### ISSUE TITLE
[Feature Request] Pattern style background outside of showcase

### ISSUE THREAD

**Issue by ggttttggggtt** [Taiko2k/TauonMusicBox#623]
It would be nice to be able to use the pattern style album art on all backgrounds instead of just the showcase, and you also can't currently enable it for the showcase without disabling album art backgrounds for the main screen.

![image](https://user-images.githubusercontent.com/87790164/143485964-35e9ffd3-e102-42dc-a10c-8bc3b9535425.png)

**Comment by Taiko2k** [comment]
Well I think the pattern only works in the showcase where nothing much obstructs it, the background is also able to be brighter there so it has better effect, it wouldn't really work in other areas.
