### ISSUE TITLE
Pressing Delete in simple tag editor removes the selected entry from playlist

### ISSUE THREAD

**Issue by maurice1** [Taiko2k/TauonMusicBox#624]
Using v6.8.1 (Fedora 35, Wayland, Flatpak).

Pressing Delete not only deletes a character in the focused text field, it removes also the currently selected item from the playlist (the one the meta tags are edited) and closes the simple tag editor window at the same time.

I think the Delete key should affect the tag editor's text field, only. ;-)

**Comment by Taiko2k** [comment]
Okay, I've committed a fix for this now.
