### ISSUE TITLE
Cannot add music when running from terminal on WSL Ubuntu 20.04

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#625]
I dug up an old Elitebook 8570W (16GB RAM, i7-3740QM, Nvidia Quadro K200M) from my closest for shits and giggles and loaded Fedora 35 on it. First thing I installed was Tauon. I was going to build from source but decided against it for this machine. Did the usual setup for Flathub installed it and nothing opened when I ran it. Terminal output is this

No previous window state
X Error of failed request: BadAlloc (insufficient resources for operation)
Major opcode of failed request: 147 ()
Minor upcode of failed request: 7
Serial number of failed requests: 103
Current serial number in output stream: 107 (this changes between 107, 105, and 110 everytime I do flatpak run com.github.taiko2k.tauonmb)

**Comment by Movisivi** [comment]
Just built it, it works as expected. But not in Flatpak hm

**Comment by Movisivi** [comment]
Gonna shift the topic to a PC I actually use.

I got it all set up with WSL on Windows 11 22000.348. It opens up fine but I am unable to add music. I chose to build it from source to try to bypass the whole permissions thing with flatseal but it looks like it didn't work haha.  Flathub behaves the same way. Is it possible for you to tweak this app to work in this setup?

**Comment by Taiko2k** [comment]
I'm not really keen on providing explicit support for WSL, you'll have to be on your own there. Or you could try ask in the discord server if anyone else has got it working.

Just giving access to all files in flatseal should solve the permission issue. Perhaps there's another reason its not working.

**Comment by Movisivi** [comment]
Closing since I mainly use  Fedora as my daily driver
