### ISSUE TITLE
Path sorter seems to be broken

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#626]
Updated to 6.8.1 (from 6.7.1) today and noticed my playlists weren't being sorted properly anymore. After a bit of playing around with the generator settings I think `ypa` is no longer working correctly. If I remove it and put it back it still sorts it differently, just not as expected (like albums from 2019 being put after 2021 ones for the same artist, etc.).

**Comment by Taiko2k** [comment]
I think *think* there's anything wrong with ypa itself. Are you sure those artist have the exact same name and are already listed sequentially in the playlist?

**Comment by Bauke** [comment]
Hmm, now that I've looked again it may be `path` instead. My main playlist uses `self a path ypa tn auto` as the generator and I'm getting stuff that (I don't think is correct). In the image below it seems like every <random> amount of artists it "resets" the sort (marked with yellow lines).

<details>
<summary>Playlist & directory</summary>

![image](https://user-images.githubusercontent.com/19501722/143664915-748357a3-6524-4503-ac8e-fcc53d9e3e60.png) ![image](https://user-images.githubusercontent.com/19501722/143664994-40ceb142-1417-468d-a4ee-f45240cfb60d.png)

</details>

I also just tried to delete and recreate my main playlist all my other ones source from and if I make that main playlist use a generator with `path` in it it messes up but if I don't touch it and import it it sorts by path like expected. Then once I do `path` in any of the other playlists they mess up.

<details>
<summary>Main playlist imported without generator set</summary>

![image](https://user-images.githubusercontent.com/19501722/143665154-fc376681-5ad5-49b6-b193-f4585dbcd78e.png) ![image](https://user-images.githubusercontent.com/19501722/143665230-903f64da-eb32-40e6-b69f-44960f4728c9.png) ![image](https://user-images.githubusercontent.com/19501722/143665264-9797abd8-de52-4a7e-823f-f0a9858dc599.png) ![image](https://user-images.githubusercontent.com/19501722/143665343-29acdac8-5fcf-452f-835e-7fad2d8129b4.png)

</details>

**Comment by Taiko2k** [comment]
Ah yep I see now, `path` is indeed broken this update due to some changes I attempted, ill revert those and push an update soon.

**Comment by Taiko2k** [comment]
Okay v6.8.2 release is out now. This should be back to normal now

**Comment by Bauke** [comment]
That seems to have done it! Thanks as always for the quick response! :heart:
