### ISSUE TITLE
Output plugin question

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#63]
I've noticed that Tauon uses Alsa plug-in [python3.7]
Why not a PulseAudio Output plugin? 
Deadbeef player on my system has some problems with Alsa plug-in and works fine with PulseAudio.

![alt text](https://ibin.co/4Z6G3nXsCMgv.png)

**Comment by Taiko2k** [comment]
Native Pulseaudio support would be desirable, but unfortunately the library I'm using only supports ALSA.

**Comment by Solarunit** [comment]
I just thought that some problems I had yesterday with sound are related to Alsa plug-in. Not sure, maybe it is just a new system updates.
Today player works fine.

**Comment by Taiko2k** [comment]
As long as it works alright, I don't suppose its too much of an immediate problem.

**Comment by legion1978** [comment]
one thing i notice is that, when the computer is performing some cpu intensive operation or its short in memory, sometimes it chokes, causing tauon to jump to the next song. its kinda when the vinyl needle jumps on scratched disks :v dont know if this is normal or what. :)

**Comment by Taiko2k** [comment]
@legion1978 Currently there is some code that detects a stall and will jump to next track. This was intended to avoid getting stuck on corrupt files. Perhaps I should adjust this.

As for the stuttering in the first place... I'm not sure exactly why, it does seem to be sensitive to low cpu/mem/diskIO resources.

**Comment by legion1978** [comment]
yes it is something extreme indeed, not the rule. and its more likely a resource problem, not tauon :) it makes sense to skip corrupt files so its helpful.

**Comment by Solarunit** [comment]
I had a browser with > 30 opened tabs yesterday but there were a lot of free cpu/memory. 
I heard stuttering and at the same time this area was blinking.  

![alt text](https://ibin.co/4Z6G3nXsCMgv.png)
