### ISSUE TITLE
Can Ctrl+F be launched with global search UI overlay?

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#632]
Title. I would  like to be able to search the songs in the playlist I'm currently in as opposed to everything in my library.   Is it possible to have Ctrl+F rerouted to the global search transparent overlay that shows up when you start typing instead of that search box?

**Comment by Taiko2k** [comment]
These two do function a bit differently. The ctrl f one is more like a *find*. Having a shortcut for the global search is redundant.

**Comment by Movisivi** [comment]
Interesting. Good to know.
