### ISSUE TITLE
Album art and gallery panel incorrectly remember size when Tauon is resized heavily

### ISSUE THREAD

**Issue by ggttttggggtt** [Taiko2k/TauonMusicBox#633]
Using most recent AUR on Arch. Size is messed up when resizing and isn't fixed by toggling panels or restarting Tauon.

https://user-images.githubusercontent.com/87790164/146294764-d68607a0-6c0a-47bf-b5be-72bdd102b408.mp4

**Comment by Taiko2k** [comment]
Okay I've committed a hopefully working fix for this

**Comment by Taiko2k** [comment]
Let me know me if you consider this fixed now with v7.0.0
