### ISSUE TITLE
Repeat/shuffle buttons don't work in Mini Mode

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#64]
Repeat/shuffle buttons don't work in Mini Mode.
Also track name without tags is not visible in Mini Mode.

**Comment by Taiko2k** [comment]
Yes I forgot about tracks that don't have tags, I will fix that.

As for the repeat/shuffle, they do work don't they? Perhaps there needs to be better visual feedback for switching them.

**Comment by Solarunit** [comment]
> As for the repeat/shuffle, they do work don't they? Perhaps there needs to be better visual feedback for switching them.

Yes they do work. I meant visual feedback.

---
I like the new Mini Mode, not sure if I will use it though.
I have some ideas about Mini Mode.

1. Mini Mode can be even more minimal. Overlay transparent bar on the cover art can be used. But current implementation is more practical.

2. Simple playlist side panel at the left/right side or bottom. And the hidden button - show/hide simple playlist.

**Comment by Solarunit** [comment]
udp

Tracks that don't have tags are not visible in UP Next Queue.

**Comment by Taiko2k** [comment]
I have fixed the titles not falling back to filename, and I've now given the mode buttons a fade animation so interacting with them now should be more intuitive.
