### ISSUE TITLE
ValueError: NULL pointer access

### ISSUE THREAD

**Issue by ariflukito** [Taiko2k/TauonMusicBox#641]
Hi Taiko2k,

I have problem opening TMB. Here is the error I got

```
Traceback (most recent call last):
  File "/usr/bin/tauonmb", line 194, in <module>
    w = raw_image.contents.w
ValueError: NULL pointer access
```

Couldn't find anything on crash.log.

I'm on Arch Linux. The TMB version is 6.8.3-2.
Thank you.

**Comment by Taiko2k** [comment]
I'm not sure why this would happen. Maybe try re-install TMB, and do a system update too.

**Comment by ariflukito** [comment]
No luck unfortunately. System is up to date and I have uninstalled, cleared cache and reinstalled.

**Comment by Taiko2k** [comment]
How are you installing / running Tauon? `"/usr/bin/tauonmb"` doesn't seem normal.

**Comment by ariflukito** [comment]
I installed it from AUR. Have tried installed it manually without AUR helper but same issue.

**Comment by Taiko2k** [comment]
In the terminal output, what path does it give for "Install directory:"?

**Comment by ariflukito** [comment]
I get this if I'm running it from install dir
```
❯ /opt/tauon-music-box/tauonmb.sh
Tauon Music Box v6.8.3
Copyright 2015-2021 Taiko2k captain.gxj@gmail.com

Window size: [1223, 787]
GTK theme is: materia-compact
Running from installed location
User files location: /home/ariflukito/.local/share/TauonMusicBox
Found XDG-Downloads: /home/ariflukito/Downloads
Found XDG-Music: /home/ariflukito/Music
Install directory: /opt/tauon-music-box
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 240, in <module>
    exec(main)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 757, in <module>
    from t_modules.t_lyrics import *
  File "/opt/tauon-music-box/t_modules/t_lyrics.py", line 22, in <module>
    from PyLyrics import PyLyrics
ModuleNotFoundError: No module named 'PyLyrics'
```
Ok I sort of fixed it. I had to rebuild python-pylyrics.
Thank you for your help Taiko2k.
