### ISSUE TITLE
[Question] How to represent play count as numbers?

### ISSUE THREAD

**Issue by undergroundwires** [Taiko2k/TauonMusicBox#642]
On settings I can represent playcount as `-` or stars. But I'd like to see the exact numbers how many times a song is played. Is it possible to do so?

Thank you a lot for creating and maintaining project. Finally I found a music-player that looks exactly as I want and have all last.fm integrations (love button, scrobble) implemented perfectly. It's only matter of time this player will be considered best and one of the most populars (if not).

**Comment by Taiko2k** [comment]
This is possible in columns view by adding the playcount column.

**Comment by undergroundwires** [comment]
I did not see the column mode, now I have it, thanks for the quick feedback and happy new year!
