### ISSUE TITLE
Exception causes a drop in the broadcast

### ISSUE THREAD

**Issue by ggttttggggtt** [Taiko2k/TauonMusicBox#643]
![Untitled](https://user-images.githubusercontent.com/87790164/147860948-a96ed40d-1b89-4384-8166-50a71166eb94.png)
I'm broadcasting a playlist to a friend and I keep getting this error. Whenever this happens it drops out for both of us and reconnects after a few seconds, about 2-4 times during each song.

**Comment by Taiko2k** [comment]
Does it still happen when only one person is connected?

**Comment by ggttttggggtt** [comment]
The same error happens with just me connected.

**Comment by Taiko2k** [comment]
Ah yes, I can confirm I can replicate the issue.

**Comment by Taiko2k** [comment]
Okay I've committed a fix now this now.

There was a bug in tauons power management causing a broadcast related component to sleep when it shouldn't, indirectly causing the stream to be marked as ended.

I'm currently in the process of preparing Tauon for v7.0.0, so this might not be out for a few weeks unfortunately.
