### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by rama-2402** [Taiko2k/TauonMusicBox#647]
Im running pop_os! 21.10. The app was working fine until i made a system update from pop shop. It did some flatpak runtime updates. After that i'm getting app crash whenever I open the music player. I ran the flatpak command to run and got this response after app crash. 

                                                                                                                                                                               910ms  Mon 03 Jan 2022 01:49:02 PM IST
Tauon Music Box v6.8.3
Copyright 2015-2021 Taiko2k captain.gxj@gmail.com

Window size: [799, 677]
Gtk-Message: 14:53:40.831: Failed to load module "appmenu-gtk-module"
Gtk-Message: 14:53:40.889: Failed to load module "canberra-gtk-module"
GTK theme is: whitesur-dark-solid
Detected running as Flatpak
Installed as Flatpak
User files location: /home/void/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/void/Downloads
Found XDG-Music: /home/void/Music
Install directory: /app/bin
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 240, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 658, in <module>
    import pylast
  File "/app/lib/python3.9/site-packages/pylast/__init__.py", line 42, in <module>
    __version__ = pkg_resources.get_distribution(__name__).version
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 471, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 347, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pylast' distribution was not found and is required by the application

**Comment by Taiko2k** [comment]
Yep, just tried it myself and it looks like this latest runtime update has indeed borked it. I've issued a rebuild and that seems to have fixed it. So you should be able to do another `flatpak update` now (or soon) to fix it. (It may take some time as of this post for the updated build to roll out to Flathub)

**Comment by rama-2402** [comment]
Thank you. Closing the issue :)

**Comment by Taiko2k** [comment]
Flathub seems slow today, so actually it might take a while before the update is available, idk.
