### ISSUE TITLE
Tauon doesn't save login creds for Airsonic or Jellyfin

### ISSUE THREAD

**Issue by winteriscariot** [Taiko2k/TauonMusicBox#648]
This is for Tauon installed on Arch Linux via the AUR, and I've tested it on 2 different computers.

My server has both Jellyfin and Navidrome (airsonic API) installed, and pointed to the same music library. It works when I freshly enter my credentials, but stops working after restarting the application and requires me to re-enter my password in the Accounts settings.
 
In the case of Jellyfin I can click the 'Test Connectivity' button after launching (but before re-entering creds) and I get a 401 error.

Not sure where I should be looking on this.

**Comment by winteriscariot** [comment]
Tested the Flatpak install and it appears that with this install it does preserve logins. AUR is the version that runs into this.

**Comment by winteriscariot** [comment]
Just tested this using the flatpak version, and the issue persists. Still need to re-input airsonic credentials whenever I open the program.

**Comment by Taiko2k** [comment]
I can seem to replicate this. Is anything else not seeming to save, like imported tracks? I can only think that Tauons config file isn't being written.

You're not force closing Tauon on exit are you?

Can you check the terminal output for crashes (especially on exit)

**Comment by winteriscariot** [comment]
the tracklist is saved. when i open Tauon and double click a song in my 'Jellyfin Collection' tab (does the same thing with Airsonic and Navidrome, though i've stopped using those and only use jellyfin now) i get a 401 error. i think have to go update the password in settings, and then i'll be able to successfully play music from jellyfin.

> You're not force closing Tauon on exit are you?

i normally right-click > close from the taskbar, or else from the systray icon. to make sure everything was clean, i opened it from the terminal (see below), got a 401 error (indicated by the 'Abort for error' line in the terminal output below), updated my password, played a few songs, then selected Exit from the menu. 

> Can you check the terminal output for crashes (especially on exit)

`> tauon
Tauon Music Box v7.1.0
Copyright 2015-2022 Taiko2k captain.gxj@gmail.com

Window size: [1084, 900]
GTK theme is: whitesur-dark-solid-orange
Running from installed location
User files location: /home/ryne/.local/share/TauonMusicBox
Found XDG-Downloads: /home/ryne/Downloads
Found XDG-Music: /home/ryne/Music
Install directory: /opt/tauon-music-box
Using crash workaround for gdk crash
Database loaded in 0.046 seconds.
Applying scale based on xft setting
Using UI scale: 1.0
Pychromecast not found
Start controller server
Start PHAzOR backend...
Warning: Missing dependency Pulsectl
Using SDL version: 2.0.20
Adjust bg vertical
Applying theme: Turbo
Auto save playtime
pa: Cleanup and exit
Start PHAzOR backend...
Warning: Missing dependency Pulsectl
Abort for error
Adjust bg vertical
pa: Cleanup and exit
Start PHAzOR backend...
Warning: Missing dependency Pulsectl
Start download
pa: Connect pulse
Download done
Refill shuffle pool
Start download
Download done
Start download
Download done
pa: End of stream
Start download
Transition gapless mode
pa: Next registered while buffer was draining
pa: -- remaining was 15149
pa: End of stream
pa: Read next gapless
Download done
Writing database to disk... done
pa: Cleanup and exit
bye
`

**Comment by winteriscariot** [comment]
I do see that my password is saved in plaintext in `~/.local/share/TauonMusicBox/tauon.conf` and it is correct

**Comment by winteriscariot** [comment]
Okay I see what's happening. It looks like Tauon is scrubbing a character from my password. When I open Tauon, I'll have tauon.conf open in gedit, and gedit will notify me that after Tauon is launched, the config has changed. I look at the password line and it appears that Tauon removed a # from my password. 

I have changed my password in Jellyfin to not include a has character (#) and the issue no longer occurs.

Does Tauon perhaps scrub hashes from passwords on load, thinking that it's perhaps a comment or something?

**Comment by Taiko2k** [comment]
Oh yep, you're right. It assumes the first # is the start of the comment and lobs of the rest of the line.

I've committed an improvement in that is now will only do it if there's a space preceding the #. (Better way would be to intelligently detect if the # is in quotes but aint no one got time for that)

**Comment by winteriscariot** [comment]
Thanks!
