### ISSUE TITLE
Change music directory

### ISSUE THREAD

**Issue by geekfish69** [Taiko2k/TauonMusicBox#649]
I'm noob when its come to computers. I just installed the app and when i import music folder, it uses ~/Music as directory where i dont keep my files.
Is there anyway I can add custom music directory cuz i dont see the option in the settings.

**Comment by Taiko2k** [comment]
In this case just drag and drop the folder from the file explorer.

**Comment by geekfish69** [comment]
> In this case just drag and drop the folder from the file explorer.

Shouldn't I use vlc then? That was litteraly the point of installing the app and getting access to all of my music instead of drag and drop.

**Comment by Taiko2k** [comment]
Tauon is designed around manual management, in a similar manner as you say to vlc. You could try a different music app if that's not what you're looking for.

**Comment by geekfish69** [comment]
oh wait. after drag and drop, the app remembers the directory the next time. You can drop entire folder from other directory this way..
Sorry.
