### ISSUE TITLE
visualizer: 3 right dots are static

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#65]
Looks like 3 (right) dots are always static.

**Comment by Taiko2k** [comment]
I think its just most music doesn't have notes that high, but you're right, I should shift the upper range in a bit.

**Comment by Solarunit** [comment]
Is it possible to implement a more complex visualization, e.g. using 2 or more colors?

**Comment by Taiko2k** [comment]
Its certainly possible, I'm not sure what it should look like though. 

To make it more interesting I could shift the colour on amplitude like this:

![Screenshot from 2019-03-09 19-57-51](https://user-images.githubusercontent.com/17271572/54067538-02c54d80-42a6-11e9-9675-a836aa7bc13d.png)

Maybe make it cycle colour over time:

![Screenshot from 2019-03-09 20-03-43](https://user-images.githubusercontent.com/17271572/54067575-8121ef80-42a6-11e9-8421-2d8b625041d9.png)

As for something more complex, perhaps you could draw me a concept mock up
