### ISSUE TITLE
I cannot install using flatpak

### ISSUE THREAD

**Issue by undergroundwires** [Taiko2k/TauonMusicBox#650]
I'm on elementary OS and installing gives me:

```txt
Aborted due to failure (Failed to read commit b07a7246ce73482c71995d34c68b93505ef07e45faf1741da76cb99bf18009b1: No such metadata object ec02d1909d9ba3157650969dad7627cb19159efc1e91f687e7f4adf4f72e8f4d.dirtree)
```

The window did not load properly (it was just showing what I had in background) so I tried to reinstall it but cannot reinstall anymore.

**Comment by Taiko2k** [comment]
Try run
> sudo flatpak repair
> flatpak repair --user
> flatpak update

**Comment by undergroundwires** [comment]
This has resolved the issue, thank you @Taiko2k , you're the best. I will be your sponsor.
