### ISSUE TITLE
Hotkey to mute the music

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#654]
Hotkey to mute the music, maybe `Crtl+M` ?

**Comment by axelsimon** [comment]
Is there a reason to not use the OS's mute function instead? This has the advantage of already being assigned a keyboard shortcut, which on any keyboard with media keys will be an actual <kbd>mute</kbd> button.

**Comment by Solarunit** [comment]
@axelsimon 

I am thinking of this scenario: you want temporary mute the radio in Tauon while watching something on YouTube. You can't just pause the radio stream.

**Comment by zkldi** [comment]
Not sure this is a good idea -- global hotkeys are polluted enough as it is, and if it wasn't a global hotkey, surely you could just click the pause button while tauon is open?

**Comment by Taiko2k** [comment]
Tauon wont assign any global hotkeys itself. If it exists in the UI then sure I think it makes sense that a local keyboard shortcut can exist as well. I'm thinking <kbd>Ctrl</kbd> + <kbd>m</kbd>?

**Comment by zkldi** [comment]
`Ctrl` + `m` doesn't appear to be used by anything else at the moment, so that should be fine. I guess it makes sense actually as a local shortcut, misunderstood the OP!

**Comment by Solarunit** [comment]
> as a local shortcut,

yea, local shortcut. You can right click on the volume bar to mute atm, but a shortcut also nice to have I think. 

![](https://i.imgur.com/dHCBs7F.png)

Maybe we need also some (red) indicator inside the volume bar when in mute mode as well?

![](https://i.imgur.com/5GNtajP.png)

**Comment by Solarunit** [comment]
Another idea: what about some **fade effect** when mute/unmute just like pause/unpause has?

**Comment by Taiko2k** [comment]
> Just to check -- by mute you mean just setting the volume to 0, right? The song would keep playing, but silently.
> 
> What's the value of this over pausing with space?

Yes exactly. Well the benifit of muting is... the benifit is .. is... um... 🤔 

Well as mentioned there is the radio benifit, which allows you to keep the stream live. There could be other use cases where the user wants to keep a song playing at realtime for whatever reason.

**Comment by zkldi** [comment]
The radio stuff sounds like a good use case to be honest! I was going to look into implementing this just to get a feel for the codebase and stuff. Would you mind if I submitted a PR for this at some point?

**Comment by Taiko2k** [comment]
Just adding the mute shortcut, that should be pretty easy. So sure. Updating the existing users previous key conf is a little more annoying to do, but you can leave that out and ill do it if you want. 

Just a bit of warning, the codebase is a nightmare.
