### ISSUE TITLE
Auto rename file by metadata might cause data loss

### ISSUE THREAD

**Issue by KiriKira** [Taiko2k/TauonMusicBox#66]
I tried `right-click menu -> Meta... -> Rename Tracks` functions and in a second it renamed all of my 1600 songs, then I found that it was only 1400 songs left.(Thanks god I have backed up yesterday)
This is because tauon also renamed those songs without complete metadata, and then it renamed them as `.mp3` one by one, and finally only one song survived and renamed as `.mp3`.
The warning is showing before the action, but actually we can do it with less risk by ignore these files, right?

**Comment by Taiko2k** [comment]
You're right, though there is a warning, it may wreck havoc if you ignore it. As you say, I should change this so it skips over files if the metadata doesn't exist or the file already exists.

**Comment by Taiko2k** [comment]
Update is out. This should be fixed now.

Sorry about this one, I should have better communicated in the UI / prevented this from happening. Good thing you had a backup! *phew*

**Comment by KiriKira** [comment]
Nice work! Thank you for taking this great software to us.
