### ISSUE TITLE
[snap] No results for Tauon

### ISSUE THREAD

**Issue by bipox** [Taiko2k/TauonMusicBox#660]
Hi,

When I type 

`snap find tauon` or search for it on snapcraft.io it returns no results. 

The page exists and `snap install tauon` works. 

Sorry if this isn't the right place to report this. 

Thanks for making this program!

**Comment by Taiko2k** [comment]
I intended to have the snap de-listed, but I didn't have the right setting set to remove the store page, I've fixed that now.
