### ISSUE TITLE
[Flatpak] [BASS] Setting output alsa device fails.

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/TauonMusicBox#67]
Does this work for anyone else?

I can't seem to set output devices any more, although setting PuseAudio Sound Server works. (I've added automatic fallback for this in v3.8.1)

 - ~~Was it after updating to tauon v3.8.0?~~
 - Was it after flatpak package updated?
 - Was it after a flatpak runtime update?
 - Was it after some other system update?

**Comment by Solarunit** [comment]
> Does this work for anyone else?

No. Error.

> I can't seem to set output devices any more, although setting PuseAudio Sound Server works. (I've added automatic fallback for this in v3.8.1)
> 
>     * Was it after updating to tauon v3.8.0?

It is working in tauon v3.8.0.
