### ISSUE TITLE
Crossfading from a high-gain track into a low-gain one starts the low-gain track too loud.

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#670]
I have a library that is mostly flac but has some mp3 files mixed in. All files have replaygain tags (computed with ffmpeg via beets) and in mpd the perceived loudness is nicely uniform. However in tauon the mp3 files are *a lot* louder for some reason. This also affects the crossfade between tracks, meaning that switching from an mp3 track to a flac one will make the flac track start out very loud before it fades to its expected volume. Files of the same type are consistent in loudness as far as I've tested.

**Comment by Taiko2k** [comment]
I assume it's the MP3 that sound *wrong*?

Can you check if Tauon is detecting the replay gain for it? You can do this by mouse hovering over the volume bar in Tauon, it should show a value there if it is attempting to use reply gain.

**Comment by jansol** [comment]
It does not show anything for mp3, while I did notice it show numbers for flacs. FWIW I checked with `mid3v2` and the replaygain data is stored in the following tags:
```
TXXX=REPLAYGAIN_ALBUM_GAIN
TXXX=REPLAYGAIN_ALBUM_PEAK
TXXX=REPLAYGAIN_TRACK_GAIN
TXXX=REPLAYGAIN_TRACK_PEAK
```

**Comment by Taiko2k** [comment]
Okay I believe I found the issue. Tauon was reading the tag names as if they should be lowercase rather than uppercase, so it ended up not reading it.

I've committed a fix for this now. On upgrade you'll need to right click playlist tab and go Misc > "rescan tags".

**Comment by jansol** [comment]
Thanks for the quick response & fix!

**Comment by Taiko2k** [comment]
I'll leave this issue open for the crossfade bug. I'll try have a go at fixing that another time.

**Comment by jansol** [comment]
The crossfade problem still persists in v7.6.4 :(

**Comment by Taiko2k** [comment]
Apologies, I forgot about this. Ive committed a possible fix now. If you can test from git master (and run `bash compile-phazor.sh`)  let me know if you still encounter the issue.

**Comment by jansol** [comment]
Works great now in some quick testing!
