### ISSUE TITLE
Automatically change UI scale when moving between displays of different DPI

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#672]
Moving the window from a 1x scaled monitor to a 2x scaled one on Wayland messes up the viewport size until a manual resize is performed. The resize fixes the viewport and layout but everything is rendered tiny as the UI scale is not adjusted. For this a separate display scale factor should be kept around and the UI scale should be updated from display scale and configured UI scale when the window is moved to a different display.

SDL2 does not seem to report scale changes per se, but there is SDL_GetDisplayDPI and SDL_RenderSetScale to make life a bit easier. Not sure if there is a good way to detect that the window was moved to a different display. As a crude workaround resize events can check the new display scale since it seems they are already updating both the physical and logical sizes.

**Comment by jansol** [comment]
Oh, SDL 2.0.18 added `SDL_WINDOWEVENT_DISPLAY_CHANGED`

**Comment by Taiko2k** [comment]
> Oh, SDL 2.0.18 added `SDL_WINDOWEVENT_DISPLAY_CHANGED`

Okay that should be helpful. Though I wonder what happens when a window is partially dragged between two windows.

Though first I'll need to work on getting Tauon to be able to change scales on the fly which will be a bit of work.

**Comment by jansol** [comment]
At least on Plasma the window is primarily on one display and if parts of it are on other screens those bits simply get scaled by the compositor.

**Comment by Taiko2k** [comment]
Hmm, SDL_GetDisplayDPI doesn't quite give me what I'd expect, it seems to give the real DPI, but not the DPI that should be used for scaling. For example, for me it gives 82 but I expect it to be 96 for default 1x scaling.

Would be good to know how scaling is supposed to work (I suppose I only care about Wayland). Ideally Tauon would just be told, okay scale at 2x, then the compositor just take care of everything else.

**Comment by jansol** [comment]
Hmm, not sure if SDL exposes other ways at the moment. Looks like wayland just has a [callback](https://github.com/glfw/glfw/blob/master/src/wl_monitor.c#L102-L153) for that. I believe X11 is the only major platform that does not have such a thing and that is likely why SDL does not report it yet.

**Comment by jansol** [comment]
You might get away with just something like `displayScale = max(round(SDL_GetDisplayDPI(currentDisplay) / 96.0), 1.0)` for the time being, but obviously that is not ideal as people do sometimes use fractional scaling despite it not being supported very well.

**Comment by Taiko2k** [comment]
Btw are you running through Wayland native or xwayland? The behaviour might be different using native Wayland. Currently you need to set an environment variable to get native (this will be the default in next SDL2 version)

AUR: `SDL_VIDEODRIVER=wayland tauon`

Flaptak: ` flatpak run --env=SDL_VIDEODRIVER=wayland com.github.taiko2k.tauonmb`

**Comment by jansol** [comment]
Xwayland automatically rescales the window, making UI element sizes stay physically the same but also making evereything blurry on the 2x monitor.

With the native wayland driver I get the visual breakage described in the OP. After the resize-induced relayout the UI is fine again, just uncomfortably small since the UI elements are not resized, only their containers are (as is appropriate for a resize with static scale).

When the window overlaps both monitors the kwin compositor seems to be using the render scale of the display that covers a bigger physical portion of the window and rescaling the window bitmap for the other. Worth noting that officially wayland only supports integer factors for scaling.

**Comment by Taiko2k** [comment]
Ah okay so! in this case the logical pixel size and physical pixel size will be different by a factor of 2, so then it will be obvious the UI needs to be scaled by a factor of 2. That solves that problem.

Hard part now is getting on-the-fly scaling working in Tauon, I'll need some time to work on that.

**Comment by Taiko2k** [comment]
Okay I've committed the changes I mentioned. I can't really test it since I don't have a HiDPI monitor.

**Comment by jansol** [comment]
With the wayland driver it's crisp on both monitors now, thanks! However a couple of problems remain:

* When moving from the 1x monitor to the 2x one, the viewport does not get resized automatically (should be fixable simply by triggering a rescale when SDL sends the monitor changed event)
* The spectrum visualizer / volume meter does not get scaled correctly when moving between monitors and frequently disappears entirely until I enabled it via the right-click menu.
* Resizing the window is sometimes weird. It seems to enforce some minimum size that I don't remember seeing with x11?
  * It also occasionally lags such that it won't even update the window rect for the compositor, making it hard to see what size it will actually be.
  * Sometimes resizing just ends up with an extremely magnified view of.... some part of the UI I suppose (like 1000x size). Resizing the window back and forth for a while makes it snap back to normal.

**Comment by Taiko2k** [comment]
I would have thought just the resize event would be enough, but okay I've not committed the display change event one. I think I've fixed the visualiser one too now. I'm not sure what's causing the 3rd point. But give it a try now.

**Comment by jansol** [comment]
My bad, I forgot I was still on SDL 2.0.14, with 2.0.20 the resize seems to be enough to fix the scale.

However there seems to be something weird going on with the viewport: the viewport does not get updated until a resize when going 1x -> 2x (in the other direction it gets clipped by the smaller window frame so can't tell) and moving in both directions bumps the drawn part to 2x the size it should be on that monitor. Again, a resize redraws everything at the correct expected size and covering the full window frame.

Another thing: the cover art appears to get "maximized" when resizing the window to something small enough that there is no space for the metadata below the image and then back to the original size, which I guess is intentional. What does not look intentional is that this also happens when simply moving the window from one monitor to the other. This is probably caused by the previous problem.

**Comment by jansol** [comment]
The remaining issues might be on the SDL side it seems: libsdl-org/SDL#4563
