### ISSUE TITLE
[MODDING] Can I mod the V.5.5.5 Windows Tauon Music Box?

### ISSUE THREAD

**Issue by satanphobia** [Taiko2k/TauonMusicBox#673]
I actually **loved** that build, no problems with it by the time of this writing, I use the _Flatpak_ one on my _Linux_ and the `V.5.5.5` one on my _Windows_.

But my question is; **Can I mod it?**

Mainly the way _Discord Rich Presence_ shows _(Like issue #544)_.
I've found a way to mod themes, but didn't find the **bulk** of the code.

**Comment by Taiko2k** [comment]
I don't know how to decompile those. And Ive long lost my old build scripts.

**Comment by satanphobia** [comment]
Welp, I'll try my best to hack it and find a way to mod the D-RPC.
I'll leave this issue as closed for now.
