### ISSUE TITLE
"Represent play time as stars" vs "Represent play count as lines" is confusing

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#679]
Different wording, is the actual behavior different beyond the visual representation too? If not, the wording should be the same.

**Comment by Taiko2k** [comment]
There is in fact a difference that I'm trying to hint at by using the different wording. Stars represent total play time (mostly), lines represent play time / length.

**Comment by jansol** [comment]
Hmm could make that more explicit in the tooltips. Something like "Display times played with stars" and "Display total duration played with lines (normalized by track length)"
