### ISSUE TITLE
Visual helper when dragging song to a playlist to prevent duplicate

### ISSUE THREAD

**Issue by nicolnt** [Taiko2k/TauonMusicBox#681]
I use to create a lot of duplicates inside playlists because I often don't remember if I added the song into it before.
I am suggesting a visual helper that would fade playlist names where the song being dragged is already in.

### For the sake of an example
I am dragging song "_Bon Entendeur/Pierre Bachelet - Coup de tête_", it is already in plyalists "Musique", "Ambiance bar", "Chill", "Late night chill", "Nostalgie" and "80's", 
#### Suggested greyed out effect
It would trigger the effect only during dragging
![Screenshot_TauonMusicBox_feature enabled](https://user-images.githubusercontent.com/12377588/153722420-132aa236-a1bc-4679-b7df-4607f8f92db8.png)

#### Current behavior, no greyed out effect:
![Screenshot_TauonMusicBox_current behavior](https://user-images.githubusercontent.com/12377588/153722481-d6c16b43-55c6-4e68-8d7f-40f25a3f357e.png)

Hope it makes sense :-)

**Comment by Taiko2k** [comment]
I think greying out might be misleading as that would more indicate that you can't drag to those playlists when its still possible.

I've gone and committed my own variation of this feature request that uses yellow bar indicators to show if a playlist already has one or more of the dragged tracks in it. I've also added a red indicator to show if a playlist cannot be dragged to which was kind of needed. 

<img width="551" alt="Screenshot 2022-02-14 at 11 45 46 AM" src="https://user-images.githubusercontent.com/17271572/153778767-ed6402e5-c972-4f87-9b09-0c600be47117.png">

**Comment by nicolnt** [comment]
You're developing things so fast, thank you!!
Very relevant approach btw, much clearer than a grey out effect
