### ISSUE TITLE
Should Ctrl+F be an alias for the normal search menu?

### ISSUE THREAD

**Issue by zkldi** [Taiko2k/TauonMusicBox#684]
The normal search menu is prettier, more intuitive and can highlight multiple matches in a fuzzy manner.

Related: I think the discovery of the normal search feature at the moment is a bit weird too. Maybe adding a button for it would help?

**Comment by Taiko2k** [comment]
I'll maintain that ctrl f is for find rather than search. There is a button for global search in the *playback* hamburger menu. Thing is having a button on the main UI for it is entirely requndent once you know how to use it.
