### ISSUE TITLE
Track info is gone from the side panel

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#685]
One of the last few commits seems to have done something to the side panel, now it only shows the cover art, but no metadata fields like it used to.

**Comment by Taiko2k** [comment]
Can you post a screenshot?

**Comment by jansol** [comment]
In 7.1.0 it was showing the title + artist + some other metadata below the cover. (Would also love to have it show arranger / lyricist / performer there). Now it seems to show them below the playback progress bar.
![image](https://user-images.githubusercontent.com/2588851/154159874-355cf796-a61b-49fd-9a2e-1d7b8e1f6e3a.png)

It does show them there when I switch to "Use centered style" so maybe something with the cover art using up the full height regardless of image size otherwise? Speaking of which, it would be nice to have a "Keep aspect ratio" under "Zoom album art to fit"

**Comment by Taiko2k** [comment]
"Use centered style" will show it in this situation, otherwise you just need to resize/shrink the panel toward the right. Since in that screenshot its wanting to fill the whole area with the cover art (and zoom to fit is not enabled).

**Comment by jansol** [comment]
Oh, I didn't notice that the panel is resizeable.
