### ISSUE TITLE
Allow setting background cover art brightness with a slider

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#687]
What it says in the title, on my secondary screen anything darker than 50% grey in the original image ends up looking almost the same since the brightness of that monitor is set very low. And that is with "stronger" enabled. Shouldn't hurt to allow setting the bg strength with a slider / combobox.

Also, it would be neat to have the option of using "pattern style" in the regular view as well.

**Comment by Taiko2k** [comment]
I get what you're saying.

Thing is allowing the brightness too high, it tends to not look good I think. There actually used to be a 3rd selectable brightness setting (i.e. "Extra Strong"),  Here's an example of what that can look like:

![Screenshot from 2022-02-16 14-18-33](https://user-images.githubusercontent.com/17271572/154178016-66009c1d-ee54-4d7f-a9c3-f9bf8419dacc.png)

Its not great I don't think.

For the pattern style. I don't think it will work. Rendering text and fine UI components over a noisy background doesn't look good.

**Comment by jansol** [comment]
That looks just about right for my secondary screen, which is where I keep tauon most of the time. Just on the upper end of how bright I'd make it on the primary screen though, so understandable. Still, I think having the brightness on a slider won't hurt anyone? Maybe make it snap to the current "default" and "stronger" spots. Or provide a combobox so one can specify the exact numeric value.

As for the pattern style, it is a lot less noisy when the text is scaled 2x (assuming the pattern scale stays the same) :wink:
