### ISSUE TITLE
[BASS] Audio garbled when starting to play something

### ISSUE THREAD

**Issue by Clleb** [Taiko2k/TauonMusicBox#69]
I had this issue occasionally in past versions and I just assumed it might have been me doing something stupid, but this version I seem to get this more often so I figured I might as well report it.

Sometimes when a new track starts to play (most often happens when double-clicking thing to play it), the beginning audio will be garbled for 1-2 seconds, rarely it will remain garbled until I skip a few tracks or close and reopen the window.
Just gonna dump my settings for relevant info:

![Selection_333](https://user-images.githubusercontent.com/45979212/54078377-912cd580-428c-11e9-86b7-50bb18cf1de7.jpg)

And I do have a last.fm account connected and scrobbling actively.

**Comment by Taiko2k** [comment]
Could you tell me what distro you're using?

**Comment by Clleb** [comment]
Distro is Mint 19

**Comment by Taiko2k** [comment]
I'm not sure what whats causing it exactly, but it might be useful to take note of what version of pulseaudio you're using. Could you give the output of `pulseaudio --version`

If it happens often and you're willing to experiment, it may be interesting to know if it occurs when outputting to a device directly (bypassing pulseaudio), to do that you would to have a spare output device (it will fail if you try set it to your default / whats currently in use by the desktop) and set the permission `sudo flatpak override com.github.taiko2k.tauonmb --device=all` to see the full list of output devices.

**Comment by Clleb** [comment]
Sorry for late reply, output of that is pulseaudio 11.1

**Comment by Taiko2k** [comment]
I suspect it may be an issue with that version of Pulseaudio. Maybe once Mint upgrades to 12.2 the issue will go away. 

In the next version of Tauon, I've added a setting that allows changing the buffer length, there may be a small chance that increasing that value could also fix it.

**Comment by Taiko2k** [comment]
So, in the latest release, try increase the device buffer length (Under settings > audio) to something like 60ms. Probably wont fix it but who knows.

**Comment by Clleb** [comment]
I've set it, will play around with this and report back in a couple days of use.

**Comment by Clleb** [comment]
Update: playing around with the buffer length has seemingly made it occur less frequently and made it so that I can just restart the program if it doesn't fix itself after a couple of song changes. A decent improve at least :)

**Comment by Taiko2k** [comment]
Sorry for the bump. Just closing this.

I would say just use the GStreamer mode for anyone encountering this issue.
