### ISSUE TITLE
Certain files fail to play (flac-in-id3)

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#690]
So I have a couple of flac albums that works fine in mpd, elisa and mpv but fails to play in tauon and when trying to serve it to a web browser in an `<audio>` tag. Tauon manages to extract all metadata successfully so that part is fine, just trying to actually play any of these files fails. Neither ffprobe nor the reference flac decoder see nothing wrong with the file. Fun.

I randomly looked at the hexdump of a problematic file and it started making a lot more sense why that might be: it's actually an ID3 container with FLAC data inside (for some reason ffprobe did not mention that at all). Applications that only look at the first few bytes to decide the type find an (empty) ID3 container and conclude that there is nothing to see. "simpler" applications just see the filename ending in .flac and blindly feed it to the flac decoder (which knows to skip extra stuff in the stream) and everything is fine. Fancier applications would scan the file and notice that it has a flac header after the ID3 block and decode from there.

This is apparently sort of a valid thing to do, and the reference flac decoder handles it gracefully but at the same time [the flac FAQ](https://www.xiph.org/flac/faq.html#general__tagging) mentions that one should not expect it to work and that it may cause applications to fail to decode the file/stream at all. Not sure if it's worth bothering with this as I can simply remux the files to make them work, but I decided to report this since most other players seem to handle them just fine as they are.

**Comment by jansol** [comment]
At least all the affected files that I have seem to be working now. Might be worth checking for other supported filetype headers too, idk. Also, it seems that ID3v2 at least specifies[1] the byte size of the ID3 data right at the start, so instead of blindly reading into the tag, tauon could read the header size and seek ahead by that much. Mutagen also provides this info[2] but having mutagen first parse the whole thing only to know how far to skip is a bit unnecessary.

[1]: https://id3.org/id3v2.4.0-structure
[2]: https://mutagen.readthedocs.io/en/latest/api/id3.html#mutagen.id3.ID3.size

**Comment by Taiko2k** [comment]
Ill close this now. If anyone runs into a file that wont open then a new issue can be made.
