### ISSUE TITLE
State of Windows support (if any?)

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#693]

**Comment by Movisivi** [comment]
I found an old download link to 2.8.3 and it works pretty good. It's missing a lot of the features the current Tauon has obviously but its so fast and better than MusicBee. I'm just curious if there's plans to restart Windows development.

**Comment by Movisivi** [comment]
That's what I figured but its still unfortunate to hear. Glad to see there's a much newer version available. Appreciate it.

Would it help any if I said I'd pay you? Like for real. Or is it just too much work to even bother porting everything?

**Comment by Taiko2k** [comment]
> Would it help any if I said I'd pay you? Like for real. Or is it just too much work to even bother porting everything?

It does take a lot of work, its not just pressing a button and producing a build. And the time I have to spare on development is at a premium. Like sure enough money would persuade me, but I would consider that, lets just say more needing to be like a corporate sponsorship level, as opposed to a individual sponsorship level, I feel.
