### ISSUE TITLE
Auto export not always working

### ISSUE THREAD

**Issue by nicolnt** [Taiko2k/TauonMusicBox#696]
I am reaaally enjoying the new feature combo (auto-export and drag and drop playlist indicator)!
I'm having issues that I can't really understand with the auto-export feature: it does only work when I manually exported the playlist during the current session.
My settings are as screenshot below
![image](https://user-images.githubusercontent.com/12377588/155756623-9c90634f-d3d9-488d-a9ec-c359b49d9c4a.png)

At the moment when I drag a new track in playlist called "90's" it doesn't update the playlist file (same situation if I remove a track from it). But if open the export dialog and click export, now it will automatically export while Tauon is open, if I quit and open again it would no longer work.

**Comment by Taiko2k** [comment]
I've looked into it and indeed found a major fault which is likely the cause. I've committed a fix and will push a new release within the next day or so.

**Comment by nicolnt** [comment]
Works fine now, thanks a bunch!
