### ISSUE TITLE
AUR package fails to build without libsamplerate

### ISSUE THREAD

**Issue by rstrube** [Taiko2k/TauonMusicBox#699]
Hello!

I recently switched from Gnome to KDE Plasma and during my system setup process I was unable to install my favorite music player TMB.  Specifically I had a problem compiling phazor.  The error message stated that it couldn't locate the `samplerate` package.

I solved the problem by manually installing `libsamplerate` and then attempting the installation again.  Could you please add this to the PKGBUILD as a dependency?  My guess is that the Gnome DE has this as a dependency, but KDE plasma does not.

**Comment by Taiko2k** [comment]
Yeah looks like I forgot to add that, or wrongly assumed it was already an indirect dependency. I've gone and added it to the PKGBUILD now.
