### ISSUE TITLE
[Feature Request] Lyrics View hotkey

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#70]
There is a Tab key to switch between Tracks+Art view and Gallery view. I think having a Lyrics View hotkey would be very useful. Maybe ctrl+tab, shift+tab

**Comment by Taiko2k** [comment]
There actually is, its <kbd>F5</kbd>. But perhaps I could change it if that is an inconvenient shortcut.

**Comment by Solarunit** [comment]
Ohh, nice! Didn't know about this. No problem then =)
