### ISSUE TITLE
Pulseaudio sink (output) is sometimes changed on song change

### ISSUE THREAD

**Issue by axelsimon** [Taiko2k/TauonMusicBox#701]
Sorry, not much more detail than that, i've noticed that "recently" (past few months?) TMB now sometimes change its output pulseaudio sink, for intance i'm listening in bluetooth earphones and the sound starts coming out of the built-in analog stereo output when the next song starts.

Happy to try and provide more useful details.

This is TMB v7.0.1 as a Flatpak on Fedora 35.

**Comment by Taiko2k** [comment]
Is this with the GStreamer backend selected?

**Comment by axelsimon** [comment]
Yes, with GStreamer backend. I've updated to v7.1.3, i'll keep an eye out to see if it happens!

**Comment by Taiko2k** [comment]
I'm kind of trying to move away from using the GStreamer backend so not keen on spending time fixing it. I assume you selected that backend for the bluetooth support. Does your distro use pipewire yet? I heard it has bluetooth support.
