### ISSUE TITLE
[Feature Request] Track pre-caching for network users

### ISSUE THREAD

**Issue by farahnur42** [Taiko2k/TauonMusicBox#704]
I would like Tauon to pre-cache tracks when playback starts (in e.g. /tmp) for people accessing their music library over a network, whether it be from a Samba/NFS share, Jellyfin, Subsonic and Airsonic and what not. This would (/should) make playback in these cases more reliable and less reliant on network stability.

**Comment by jansol** [comment]
Somewhat related to #698

**Comment by Taiko2k** [comment]
This is done now. By default it will now use /tmp, but theres now also a setting to change it to a persistent location
