### ISSUE TITLE
Flatpak Tauon - Album tracks not grouped properly when adding songs outside of Music Folder

### ISSUE THREAD

**Issue by Roddyboii** [Taiko2k/TauonMusicBox#705]
Most of my songs are in my external hard drive. I can't really add it as a folder in flatseal because I frequently unplug the drive. 

Whenever I would add a whole album outside of the Music Folder (by opening all tracks at the same time in a file manager) the whole album gets added but aren't grouped properly.

https://prnt.sc/EwmAgG3sq0Rr

**Comment by Taiko2k** [comment]
In flatseal, just add a higher level folder like `/media` for example. Then drag and drop the folder into Tauon.
