### ISSUE TITLE
Radio does not resume after pausing it

### ISSUE THREAD

**Issue by undergroundwires** [Taiko2k/TauonMusicBox#706]
Reproduce:
1. Pause using keyboard pause button on radio
2. Play using keyboard play button

Expected behavior:
Radio will play again.

Actual behavior:
Plays the latest song instead of radio. Then going back to radio and playing it does not work before I restart the app.

**Comment by Taiko2k** [comment]
> Pause using keyboard pause button on radio

Currently, both "Pause" and "Play/Pause" buttons should have no effect when a radio station is playing.

>  Expected behavior: Radio will play again.

Okay, I've committed this change now.

> Then going back to radio and playing it does not work before I restart the app.

Not sure what's causing this, I can't replicate.

**Comment by undergroundwires** [comment]
Thanks for the reply. I'll close this issue once the update is rolled out. I could not reproduce the issue either first time I tried today but saw it happen again after a while. I don't know what exactly is causing it. I'll post more context if I figure out the conditions.
