### ISSUE TITLE
Sorting by Genre?

### ISSUE THREAD

**Issue by Horuyuki** [Taiko2k/TauonMusicBox#707]
Is it possible to export a separate playlist from the current one with different genre tag?

**Comment by Taiko2k** [comment]
Yeah, you can create a genre playlist by searching for a genre using the global search. You can then edit a playlists generator to source from a specific playlist.

**Comment by JoepKT** [comment]
It would be super nice if you could add genres as an option to the top left menu. Adding Genres next to Queue, Playlists + Queue, Artist List, and Folder navigator would allow everyone to super quickly look through the genres they have and click through them to see which artists/albums they are comprised of.

**Comment by Taiko2k** [comment]
@ramilrgk The single genre result should still include the multi-tag ones, even though they're shown as separate results in the search. Let me know if its not.
