### ISSUE TITLE
Excessive RAM consumption

### ISSUE THREAD

**Issue by lucilily** [Taiko2k/TauonMusicBox#708]
I've been using Tauon (AUR) for quite a bit with no issue, but recently it has started to consume huge amounts of RAM on open and stays frozen for a good solid couple of minutes. Afterwords it unfreezes, but still consumes about 5gb of RAM at a constant rate. Closing the program still leaves it running in the background and has to be manually killed through System Activity.

This affects Gstreamer and PhaZor both, and any song played or setting change completely locks up the computer.

Output from the terminal is
```Tauon Music Box v7.1.3
Copyright 2015-2022 Taiko2k captain.gxj@gmail.com

Window size: [1387, 1041]
GTK theme is: breeze
Running from installed location
User files location: /home/l$USER/.local/share/TauonMusicBox
Found XDG-Downloads: /home/$USER/Downloads
Found XDG-Music: /mnt/HDD2/Music
Install directory: /opt/tauon-music-box
Database loaded in 34.593 seconds.
Pychromecast not found
Could not connect to gnome media keys
Start controller server
Init GStreamer...
Using SDL version: 2.0.20
Found game controller: Generic X-Box pad
Load Bio Data
Applying theme: Carbon
Load Bio Data
Load cached bio and image
Auto save playtime
```
I attempted even doing a clean install through yay and the problem remains. Just let me know anything else you need!

**Comment by Taiko2k** [comment]
Oh, you'll need to delete `state.p.backup` too

**Comment by lucilily** [comment]
That totally fixed it, I will keep an eye on that in the future!

I do not use Jellyfin, but I do rescan often. I had about 12 different state.p.backup files so maybe that had something to do with it, haha. I did copy my state.p file if you would like to look over it still. It's about 378kb so I should be able to upload it wherever is best.

**Comment by Taiko2k** [comment]
When you would rescan, what method would you use to do that? Also, would your music be in the same location, or would you move your music library to a different location often?

**Comment by lucilily** [comment]
I am so so sorry for the delayed response, life got in the way! What I do is right-click "Default" > rescan. I keep my files in a permanent location, however I just renamed all of my music files for consistency, and I am constantly adding/removing files from my Music folder.

**Comment by Taiko2k** [comment]
> I just renamed all of my music files for consistency, and I am constantly adding/removing files from my Music folder.

In this case, if you do it a lot you should eventually get a blue coloured option under MENU named something like "clean database", it's good to click that if you ever see it.

**Comment by lucilily** [comment]
Awesome, I'll go ahead and close this out. Thank you!
