### ISSUE TITLE
Change behavior of mouse click in grid view

### ISSUE THREAD

**Issue by bashl** [Taiko2k/TauonMusicBox#709]
Right now, the mouse behavior on grid view is kinda weird. When I'm viewing the grid to see what I'm going to play next, I often need to see the track list to choose a music, but as soon as I click on a album, its starting to play and jump to the current track list on the left, so I need to, either, click on the album and press pause to see/read the track list or just browse through the left panel, which totally defeats the purpose of a grid view.
The idea would be 1 mouse click to jump to the track list on the left column and 2 mouse clicks to start playing from the beginning of the album and jumping on the left.

**Comment by Taiko2k** [comment]
Theres actually two other things you can do:

 1. Right click an album in the gallery grid, and click "Show in Playlist"
 2. You can get 2 clicks to start playing behavior by disabling the setting "Single click to play":
    <img width="299" alt="Screenshot 2022-03-20 at 7 40 21 PM" src="https://user-images.githubusercontent.com/17271572/159151312-f6a58322-a3b2-41b4-b63c-bf6b01ac3950.png">

**Comment by bashl** [comment]
Thanks, this solved
