### ISSUE TITLE
Gracefully shut down when killed by session shutting down

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#712]
If tauon gets killed by the session ending because the user hit the shut down or reboot button, state is not saved like it is when tauon is closed manually via the menu or the window close button. Would be nice if it did.

AFAIK the way to do this on Linux is to set up a handler for the TERM signal and perform the usual shutdown routine when that signal is received.

**Comment by Taiko2k** [comment]
This *should* work already. It should also inhibit shutdown until tauon has fully saved its state. There must be some issue somewhere. What desktop environment are you using?

**Comment by jansol** [comment]
KDE Plasma 5.24.3

It seems that issuing a `reboot` from the command line works as expected, but if I reboot via the reboot button in the plasma main menu tauon state does not get saved. Instead, when I boot the PC and launch tauon again it ends up restoring a much earlier state (i.e. the one from when tauon was last shut down correctly).

**Comment by jansol** [comment]
And yea, the Wayland variant of that desktop environment specifically.

**Comment by Taiko2k** [comment]
If you launch Tauon from terminal then term it, you should see it gracefully shut down. How long does it take? If it's less than say 3 secs then that should be fast enough I would have thought...

**Comment by jansol** [comment]
When I was testing the wayland fixes I did just that, and it would usually shut down within ~2s. Sadly it was also not entirely uncommon for it to get stuck for 30s or so at which point I'd just Ctrl+C it.

**Comment by Taiko2k** [comment]
How many tracks in database does Tauon say for you under Stats?

**Comment by jansol** [comment]
```
Tracks in playlist: 12,009
Albums in playlist: 884

Tracks in database: 23,848
Total albums: 884
```

Seems like it's got quite a few duplicates there. Probably because I recently set up a read only bind-mount of my music library and told tauon to use that instead of the original writable directory. Doesn't look like there is a way to purge those old paths either...

**Comment by jansol** [comment]
Aand just as I posted that I noticed the "Clean Database" menu item.

**Comment by Taiko2k** [comment]
Still, 23k should be well within safe.

**Comment by jansol** [comment]
Okay, looks like this is a Plasma Wayland issue: https://bugs.kde.org/show_bug.cgi?id=461176 https://bugs.kde.org/show_bug.cgi?id=436318
