### ISSUE TITLE
FR: MPD support

### ISSUE THREAD

**Issue by gerroon** [Taiko2k/TauonMusicBox#715]
Hi

It would be great Tauon can control MPD instances with playlist  features.

thanks

**Comment by Taiko2k** [comment]
Problem is a MPD client UI really needs to be designed specifically from the ground up for MPD. Tauon could try mirror and sync its database but that's likely going to get messy. Its also a lot of work but I don't think it would be of great benefit to Tauon as a project. Gonna have to go with wontfix on this one.
