### ISSUE TITLE
Show controller button mapping in-application

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#716]
Controller support is neat, and it worked nicely right out of the box with my PS5 controller. One thing that would be nice is showing the button mapping when pressing say, start.

Basically this would mean replacing the window body with a simple image of the mapping, or maybe even compositing said image with a semitransparent background on top of the window body.

This could also be reused later for shifting focus to the menus and maybe used as a mode hint to distinguish between menu and "normal" navigation modes.

**Comment by Taiko2k** [comment]
Yep an in app mapping guide is on the to-do list

**Comment by jansol** [comment]
Ah right, I somehow missed that line while scanning the list in the steam deck tracking issue.
