### ISSUE TITLE
Anyone facing cant start Tauon?

### ISSUE THREAD

**Issue by thyeun** [Taiko2k/TauonMusicBox#718]
Cant start tauon, no matter in terminal or launch it by dmenu, but in `htop`, i only see `tauonmb` running at the system background.

try using `killall tauonmb` to kill the process, but it will still running at system background.
![Screenshot_2022-03-30-12-53-01_1366x768](https://user-images.githubusercontent.com/1939446/160753995-72acaf2b-ce9a-43a3-a9ec-688d937b3d90.png)

**Comment by Taiko2k** [comment]
What is the output when staring from terminal?

**Comment by thyeun** [comment]
@Taiko2k No error output appear while running at terminal, 

the message as below appear while running at terminal
![Screenshot_2022-03-30-01-13-21_1366x768](https://user-images.githubusercontent.com/1939446/160756228-0733de34-9609-49b3-b367-c46cd8f1f08a.png)
.

**Comment by Taiko2k** [comment]
Not sure why it wont die. Restart PC maybe?

**Comment by thyeun** [comment]
@Taiko2k No matter i `killall tauon` or `killall tauonmb`, i still cant start `tauon` as normal way.

And below is what i been try out.
1. Restart PC
2. Remove `tauon --tray` and login & logout
3. Remove and reinstall `tauon` from AUR

Still no way to start `taoun` as normal way

**Comment by Taiko2k** [comment]
If you removed the autostart, then it shouldn't be already running on reboot right?

**Comment by thyeun** [comment]
@Taiko2k if remove from autostart and logout/login and it will stop `tauonmb` running, than i can start back `tauon` as normal.

but if i only exit the tray, `tauonmb` still will continue running at background.

**Comment by Taiko2k** [comment]
Hmm, I can't replicate the issue myself.

**Comment by thyeun** [comment]
@Taiko2k 

1st scenario (error scenario)
if the error occur, from `htop`, i can see `tauonmb` appear alot of time with different pid number

2nd scenario (normal scenario)
if `tauon` start as normal, from `htop`, i can see `tauonmb` only appear three time with different pid number

**Comment by thyeun** [comment]
@Taiko2k close it, not sure why it happen to me that `tauomb` will lock `tauon` for start up
