### ISSUE TITLE
[BUG] Deleting a song while listening to a song change play order

### ISSUE THREAD

**Issue by undergroundwires** [Taiko2k/TauonMusicBox#719]
**Description:**

I tend to delete songs I don't like from my playlist when listening to them. However when I do that, the next song in the album does not play. I must first wait for the song to finish to delete it to get back to next song.

**Reproduce:**

1. Create a playlist with a few songs e.g. Song1 -> Song2 -> Song3.
2. Start listening to a song e.g. Song1.
3. Delete the song from playlist when listening to it.

**Expected behavior:**

When the song ends (deleted Song1), next song plays (Song2).

**Actual behavior:**

Next song (song2) is skipped, the song after (Song3) is played instead.

**Comment by Taiko2k** [comment]
This should be fixed now in v7.2.0
