### ISSUE TITLE
UI: When hovering cursor over the playback progress bar, show the timestamp of that position.

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#721]
Similar to how hovering the volume bar shows the replay gain.

**Comment by Taiko2k** [comment]
You can middle click to bring up the cursor that displays this

**Comment by jansol** [comment]
Nice. Is there some reason this can't be the default behaviour?

**Comment by Taiko2k** [comment]
> Is there some reason this can't be the default behaviour?

Mainly that it's visual bloat / unessasary. I think it's quite rare that people navigate to specific timestamps. Knowing the current playback position already gives a good intuitive sense of the mapping of the seek bar.
