### ISSUE TITLE
audio breaks up while playing mp3 files on phazor backend

### ISSUE THREAD

**Issue by secYOUre** [Taiko2k/TauonMusicBox#722]
Whenever I try to playback an mp3 file with the phazor backend the audio breaks up, while running Tauon on my RPI, Raspbian GNU/Linux 11 (bullseye) connected to bluetooth speakers. However, on the same setup, phazor plays smoothly my m4a files or radio streams. No such issues were observed with the gstreamer backend, removed with commit f8cbd79. Therefore I am using the new stable release (8c304c3), where the gstreamer support is still present. I know phazor is the way forward, and I am sure this playback issue will be fixed in the future. Thank you so much for developing Tauon Music Box, I love it! <3

**Comment by Taiko2k** [comment]
Ive committed some new settings in the config file now that I'd like you to test to see if it fixes it. So, pull latest commit, recompile Phazor, run Tauon at least once and change the following settings in the config file:
 - `output-samplerate` to 44100
 - `resample-quality` to 2 or 3

Then restart tauon once again.

Let me know if that fixes MP3 playback with Phazor

**Comment by secYOUre** [comment]
Thank you very much for your prompt follow up on this. I think the implementation of

  void config_set_resample_quality(int);

is missing in phazor.c in master, because when t_phazor.py tries to call it at line 64 it results in an AttributeError due to an undefined symbol in libphazor.so. This prevents all playbacks. But, yeah, exposing this degree of parametrisation should fix this issue on resource constraint system like the rpi. Looking forward to test it and keep you posted, as soon as you push the update for libphazor. Thanks!

**Comment by Taiko2k** [comment]
My bad, forgot to committ a file. Try pull again now.

**Comment by secYOUre** [comment]
Thank you, all needed symbols are now present in libphazor.so. Unfortunately the parametrisations attempted so far do not fix the cracking playback of MP3s. Here are a few things I tested:

  * output-samplerate to 44100
  * resample-rate to 2 (and 3)
  * output-buffer-length to 500ms
  * precache-local-files to true  (just to rule out any issues with the local storage)

None of the above resulted in improvements in the playback quality. Furthermore I tried to select different audio sinks, so as to rule out any further condition related to pulse audio. I am sorry because at the moment I have no clues... If there is anything I can do to be of help please let me know!

**Comment by Taiko2k** [comment]
Ok I have a new setting for you to pull and try (recompile phazor again), try set `always-ffmpeg` to true

**Comment by secYOUre** [comment]
Yay, decoding with ffmpeg works perfect across all audio file formats, many thanks! 
Before setting always-ffmpeg to true, I noticed that when the audio cracks the levels across the whole frequency spectrum are unusually high, which may suggest indeed issues with erroneous decoding.

**Comment by Taiko2k** [comment]
Glad we found a way to get it working. I've made a note about it in the wiki.
