### ISSUE TITLE
[Feature Request] When playing a song then going back, it should start the currently playing song from the beginning instead of going to the previous  

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#723]
This is something MusicBee does, its super helpful when I liked a song so much on first listen I wanna hear it again. In MB, this only works when certain amount of time has passed in a song say 15 to 20 seconds. If its less than that then the default behavior of going to the previous song should kick in

**Comment by Taiko2k** [comment]
Okay I've pushed a commit adding this to the setting to menu > settings > audio.

This setting actually already exists in the config file as `back-restarts` so you don't actually have to wait for a release to enable this.

**Comment by Movisivi** [comment]
> This setting actually already exists in the config file as `back-restarts` so you don't actually have to wait for a release to enable this.

Thanks, all good now!
