### ISSUE TITLE
Can’t read metadata from some FLAC files

### ISSUE THREAD

**Issue by da2x** [Taiko2k/TauonMusicBox#726]
Four tracks out of an album can’t be read in Tauon 7.1.3. There’s nothing special I can discern about the affected files. The metadata shows up in VLC, Picard, and other apps. Right-clicking and Rescan tags does nothing. Not sure what data to provide or how to troubleshoot further. (I can’t share the files, because you know, copyright.)

**Comment by Taiko2k** [comment]
Do the files have a `.flac` extension? Are they really FLAC files?

Next, for troubleshooting, I would un-comment these two lines *print a and b*, and just move them up out of that if statement.  https://github.com/Taiko2k/TauonMusicBox/blob/b6d0f5f8bb1f783150624ea70f92977ca0b1c0b7/t_modules/t_tagscan.py#L178 and see if the tags are being read at that point.

**Comment by Taiko2k** [comment]
Looking at the source I found one mistake that could cause it. I've committed a fix.

**Comment by da2x** [comment]
Those lines don’t print anything, but I noticed `Warning: Tag read error on $filepath` for each of these songs.

**Comment by da2x** [comment]
With pull #729, I get `could not convert string to float: '-8.6 Db'` The value is stored in `replaygain_track_gain` and a similar value in `replaygain_album_gain` and `replaygain_album_gain_reference_loudness`. I don’t know what software encoded this. I got it from the Humble (Bundle) Store years ago.

**Comment by da2x** [comment]
I’ll send a fix in a moment.
