### ISSUE TITLE
Playing music does not prevent screen to lock 

### ISSUE THREAD

**Issue by B0ByPop** [Taiko2k/TauonMusicBox#731]
When playing music from local files, and leaving it play (TBM frame still selected) it does not prevent my screen to lock when reaching the time delay.

The music still plays after, although there is a little glitch when the screen locks. When the computer is link to an other screen (especially a TV itself linked to an external speaker), the audio output is set back to the laptop internal speaker.

I updated to the last version of TMB only to face the same issue.

I have looked for some answers to isolate TMB from the screen locker without much results.
Do you have a procedure I can look at to solve this out?

Specs:
Running Fedora 35 with Gnome 41.3
Downloaded from Flatpak: v7.1.3

**Comment by Taiko2k** [comment]
Not sure. I've committed a fix now that may or may not help.

**Comment by Taiko2k** [comment]
Theres a setting called "Block Suspend" in Tauon settings > function somewhere, try enable that too.

**Comment by quesada** [comment]
I tried this option on gnome 45 opensuse Aeon and it doesn't work
