### ISSUE TITLE
D&D from one playlist to another doesn't work

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#74]
Looks like D&D from one playlist to another playlist is broken in 3.9.0

**Comment by Taiko2k** [comment]
I can't seem to replicate. Could you provide steps?

**Comment by Solarunit** [comment]
I try to d&d one track from playlist1 to playlist2, nothing happens.

**Comment by Taiko2k** [comment]
Does it show the purple square indicator as you try?

**Comment by Solarunit** [comment]
Yes

**Comment by Taiko2k** [comment]
Oh it see, its related to having tabs on top disabled

**Comment by Taiko2k** [comment]
Fixed
