### ISSUE TITLE
Track changes before end of song

### ISSUE THREAD

**Issue by Koneko349** [Taiko2k/TauonMusicBox#753]
Tauon 7.2 flatpak, Ubuntu 20.04 LTS

Since the upgrade, songs are changing to next in queue 1 - 2 seconds before the actual end of the song.

**Comment by Taiko2k** [comment]
I'm having trouble replicating the issue. Have you noticed any pattern, like, does it only happen when using the "queue" function? Are you just queuing up ordinary tracks?

**Comment by Koneko349** [comment]
I also converted a song from m4a to wav with the same result (song was truncated 1-2 seconds at the end) the file plays normally in both m4a and wav on other audio players.

**Comment by Taiko2k** [comment]
Okay I came across one bug in the code that may be causing this and committed a fix.

**Comment by Taiko2k** [comment]
Release is out now with possible fix. Let me know if you still run into this issue

**Comment by Koneko349** [comment]
The fix did resolve the track ending early, thank you. The one thing that I noticed however was the track time and progress bar. The timer and progress bar reset to 00:00 and stars counting up again at about the same time that songs were ending early before the (though the song platy thru the end correctly). Said another way, it looks like the fix resolved playback but not song play time on the progress bar or total play time.

**Comment by Taiko2k** [comment]
> The timer and progress bar reset to 00:00 and start counting up again at about the same time that songs were ending early before.

I've committed a fix for this now along with general timing improvements
