### ISSUE TITLE
phazor fails to build due to wrong include path for opusfile.h

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#755]
```
src/phazor/phazor.c:38:10: fatal error: opusfile.h: No such file or directory
   38 | #include "opusfile.h"
      |          ^~~~~~~~~~~~
```

Checked the opusfile (NixOS) package and the right path seems to be `<opus/opusfile.h>`. The file listing for the libopusfile-dev on ubuntu also appears to agree on that.

**Comment by jansol** [comment]
Ah, nevermind, it seems [the pkg-config file for opusfile](https://gitlab.xiph.org/xiph/opusfile/-/blob/master/opusfile.pc.in#L15) actually adds `<includepath>/opus` to the include search path so that is actually correct despite looking odd on disk. And I guess the build error was because pkg-config did not produce any cflags at all because of a missing wavpack.

**Comment by LaineZ** [comment]
Encountered with the same problem on ArchLinux while installing from AUR. Installing wavpack fixes this issue:

```sudo pacman -S wavpack```

**Comment by Taiko2k** [comment]
I see that was missing, I've added it to the PKGBUILD now
