### ISSUE TITLE
Text input not working on wayland (Sway)

### ISSUE THREAD

**Issue by madhogs** [Taiko2k/TauonMusicBox#758]
I have installed Tauon using Flatpak and am currently running it using the wayland compositor Sway.

The app recognises input from the keyboard as I can ctrl-f to open quick find for example, however it does not accept any character input from the keyboard here, I cannot type anything.
I believe this is an issue specific to wayland as if I remove the wayland permission from Tauon, forcing it to use X, it works as expected and can accept text input.

No errors seem to be outputted to the terminal when this issue occurs. eg. running com.github.taiko2k.tauonmb and then trying to type anything into the quick find does not result in any error messages being displayed.

**Comment by Taiko2k** [comment]
>  if I remove the wayland permission from Tauon, forcing it to use X, it works as expected and can accept text input.

Though wayland still won't be used unless a environment variable is set, unless maybe you're remiving the x11 permission. What happens if you add `SDL_VIDEODRIVER=wayland` for Tauon? (You can do this in Flatseal)

**Comment by madhogs** [comment]
Yes, I was removing the x11 permission to force it run through wayland. With the normal config (Both X11 and Wayland permissions enabled) it works fine as I assume it is using X11.
Adding `SDL_VIDEODRIVER=wayland` does not seem to make a difference, I still cannot type anything when wayland is used.

**Comment by Taiko2k** [comment]
I can confirm I can replicate this. Only seems to happen under Wayland + Flatpak. I've got a workaround fix ready for next Tauon release.

**Comment by madhogs** [comment]
This is working as expected now after upgrading to 7.3.0. Thanks
