### ISSUE TITLE
[Feature Request] Lock icon in the context menu

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#76]
So its easier to identify the locked playlist.

**Comment by Taiko2k** [comment]
This is what I got so far, shows a lock icon that highlighted when locked, and also a triangle thing in the playlist side panel.

![Screenshot from 2019-03-21 22-04-47](https://user-images.githubusercontent.com/17271572/54742372-179acd00-4c26-11e9-954b-b582ed9916fe.png)

**Comment by Solarunit** [comment]
Triangle thing is like tab unread indicator in Vivaldi. :triangular_flag_on_post:
