### ISSUE TITLE
Tauon's not loading, but also not crashing

### ISSUE THREAD

**Issue by AftDawn** [Taiko2k/TauonMusicBox#760]
Hi, Tauon music box is not loading, and when i run it from a terminal i don't get any errors untill i `SIGINT` it, then it shows
```
^CTraceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 150, in <module>
    SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER)
KeyboardInterrupt
```

it was working fine before, but i have seen that the AUR ver after a python update can break alot of things

Tauon Music Box installation method: `AUR`
OS: `EndeavourOS Linux x86_64`

**Comment by Taiko2k** [comment]
Hmm, I've run into this issue once before. Logging out and back in again fixed it for me.

**Comment by AftDawn** [comment]
Just logged out and back in, same thing, i'll try doing a restart and see if that makes something work
