### ISSUE TITLE
Auto-updating playlists (auto-regenerate)

### ISSUE THREAD

**Issue by ramilrgk** [Taiko2k/TauonMusicBox#762]
I think it would be a good feature to be able to automatically update playlists. My media library is arranged as follows: there is a playlist "All" which contains music that I sort by folders using Picard. Alphabetically by artists. I also use a playlist generated using "File Modified". Based on the "All" playlist. This way I get a list of the latest albums that I downloaded and added. I also use the "Loved" playlist, with favorite tracks. It is necessary to constantly update them. Yes, there are hotkeys, but it would be convenient to be able not to think about it. Some "auto-update" checkmark in the playlist settings or general settings

**Comment by ramilrgk** [comment]
Is it also possible to sort inside the "Loved" playlist by the time it was added? Yes, this is a habit from streaming services. But it's really convenient. It's nice to have access to tracks that you recently marked as your favorite.

**Comment by Taiko2k** [comment]
You're probably looking for this setting (settings > function (first page)): 
![Screenshot from 2022-05-26 12-10-25](https://user-images.githubusercontent.com/17271572/170389371-2180cea1-dd4a-4dfb-a631-47725e87bfd4.png)

> Is it also possible to sort inside the "Loved" playlist by the time it was added?

Tauon doesn't record when a track was liked, so its not possible to sort by this. You could combine the "File Modified" with "loved" though: Create a new playlist, ctrl+e, type `a l m>`, enter

**Comment by ramilrgk** [comment]
@Taiko2k Thank you! I'm inattentive, but I hope this helps someone who asks the same question and comes here
