### ISSUE TITLE
Windows Releases (question)

### ISSUE THREAD

**Issue by smaragdus** [Taiko2k/TauonMusicBox#77]
I see that the last Windows release is [2.8.3](https://github.com/Taiko2k/TauonMusicBox/releases/tag/v2.8.3). I would like to know whether there would be new Windows releases of **Tauon Music Box** in the future or Windows support is dropped for good. However the last Windows release (**2.8.3**) works fine under Windows 8 x64.

**Comment by Taiko2k** [comment]
Not necessarily for good. I might look at doing a new Windows release if that's something that is wanted.

**Comment by smaragdus** [comment]
@Taiko2k 

If it is not too much of a burden and if you still have access to Windows I will highly appreciate if you choose to release Tauon Music Box for Windows again. I had a  look at the [Change Log](https://github.com/Taiko2k/TauonMusicBox/blob/master/CHANGELOG.txt) and I saw that there were lots of changes since the last Windows release (2.8.3). For the time being it is useless to suggest new features- currently I have only Windows. If there are new Windows releases I may suggest some new features. (I miss a couple of things in version 2.8.3). There are some capable audio players for Windows but I like the GUI of Tauon Music Box and its excellent support for Cue sheets.

Regards

**Comment by Taiko2k** [comment]
OK I think this is working alright on Windows now. In the latest release I have an installer available for testing.

**Comment by smaragdus** [comment]
@Taiko2k 

> OK I think this is working alright on Windows now. In the latest release I have an installer available for testing.

What an excellent news, thanks!

I have downloaded the latest version ([4.0.0](https://github.com/Taiko2k/TauonMusicBox/releases/tag/v4.0.0)) but I will test it (under Windows 8 x64) perhaps tomorrow (now it is late at night here). I just saw that the program icon (at least in the installer) is different.

I didn't expect Windows support to be restored so fast, I appreciate your work.

After I test the latest Windows version I will respond here whether all works fine.

I may suggest a few new features in the future.

Regards

**Comment by Taiko2k** [comment]
Yes hopefully its working ok. BTW please discard and re-download that installer, I just updated it to **v4.0.0-1** (I have now set the correct app-id so it should now upgrade correctly)

**Comment by smaragdus** [comment]
@Taiko2k 

Thanks for the tip. I downloaded the latest installer (**tauon-setup32-v4.0.0-1.exe**). I will test it within 24 hours and I will report my test results here. If the latest Windows version runs fine this issue may be closed.

**Comment by smaragdus** [comment]
@Taiko2k 

I did an initial brief test of version **4.0.0** (**tauon-setup32-v4.0.0-1.exe**) under Windows 8 x64. So far everything seems fine- no problems, no errors, no crashes.

The previous version I had- **2.8.3** (**Tauon.Music.Box.v2.8.3-64bit-Setup.exe**) seemed to be _x64_ only- it installed in `C:\Program Files` while the latest one- **4.0.0** (t**auon-setup32-v4.0.0-1.exe**) seems to be _x32_ only- it installed in `C:\Program Files (x86)`. Actually I don't need _x64_ version, it is just that the previous and the latest Windows builds install in different locations and as a precaution I first uninstalled version **2.8.3** and then installed version **4.0.0**. You might release either a combined **x32-x64** installer or separate installers for **x32** and **x64** systems.

I am not closing this issue right now because you may have some other considerations. I have no complaints about resumed Windows support- the programs worked smoothly during my short test (about half an hour). If it happens that I encounter any issues I will report them. Also I may suggest a couple of new features but I suppose they would require some work. By the way I liked the old yellow-black icon better- for me it was more stylish.

Thanks for re-enabling Windows support!

**Comment by Taiko2k** [comment]
If you have suggestions, I'd be interested to know what they are, even if I don't agree or have the time to implement them.

**Comment by smaragdus** [comment]
@Taiko2k 

I have just opened two new issues (#78 & #79).

Since my last post here I have used **Tauon Music Box** for quite some time and so far I have not come across any kind of problems. Version **4.0.0** for Windows seems stable enough and bug-free. You may close this issue- for me the program works fine.

Regards

**Comment by smaragdus** [comment]
@Taiko2k 

### Question
I see that Windows version is several releases behind Linux version. Is Windows version temporarily put on hold? Shall I expect new releases of Windows version in the near future?

### Off-topic
I see that there is a folder navigator since version [5.0.0](https://github.com/Taiko2k/TauonMusicBox/releases/tag/v5.0.0). What I missed in [Tauon Music Box](https://github.com/Taiko2k/TauonMusicBox) is file browser, like in [Clementine](https://www.clementine-player.org/):

![Clementine 1 3 1 0 - 2019-11-01 - 001](https://user-images.githubusercontent.com/9025757/68025903-b1dfea80-fcb6-11e9-8448-a35a5c887e7b.png)

or like in [MusicBee](https://getmusicbee.com/):

![MusicBee 2 4 5404 - 2019-11-01 - 001](https://user-images.githubusercontent.com/9025757/68025985-f7041c80-fcb6-11e9-8f85-2ff7c8d6ba76.png)

But I never requested such a feature because I supposed that it would require too much work. Since now there is some kind of folder navigator I would like to ask- is real file browser planned for the future? I would appreciate a file browser integrated in the player as I would not need external file manager or [Everything](https://www.voidtools.com/) to search and add music (audio files plus cue sheets) to the player.

**Comment by Taiko2k** [comment]
> is a real file browser planned for the future?

A full tree browser like that is not something I've really considered, or at least felt was worthwhile implementing. Though fun fact, Tauon used to have a built in file browser many versions ago, but I removed it. I didn't really feel it would be particularly useful more than just using external applications. (Instant search seems like it would be a bit of a challenge btw).

Do you not have your music placed in a centralised location?

> Shall I expect new releases of Windows version in the near future?

Testing, maintaining and packaging for Windows is time consuming, and I don't use Windows any more which makes it further inconvenient. I don't really wanna say never, so unfortunately I can't give a straight answer. Maybe I will find time in the future. Maybe not.

Have you considered switching to Linux? :smiling_imp:

**Comment by smaragdus** [comment]
@Taiko2k 

> Do you not have your music placed in a centralised location?

I have most of my music in 2 main folders which contain thousands of sub-folders. Using instant search is fine but not always as sometimes there are sub-folders with names CD1, CD2, CD3, etc.

For me internal file browser is very handy because it allows to browse big directory trees easily.

Anyway, if you consider re-adding file browser to Tauon Music Box in the future I may open a separate issue.

> Testing, maintaining and packaging for Windows is time consuming, and I don't use Windows any more which makes it further inconvenient. I don't really wanna say never, so unfortunately I can't give a straight answer. Maybe I will find time in the future. Maybe not.

I understand. Can't Windows packaging be a bit automated? If you don't have Windows any more would a virtual machine be of any help? Are there any contributors who could help with the Windows releases? Anyway, I hope that version [4.8.0](https://github.com/Taiko2k/TauonMusicBox/releases/tag/v4.8.0) will not be the last Windows release.

> Have you considered switching to Linux?

Long ago (perhaps 9 years ago) I had dual boot system (Windows + Ubuntu) but I had problems with the video driver it seemed and later I removed it. I have considered going back to dual boot system (Mint + Cinnamon) but for the time being I don't have enough time. Sooner or later I will have to switch to Linux entirely as Windows 8 will be my last Windows version (I don't plan to have spyware monstrosity alpha quality Windows 10 on my machines).
