### ISSUE TITLE
Use hex colors in themes

### ISSUE THREAD

**Issue by coral-hungus** [Taiko2k/TauonMusicBox#770]
Hi, I’d like to automatically change themes in Tauon using https://github.com/misterio77/flavours but I need to be able to use hex color codes in the .ttheme file. Is it currently possible to do this or is it a feature that could be included in a future release? 

Thanks!!

**Comment by Taiko2k** [comment]
It could be possible to add this.

Is the format of the theme file compatible in all other regards?

**Comment by Taiko2k** [comment]
Okay I've committed this change to master now. It should work with any of `#ab12ab`, `0xab12ab` or `ab12ab` formats. Let me know if you have any issues with it.

**Comment by coral-hungus** [comment]
That was fast! It might take me a day to get to it but I'll report back results. Thank you!

**Comment by coral-hungus** [comment]
Initial testing looks good. Hex values seem to be interchangeable with rgb values with no problems. I'll work on getting the Flavours integration working in the next couple of days and share my results. Thanks again for making this change for me!

**Comment by coral-hungus** [comment]
Hey - everything is working as expected! Here's a gif of applying a few different themes with Flavours. I'm using xdotool to send a keypress to Tauon to automatically refresh the theme when the new file is generated. 

![Peek 2022-06-11 14-40](https://user-images.githubusercontent.com/86207274/173202575-7884c09d-e520-4d4b-af87-1eb73ac8a3d7.gif)

The template I created should work with any [Base16](https://github.com/base16-project/base16) builder, of which Flavours is only one. Note I am linking to a new fork of the project, the [original](https://github.com/chriskempson/base16) was forked and deprecated in the last couple days. I'll include my template and config as an attachment (remove the .txt to use) to this comment, and if you want to submit it to the Base16 repo, feel free to do so. If you're interested in testing with Flavours, here is the relevant section of the config:

```
#Tauon Music Box
[[item]]
file = '~/Downloads/TauonMusicBox/theme/flavours.ttheme'
template = '/home/marshall/.config/flavours/base16/templates/tauon'
subtemplate = 'default'
#use xdotool to refresh theme. this works most of the time
hook = 'fish -c "xdotool key --window "$(xdotool search --class Tauon | head -1)" F10"'
rewrite = true
```
[config.yaml.txt](https://github.com/Taiko2k/TauonMusicBox/files/8884667/config.yaml.txt)

[default.mustache.txt](https://github.com/Taiko2k/TauonMusicBox/files/8884672/default.mustache.txt)

Thanks again for making this change for me!
