### ISSUE TITLE
sorting by modification date not working with Airsonic

### ISSUE THREAD

**Issue by kuleje** [Taiko2k/TauonMusicBox#772]
I'm trying to sort my airsonic playlist by modification date like this `s"airsonic" a m>`.  Generator shows as OK,  but the order of albums doesn't seem to change. Same with duplicating airsonic playlist and setting generator to `self a m>` in the duplicate. 

Am I doing something wrong or is it just not working?

**Comment by Taiko2k** [comment]
Tauon only reads the modification date from local files, so sorting a playlist of network tracks by this isn't possible.

**Comment by kuleje** [comment]
Ah, ok. May I suggest adding that information to the wiki?

**Comment by Taiko2k** [comment]
Okay Ive added a note on the wiki about it.
