### ISSUE TITLE
Crash when enabling icon on system tray

### ISSUE THREAD

**Issue by Dominiquini** [Taiko2k/TauonMusicBox#777]
The app crash when, in Settings, I tried to enable the option "Show icon in system tray"

Crash log:

> Traceback (most recent call last):
>   File "tauon.py", line 270, in <module>
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
>   File "t_modules/t_main.py", line 45394, in <module>
>   File "t_modules/t_main.py", line 29690, in render
>   File "t_modules/t_main.py", line 27518, in funcs
>   File "t_modules/t_main.py", line 27713, in toggle_square
>   File "t_modules/t_main.py", line 26353, in toggle_use_tray
> NameError: name 'gnome' is not defined

App Version: 7.3.0
SO: Windows 10 x64 Version 21H2 (OS Build 19044.1766)

Thanks

**Comment by Taiko2k** [comment]
Okay Ive pushed a fix, you can download the new exe.

Simply this setting needed to be disabled, its just always on with the windows version.
