### ISSUE TITLE
Sytem Tray (Windows)

### ISSUE THREAD

**Issue by smaragdus** [Taiko2k/TauonMusicBox#78]
I am used to control audio players from system tray, in fact all the players I have support it. So I would like to suggest a new option in **Tauon Music Box**:

- Minimize to tray;

You may add a new check-box in Settings (perhaps in Function)- `Minimize to tray`, which, if enabled, sends **Tauon Music Box** to system tray upon Minimize command (the program does not appear in task bar when minimized).

If tray support is implemented you may add some commands to tray icon (accessible at  right click), for example:

- Play;
- Pause;
- Stop;
- Previous;
- Next;
- Repeat;
- Shuffle;
- Exit;

For me it would be handy if I can minimize the player to system tray and control it via tray icon commands- left click restores the player, right click shows the available tray commands. Also, I usually use a lot of programs and my task bar easily gets cluttered, So I prefer to be able to send to tray the programs that are working in the background.

Several examples of tray controls:

- [Audacious](https://audacious-media-player.org/):
![aud-snipaste-2019-03-26_024133](https://user-images.githubusercontent.com/9025757/54964539-84d79680-4f75-11e9-8b33-a8a849bab6ae.png)
- [Clementine](https://www.clementine-player.org/):
![cle-snipaste-2019-03-26_031028](https://user-images.githubusercontent.com/9025757/54964553-9456df80-4f75-11e9-9aaf-e3bf3f4ef0c3.png)
- [foobar2000](http://www.foobar2000.org/):
![foo-snipaste-2019-03-26_024525](https://user-images.githubusercontent.com/9025757/54964562-9f117480-4f75-11e9-8430-e12436715063.png)
- [MusicPlayer2](https://github.com/zhongyang219/MusicPlayer2):
![mp2-snipaste-2019-03-26_023951](https://user-images.githubusercontent.com/9025757/54964570-aa64a000-4f75-11e9-8f20-9d3a4fe4a54b.png)
- [Qmmp](http://qmmp.ylsoftware.com/):
![qmm-snipaste-2019-03-26_023914](https://user-images.githubusercontent.com/9025757/54964592-ba7c7f80-4f75-11e9-865b-3dc9179fb2e0.png)

I suppose that system tray support might require a lot of work, especially if the feature is implemented for Linux builds of **Tauon Music Box**- as far as I know some Linux desktop environments (like GNOME) have dropped support for system tray.

**Comment by Taiko2k** [comment]
I have a working prototype. Unfortunately the library I am using to do this is somewhat limited, so there is no dynamic feedback, just a static menu. But at least, it should serve the function of being able to hide the window to tidy up your taskbar.

![Capture](https://user-images.githubusercontent.com/17271572/55051835-05e56b00-5014-11e9-808b-599a5b05168f.PNG)

If you want, you can test it. https://github.com/Taiko2k/TauonMusicBox/releases/download/v3.9.1/tauon-v4.0.1-dev1-windows.zip

The tray always shows and there is a single new option under "View" called "Minimize to tray"

**Comment by smaragdus** [comment]
@Taiko2k 

Thank you for implementing tray support and for providing a test version.

In did a test and I am satisfied with the implementation.

Several observations:

- I particularly like that the program window is restored from tray on double click- I always prefer double click to single click which eliminates the risk of accidental clicks.
- Wouldn't it be better just 'Show' in stead of 'Show Windows'?
- Do you prefer 'Advance' in stead of 'Next'?
- Did you exclude 'Stop' command from tray commands on purpose?
- Don you think that it would be better to add two separators which separate playback commands from 'Show Window' and 'Quit' commands, screen:
![Tauon Music Box 4 0 1 - 2019-03-27 - 002](https://user-images.githubusercontent.com/9025757/55080761-58bc3280-50a7-11e9-8600-a821bd59cd1e.png)

I am glad that you decided to add an option for minimizing the program to tray. This was the feature I missed. Many thanks!

**Comment by Taiko2k** [comment]
I will change the text to just "Show", and I'll add "Stop", I left it out because I thought it might be more compact without it, but upon thinking about it again, I think having "Stop" is be desirable.

I do prefer the word "Advance", I think it makes more sense. ("Next" implies a fixed set or queue, but a playlist is mutable and can be randomly shuffled").

As for the separators, the library I'm using doesn't provide a method for them unfortunately. Modifying its code is a bit more than I wanna get into at the moment.

**Comment by smaragdus** [comment]
@Taiko2k 

The separators are cosmetic, visual stuff with no real significance.

I asked about 'Advance' because perhaps I am used to 'Next'. Wouldn't 'Forward' and 'Back' in stead of 'Advance' and 'Previous' make the tray menu look more homogenic?

**Off-topic 1**
I noticed that some main window buttons ('Repeat Track', 'Shuffle', 'Playback menu') have tool-tips while playback buttons do not have tool-tips. Of course the playback buttons are quite obvious but I suppose that if they have tool-tops the looks will be more unified, don't you think? Also- wouldn't be better if you unify the case? I mean, either:

- 'Repeat Track' and 'Playback Menu';
or
- 'Repeat track' and 'Playback menu';

**Off-topic 2**
For me **Tauon Music Box** solves some core problems I have had with other players:

- [Audacious](https://audacious-media-player.org/) is not portable but it supports cue sheets;
- [Clementine](https://www.clementine-player.org/) is portable and supports cue sheets but its portability is partial- it still writes outside its program folder (`C:\data\cache\networkcache`);
- [Quod Libet](https://github.com/quodlibet/quodlibet) is portable but it does not support cue sheets;

Further, the developer of **Quod Libet** is unwilling to add support for cue sheets:

> Cue sheets really are an anachronism that has to real reason to be kept alive any
> longer.

([issue](https://github.com/quodlibet/quodlibet/issues/493), [comment](https://github.com/quodlibet/quodlibet/issues/493#issuecomment-80747267))

For me this comment is absolutely ridiculous and ignorant so I have given up on this player.

I am very pleased that **Tauon Music Box** is portable and supports cue sheets and now it has tray support to boot, thanks.

**Comment by Taiko2k** [comment]
I think you're right. I'll add toolips to the playback buttons, and unify the text to lower-case, and unify the wording to "Forward" and "Back".

**On the subject of CUE sheets**

Indeed I don't think I agree with the idea that CUE sheets are archaic, at least not necessarily the idea of a whole album as a single stream with external metadata, it does have benefits;

 - Saves a small amount of space, prevents redundant data
 - Speeds up file copying by a moderate amount
 - Doesn't require a specialized application to edit metadata
 - Ensures perfect gapless playback
 - Makes transcoding to a different codec a simpler process
 - Less probability of missing tracks (You might never realise there are more tracks to an album than you have)


And not to mention that a lot of people happen to use them.

I'm guessing that the developer of **Quod Libet** didn't consider them when initially developing their application so its harder to implement such a feature now that its matured.

**Comment by smaragdus** [comment]
@Taiko2k 

You provided excellent arguments about the relevance and importance of cue sheets- I haven't thought about some of them. When I rip a CD I prefer to rip it into a single lossless file plus a cue sheet- that way it is easier to burn it if the original CD gets damaged. Also, I have a huge collection of downloaded torrents and most of them consist of a single lossless file plus a cue sheet- I can split these lossless files into separate tracks but since I still seed the original torrents (to some of them I am the only seeder) this will mean that I will have to double the size of my already big audio collection.

I have thought of some other possible tiny enhancements of Tauon Music Box and I wonder what would be better- to suggest them here or to open new issues?

**Comment by Taiko2k** [comment]
You can make new issues, or here if you want, either way is fine.

**Comment by smaragdus** [comment]
@Taiko2k 

Thank you very much for version [4.1.0](https://github.com/Taiko2k/TauonMusicBox/releases/tag/v4.1.0). I am completely satisfied with the current tray commands:

![Tauon Music Box 4 1 0 - 2019-04-10 - 001](https://user-images.githubusercontent.com/9025757/55847840-96af6100-5b53-11e9-8bf5-b4918d8d0d81.png)

Excellent work!

**Comment by smaragdus** [comment]
@Taiko2k 

`Stop` command executed from tray menu does not work. Please confirm.

**Comment by Taiko2k** [comment]
I can conform, this is a bug.
