### ISSUE TITLE
Scrobbling on reaching the threshold

### ISSUE THREAD

**Issue by teackot** [Taiko2k/TauonMusicBox#783]
Wouldn't it make more sense to scrobble when the threshold is reached, like official Last.fm android app does? If scrobbling happens on the end of a track then what's even the point of the threshold?

**Comment by Taiko2k** [comment]
It will still not scrobble if the threshold was never reached. It just delays the scrobble. It was a requested change, and makes sense to me, ref https://github.com/Taiko2k/TauonMusicBox/issues/15.
