### ISSUE TITLE
Publish to WinGet 

### ISSUE THREAD

**Issue by vedantmgoyal2009** [Taiko2k/TauonMusicBox#789]
With every new release of TauonMusicBox, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if the maintainers would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

**Comment by vedantmgoyal2009** [comment]
cc @Taiko2k

**Comment by Taiko2k** [comment]
Its currently all manual on my end, so a new release might not have an exe right away or at all. Might be best that its done manually elsewhere then.

**Comment by vedantmgoyal2009** [comment]
Maybe we can keep the workflow trigger manual - workflow_dispatch?
