### ISSUE TITLE
Settings : a way to manually set path to the config directory

### ISSUE THREAD

**Issue by nicolnt** [Taiko2k/TauonMusicBox#792]
As TauonMusicBox is now available on Windows I would love to be able to use the same configs on both OS that share a drive on my laptop.

This would make the transition seamless, as I would find all my playlists, listen count and general configuration either when I'm on Linux or Windows.

It could be achieved with an option that let me select the path to Linux config when I am on windows.

**Comment by Taiko2k** [comment]
That'd be the data directory, Tauon doesn't make use of the config directory. (Under Linux they're specifically different folders)

Anyway, hmm... Sharing the data dir between platforms isn't explicitly supported by Tauon, though I can't think why it wouldn't work, except that your music would all have different paths on windows right? Like how paths start with `c:\\` so it wouldn't work?

I could add a config for just the `star.p` file, that'd work for the listen count, but not playlists.

**Comment by Taiko2k** [comment]
OK magic, you can do this all by using symlinks!

I've made a guide [here](https://github.com/Taiko2k/TauonMusicBox/wiki/Windows-Linux-dual-install). Let me know if that's fun.

**Comment by nicolnt** [comment]
Wowww you are impressive, always have a solution 😻
I can tell you that it works pretty well! Nice trick, I'm so happy to be able to use it on both systems

**Comment by nicolnt** [comment]
Actually I went back on Linux and the app didn't open:

```
─ flatpak run com.github.taiko2k.tauonmb
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 91, in <module>
    os.makedirs(user_directory)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/nicolas/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox'
```
It's because of Flatpak permissions.
I had to give it access using this command: `sudo flatpak override com.github.taiko2k.tauonmb --filesystem=/home/nicolas/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox`.
Maybe you should add a note on your guide to remind flatpak users to do this step :wink:
