### ISSUE TITLE
No sound for WMA files

### ISSUE THREAD

**Issue by david-cortes** [Taiko2k/TauonMusicBox#795]
If I try to play a WMA audio file in Tauon, it will not produce any sound, even though it looks as if the file was playing and all the metadata (such as length of the file) is identified correctly. The same file plays correctly in other software such as JuK.

In case it makes a difference, I am using the flatpak version of Tauon in a debian bookworm setup.

**Comment by Taiko2k** [comment]
Its a Flatpak thing. I've updated the instructions in the wiki here, see [Extra Codecs](https://github.com/Taiko2k/TauonMusicBox/wiki/Flatpak-Extra-Steps#extra-codecs).

**Comment by david-cortes** [comment]
Thanks. Installed it and it now plays WMA. But given it's only ~20mb, why not make it a hard dependency for tauon's flatpak too?

**Comment by Taiko2k** [comment]
Yeah might as well. I've now set it so that Flatpak will install it automatically, and removed those wiki instructions as they should no longer be needed.
