### ISSUE TITLE
Flatpak not installable on Ubuntu 20.04.4

### ISSUE THREAD

**Issue by SalusVF** [Taiko2k/TauonMusicBox#797]
I had Tauon Music installed as Flatpak on my computer. Suddenly after a normal restart I could not find it anymore. I tried to install it again but it keeps giving me this error.

`Warning: Wrong origin flathub for update`
`Error: Wrong origin flathub for update`
`error: Failed to install com.github.taiko2k.tauonmb: Wrong origin flathub for update`

After that I tried to install another Flatpak application, just to see if the problem was only in your app or a general problem from Flatpaks. I could install the other app without any issues. So I guess it could be something wrong with yours.

Thanks,
Salus

**Comment by Taiko2k** [comment]
Hmm, seems to be working for me. Try run `flatpak repair --user && flatpak reair --system`

Then try again `flatpak install com.github.taiko2k.tauonmb`

**Comment by SalusVF** [comment]
I have tried what you said and unfortunately it does not work. I am still having the same error. 
I have also tried the command in two flavors:
* `flatpak install flathub com.github.taiko2k.tauonmb`
* `flatpak install com.github.taiko2k.tauonmb`

**Comment by SalusVF** [comment]
I have also tried upgrading to ubuntu 22.04 and reinstalling flatpak. Somehow it is the only flatpak that fails on installing. All other flatpaks work just fine.

**Comment by Taiko2k** [comment]
I have no idea on how to further diagnose this. Maybe try ask on the Flatpak [matrex](https://matrix.to/#/#flatpak:matrix.org) or [discourse](https://discourse.flathub.org/).

**Comment by SalusVF** [comment]
Thanks I'll try there and in case I get a solution I will post it here.

**Comment by SalusVF** [comment]
I am going to close these issue, since it is not fair for you now that I have discovered that the same problem appears with GIMP and Curtail flatpak applications. I will comment ayway if I find a solution,though. 

Thanks for your help.
