### ISSUE TITLE
Audio garbled

### ISSUE THREAD

**Issue by portal2poe** [Taiko2k/TauonMusicBox#806]
When I attempt to play any song, (FLAC, mp3, etc), I get garbled audio coming out of TMB.  On other players, however (VLC, rythmBox, etc) everything sounds fine.   I had this problem with Ubuntu, and thought I'd switch to RasberryPi OS (rasbian) to see if that might help...but no luck.   

I did try and set always-ffmpeg = true, but still am getting garbled audio.

I would bet that this problem has to do with my HiFiBerry Digi+ optical out..?  I would guess phazor is unhappy with it?  Can I turn on debugging to provide a few hints?

This is my "stack"
Tauon Music Box: v7.3.2 installed from flatPak
Raspberry PI 4: Debian GNU/Linux 11 (bullseye)
HiFiBerry:  Digi+ Standard (https://www.hifiberry.com/shop/boards/hifiberry-digiplus-standard-version/)

**Comment by Taiko2k** [comment]
Try switch audio output and see if it still does it. Like test using the onboard 3.5mm jack, might help narrow it down. Could be an optimisation issue and Tauon is CPU starved.

**Comment by portal2poe** [comment]
"Try switch audio output using 3.5mm jack":   Did not work.  Still garbled...so probably HiFi Berry has nothing to do with it. CPU starved..? so...

Just to see, I then reinstalled Raspberry Pi 4: using a new much larger microSSD (new 128gb / old 32gb)...got TMB 7.3.2 running:
    1.  FLAC audio files now play fine.
    2. M4a files (most of my library was encoded was encoded as apple lossless on a Mac) have Garbled Audio
    3. Mp3 files have garbled audio
  
I then set always-ffmpeg = true, and retested all three formats.
1. FLAC now also garbled
2. M4a files garbled
3. Mp3 files garbled

**Comment by Taiko2k** [comment]
Interesting, almost seems like its some sort of platform compatibility bug with the way Tauon is copying data in memory, like using the wrong endianness or probably the wrong assumption about the default `int` or `float` sizes. Probably the ffmpeg trick used to work but a refector in Tauon broke it at some point.

**Comment by Taiko2k** [comment]
Found the issue. I've committed a fix now.

For some reason an implicit C type conversion wasn't working on this platform, using an explicit conversion worked.

**Comment by portal2poe** [comment]
Awesome!  Sure seems like a fix big enough to cut the 7.3.3 release, if you ask me! :)

**Comment by Taiko2k** [comment]
Its locked in for next release, which ive decided to call v7.4.0. Maybe ready in about 2 weeks.

**Comment by portal2poe** [comment]
Great!  Well I speak on behalf of all RPI TMB users (can't just be me can it, even though no one else that I could see even noticed it?) that we'll (I'll ?)  be very happy when you get a chance to push out a release!    Thanks again for creating a really cool piece of software!

**Comment by Taiko2k** [comment]
If you'd like to test it, ive set up a beta flatpak channel for testing. Instructions here https://github.com/Taiko2k/TauonMusicBox/wiki/Beta-Flatpak

**Comment by Solarunit** [comment]
@Taiko2k I have `flathub-beta` added, but `flatpak search tauon` only shows tauon in stable branch for some reason

**Comment by Taiko2k** [comment]
Oh, for some reason the publish to Flathub failed. Maybe I did something wrong. It is my first time doing it.

In the mean time you can try install the one off build directly using:

```
flatpak install https://dl.flathub.org/build-repo/101837/com.github.taiko2k.tauonmb.flatpakref
```

Just uninstall any previous version of tauon first `flatpak uninstall tauon`.

**Comment by Solarunit** [comment]
still in the stable branch only

**Comment by Taiko2k** [comment]
@Solarunit Looks like its there to me. Did you add the beta remote?

![Screenshot from 2022-08-10 01-09-13](https://user-images.githubusercontent.com/17271572/183655106-e3df2e49-23e8-43ce-8567-796dcc0838fc.png)

**Comment by Solarunit** [comment]
`flatpak remotes` shows me `flathub` and `flathub-beta`

`flatpak search kodi` founds it in two repos, but not tauon...
____

BTW how did you make flatpak command colorful?

**Comment by Taiko2k** [comment]
Huh. I wonder if you run `flatpak update` maybe it will show.

As for the terminal colours, im using [fish](https://fishshell.com/).

**Comment by portal2poe** [comment]
I got a chance to pull down the beta last night...the fix you put in is working great! Thank you!
