### ISSUE TITLE
[Feature Request] Tracks separator in album with multiple discs by reading the "Disc Number" tag

### ISSUE THREAD

**Issue by glu8716** [Taiko2k/TauonMusicBox#807]
I usually don't like to divide an album that has multiple discs in different folders (called, for example, **Disc 1** and **Disc 2**), otherwise Tauon would create two different entries in the albums list:
![2022-08-03_14-31](https://user-images.githubusercontent.com/33501455/182608313-c06f08fb-2745-442a-bd72-77a345a3a972.png)
If that's the case I'd have to add something like **Disc 1** and **Disc 2** in the **Album Title** tag of the tracks of the two different folders if I'd want to differentiate them.

To prevent this from happening I usually put every track in the same folder and add the **Disc Number** tag in every file. However by doing this there are no signs of the presence of multiple discs if not the fact that at some point tracks start back from 1.
What I'd like is that Tauon could separate multiple discs by reading the **Disc Number** tag. By "separate" I don't mean creating multiple entries in the albums list like I mentioned before, but creating something like a separator in the tracks list so that one know which tracks are of which disc. Something like this:
![2022-08-03_14-01](https://user-images.githubusercontent.com/33501455/182605134-2cad150f-65e2-4d17-9299-13e8f6d7e7ec.png)
Maybe adding a "Disc X" reference alongside or above the separator is also an idea.

**Comment by Taiko2k** [comment]
OK here's my proposal, its the same as the folder separator except without additional space or text. Not really any room for text unless we do allow it to take up its own row like the folder separator.

![Screenshot from 2022-08-04 01-27-11](https://user-images.githubusercontent.com/17271572/182620433-cb2ba292-d53b-46bd-b3d2-38dcce25f85c.png)

Tracks must be in the same folder and have the same album tag for this to show.
