### ISSUE TITLE
[Question] How to disable transparent window background?

### ISSUE THREAD

**Issue by qlyoung** [Taiko2k/TauonMusicBox#808]
Somehow I changed the background of TMB to be transparent, and cannot figure out how to undo that. If someone could point me in the direction of the docs that explain this setting I would be very thankful! Apologies for the spurious GH issue.

![tauonhelp](https://user-images.githubusercontent.com/6827003/183309340-056a211c-d8e2-4f8c-93d1-e7328a8a2233.png)

**Comment by Taiko2k** [comment]
Bottom of this page https://github.com/Taiko2k/TauonMusicBox/wiki/Keyboard-Shortcuts

**Comment by qlyoung** [comment]
Thank you!
