### ISSUE TITLE
[Feature Request] Synced Lyrics

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#81]
Hi, is it possible to get synced lyrics on the app? I think they would be better than scrolling up and down the lyrics to find where the song has reached. It would also make for a good visualization in the lyrics view.

**Comment by legion1978** [comment]
that would require a special format lyric file if im not mistaken. something like this: http://www.crintsoft.com/mlfaq-lyrics.htm
theres OSD Lyrics for linux, but lyrics are almost always unsynced and after a bit of trying to get them right (via keyboard shortcut if it works) it gets old. 
perhaps taking a look at these may give taiko some idea of it :) 

now ill double it down: i've always thought adding support for [scrolling] guitar chords would be nice.

**Comment by Taiko2k** [comment]
Is not something I think that would be a bad feature, but, the issue I see is that synced lyrics are extremely rare. So its just not worth it. I've never come across a `.lrc` file in the wild before, and afaik the only places that supply synced lyrics are closed proprietary services that aren't publicly accessible.

**Comment by Taiko2k** [comment]
@legion1978 Guitar chords... interesting. Though I think that might be something better off as its own application maybe? It could connect via MPRIS2 to synchronize with the player, and then it could be used with any music player.

**Comment by keystroke3** [comment]
> So its just not worth it. I've never come across a .lrc file in the wild before
What if you allowed the user to add an `.lrc` file of their own? Like if the music service I use to download my music offers me the option to download the file. Could that be added as an option?

**Comment by legion1978** [comment]
> Is not something I think that would be a bad feature, but, the issue I see is that synced lyrics are extremely rare. So its just not worth it. I've never come across a `.lrc` file in the wild before, and afaik the only places that supply synced lyrics are closed proprietary services that aren't publicly accessible.

yes, indeed. minilyrics is an ancient windows application. i was actually surprised its still alive. though i figure .lrc and similar files are more to the karaoke apps side than players'

then again, as i said, there are some apps around: https://alternativeto.net/software/osd-lyrics/?license=opensource

keep in mind that a .lrc is mostly like a regular lyric file, but with timestamps. something like this: 
[id: 32_565894]
[ar:Haggard]
[ti:Outro_ A Midnight Gathering]
[01:13.23][02:21.10]In the woods we met you, stranger
[01:14.82]And though we don't know your face
[01:16.90]Taken your fiddle, come on over
[01:19.40]Sit down 'round the fireplace
[01:21.55][01:37.31]Watch the flames are dancing higher
[01:23.17][01:39.78]They are longing for the sky
[01:25.21][01:41.78]heroes now will be awaken
[01:27.16][01:43.71]Elder stories let their spirits fly

personally, i use osdlyrics, so i can keep it on top of the window, so i can check it out without interfeering with my work (i set it up so it displays lyrics line by line). thing is, it keeps going out of sync and its annoying after a while (this depends on the lrc file not the app itself, i figure).

so i would most likely use it for chords.. >

**Comment by legion1978** [comment]
> @legion1978 Guitar chords... interesting. Though I think that might be something better off as its own application maybe? It could connect via MPRIS2 to synchronize with the player, and then it could be used with any music player.

not exactly-- i often jump to the player, grab the guitar and then crank it up.. so it implies the use of a media player. 
thing is, [i think all of them] players support lyrics, not chords (meaning retrieve them from some place). 

consider this, but scrolling slowly up: 

![2019-03-30_09-39](https://user-images.githubusercontent.com/331242/55277678-cbf4bd00-52d0-11e9-80ae-800cb19295d7.jpg)

so it doesnt have to be a .lrc file ;) in fact, i very often paste chords and not lyrics in Taoun. 
it would be an interesting addition.

**Comment by Taiko2k** [comment]
Ive got basic support for timed lyrics working. Nothing too fancy though, so no fading animations.

Some notes on how it works:
 - Highlights and scrolls with current line
 - Requires `.lrc` file in the same directory and same filename as track

![Screenshot from 2019-04-04 23-34-24](https://user-images.githubusercontent.com/17271572/55549749-16dc5d80-5733-11e9-9e08-864cff6c741b.png)

**Comment by keystroke3** [comment]
This is better than having to manually scroll through the lyrics and trying to figure out where it has reached. So is it possible to make the player prefer the `.lrc` over the auto searched lyrics previously gotten the songs before the new feature?

**Comment by Taiko2k** [comment]
Yes, there will be a button to prefer either `.lrc` or normal in the case both exist.

**Comment by Taiko2k** [comment]
This feature will be live in the latest version.
