### ISSUE TITLE
Weird behavior with shuffle/playback history

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#812]
Ran into this a few times now:
1) Shuffle on
2) Manually start a track by clicking in the playlist
3) Let tauon play through the track and also through the next one
4) During the 3rd track, click the back button twice to return to the track selected in step 2
5) Let tauon do its thing
6) After finishing the 1st track, it jumps directly to the 3rd one. However clicking the back button makes it first jump to the 2nd track and only then to the 1st.

Simply skipping back and forth with the back and forward buttons keeps the sequence intact (with all 3 tracks) in both directions.

**Comment by Taiko2k** [comment]
Yep looks like you've indeed found a bug. I've committed a probable fix.

**Comment by jansol** [comment]
Seems indeed to be working with that.
