### ISSUE TITLE
Automatically fetch album cover (ignoring local files)

### ISSUE THREAD

**Issue by evilsh3ll** [Taiko2k/TauonMusicBox#814]
Hello, is there any way to automatically fetch album cover when a song is played without saving the fetched file and without looking for local files?

**Comment by Taiko2k** [comment]
Sorry for the slow response. Answer is there is neither a way to fetch automatically or ignore local files. Due to tauon being intended to be manual in nature and kind on APIs I avoid adding automatic features.
