### ISSUE TITLE
[Feature Request] Add real bitrate count (Kbps)

### ISSUE THREAD

**Issue by prestidigitonium** [Taiko2k/TauonMusicBox#815]
Hello, could you add a feature to show the real bitrate in **Kbps** (for example like Strawberry does)?
![image](https://user-images.githubusercontent.com/63223659/187031597-3faff39e-773e-4427-b231-deed8c235d96.png)

**Comment by Taiko2k** [comment]
The idea in Tauon was to combine those three fields into one to save space. Since samplerate doesn't make much sense for lossy, and bitrate doesn't make much sense for lossless. In any case, Tauon's bitrate guess for lossless isn't real as such, its just a crude approximation.

**Comment by prestidigitonium** [comment]
ok thanks
