### ISSUE TITLE
Multiple "like" problem across different albums with the same name

### ISSUE THREAD

**Issue by prestidigitonium** [Taiko2k/TauonMusicBox#817]
Hello, if I have multiple albums with the same name but in different folders, and I "like" a song, that song is liked across all albums automatically. The problem is that songs are different because they are in different albums with the same name/artist/year (just different version, for example a remix album).
![image](https://user-images.githubusercontent.com/63223659/187035256-5bf3d1fc-fa8f-43b1-a46f-f1cd4a52455d.png)
Is there a way to fix it?

**Comment by Taiko2k** [comment]
Its just the way it works. Songs are uniquely identified for the purposes of liking by matching a *artist*, *title* and *filename*. Only workaround would be to have unique filenames for each album.
