### ISSUE TITLE
[Feature Request] Stop after track

### ISSUE THREAD

**Issue by albatros-hmd** [Taiko2k/TauonMusicBox#821]
Hello there,
Currently migrating from clementine which has become unstable on my system.
One feature I really miss is the ability to insert a stop after the track.

Behavior is the following : 
- I mark a track for "stop after track".
- The track is visually marked on the player to signify a "stop after track".
- once the track has played in full, the next track is selected, but not played.

If called from a global shortcut, the current track is marked as "stop after track".

Cheers.

**Comment by albatros-hmd** [comment]
outch,
Very sorry, it seems almost everything is already implemented. I should have waited to know more about Tauon before posting.

The only thing that would be left is the ability to toggle autostop on playing track from the remote control API.

**Comment by Taiko2k** [comment]
This has been added. The point `/api1/auto-stop` toggles auto-stop of the playing track. The `auto_stop` attribute of `/api1/status` gives the status of auto stop (boolean).
