### ISSUE TITLE
Build dependencies on Fedora

### ISSUE THREAD

**Issue by namesarebloat** [Taiko2k/TauonMusicBox#823]
I've had success building tauon on fedora after installing build dependencies with this command

`sudo dnf install pygobject2-devel ffmpeg-devel libnotify-devel SDL2-devel SDL2_image-devel wavpack-devel flac-devel libvorbis-devel opusfile-devel libopenmpt-devel libsamplerate-devel libmpg123-devel`

Just in case you want to add this to https://github.com/Taiko2k/TauonMusicBox/wiki/Building

**Comment by Taiko2k** [comment]
Ok added
