### ISSUE TITLE
[Feature request] Shuffle would be nice as individual setting of each tab

### ISSUE THREAD

**Issue by k9bbzJavftZaqAqSW3dY** [Taiko2k/TauonMusicBox#826]
Hi :)
There are some music folders where I primarily use shuffle mode, because it's a specific style of music and goes well in any order, and the surprise appearance of a song is nice - and then there is my main music library where I manually switch shuffle off before I listen to music, because there's too much whacky shit and different genres, and the random next song makes the experience quite bad.

It would be nice if shuffle was a per-tab-setting.

Cheers!

**Comment by Taiko2k** [comment]
It would be plausible to add such a feature... Though did you know you can shuffle an existing playlist?
 
 1. Create a new playlist and drop in a folder, or use an existing playlist
 3. <kbd>Ctrl</kbd> + <kbd>e</kbd>
 4. Type `self a st`, enter
 5. You can then right click the tab and press "Regenerate" to reshuffle whenever.
 - To temporarily have it not shuffled, right click tab -> sort -> filepath

**Comment by k9bbzJavftZaqAqSW3dY** [comment]
that's cool, also the alt+r combo to reshuffle is nice and handy.
you read my mind with the "toggle breaks", now the only visual quirk is that in gallery mode, it massively blows up the album cover list.

yeah, this works for me, no pressure on the feature request! :)
