### ISSUE TITLE
[Feature Request] Show bitrate and codec for songs from Jellyfin

### ISSUE THREAD

**Issue by jibsaramnim** [Taiko2k/TauonMusicBox#829]
It'd be nice to be able to see the actual codec and bitrate of songs loaded through Jellyfin. In the current implementation, it always shows `JELY` as the codec, and the bitrate column stays empty. Would this be possible, or does Jellyfin not provide this information in a reasonable/usable way?

Less useful perhaps, but if the data is available, it might be nice to have other columns work for Jellyfin provided music too (ie. `Has Lyrics`, `File name`).

Thanks so much for everything you do! :)

**Comment by Taiko2k** [comment]
OK, pushed an initial commit for this, this adds bitrate, samplerate, codec and filepath metadata.

The filepath one is extra cool because it unlocks sorting your library by that, the actual folder layout on disk.

Note on upgrade, you'll need to click "import music to playlist" again.

**Comment by jibsaramnim** [comment]
Wow, you're lightning fast. Thanks so much for this! 

I should've checked if Jellyfin itself actually supported lyrics, sorry about that.

**Comment by jibsaramnim** [comment]
This is wonderful, I can confirm that these new columns are showing up great in the new version released! Both the codec and bitrate are showing up nicely now with content pulled in through Jellyfin. Nice! I couldn't spot samplerate, but maybe I'm looking in the wrong place for that.

Thanks so much for this!

![image](https://user-images.githubusercontent.com/18850/192402953-64bbe714-533e-4cb3-bc08-f93be377c28d.png)
