### ISSUE TITLE
Guitar chord retrieval and display

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/TauonMusicBox#83]
> @legion1978 Guitar chords... interesting. Though I think that might be something better off as its own application maybe? It could connect via MPRIS2 to synchronize with the player, and then it could be used with any music player.

not exactly-- i often jump to the player, grab the guitar and then crank it up.. so it implies the use of a media player. 
thing is, [i think all of them] players support lyrics, not chords (meaning retrieve them from some place). 

consider this, but scrolling slowly up: 

![2019-03-30_09-39](https://user-images.githubusercontent.com/331242/55277678-cbf4bd00-52d0-11e9-80ae-800cb19295d7.jpg)

![image](https://user-images.githubusercontent.com/331242/55277879-dc0d9c00-52d2-11e9-978a-5d68992ec168.png)

so it doesnt have to be a .lrc file ;) in fact, i very often paste chords and not lyrics in Taoun. 
it would be an interesting addition.

_Originally posted by @legion1978 in https://github.com/Taiko2k/TauonMusicBox/issues/81#issuecomment-478253567_

**Comment by Taiko2k** [comment]
I'm not sure if it should have automatic scrolling, or how that would work, but I got a concept here:

![Screenshot from 2019-03-31 12-59-57](https://user-images.githubusercontent.com/17271572/55282992-22d3c280-53b5-11e9-82ab-ec08f2d38b6d.png)

**Comment by legion1978** [comment]
so cool. 
and sure it should scroll (on/off state, maybe). so you can keep up with the song till it ends. believe me its very annoying scrolling manually and strumming at the same time :v

**Comment by Taiko2k** [comment]
How this feature works:
 - Theres a new option in the settings, when enabled:
    - Prefers showing lyrics with guitar chords in place of normal lyrics
    - Shows button to search and retrieve guitar chord lyrics of current song
 - Theres button to enable auto-scrolling (Auto deactivates if you attempt to scroll manually) 

The site I'm using for this is http://www.guitarparty.com/en/. Hopefully they have songs you're interested in there, they seems to have a decently large collection from my quick observation.

**Comment by legion1978** [comment]
ill test and report back-- man, youre the best.

**Comment by Taiko2k** [comment]
Just a few things I need to clean up before I do I git push

**Comment by legion1978** [comment]
:3

**Comment by Taiko2k** [comment]
OK pushed, hopefully it works. I assume you're familiar with running a git/dev version

**Comment by legion1978** [comment]
its been a while. lets see how that goes heh

**Comment by legion1978** [comment]
Running in portable mode
Install directory: /home/downloads/TauonMusicBox-master
Dev mode, ignoring single instancing
Traceback (most recent call last):
  File "./tauon.py", line 302, in <module>
    from PyLyrics import *
ModuleNotFoundError: No module named 'PyLyrics'

**Comment by Taiko2k** [comment]
I thought that might happen, if you have the aur version installed, just copy the folder in from /opt/tauon-music-box, or copy it out of https://github.com/Taiko2k/TauonMusicBox/releases/download/v4.0.0/Tauon.Music.Box.v4.0.0.Linux.Bass.64bit.zip or you could do `sudo pip install pylyrics`

**Comment by legion1978** [comment]
ill get to it

**Comment by legion1978** [comment]
ok. i had to copy couple of other folders. (then i replaced the executable the other way around) then it broke when didnt find guitar-chords, so i created it. 
then it worked! :) 
is there a way to scroll already pasted chords? meaning when they dont have the special guitar party format? though *it* is better with the colored chords, guitarparty catalogue doesnt seem that extense :v

great work

**Comment by Taiko2k** [comment]
I could add a function to attempt to parse it from the format you have in that screen shot. Do you know if the chord positions are just a rough estimate... or it is accurate and using relative monospacing to give the positions?

**Comment by legion1978** [comment]
the difference in formats is that the usual chord found online has the letter on top of the word it should be played (as in the screenshot), whereas this guitarparty format has them before the word in brackets, like this:

[F]   [Gm]    [Bb]    [Gm]    [Bb]    [F]
[F]   [Gm]    [Bb]    [Gm]    [Bb]    [F]

I'd [F]sit alone and watch your light 
My [Gm]only friend through teenage nights 
And [Bb]everything I had to know 
I [Gm]heard it on my [Bb]radi[F]o 

so yes its accurate. 

for some reason, TMB is not honoring the spaces on those letters at the beginning:
 
![image](https://user-images.githubusercontent.com/331242/55284946-385dd380-5346-11e9-9a80-92c9056ee51b.png)

**Comment by Taiko2k** [comment]
It is actually measuring the spaces, just since the font is not monospace, they're much narrower, I can compensate this by replacing multiple spaces with wider spaces:

![Screenshot from 2019-03-31 18-48-11](https://user-images.githubusercontent.com/17271572/55285315-d5bc1480-53e5-11e9-9fca-a0c360cb64cf.png)

**Comment by Taiko2k** [comment]
I pushed an update.

Now, in the right click menu, there's an option 'Paste Chord Lyrics", which will take that 2 line format and save it. Theres also now a `Clear Chord Lyrics` option too. (So, to copy your existing lyrics, you'll need to a copy then paste)

Its not perfect reading separated line format, but it seems to work most of the time.

**Comment by legion1978** [comment]
man, it works and its awesome! 
really, thanks for this.

**Comment by C0rn3j** [comment]
>or you could do sudo pip install pylyrics

That makes the package manager sad. You shouldn't run pip with sudo, either run it with --user or in a virtualenv to not mess with your OS packaging.

Looks like you can add Tauon to the list here -

https://en.wikipedia.org/wiki/LRC_(file_format)#Software

**Comment by Taiko2k** [comment]
You're right. Pacman would get angry with me sometimes. I never realised there was a --user flag or I guess I never thought to use it, but I should.

As for editing Wikipedia, I'm not sure I feel that's something _I_ should do myself, seems like conflict of interest on my part.

**Comment by C0rn3j** [comment]
Well at least you didn't sudo pip update all packages, that was the only time I was forced to reinstall Arch.

I added Tauon to the Wiki page myself then.

**Comment by legion1978** [comment]
hello.
did we lose this? :(

**Comment by C0rn3j** [comment]
Yep - https://github.com/Taiko2k/Tauon/blob/master/CHANGELOG.md#v790

The old guitarparty.com API is completely dead now, someone would need to port things over to the new API - https://github.com/Taiko2k/Tauon/issues/1342

It was assumed that nobody was even using the chords feature, it's currently kept commented and the module is separated out (and semi-broken) here - https://github.com/Taiko2k/Tauon/blob/9afde0c4a29b9f6742d94b935ec8c28569dd565b/src/tauon/t_modules/guitar_chords.py

It's not impossible to resurrect the chords feature, but someone would have to fix the API integration with guitarparty.com too to make it complete.

**Comment by legion1978** [comment]
gotcha. 
though just the hability to paste/display the chords should suffice. because for instance i rarely got any hit from guitarparty anyway.

thanks

**Comment by C0rn3j** [comment]
@legion1978 you can test the build from #1409 as per https://github.com/Taiko2k/Tauon/wiki/Development-builds

**Comment by legion1978** [comment]
> [@legion1978](https://github.com/legion1978) you can test the build from [#1409](https://github.com/Taiko2k/Tauon/pull/1409) as per https://github.com/Taiko2k/Tauon/wiki/Development-builds

yes, it works ;) great

![Image](https://github.com/user-attachments/assets/fd5c397d-acd2-484e-adf2-bbb4c1d78260)
