### ISSUE TITLE
"Playlist regenerate" removes all songs if source is Jellyfin

### ISSUE THREAD

**Issue by jibsaramnim** [Taiko2k/TauonMusicBox#835]
Some background: My entire music library is hosted by Jellyfin, I have no local songs. I use the "Jellyfin Collection" as my main libary/playlist view, and have deleted the "default playlist" (or whatever it was called, I forgot) that Tauon Music Box had at first launch.

I create playlists for artists I more frequently listen to, so use the handy _search for artist by just typing > hit enter_ to create these playlists. However, in order to have these playlists continue to work correctly (even after refreshing the main Jellyfin playlist, for example), I have to edit their generators and add `s""` to them. Without this when regenerating the playlist, they immediately go empty.

Do you happen to know what might be causing this? Because I don't even have to add an actual playlist title (`""` is enough for it to work), it feels like it might be possible to just have this added as a default to a generator, or at least internally used as a fallback default if no `s` is specified in the generator.

**Comment by Taiko2k** [comment]
Yep this is a bug. Ive committed a fix now. 

Result of using `s""` is undefined behavior, but you shouldn't need to use that now after this fix.

**Comment by jibsaramnim** [comment]
Oh that's very nice, thank you so much! Once a new version is out (I'm sticking with stable releases for now) I'll update all my playlist generators and report back! :)
