### ISSUE TITLE
[Feature Request] Ability to specify default generator values for all playlists subsequently created 

### ISSUE THREAD

**Issue by jibsaramnim** [Taiko2k/TauonMusicBox#836]
There's a few sorting/filter values I manually set for every playlist I create. It would be really nice if there was a way to be able to set these as a defaults option somewhere, so that any subsequently created playlist automatically picks up on these. Would this be something that could be considered?

If it helps; I currently always immediately modify a playlist's generator by adding `s""` (for #835), `tn` to correctly sort multi-CD albums, and `auto` to have the playlist updated automatically, should new albums be added to my library from that artist later on.

How I originally thought of this was to have an optional "New playlist generator defaults" option in the app's settings, but thinking about it some more, it might actually be a good idea to consider `tn` as an app-wide default sort, or have a specific option to set an app-wide default sort option with this in there.

The same for the other option, it might actually be nice to have a checkbox in the app's settings that would make all playlists automatically refresh on open. Basically an app-wide `auto` option.

Thank you as always for your hard work and for your consideration!

**Comment by Taiko2k** [comment]
I think you only should need `tn` on the main Jellyfin playlist, then that sorting ought to carry over to derived playlists.

> Basically an app-wide auto option.

There is, under Settings > Function

![Screenshot from 2022-09-10 15-56-10](https://user-images.githubusercontent.com/17271572/189467738-e07ff952-d0e0-4e2d-921b-175c37e901de.png)

(Though note some generator codes ignore that setting, such as the jellyfin library playlist.)

**Comment by jibsaramnim** [comment]
> There is, under Settings > Function

Oh gosh, that's silly of me.. :facepalm: 

> (Though note some generator codes ignore that setting, such as the jellyfin library playlist.)

Does this mean any (e.g. Artist specific) playlist that fetches content from my main playlist (which has all content from Jellyfin) also does not automatically update?

**Comment by Taiko2k** [comment]
> Does this mean any (e.g. Artist specific) playlist that fetches content from my main playlist (which has all content from Jellyfin) also does not automatically update?

No, an artist playlist will auto update with that setting.

**Comment by jibsaramnim** [comment]
> No, an artist playlist will auto update with that setting.

This is wonderful, thank you so much! I am not sure what happened, but I feel like I remember this not working before, but it seems to be working exactly as you said, wondeful!

I think this makes this issue basically redundant, at least for the specific flags I mentioned. Please feel free to close this issue, unless you'd like to keep open for something more specific of course! :)
