### ISSUE TITLE
Wrong album art displayed

### ISSUE THREAD

**Issue by gSilas** [Taiko2k/TauonMusicBox#84]
TauonMB v4.0.0 displays Album art based on image type and art folder names, on some of my albums this leads to the wrong album art being displayed.
These albums are containing a sub directory with supplementary art (disc scans, booklets, ...) and a "cover" image file in the album folder.

Schematic view:
```
Album
|- art folder
|- music files
|- cover image file
```
I would expect the cover image to be used as album art in Tauon. However that is not the case. This is caused by the os.path.listdir() function and linux which return a list containing directories before files. Thus the [first condition](https://github.com/Taiko2k/TauonMusicBox/blob/master/tauon.py#L6459) fails and the [second condition](https://github.com/Taiko2k/TauonMusicBox/blob/master/tauon.py#L6463), which iterates through sub directories, is executed and an image file from the supplementary art folder is used as album art.

I am unsure if this is the expected behavior. During my testing I programmed this script (based on Tauon code) which first iterates through files and then through sub directories. This would result in the cover image file being used as album art.
```
import os

items_in_dir = os.listdir()
image_types = {'jpg', 'JPG', 'jpeg', 'JPEG', 'PNG', 'png', 'BMP', 'bmp', 'GIF', 'gif'}
art_folder_names = {'art', 'scans', 'scan', 'booklet', 'images', 'image', 'cover', 'covers', 'coverart', 'albumart', 'gallery', 'jacket', 'artwork',
'bonus', 'bk', 'cover artwork', 'cover art'}

direc = "."
dirs_in_dir = [subdirec for subdirec in items_in_dir if os.path.isdir(os.path.join(direc, subdirec)) and subdirec.lower() in art_folder_names]

for i in range(len(items_in_dir)):
    if os.path.splitext(items_in_dir[i])[1][1:] in image_types:
        dir_path = os.path.join(direc, items_in_dir[i]).replace('\\', "/")
        print(dir_path)

for i in range(len(dirs_in_dir)):
    subdirec = os.path.join(direc, dirs_in_dir[i])
    items_in_dir2 = os.listdir(subdirec)

    for y in range(len(items_in_dir2)):
        if os.path.splitext(items_in_dir2[y])[1][1:] in image_types:
            dir_path = os.path.join(subdirec, items_in_dir2[y]).replace('\\', "/")
            print(dir_path)
```

**Comment by Taiko2k** [comment]
Indeed, that was not expected behavior. Now that I think of it, I think I have encountered this issue myself but I just manually switched the art and didn't think anything of it at the time.

I'm impressed you managed to find and fix the code. I will accept these changes. Here's my re-adapted code.

```
        if not tr.is_network:

            dirs_in_dir = [subdirec for subdirec in items_in_dir if
                           os.path.isdir(os.path.join(direc, subdirec)) and subdirec.lower() in self.art_folder_names]

            for i in range(len(items_in_dir)):
                if os.path.splitext(items_in_dir[i])[1][1:] in self.image_types:
                    dir_path = os.path.join(direc, items_in_dir[i]).replace('\\', "/")
                    source_list.append([0, dir_path])

            for i in range(len(dirs_in_dir)):
                subdirec = os.path.join(direc, dirs_in_dir[i])
                items_in_dir2 = os.listdir(subdirec)

                for y in range(len(items_in_dir2)):
                    if os.path.splitext(items_in_dir2[y])[1][1:] in self.image_types:
                        dir_path = os.path.join(subdirec, items_in_dir2[y]).replace('\\', "/")
                        source_list.append([0, dir_path])

        self.source_cache[index] = source_list

        return source_list
```
I will include this change in the next release. If you'd like, I will accept a pull request with this if you would like to be credited that way.

**Comment by gSilas** [comment]
Great! Then I'll close this issue!
