### ISSUE TITLE
Up Next panel is not DPI-aware

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#840]
Wayland, 200% monitor scale:
![image](https://user-images.githubusercontent.com/2588851/191128972-52f1c1e0-cf0c-45b9-9d0e-d27ac9ea504c.png)

**Comment by Solarunit** [comment]
I also see that playlist selections is shifted up.

____

When I tested Tauon on Wayland I noticed that fonts are blurry (probably not related to this issue)

**Comment by jansol** [comment]
Fonts being blurry is a side effect from Tauon not actually using the Wayland backend of SDL by default (since SDL does not use it by default). As a result Tauon runs through XWayland and if the window is placed on a screen with scaling, it will be blurry because the window gets rendered at some other resolution and then the final bitmap gets scaled to whatever size it is really supposed to be.

I saw a commit just now that makes Tauon request the Wayland backend from SDL when it detects that it is running in a Wayland session, so from the next release on the blurry text should be gone.

**Comment by jansol** [comment]
You can also force Tauon to use the Wayland backend right now by launching it with the SDL_VIDEODRIVER environment variable set to "wayland". Glad to not need that workaround much longer. :tada:

**Comment by Taiko2k** [comment]
Ive committed a fix now. (Issue resolves if you restart Tauon btw)
