### ISSUE TITLE
Tray menu isn't translatable

### ISSUE THREAD

**Issue by adem4ik** [Taiko2k/TauonMusicBox#843]
Version: 7.4.1
OS: Manjaro Linux with non-English localization

1. Start Tauon Music Box
2. Enable Settings > Function > Show icon in system tray
3. Perform right mouse click on the tray icon

Result: Menu isn't translated and its strings aren't present on https://hosted.weblate.org/projects/tauon-music-box/

![image](https://user-images.githubusercontent.com/4707112/192116581-bdaea04f-abeb-4d7e-820f-38664a042d33.png)

**Comment by Taiko2k** [comment]
Okay fixed those for translation now. Some new strings may appear in weblate now.
