### ISSUE TITLE
Playback follow cursor (feature request)

### ISSUE THREAD

**Issue by dic1911** [Taiko2k/TauonMusicBox#85]
First of all, thanks for making a beautiful cross-platform music player

As title, the feature missing from most(if not all) music players on linux, the way it work is to check if the selected track is the one currently playing, if not, then override the original behavior like random/shuffle or play the next song in the list but play the selected one instead.

Thanks again!

**Comment by Taiko2k** [comment]
I believe I understand. Play the selected track if it was not the one just playing.

I suppose this should have lower priority than the queue, but higher than shuffle/repeat. Also, I suppose this should only apply when transitioning at the end of a track, but not when using the back/forward buttons manually.

**Comment by Taiko2k** [comment]
Actually, following cursor on pressing forward does seem more inline with behavior of other players. Ill have it that way too then. Let me know if you agree/disagree.

I've now got this setting working and committed so will be in the next release, whenever that will be (probably in a week or so)

**Comment by dic1911** [comment]
Hmm... I prefer the priority of selected track is above repeat but I'd respect your decision, and yeah, I agree with your last reply, that makes more sense :p

**Comment by Taiko2k** [comment]
OK, I will add that repeat behavior too. I wasn't really sure at first but I guess it makes sense. 

(So you would just keep the current track selected with repeat on if you want to repeat, and selecting something else will allow you to smoothly transition to repeating that track after the current one has finished)

**Comment by dic1911** [comment]
Yes, that's exactly what I asked for, thanks for your patience.

**Comment by Taiko2k** [comment]
This is live in the latest release now. Hopefully its working OK, but there might be issues, if its not behaving as expected we can re-open this issue.
