### ISSUE TITLE
Shuffle & repeat feature seems doesn't work

### ISSUE THREAD

**Issue by Jeddi212** [Taiko2k/TauonMusicBox#850]
version 7.4.2
on Arch

The shuffle & repeat feature has completely stopped working. 
The button display still acts normally, but the functionality doesn't work.

### Shuffle
- **Current condition** &nbsp;&nbsp; >>> Next track going sequentially
- **Expected condition** >>> Next track is random

**Comment by Taiko2k** [comment]
The queue may override shuffle, make sure its empty. Also, did you enable "Random Albums"?, try right click the shuffle button and select "Shuffle Tracks"

**Comment by Jeddi212** [comment]
You're right, the queue just overrided shuffle. Thanks :pray:
