### ISSUE TITLE
.wav files tags aren't recognized correctly

### ISSUE THREAD

**Issue by glu8716** [Taiko2k/TauonMusicBox#851]
I'm using two .wav files as examples. Both were tagged with MusicBrainz Picard.

![2022-10-07_13-00](https://user-images.githubusercontent.com/33501455/194538571-6b23c518-fa36-46ce-8e8d-7fe07fe977a6.png)

- Even if the "Album Artist" and the "Album Title" tags are present, in both cases only the folder name is showed in the album title field. The year is also missing.

- While the first file is showing correctly the "Artist", the "Title" and the "Track Number" tags, the second one is missing everything.

These are the ffprobe outputs (I don't know why the "Album Artist" tag isn't reported here, but it's present in MusicBrainz Picard):

> [wav @ 0x556958fe0300] Discarding ID3 tags because more suitable tags were found.
> Input #0, wav, from '01 - Bauer & Lanford - Leave me Behind (Rebourne RMX).wav':       
>   Metadata:
>     encoder         : FL Studio 11
>     title           : Bauer & Lanford - Leave me Behind (Rebourne RMX)
>     artist          : Rebourne
>     date            : 2014
>     album           : Bauer & Lanford - Leave Me Behind (Rebourne RMX)
>     track           : 01
>   Duration: 00:04:08.01, bitrate: 1411 kb/s
>   Chapters:
>     Chapter #0:0: start 0.000000, end 248.012494
>       Metadata:
>         title           : 
>   Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s

> [wav @ 0x5598e1fc3300] Discarding ID3 tags because more suitable tags were found.
> Input #0, wav, from 'Armitage.wav':                                                    
>   Metadata:
>     title           : Armitage
>     album           : Armitage
>     artist          : Biotronix
>     date            : 2016
>     track           : 01
>   Duration: 00:05:08.42, bitrate: 1411 kb/s
>   Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s

I tried with another player (Audacious) and the tags are showing correctly.

**Comment by Taiko2k** [comment]
Can you send me those files?

**Comment by glu8716** [comment]
[Sure](https://anonfiles.com/TfJa79Bay0/wavtauon_zip).

**Comment by Taiko2k** [comment]
I see, its using embedded ID3 tags *and* there's multiple ways to do that, so cursed. Fortunately tagging library can take care of that. I've committed the fix now.

**Comment by glu8716** [comment]
Can confirm that with the new 7.4.3 version this is now fixed. Thanks :)
