### ISSUE TITLE
remove prefix "the" for bands and artists

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#855]
tauon is organizing music with artists like goo goo dolls, script, hunna and so on at letter T cause they have the  "the" prefix, like the goo goo dolls, the script, the hunna and so on

most of the times anyway not even them use this prefix anymore, so for example you would find the goo goo dolls at letter G for goo goo dolls, and not on T anymore...

would be nice to have this in tauon too, seems more convenient...

**Comment by Taiko2k** [comment]
I assume you're just referring to the ***artist list*** after selecting ***sort alphabetically***?

**Comment by Taiko2k** [comment]
Ok ive committed a change now so that the artist list will ignore `The` when sorting alphabetically.

**Comment by legacychimera247** [comment]
perfectly working
