### ISSUE TITLE
have clear separation between disc one and two

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#856]
Althought i know discs are already correctly ordered and tracks order is the right one, it would be nice to have some sort of separator in the list that would help identify whether it's disc one or two :)

**Comment by jansol** [comment]
There is a line separating discs now. What version are you on?

**Comment by Taiko2k** [comment]
I think they're requesting a disc number label in addition to the separator. I'm not keen on the idea though, would add to clutter and its usually visually obvious what disc you're on.

**Comment by legacychimera247** [comment]
> I think they're requesting a disc number label in addition to the separator. I'm not keen on the idea though, would add to clutter and its usually visually obvious what disc you're on.

yes, exactly this, anyway i guess i can close it...

**Comment by legacychimera247** [comment]
Reopening this for a quick question, i have created two records with the image+cue method, then, in the cue file i specified a DISCNUMBER tag, which seems to work as for ordering the two discs, but in tauon there is no separator line between them, is this right and no line is present for image+cue or i am just doing something wrong?

**Comment by Taiko2k** [comment]
> Reopening this for a quick question, i have created two records with the image+cue method, then, in the cue file i specified a DISCNUMBER tag, which seems to work as for ordering the two discs, but in tauon there is no separator line between them, is this right and no line is present for image+cue or i am just doing something wrong?

Indeed won't work with CUE sheets as tauon didn't associate a disc number with them. Ive now committed a change so that it will. So I assume this should start working as expected once you re-import. It would be helpful if you could test this from git master (I can push a beta built on Flathub if that's easier)

**Comment by legacychimera247** [comment]
Oh really thank you, yes a flatpak would be much easier

**Comment by Taiko2k** [comment]
OK pushed. Info on how to switch is here https://github.com/Taiko2k/TauonMusicBox/wiki/Beta-Flatpak

Let me know if you see any difference once you re-import.

**Comment by legacychimera247** [comment]
hello, tried it, and it's perfectly working, thank you :)
