### ISSUE TITLE
band info overlaps with album list

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#860]
well i guess the title say it all, the album is completely covered by the info panel...

![Schermata del 2022-10-27 01-56-23](https://user-images.githubusercontent.com/22254556/198160451-719dc6a8-df10-4f3a-9517-5651a531ff85.png)
?

**Comment by Taiko2k** [comment]
Found and committed a fix for this issue. The issue is the artist info panel checkbox setting is bugged, in the mean time as a workaround; toggling the panel using the keyboard shortcut <kbd>Ctrl</kbd> + <kbd>o</kbd> fixes it.

**Comment by legacychimera247** [comment]
this is fixed, thank you...
