### ISSUE TITLE
Old version in about page

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#862]
After today's flatpak update I still see 7.4.1 version in about page
And also when running:
`flatpak run com.github.taiko2k.tauonmb`

BTW I have beta version too `flatpak list --app`

```
Tauon Music Box            com.github.taiko2k.tauonmb                     7.4.0               beta        flathub-beta      system
Tauon Music Box            com.github.taiko2k.tauonmb                     7.4.3               stable      flathub           system
```

**Comment by Taiko2k** [comment]
I assume you're still on the beta, which I don't always update. You can switch to stable using:

> sudo flatpak make-current com.github.taiko2k.tauonmb stable

**Comment by Solarunit** [comment]
I was pretty sure that I'm on stable..
Ok I run `flatpak run com.github.taiko2k.tauonmb`
The issue probably was with the tauon icon pinned on the panel.
Now I see 7.4.3, thanks!
