### ISSUE TITLE
AUR package for tauon-music-box-7.4.3-1 fails to install, md5sum issue with miniaudio.tar.gz

### ISSUE THREAD

**Issue by rstrube** [Taiko2k/TauonMusicBox#863]
There appears to be a checksum issue with one of the required packages: `miniaudio.tar.gz` which is preventing the installation of the latest version from the AUR.

```
Aur (1) tauon-music-box-7.4.3-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: tauon-music-box 7.4.3-1 (Tue 01 Nov 2022 10:45:18 AM MDT)
==> Retrieving sources...
  -> Found tauon-music-box-7.4.3.tar.gz
  -> Found kissfft.tar.gz
  -> Found miniaudio.tar.gz
==> Validating source files with md5sums...
    tauon-music-box-7.4.3.tar.gz ... Passed
    kissfft.tar.gz ... Passed
    miniaudio.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'tauon-music-box-7.4.3-1': 
error: packages failed to build: tauon-music-box-7.4.3-1
```

**Comment by rstrube** [comment]
I saw your comment on the AUR package listing about cleaning the build directory.  I did this, and everything is working as expected now.  For me I deleted `~/.cache/paru/clone/tauon-music-box` (because I'm using the paru AUR helper).  Is there anyway to automatically clean the build directory if necessary?

Either way I'm closing this issue for now.

**Comment by Movisivi** [comment]
I have sudo pacman -Qtdq | sudo pacman -Rns -; sudo pacman -Scc aliased to maintain. This among other things cleans up the build directory
