### ISSUE TITLE
I found this randomly in the app store and it rocks

### ISSUE THREAD

**Issue by BarbzYHOOL** [Taiko2k/TauonMusicBox#864]
Hello,

I tried quodlibet (buggy), clementine, strawberry, exaile (not bad), g4music (not bad either) and more. I was kinda bored of testing but Tauon seems to be the best.

Just wanted to give a shoutout.
This app must get some love and spread the word, like on reddit and youtube

**Comment by Taiko2k** [comment]
Thanks, I'm glad you like it 😄
