### ISSUE TITLE
image+cue does not see date on created albums

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#866]
i created some albums in the image+cue format, from my personal collection, with abcde, and i noticed that tauon is not able to see the release date, and i guess this is due to the fact that date seems to be saved on the on the image file and not on the cue one (with the DYEAR tag). Now i wonder if there's a way to make tauon read the date without the need to edit every cue file separately

or, you have any suggestion on any tag editor for image+cue files, or some other program than abcde to do this?

**Comment by Taiko2k** [comment]
OK Ive now committed a change so that CUE tracks will inherit various missing metadata from the source file. (On update you'll need to re-import tracks for this change to take effect.)

**Comment by legacychimera247** [comment]
this one is working also :)
