### ISSUE TITLE
[Windows] Tauon doesn't remember window location when reopening from close

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#869]
Title

**Comment by Taiko2k** [comment]
Tauon has the config setting `restore-window-position`, with default to off. I assume this is the more normal default, other apps don't usually remember their positions do they?

Though note this setting won't work on Wayland where I don't think its possible for windows to determine/know their location.

**Comment by Movisivi** [comment]
Yes. Pretty much every application remembers its last position and window state. I'm on Windows 10 19044.2251

Wayland is a non issue, I use GNOME Tweaks to center all windows.

**Comment by Taiko2k** [comment]
Did changing that setting fix the issue?

**Comment by Movisivi** [comment]
Yes it did, thanks! Last time I tried editing the conf on Linux the changes wouldn't save because they got overwritten. I see you added a reload button so that's handy

**Comment by Taiko2k** [comment]
Ok ive changed the default of that setting to *on* now
