### ISSUE TITLE
[Flatpak] click to open does not work 

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#87]
hi there, installed the app the other day and although i still have to play with it, i must admit i am impressed, can't explain but that interface just feels right.

anyway i have set tauon to be the default player for music files but it's not working, if i double click on a file (in a folder) tauon just opens without playing any song.

i am using fedora 30 mate beta but the same was happening in fedora 29 mate, and the app is of course in flatpak (if needed )

**Comment by Taiko2k** [comment]
I see, I had not allowed for this with Flatpak. I believe I have fixed this now. I've pushed an update, try run `flatpak update` to get it.

**Comment by legacychimera247** [comment]
thanks, it's perfectly working now, we can close this one...
