### ISSUE TITLE
some covers are not shown

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#875]
hello,

it may happen that some covers are shown in the cover mode and showcase mode but not on the gallery mode, and image cache reset did not help, nor deleting the image and downloading it again.

Any suggestions?

![Schermata del 2022-11-14 00-48-42](https://user-images.githubusercontent.com/22254556/201551131-4109b23e-b15e-486c-8f50-60cf3b149b80.png)

![Schermata del 2022-11-14 00-51-43](https://user-images.githubusercontent.com/22254556/201551147-bdbf0cc3-b3eb-4f67-812b-c6dbddbe3bd6.png)

**Comment by Taiko2k** [comment]
Is it always the same tracks? If so could you zip up one of the folders and send it to me, (only one music track is necessary in the event its embedded, I don't need all the tracks, just enough to display the art)

**Comment by legacychimera247** [comment]
Not the same tracks  ut same album yes, and it's actually an image+cue file, will try to compress it and send it to you...

**Comment by legacychimera247** [comment]
ok here we are :)

https://mega.nz/file/99NC3ByQ#YYFbTgNd9ldU9nABN3rZdF7HymPDdltFLuzOd39U8Hc

**Comment by Taiko2k** [comment]
Mmm, main issue is that the embedded image file in the flac file is corrupted so wont load in tauon. You can see that just from the thumbnail in Files:

![Screenshot from 2022-11-15 02-55-03](https://user-images.githubusercontent.com/17271572/201677737-ae1f6dc3-0e5e-4312-9dd8-6d01f64d9294.png)

The secondary issue is that the gallery in tauon doesn't fallback to the other art on failure like the side panel does. Not sure if its worth trying to fix that.

Easy solution is to wipe the embedded art from those files using a tag editor.

**Comment by legacychimera247** [comment]
no i guess it's not worth fixing that, thank you anyway (and yes i legally own the album :P )

**Comment by Taiko2k** [comment]
The behavior is still a little inconstant and I think its good if the user is made aware there is an issue. As a solution I've added a fallback error image. With this, the behavior of the side panel and gallery is consistent and you can manually switch to the good image now.

Here's what it looks like:

![Screenshot from 2022-11-15 13-21-04](https://user-images.githubusercontent.com/17271572/201799016-b334f75a-e2e2-46c2-a90d-34fe7fdffcd1.png)
