### ISSUE TITLE
issues on wayland

### ISSUE THREAD

**Issue by Korothi** [Taiko2k/TauonMusicBox#886]
On wayland,
there are issues with window buttons and window position:
buttons responsiveness is very bad + click spot is not where graphics are.
What library does it use?
If i disable window decorations in settings it doesnt draw them at all.
+ window manipulation is also not in the correct spot.

**Comment by Korothi** [comment]
On wayland,
there are issues with window buttons and window position:
buttons responsiveness is very bad + click spot is not where graphics are.
What library does it use?
If i disable window decorations in settings it doesnt draw them at all.
+ window manipulation is also not in the correct spot.

**Comment by Korothi** [comment]
Gnome, Arch
2x 1440p 27" at 100%
Im using aur version (flatpak one behaved the same)

pt., 2 gru 2022, 14:55 użytkownik Taiko2k ***@***.***>
napisał:

**Comment by Taiko2k** [comment]
Can you take a screenshot of the window controls for me? Also, is it just the window controls or are other buttons/controls in Tauon behaving unexpectedly?

**Comment by jansol** [comment]
Possibly related to #876 despite 1x scaling

**Comment by Korothi** [comment]
fixed after recent updates? disabling draw window decorations solves all issues i had and draws them properly
