### ISSUE TITLE
IME (Input Method Editor, for Chinese/Japenese/Korean input) does not work

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#888]
So I recently got fcitx working again on Wayland and noticed that Tauon does not seem to react to it at all. I don't even get the popup for activating the IME. Even if I activate the IME in another application and then switch to tauon, I only get input matching the physical keyboard layout, meaning I can't directly search for tracks whose titles are not written in Latin (or hiragana/katakana, it seems tauon is attempting a basic conversion for those).

SDL2 does have [an API for handling text input methods](https://wiki.libsdl.org/SDL2/Tutorials-TextInput). As a bonus this is also the API used for on-screen keyboards so dealing with this will also solve that part of the touchscreen UX. The macOS press-and-hold-for-accented-characters feature apparently also uses this mechanism.

**Comment by jansol** [comment]
It is possible to leave rendering the the in-progress input string to the IME, but that looks awkward at best and a well-behaved application should render it natively instead. The usual convention seems to be to highlight the in-progress part that is being edited by underlining it.

**Comment by Taiko2k** [comment]
Tauon does implement that API. Its working on superior Flatpak :smile: 

Either SDL2 made a breaking change with a newer version or Arch Linux broke their SDL2 package. I assume its the latter since its happened before. I assume you're on Arch Linux?

**Comment by jansol** [comment]
I'm on NixOS and it's not working on superior Flatpak either.

However that flatpak pulls in something it calls `org.gnome.Platform` whereas I'm on KDE Plasma. And upon further investigation I noticed there is something weird with a couple of other apps as well... Gotta keep investigating then.

**Comment by Taiko2k** [comment]
Maybe it is related to the newer version of SDL because its not working for me on Arch.
