### ISSUE TITLE
some image+cue files are shown as a single file

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#889]
i have some records stored on the image+cue files, and i've noticed that some of there are shown as a single file, doing some tests i noticed that despite being done correctly, tauon does not recognize the associated cue file, any hint?

**Comment by Taiko2k** [comment]
One thing it could be is that either the filenames of the track and cue need to match, i.e example.flac, example.cue, or the reference in the cue file needs to match the track filename. Or Tauon wont pick it up.

**Comment by legacychimera247** [comment]
so, the cue files were actually right, but after renaming them and then renaming back it works, how weird...

i guess i can close this issue anyway...
