### ISSUE TITLE
Issues with queuing albums

### ISSUE THREAD

**Issue by BeliefSuffering** [Taiko2k/TauonMusicBox#891]
All of these issues occur on Tauon v. 7.4.5 flatpak; they occur on both backends, and I am playing local files. 
When multiple albums are queued, only the first track of each gets played. The last album in the queue gets played normally.

When an album is playing and I enqueue another album as next (Enqueue Album Next), the track that was playing gets stuck on loop, meaning that when it ends, it repeats. Clicking the skip (>>) button either: 
skips to the next track, and the rest of the album plays fine,
skips to the next track, and all tracks in the album currently playing are looped,
skips to the first track of the album I enqueued as next, skipping all the remaining tracks in the already-playing album.

In all three cases, when the album I enqueued as next comes up, all of the tracks in it are stuck on loop. 

P.s., I created a github account with temp mail, it got flagged and I do not know if you saw the issue I submitted with it, so here is me trying again with a new account.

**Comment by Solarunit** [comment]
Have you tried v.7.4.6 flatpak? I had similar issue, but with single track in queue: https://github.com/Taiko2k/TauonMusicBox/issues/882

looks like it was fixed.

**Comment by BeliefSuffering** [comment]
> Have you tried v.7.4.6 flatpak? I had similar issue, but with single track in queue: #882
> 
> looks like it was fixed.

Thank you for

**Comment by Taiko2k** [comment]
Could you open a new issue with details on the skipping issue specifically.

**Comment by BeliefSuffering** [comment]
> Could you open a new issue with details on the skipping issue specifically.

Done, if you need more information please do ask
