### ISSUE TITLE
selected tab in top bar is almost undistinguishable from bar

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#892]
well, i guess the title says it all, it's very hard to determine in which tab you are as tabs are undistinguishable in 7.4.6

here's a screen
![Schermata del 2022-12-14 02-28-50](https://user-images.githubusercontent.com/22254556/207482898-95a3705e-6d75-499c-937f-36834924e7f4.png)

**Comment by Taiko2k** [comment]
Are you sure anything changed since the last version? Also, the theme in your screenshot is a customized one right?

**Comment by legacychimera247** [comment]
No, it's autotheming from album art, and basic theme it's exactly the same

**Comment by Taiko2k** [comment]
I think its just that you have *album art in the background* enabled and that album cover being white causes the contrast to reduce a fair amount. But I don't think anything changed, its not a bug, just many themes happen to have already low contrast. 

It might be worse for people on lower quality LCD screens or on a laptop in a bright environment etc. The solution would be to add more built in themes with higher contrast so users have more of a range of themes to choose from.

**Comment by legacychimera247** [comment]
i have a full hd 24 from xiaomi, and it's not that bad, anyway i did some tests, and even without the background from album art tabs in dark themes (especially the turbo one) are indistinguishable, and wasn't this way in 7.4.5

no problems at all on lighter themes

**Comment by Taiko2k** [comment]
In your screenshot I can tell the playlist you have selected is "Artist: Teenage Fanclub", so its not indistinguishable right?

I did make some underlying changes to the theming code in v7.4.6 so maybe a bug was introduced, but replicating your configuration on in this screenshot (v7.4.5 bottom, yours top), doesn't seem like anything has changed visually.

![Screenshot from 2022-12-15 02-45-31](https://user-images.githubusercontent.com/17271572/207611652-fa653653-20da-4a3a-84df-bb92e4e993d8.png)

**Comment by legacychimera247** [comment]
well i don't recall it was this way, but nevermind, i will change theme and disable the auto-theming from cover :) nevermind :)
