### ISSUE TITLE
Bitmap fonts support

### ISSUE THREAD

**Issue by glu8716** [Taiko2k/TauonMusicBox#897]
Does TMB support bitmap fonts? On my system I use the **[WenQuanYi Bitmap Song](https://archlinux.org/packages/community/any/wqy-bitmapfont/)** fonts for chinese and japanese characters but when I try to use it on TMB it doesn't work (while other otb converted bitmap fonts, like **[Terminus](https://archlinux.org/packages/community/any/terminus-font/)**, work).

Is it possible for TMB to support bitmap fonts?

**Comment by Taiko2k** [comment]
Tauon uses Pango for font management which apparently dropped support for Bitmap fonts a few years ago. So this is out of scope for Tauon to fix.
