### ISSUE TITLE
I have no audio.

### ISSUE THREAD

**Issue by Konglomneshued** [Taiko2k/TauonMusicBox#898]
I try to play songs and I have no audio in the app.

I tried setting my sound device.  I played the same song in a different app and I have audio there.

App installed with Flatpak.

**Comment by Konglomneshued** [comment]
✔️ Active: active (running)

Here is my output after playing a song.
![image](https://user-images.githubusercontent.com/94726665/208255883-9d0e70b7-329c-4457-86d7-a45907900f60.png)

**Comment by Taiko2k** [comment]
Hmm no clues there.

If you go MENU > Settings > Window and check "Top panel level meter", then play a song, do you see activity in the level meter?

**Comment by Konglomneshued** [comment]
> Hmm no clues there.
> 
> If you go MENU > Settings > Window and check "Top panel level meter", then play a song, do you see activity in the level meter?

Yes, I do see activity up there.

**Comment by Konglomneshued** [comment]
I'll try installing the app another way.  Perhaps it's a permission issue with it being a flatpak?

**Comment by Konglomneshued** [comment]
Oh, it's only a flatpak.

**Comment by Konglomneshued** [comment]
Any update?  I'd really like to use this software.

**Comment by Taiko2k** [comment]
Unfortunately im really out of ideas as to why its not working. Did you lower/mute Tauon soft volume (bar in he lower right corner)?

**Comment by Konglomneshued** [comment]
> Unfortunately im really out of ideas as to why its not working. Did you lower/mute Tauon soft volume (bar in he lower right corner)?

Oh my word, thank you so much!  I don't recall if I did it or if it somehow set itself.

Just as a suggestion, I think it would be helpful to have some icons indicating the purposes of UI elements such as this one because I didn't even know that was there, nor did I suspect it could have been a volume bar from looking at it.  It's also rather hard to see on most themes.
