### ISSUE TITLE
monitor folders

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#90]
simply enough, if i add new music into folders i need to scan that manually, would be nice to have a way to do this automatically, or it would be to much ram consuming?because it would be nice but if it's too ram consuming, better stay this way then...

**Comment by Taiko2k** [comment]
I can't think of an elegant way of doing this while avoiding unnecessary disk thrashing. Being playlist based also makes this more difficult. Ill say it doesn't really fit the design paradigm and direction for Tauon, which is more focused on *manual* control.
