### ISSUE TITLE
some artists are not shown in the artist list

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#906]
hello, i have noticed i have an artist not shown in the artist list, it has just one record and (the record) is actually shown right in the album list, but still the artist is not in the list, any suggestion on how to make him appear?

**Comment by Taiko2k** [comment]
Yeah it does that, its intentional. Should probably make it a setting since it might be unexpected and perhaps unwanted behavior.

**Comment by Taiko2k** [comment]
Ok, ive now committed an entry to the artist list box context menu that toggles this. 

![Screenshot from 2023-01-31 20-39-09-cropped](https://user-images.githubusercontent.com/17271572/215696533-1d4abec0-a7ab-4ed9-a367-bc2002ef9be8.jpg)

**Comment by legacychimera247** [comment]
thank you, i guess we can close this one...
