### ISSUE TITLE
italian translation

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#907]
just thinking, interested in an italian translation?

**Comment by Taiko2k** [comment]
Its up to you. You can get started using the Weblate interface and translate as much or as little as you feel like.

**Comment by legacychimera247** [comment]
would you help me on how to do that?

**Comment by Taiko2k** [comment]
I got a landing page here https://github.com/Taiko2k/TauonMusicBox/wiki/Translations. I don't actually know the exact steps, not done it myself.

**Comment by legacychimera247** [comment]
thank you, translating right now...
