### ISSUE TITLE
Title text in system tray doesn't update/load when listening to radio stream

### ISSUE THREAD

**Issue by axelsimon** [Taiko2k/TauonMusicBox#911]
Hi and thanks again for TauonMB, love using every day :)
Just discovered a small issue: if you enable the (very neat) Title text in system tray option while listening to a radio stream, it will correctly display the artist and title as provided by the radio stream, but won't update when this changes to a new one.

Also, just tried this: if a radio stream is the first thing you play after starting TauonMB, then the title and artist don't get displayed in the system tray. 

Thanks!

**Comment by Taiko2k** [comment]
Ok, Ive committed a fix for this now.
