### ISSUE TITLE
Sponsor only repo still available? I can't seem to find the link anywhere

### ISSUE THREAD

**Issue by rstrube** [Taiko2k/TauonMusicBox#913]
Hi @Taiko2k,

A while back I received a link for a sponsor only repo with "tricks & tips" etc.

For the life of my I can't seem to find that link anywhere.  Is the sponsor only repo still active?

Thanks!

**Comment by Taiko2k** [comment]
Nothing changed, here's the link https://github.com/TaikoExtra/TauonSupporterRepo

**Comment by rstrube** [comment]
Thanks, for some reason I couldn't find it!
