### ISSUE TITLE
Split up t_main.py file?

### ISSUE THREAD

**Issue by Merlin04** [Taiko2k/TauonMusicBox#919]
I installed tauon a few days ago and I'm really enjoying it and I thought I'd try to implement some features I wanted. However, I found that the `t_main.py` file which seems to contain a large portion of the program logic is incredibly long, to the point where github is unable to display it. This makes it really hard to understand the codebase and figure out how to add new features - could it be broken up into separate files?

**Comment by Taiko2k** [comment]
Theoretically, but its just so big and wasn't designed in a way that allows easy splitting. I have attempted to split modules off over time, but the damage has already been done, its too much work to fix now.

Though perhaps in a way acting as a contribution deterrent isn't the worst thing. I am rather opinionated and don't like to be faced with the decision of rejecting peoples PR's that I don't agree with 100% but that they might have put work into.
