### ISSUE TITLE
(flatpak) rescan not always working

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#92]
Yeah well sorry for all these reports :P , anyway, as the title says the rescan is not always working. i've inserted an album into the music folder then hit rescan on tauon and it immediately said the scan was complete, but the album wasn't there. At the end i had to manually drag n drop the album into the playlist panel to add it to the music list.

just in case the album is "the ideal condition" by paul hartnoll and nor the the title nor the tracks titles contains any special character...

**Comment by Taiko2k** [comment]
Are you sure the added folder is somewhere under/within the folder it shows when it says "Rescan folder complete."? Also, are you sure the new tracks are not in the playlist somewhere? (It doesn't necessarily only add items to the end of the playlist)

**Comment by legacychimera247** [comment]
Well, tried searching for them with the global search but i had no results. I will try again anyway

**Comment by Taiko2k** [comment]
Also check the folder it scanned. To clarify the expected behavior, it only re-scans the original folder imported to the playlist.

**Comment by legacychimera247** [comment]
well i had previously imported all my folders in music and not the folder music itself, and that's why it was not working...now it's perfectly working...must admit i feel a little dumb but oh well :P

**Comment by Taiko2k** [comment]
Hehe, as it says there in the manual :grimacing: : 
 > ...you should import just the single top level folder of your music collection after making the playlist rather than importing multiple lower level folders simultaneously.

Though I will admit, this behavior is a little unintuitive.
