### ISSUE TITLE
Support for webm

### ISSUE THREAD

**Issue by canadaduane** [Taiko2k/TauonMusicBox#925]
When downloading music from the web, its native format is often "webm"--a media file format that contains audio, video, or both. It would be nice to be able to play these audio files directly in Tauon without first converting to another format.

**Comment by Taiko2k** [comment]
OK, Ive committed this change now. This will be the new default behavior starting next release, but for anyone who doesn't want this behavior they will be able to change the setting `allow-video-formats` in the config file.

**Comment by canadaduane** [comment]
Great idea! And thanks!
