### ISSUE TITLE
Cannot open Tauon after Windows Update

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#928]
22621.1105 > 22621.1265

Worked fine before I restarted to apply the update.   Reinstall doesn't work. I try to delete window.p but it says it is open in tauon even though tauon isn't open. Task Manager doesn't show it listed and the message stays the same even after repeated PC restarts. 

Traceback (most recent call last):
  File "tauon.py", line 169, in <module>
_pickle.UnpicklingError: invalid load key, '\x00'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tauon.py", line 186, in <module>
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\admin\\AppData\\Local\\TauonMusicBox\\window.p'

**Comment by Taiko2k** [comment]
You should be able to delete window.p after a restart right?

**Comment by Movisivi** [comment]
I feel so dumb. I hadn't tried that. Yes that works. Any idea what caused this so I can avoid it again?

**Comment by Taiko2k** [comment]
Not sure, not had that issue before.

**Comment by Movisivi** [comment]
I think this driver had something to do with it https://old.reddit.com/r/Windows11/comments/10nrdio/alternative_a2dp_driver_is_now_out_of_beta_ldac/

I had just installed it shortly before this window failed to open.
