### ISSUE TITLE
Tauon deleted cover arts of my whole music collection!!

### ISSUE THREAD

**Issue by the-root-user** [Taiko2k/TauonMusicBox#934]
Man! Seriously? What the ..!
I, on the album art of an song, deleted the image and.. in a few seconds, covers of all songs got wiped. Just ridiculous.
Any way to restore em? Why is the behavior so?

**Comment by Taiko2k** [comment]
I'm sorry to hear this has happened. Unfortunately there's no way to undo that function. 

It would be good to clarify with you exactly what happened to determine if this is a bug or a matter of UI communication of how this feature works. 

How it works is it only deletes one file, unless its an embedded file in which it removes any embedded image of all tracks in the same folder. In this case label of the track should have said "Delete Embedded | Folder" to indicate this.

Is all your music in the same folder?

If Tauon automatically removed embedded art across multiple folders, then that would be a bug / unintended behavior. In this case can you recall what exactly the label said when you clicked it?

**Comment by Taiko2k** [comment]
The detete album art function deletes all album ar

**Comment by the-root-user** [comment]
It's all just like you said. The image was embedded which I occasionally tinker with, with kid3 (picard, etc).
Did it have to delete embedded images of all the tracks? That really isn't necessary or at least there should have been some check.
Now, ig, the "Import Folder" does some importing which i
