### ISSUE TITLE
escape key should exit radio page

### ISSUE THREAD

**Issue by axelsimon** [Taiko2k/TauonMusicBox#935]
I mean, I'd like that, probably? :)

When in the radio page / menu, the top-left icon turns from "toggle playlists" to "return". Being able to use <kbd>esc</kbd> here would be a quick and convenient shortcut.

**Comment by axelsimon** [comment]
Escape is a common key for getting out of a submenu.

It looks like <kbd>F5</kbd> means "toggle Showcase view". So unless that other <kbd>F</kbd> key meant something like "toggle Radio view" i'm not sure it would make sense.

But it's nice to discuss this!

**Comment by Solarunit** [comment]
>Escape is a common key for getting out of a submenu.

Yes, but in Tauon it's different views, and `Esc` is never used. Well maybe for Radio `Esc` would be a good choice :thinking:

**Comment by axelsimon** [comment]
Funny, i was just trying out Showcase view, which i never use, because of this conversation. Went back to Tauon's window to check where i was in the current album playing, and pressed <kbd>esc</kbd> a few times to get out of that view and back to the main view :smiley: 

It really is a reflex, i imagine others have it too.
(F5 worked fine to toggle it away, of course)

**Comment by Taiko2k** [comment]
OK, Ive committed this change.
