### ISSUE TITLE
Tauon icon doesn't show in KDE task switcher

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#936]
Tauon is the only application that doesn't have its icon in the task switcher instead showing the  Wayland icon. It shows up just fine in the taskbar.   Not a big deal,  I don't use KDE often, twice a month at most), just thought I'd get this filed away since I didn't see anything when searching

**Comment by Taiko2k** [comment]
Committed a fix for this now

**Comment by Movisivi** [comment]
Awesome, thanks a lot. I assume this will be the next release but I pull from master so I'll close this  early
