### ISSUE TITLE
Broadcast what is currently being played 

### ISSUE THREAD

**Issue by WX580** [Taiko2k/TauonMusicBox#937]
It would be nice to have an option to broadcast what is locally being played kind of like the listen together feature on Spotify

**Comment by Taiko2k** [comment]
Yeah I understand the desire. Unfortunately I don't think working on the existing broadcast feature is the best solution. I'm thinking of overhauling this feature to something that's web based, using a client side web player.

The benefit would be reduced latency. The downside would be it would no longer be compatible with streaming clients. Not sure if that would be missed.

**Comment by Taiko2k** [comment]
The above change I described is now live.

**Comment by WX580** [comment]
Upon running this the vibribbon folder is made but the command to make the .cue file doesnt seem to work and if i open the terminal in the directory of the file then it just says that it isnt a command

**Comment by natto1784** [comment]
holy shit that was fast, thanks
