### ISSUE TITLE
Changing the base offset, highlight behaves weirdly

### ISSUE THREAD

**Issue by the-root-user** [Taiko2k/TauonMusicBox#938]
On changing the base offset in settings, highlight (line) stays wherever it was (as if the offset still is zero).
\---
### 0px
![Screenshot-13](https://user-images.githubusercontent.com/70033863/223954840-2d82dc8f-21fd-4892-a65a-9a5ea90f4b64.png)

### 5px
![Screenshot-14](https://user-images.githubusercontent.com/70033863/223954873-52e00d2a-898b-4ea4-854e-8ee06b11bb7b.png)

### 10px
![Screenshot-15](https://user-images.githubusercontent.com/70033863/223954902-a89f736e-bfba-4e21-8c82-71be53e93f27.png)

### -7px
![Screenshot-19](https://user-images.githubusercontent.com/70033863/223954964-0bf8bc62-dac8-4c08-b10f-a93656073147.png)

**Comment by Taiko2k** [comment]
Yeah that's the intended behaviour. It's to fix the position of the text in case of using a different font or row size. You don't normally need to change that setting.

**Comment by the-root-user** [comment]
I don't get how that is intended. While changing offset, Title, etc move on every pixel change though(as in 0px and 10px SSs), it's the highlight which doesn't obey ;)

**Comment by Taiko2k** [comment]
It's to adjust the text in the context of the highlight, not the highlight itself. I put that setting there because I couldn't manage to come up with an algorithm that could solve it for all use cases.

**Comment by the-root-user** [comment]
Oh, interesting.
