### ISSUE TITLE
[Feature Request] Launch Tauon from folder and terminal.

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#94]
Hi, I would like to make Tauon my default music player, but I want to be able to launch it from wherever there is an audio file. Currently, when I double click on an music file in the file manager, Clementine is automatically launched. I would like it if t Tauon was launched instead. When I select Tauon in the  "open with" section, Tauon launches but no music plays. Launching Tauon from the terminal does not make any difference.

**Comment by Taiko2k** [comment]
What version are you using? Could this be the same issue as #87 ?

**Comment by keystroke3** [comment]
Yes, it is similar to that, but the solution you have provided does not seem to work for me. I was previously using AUR helper (yay) to update Tauon. I uninstalled it and reinstalled using flatpak. It still only opens starts up but does not play when I launch from file explorer.

**Comment by Taiko2k** [comment]
That was just a Flapak issue, the AUR version *should* be working in any case. So, if you're using the AUR version then this certainly is a separate issue. 

Though just realised, launching with a file from CWD currently does not work, but I could implement it. Still, launching with a full path within quotes should work. i.e:   
`python3 /opt/tauon-music-box/tauon.py "/mnt/drive/music/01 song.flac"`   
Maybe check if that's working for you.

Can I ask what file manager you're using? e.g GNOME Files (Nautilus), Dolphin (KDE) etc

**Comment by keystroke3** [comment]
> Can I ask what file manager you're using? e.g GNOME Files (Nautilus), Dolphin (KDE) etc
Now that you have mentioned it, I had not considered trying Nautilus. I use PCmanFM and I am running Gnome. Tauon feature actually works with Nautilus. I don't understand why it does not work with PCmanFM.

**Comment by Taiko2k** [comment]
I figured out the issue, PCmanFM passes the path using URL encoding. Tauon does already handle this with drag and drop, but didn't for launch args.

Ive pushed a fix for this. If you want to apply this fix before the next release, its currently safe to copy tauon.py from master to `/opt/tauon-music-box` (with AUR version)

**Comment by keystroke3** [comment]
Yay!. It works now. Thanks.
