### ISSUE TITLE
Wrong album title and tracks lenght with APE files

### ISSUE THREAD

**Issue by glu8716** [Taiko2k/TauonMusicBox#940]
![2023-03-10_21-01](https://user-images.githubusercontent.com/33501455/224416641-43148af1-cc01-42de-8d2e-c7084d26653b.png)
As you can see from the image the duration of the songs is missing. The title of the album in the tracklist section is also missing (the folder's name is read instead). You can see the correct name of the album on the right.
I can provide the used file if needed.

**Comment by Taiko2k** [comment]
What platform are you on? And yes, providing me the file would be helpful.

**Comment by glu8716** [comment]
Here's the file: https://a.pomf.cat/ymtkxg.ape
I'm on Linux by the way.

**Comment by Taiko2k** [comment]
OK, Ive now made a commit that improves APE tag reading compatibility with Tauon. This fixes the issues reading that file.

Once a new version of Tauon is released, you'll need to do a tag re-scan for this change to take effect on already imported tracks.

**Comment by glu8716** [comment]
Thanks a lot!

**Comment by glu8716** [comment]
I am still having problems with the new version. The album's title tag is now correct, but the length is still showing 00:00 and the track only plays the first 3/4 seconds, then it automatically goes to the next track.
