### ISSUE TITLE
Is it possible to have the cover image as the background of the app?

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#95]
I was wondering if it would be passible to add a feature whereby the image in the cover art is used as a background for a theme. Here are a few descriptive illustrations: 
![selena gomez blur](https://user-images.githubusercontent.com/37796862/56469936-adee2880-6448-11e9-9e95-11ef866bc3ac.png)

![lyrics view selena blur](https://user-images.githubusercontent.com/37796862/56469949-db3ad680-6448-11e9-9f17-b1463cf39d30.png)

**Comment by Taiko2k** [comment]
There's no current built in way of doing that.

___

As for implementing this... I have a working prototype. 

Here I have it more subdued than in your example and without blur:

![Screenshot from 2019-04-22 01-45-27](https://user-images.githubusercontent.com/17271572/56471028-97c08680-64a1-11e9-82c6-73a892316508.png)

![Screenshot from 2019-04-22 02-08-33](https://user-images.githubusercontent.com/17271572/56471187-a5770b80-64a3-11e9-938b-467f56e6a2fb.png)


And here's how it looks a bit stronger examples with blur:

![Screenshot from 2019-04-22 02-07-52](https://user-images.githubusercontent.com/17271572/56471186-a0b25780-64a3-11e9-88d5-d348ef9b9885.png)


![Screenshot from 2019-04-22 02-06-01](https://user-images.githubusercontent.com/17271572/56471151-3e595700-64a3-11e9-8d4d-b1784f5483cd.png)

**Comment by keystroke3** [comment]
That is a good implementation. I personally do not like how the app cover colors from the album and applies them in the current version. This new look can be a great improvement on that. I thought maybe scaling the cover like I have done could have pose challenge, but that is a nice look to it. I hope the lyric view will also have such a look (like in my second illustration). I also hope to see it in an update soon.

**Comment by Taiko2k** [comment]
This is now available in the latest release. Its not quite as strong as your original concept, but I think the way I've tweaked it works really well.

**Comment by legacychimera247** [comment]
tried this and it's not working, as enabling it crashes the program at least to me.

for info, i am using fedora mate 30

**Comment by Taiko2k** [comment]
That's no good. Could you give me the terminal output for the crash? 

  > To run from terminal use `python3 /opt/tauon-music-box/tauon.py` or for flatpak `flatpak run com.github.taiko2k.tauonmb`

**Comment by legacychimera247** [comment]
there are other things but i do guess this is what matter the most

> Traceback (most recent call last):
  File "/app/bin/tauon.py", line 25561, in <module>
    rect = SDL_Rect(x, y, album_mode_art_size, album_mode_art_size)
  File "/app/lib/python3.7/site-packages/sdl2/rect.py", line 42, in __init__
    self.x = x
TypeError: int expected instead of float

**Comment by Taiko2k** [comment]
That should be fixable.. out of curiosity, do you have UI scaling enabled?

**Comment by legacychimera247** [comment]
hnestly i don't know, where to look for that?
