### ISSUE TITLE
I have some FLAC files that are not playing in Tauon

### ISSUE THREAD

**Issue by glu8716** [Taiko2k/TauonMusicBox#952]
As the title says, I have an album in FLAC that is not playing in Tauon. It works fine in mpv.
I'm providing one of the files: https://anonfiles.com/T2E921fdze/05_flac
And this is the output from the terminal:
```
Start PHAzOR backend...
pa: ERROR, encoding format not supported!
ph: Jump
ph: Load file failed

**Comment by Taiko2k** [comment]
OK I have committed a fix for this now. I expect to have a new release ready within a few days.
