### ISSUE TITLE
Some problems with new mini-mode

### ISSUE THREAD

**Issue by BabaJi-0** [Taiko2k/TauonMusicBox#959]
Fedora 37
wayland
Installed as Flatpak
tauon v7.6.0

1. Extra bars on top and bottom(?)
2. Higher CPU usage specially when focused.

![Screenshot from 2023-03-22 19-28-12](https://user-images.githubusercontent.com/92249486/226934354-6dac6948-b6f1-4a70-b887-773c7eef14a5.png)
![Screenshot from 2023-03-22 19-48-34](https://user-images.githubusercontent.com/92249486/226934380-34934d01-8ee6-462a-bf46-c236109369e7.png)

**Comment by Solarunit** [comment]
>Extra bars on top and bottom(?)

I have them too.

>Higher CPU usage specially when focused.

Is that a local file, or radio?

**Comment by BabaJi-0** [comment]
>Is that a local file, or radio?

Local file.
I tried other files as well. It doesn't happen immediately.
