### ISSUE TITLE
Unable to play through "Pro Audio" audio interface

### ISSUE THREAD

**Issue by Merlin04** [Taiko2k/TauonMusicBox#964]
I have a Scarlett 18i6 I use for audio recording as well as general audio output from my system (my speakers are connected to the "headphones" port). It's configured to use the "Pro Audio" profile with Pipewire. I've set the mixer so my computer's sound outputs to the speakers, and it seems to work for everything except Tauon. When I click the play button in Tauon, nothing comes out of my speakers. 

Here's a screenshot of the relevant part of `qpwgraph`:

![Screenshot of a node graph of audio devices](https://user-images.githubusercontent.com/11800751/228058059-817921e3-4495-4005-b43f-c539afc933d1.png)

I'm wondering if the issue might be somewhat related to Tauon trying to connect to all of the outputs, rather than just 0 (left) and 1 (right)? Maybe it doesn't know how to interpret that many channels?

**Comment by Merlin04** [comment]
It seems that if I set Tauon to output to my laptop's built-in speakers it makes Tauon only create 2 output channels (`output_FL` and `output_FR`), and I can then use `qpwgraph` to send the outputs of Tauon to `playback_AUX0` and `playback_AUX1` respectively, which works correctly.

**Comment by Taiko2k** [comment]
OK Ive got in touch with mackron at miniaudio and we now have a fix on the way for this now.
