### ISSUE TITLE
when i open an artist i get into the last of the album

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#967]
As the tilte says, when i click on an artist, i get directly on the last album of the list (namely "last of artist albums, as tauon call it) instead of going to the first one (location 1 of 1) for which i need to scroll or double click

it feels very inconvenient, can it be reverted to open the first album directly, or at least made selectable in settings? :)

**Comment by Taiko2k** [comment]
OK Ive committed a change that it will always go to the first album when switching artist in the artist list. I think that's a good compromise so no need for a setting.

**Comment by legacychimera247** [comment]
oh thank you

on a side note, italian translation coming along nicely, finaly 90% of the ui+settings are translated :)
