### ISSUE TITLE
"Set audio output device" setting on Windows 10 doesn't do anything

### ISSUE THREAD

**Issue by Someone65** [Taiko2k/TauonMusicBox#970]
Running 7.6.3, TMB will use whatever is set as the default output device on Windows' settings rather than what you set in its audio settings. Restarting doesn't help. Tried this with VBAudio Cable and what happens is it still outputs to whatever the default output device is set to on Windows. I can get it to output to the virtual audio cable by setting it as the default on Windows.

![screenshot](https://i.imgur.com/ieSWZMh.png)

**Comment by Taiko2k** [comment]
This should be fixed now with v7.6.4. Let me know if its still not working for you.
