### ISSUE TITLE
It seems there are still problems with some APE files playback

### ISSUE THREAD

**Issue by glu8716** [Taiko2k/TauonMusicBox#971]
Some days ago I opened [this issue](https://github.com/Taiko2k/TauonMusicBox/issues/940). While the album title tag problem has been fixed and is now showed correctly, there are still problems with the playback. The time is still showing 00:00 and now the file just plays for about 3 seconds, then it automatically plays the next song (and the time bar isn't moving at all).

I did rescan the folder and the tags.

**Comment by Taiko2k** [comment]
Ah looks like I broke it again while tidying up the code and forgot to test it. Ive committed a fix now.

**Comment by glu8716** [comment]
Fixed now, thanks!
