### ISSUE TITLE
Prefer x11 under Wayland is ambiguous

### ISSUE THREAD

**Issue by Konglomneshued** [Taiko2k/TauonMusicBox#973]
![image](https://user-images.githubusercontent.com/94726665/229948980-461b7711-8b51-4081-beff-85b6fa5de066.png)

### Suggestion:
Switch to: 
Prefer Wayland over x11

Or if you mean the other way around then:
Prefer x11 over Wayland.

**Comment by Taiko2k** [comment]
> Prefer Wayland over x11

Surely a native English speaker wouldn't interpret it that way. But yeah it could to with rephrasing. 

What it means to say is: "When running in a Wayland environment, prioritise using XWayland rather than native Wayland." but that's too long. Ill change it to "Prefer x11 when running in Wayland".
