### ISSUE TITLE
requirements.txt is missing some dependencies

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#976]
See NixOS/nixpkgs#227728 . If that is intentional (i.e. it is an optional dependency) it would still be nice to have it documented somewhere.

**Comment by Taiko2k** [comment]
I don't currently intend that file to be used for anything and is currently in limbo. There are a number of missing dependencies from it such as gobject-introspection. I should probably delete it to avoid confusion.

**Comment by jansol** [comment]
It would be nice to have a full listing of dependencies somewhere then.

**Comment by Taiko2k** [comment]
Oh, libappindicator isn't a Python package so it wouldn't go in requirements.txt anyway.

The main reference is in the [wiki](https://github.com/Taiko2k/TauonMusicBox/wiki/Building). And you can also refer to the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tauon-music-box).

**Comment by jansol** [comment]
Thanks!
