### ISSUE TITLE
Track numbers are gone?

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#980]
Noticed today that track numbers are gone for some tracks. I guess those are songs without track numbers in metadata. 
I am not sure, I think I saw them in previous version :thinking: 

v. 7.6.4

**Comment by Taiko2k** [comment]
Hmm, if you could give me a track that you're sure has a track number that's not showing in Tauon that could help. Do a tag rescan in Tauon first to make sure its not already fixed.

**Comment by Taiko2k** [comment]
Seems like that track does not have a track number in its tags. (Dunno why Picard reports that it does)

**Comment by Solarunit** [comment]
so is it normal that song without a track number in its tags has empty track number in tauon? I think it always been like this, but not remember for sure.

**Comment by Taiko2k** [comment]
Yeah its always been like that. The alternative would be to default to '1', but I don't feel that's the correct way of doing it, better to just show nothing I think.

**Comment by Solarunit** [comment]
ok, thanks for confirmation! Gonna close this then
