### ISSUE TITLE
Tauon Music Box (Flatpak) does not use my system font. Also, it does not respect my cursor theme and instead uses a blackish cursor (probably Adwaita cursors).

### ISSUE THREAD

**Issue by Vibhav201** [Taiko2k/TauonMusicBox#983]
How can i make TMB use the system font (I'm on KDE Plasma)? 

Also, how can i make it use the system cursor instead of its own Adwaita cursor?

Thanks in advance.

**Comment by Taiko2k** [comment]
Tauon is intended to be used with the font Noto Sans. But you can change the font to your own choice.

For Flatpak to import a font, it seems you would need to copy the fonts file(s) to `~/.local/share/fonts`. 

Then in Tauon select MENU > Settings > Open Config File. Change `font-main-standard` to the name of your font (not the filename but the proper name). You can change the other 2 settings there as appropriate. Save and close your editor, then press the "reload" button in Tauon, then restart Tauon for the change to take effect.

As for cursors, hmm, maybe you need to do:

> flatpak --user  override com.github.taiko2k.tauonmb  --filesystem=/home/$USER/.icons/:ro

or 

> flatpak --user override com.github.taiko2k.tauonmb --filesystem=/usr/share/icons/:ro

(Remove --user if its a system flatpak install)
