### ISSUE TITLE
Drag'n drop of a track into an album isn't preserved after rescanning folder

### ISSUE THREAD

**Issue by glu8716** [Taiko2k/TauonMusicBox#986]
When you change the filename of a track and rescan the playlist Tauon will recognize it as a new track outside of the original album. You are then supposed to drag that track back to the album (or at least that's what I do). However by rescanning the playlist again the track goes back to being a single track again. 
https://user-images.githubusercontent.com/33501455/236205372-58ce2c5c-5f9a-4338-922e-380bed2fd1c6.mp4

EDIT: I understand that since I sort them "by imported" it makes sense for the track to be there, but I don't want to have it separated from the album if I want to sort my albums by the imported date from now on just because I changed the filename of one track of the album, that would be too inconvenient.
I know I could change the folder's name so that Tauon could see it as a completely new album, but I can't change it as I have a specific naming for that folder that I can't touch now.

**Comment by Taiko2k** [comment]
Yeah that's just the way the "by imported" sort works.

A way around this issue is to use Tauon's built in renamer. That way Tauon won't see the track as a separate file like if you were to rename externally. (Right click track > meta... > rename tracks (will rewrite in batch unless you hold shift while clicking that menu button))

**Comment by glu8716** [comment]
I see. I'll do that way from now on then. But is there a way now to merge the track back with the album and keeping them together when sorting by imported without having to change the folder structure again?

**Comment by Taiko2k** [comment]
Perhaps there could be a sorting method that does that but there isn't one currently.

**Comment by glu8716** [comment]
It would be really useful for me. If it's not a new sorting method, then maybe an option like "Preserve album structure when sorting by imported".

**Comment by Taiko2k** [comment]
OK I've committed a change now the splits "sort by imported" into "tracks" and "folders" versions.

![Screenshot from 2023-05-13 18-29-29-cropped](https://github.com/Taiko2k/TauonMusicBox/assets/17271572/ab437328-9ad2-4233-892b-becb93aa5cc5)

I believe this satisfies what you're looking for. 

Note that you would likely want to do a "sort track numbers" after doing a "sort by imported folders".
