### ISSUE TITLE
album repeat not working properly

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#99]
sometimes it may happen that the "repeat album" function only repeat first and last track, this happen after album has played one time in it's entirety...

**Comment by Taiko2k** [comment]
I'm not sure what you mean, could you explain in detailed steps?

Though, it seems to be working OK for me. Note that the expected behavior is that Forward and Back buttons always override the repeat function.

**Comment by legacychimera247** [comment]
how to reproduce :+1: 

1 set album repeat
2 listen the entire album
3 on the repeat (second time you hear the album) only first and last tracks are repeated, pratically tauon is repeating only first and last tracks and not others, and this for the other consequential times you repeat the album

**Comment by Taiko2k** [comment]
I see, this happens when having "Playback follows cursor" enabled.
