### ISSUE TITLE
AUR: No loved tracks were found.

### ISSUE THREAD

**Issue by k4yp** [Taiko2k/TauonMusicBox#990]
Tauon used to work fine when loving tracks but now when regenerating a playlist, it gives the error "No loved tracks were found." I have reinstalled multiple times, deleted the config and data folder and built from source but nothing seems to fix this issue. Thanks in advance if anyone knows how to solve this issue.

**Comment by Taiko2k** [comment]
Are you sure the playlist you are selecting has loved tracks in it?

**Comment by k4yp** [comment]
Thanks problem solved.

**Comment by 3metreflattyworldrecordholderbigdog** [comment]
aaaaaaand you got tyhem damn pronouns in yo profiel
Hi there friend 🌌
I make some cool software for Linux. Take a look around and enjoy your stay.

Socials: [Twitter](https://twitter.com/starlightcodex) | [Rate Your Music](https://rateyourmusic.com/~Taiyo)

Love is the law, love under will.  ass mf type sh
