### ISSUE TITLE
Monochrome tray icon option

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#991]
Some apps have several tray icon option in the setting.
I think it would be nice to have alternative monochrome tray icon for Tauon?

**Comment by Taiko2k** [comment]
OK Ive committed a new monochrome theme.

![Screenshot from 2023-05-31 21-16-22](https://github.com/Taiko2k/TauonMusicBox/assets/17271572/a40bd45c-65d2-4a9c-92b7-345040b62816)

And new setting is here:

![Screenshot from 2023-05-31 21-16-42](https://github.com/Taiko2k/TauonMusicBox/assets/17271572/5bba618b-fad4-4ddb-8e0e-3050044dbd95)

Not sure if this icon design is like amazing or not.

Note this change is Linux only, let me know if you wanted this for Windows.

**Comment by Solarunit** [comment]
Thanks! It looks okay, I gonna test it on next release. 
The current tray icon is too bright and while almost all other tray icons are monochrome, tauon icon is a bit destructing.

**Comment by Solarunit** [comment]
Updated today!
I think I prefer the new monochrome icon now, less destructing.
Another variant could be just black and white icon :)
Anyway, gonna close this, thank you!
