### ISSUE TITLE
[Feature Request]: Option to hide "separators" in Tracklist

### ISSUE THREAD

**Issue by RetroAbstract** [Taiko2k/TauonMusicBox#993]
Hi,

I would like to be able to hide these separators in the tracklist view mode that I've partially highlighted with a red line:

![1](https://github.com/Taiko2k/TauonMusicBox/assets/103272301/2ac5ddfc-e1df-4ac8-85a3-e6bf2e8d9547)

Which would result in having a unified long tracklist with no separators.

Thanks

**Comment by Taiko2k** [comment]
You can use the <kbd>F1</kbd> key to toggle those. This is a per-playlist setting.
