### ISSUE TITLE
Koel integration doesn't work

### ISSUE THREAD

**Issue by romner-set** [Taiko2k/TauonMusicBox#998]
Tauon seems to be unable to play any music from a koel server. The connection itself works and I can see the songs, but trying to play anything throws a "Server: File not found" popup error. Tested this on Linux and Windows with the https://demo.koel.dev official server.

Tauon console logs don't seem to show anything out of the ordinary:
```
Tauon Music Box v7.6.6
Copyright 2015-2023 Taiko2k captain.gxj@gmail.com

xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
Window size: [941, 1013]

(tauon.py:242879): Gtk-WARNING **: 23:47:48.937: Theme parsing error: gtk.css:5822:26: '-shadow' is not a valid color name

(tauon.py:242879): Gtk-WARNING **: 23:47:48.937: Theme parsing error: gtk.css:5825:14: not a number

(tauon.py:242879): Gtk-WARNING **: 23:47:48.937: Theme parsing error: gtk.css:5826:13: not a number

(tauon.py:242879): Gtk-WARNING **: 23:47:48.937: Theme parsing error: gtk.css:5827:11: Expected a length
Running from installed location
User files location: /home/main/.local/share/TauonMusicBox
Found XDG-Downloads: /home/main/downloads/
Found XDG-Music: /home/main/
Install directory: /opt/tauon-music-box
Database loaded in 0.007 seconds.
Pychromecast not found
Error loading xcursor
Start controller server
Start PHAzOR backend...
Using SDL version: 2.26.5
Applying theme: Turbo
GOT KOEL TOKEN
Writing database to disk... done
Start PHAzOR backend...
Start PHAzOR backend...
Start PHAzOR backend...
Start PHAzOR backend...
Start PHAzOR backend...
Start PHAzOR backend...
Start PHAzOR backend...
Writing database to disk... done
Lost the playing playlist!
Shutting down. Reason: Window received exit signal
Writing database to disk... done
Clear tmp cache
bye
```

**Comment by Taiko2k** [comment]
Tried it myself and indeed I can replicate this issue too. It used to work because I remember testing against the koel demo site. Digging into it I have no idea why its not working, the API call looks fine to me but the server returns a 404.

I tried setting up a local koel server to test, but ran into issues trying to get that to work. Considering the low usage of koel I think at this point I'd rather just remove support for koel and focus on Jellyfin which is much easier to set up and has more features.

**Comment by romner-set** [comment]
That's fair, especially since nobody even seemed to notice that it didn't work until now. I do have a local test server set up though, so I could try tracking down the commit that broke it if you want. Do you remember which koel version did work?
